### ISSUE TITLE
Can't copy/paste multi-line varchar text from query results pane

### ISSUE THREAD

**Issue by justingrant** [Microsoft/sqlopsstudio#1000]
- SQL Operations Studio Version: 0.26.7
Running on Mac OS

Steps to Reproduce:
1. Query a varchar(max) column that contains multi-line content.  I've tried line separators of \r, \n, and \r\n. Results are same in all cases.
2. Right-click on the cell in the query results and choose Copy
3. Paste that content into any editor. I tried SQL Ops Studio, VS Code, Word for Mac, even Visual Studio and Notepad on a Parallels Windows VM.

Expected: Content is pasted with line breaks intact
Actual: Single (long) line. 

I did find one really hacky workaround which is to export to XLSX, and then to select the cell and copy the multi-line content from the formula bar in Excel.  But this is undiscoverable and weird. Multi-line content should be correctly copied to the clipboard without this hack.

**Comment by anthonydresser** [comment]
theres a settings `sql.copyRemoveNewLine` that is true by default. I believe changing this to false will solve your problem.
