### ISSUE TITLE
sp_whoisactive widgets return no results when refreshed

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#1014]
SQL Operations Studio Version: March public preview 0.27.3

Steps to Reproduce:
1. Open a dashboard for a server where sp_whoisactive is installed and go to the sp_whoisactive dashboard tab. All the widgets will show values
2. Click on any of the widgets to refresh. The refresh will fail

In addition to failing, the widget also renders the "No results to show" message on top of the old data:
!["No results to show" message is on top of old dashboard data](https://user-images.githubusercontent.com/3758704/38049802-fd385cec-327d-11e8-9f1f-bb1857c42945.png)

**Comment by AbbiePetcht** [comment]
@kburtram This should not be sp_whoisactive specific issue. It's a regular widget that uses exec statement. We fixed many widget issues last month. We might introduce a regression 
@anthonydresser thought?

**Comment by anthonydresser** [comment]
I don't see this on other insights so

**Comment by AbbiePetcht** [comment]
I run the exec statements. It does take few seconds for the query result to return, so it might be issue with getting query results or widget doesn't property wait for the data to return.

**Comment by anthonydresser** [comment]
I don't see how that would make a difference since insights just uses the standard query code for sqltoolsservice, so it just waits for the query to finish.
