### ISSUE TITLE
Relase tags and version don't align

### ISSUE THREAD

**Issue by TheConstructor** [Microsoft/sqlopsstudio#1018]
With the latest GitHub releases the release-tag and the name are one build-number apart (0.27.4 vs. 0.27.3):
![grafik](https://user-images.githubusercontent.com/437735/38053895-9718d574-32d5-11e8-8a7b-171c94519418.png)

If possible it would be great to fix this. Maybe 0.27.3 could be re-released as 0.27.5 to have a uniform version again.

**Comment by kburtram** [comment]
@TheConstructor we'll try to keep these in sync in the future.  The issue here was that we already provided our doc team the final version number of `0.27.3` and then needed to take additional changes requiring a new tag.

In general we haven't been keeping the tags in-sync with the published bits.  We've been using release branches and publishing a changelog.  Are you using the tags for anything or just noting the discrepancy?

**Comment by TheConstructor** [comment]
@kburtram hombrew-cask (for example) uses version-interpolation to generate the URL for each release. This can not easily be automated, when there are two versions involved… My PR there to update to latest version: https://github.com/caskroom/homebrew-cask/pull/45318

**Comment by kburtram** [comment]
@TheConstructor Got it, that makes sense, thanks!  We'll keep these in-sync for future releases.  

We have a bunch of dependencies on our download paths and version numbers, so I can't easily change for this release.  There's a good chance we'll need to publish a March Hotfix build next week where I can correct this.  

Hope it's not too much trouble until then.  If it really is causing problems I can publish duplicate copies of the `0.27.3` download files under the existing `0.27.3` tag.

**Comment by TheConstructor** [comment]
@kburtram I submitted the URL change for now. If you upload the file to the 0.27.3-tag I can revert that change; if you release the next version with aligned tag&version I (or somebody else) will need to switch back to the original URL template.

Right now I feel that uploading those files could also help others looking for 0.27.3 files, but I don't know if somebody is interested in the files currently under that tag and if that somebody would be confused.

**Comment by kburtram** [comment]
@TheConstructor I've uploaded duplicated copies of the `0.27.3` files under https://github.com/Microsoft/sqlopsstudio/releases/tag/0.27.3.  

We'll keep the build version and tag version aligned in future releases.  Thanks for letting us know of this dependency.
