### ISSUE TITLE
DB Space Usage in Server Reports Extension throws error when database names contain special characters

### ISSUE THREAD

**Issue by flyfishingdba** [Microsoft/sqlopsstudio#1022]
- SQL Operations Studio Version: 0.27.3

Steps to Reproduce:
-Create a database that a contains a special character (such as a space)
-Open the Server Reports extension
-DB Space Usage will show "Error: Query has no results to return"

**Comment by philcart** [comment]
Adding to this.

The declaration of the name columns in the table variables should use the sysname datatype. 

The current varchar(30) declaration doesn't provide enough characters for a couple of our vendor supplied databases. That means the query errors with
```
Msg 8152, Level 16, State 2, Line 2
String or binary data would be truncated. 

```

And DB Space usage will show "Error: Query has no results to return"


Cheers
Phil
