### ISSUE TITLE
New Connection shows multiple copies of "Microsoft SQL Server" as Connection Type

### ISSUE THREAD

**Issue by cairneym** [Microsoft/sqlopsstudio#1027]
- SQL Operations Studio Version: sqlops 0.27.3 (9474415ad68b5a70e8b851698c8c836664a9d5b5, 2018-03-27T05:25:59.481Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Open SQL Ops Studio
2. Click on "Add Connection"
3. On the Connection pane, drop down the box next to "Connection Type"
4. Four copies of "Microsoft SQL Server" are shown but with no further clarification and no other types

![image](https://user-images.githubusercontent.com/28552348/38062582-6959751a-3340-11e8-86f5-09342542a80f.png)

**Comment by kburtram** [comment]
@cairneym this is a regression.  We only support a single connection type.  For some reason it's being registered multiple times.  Please use the default and we'll remove the duplicates in the next release.

**Comment by anthonydresser** [comment]
Doesn't look like its happening in master, not sure what was causing this but maybe my connection overhaul fixed it.

**Comment by kburtram** [comment]
This is fixed in current `insiders` builds
