### ISSUE TITLE
Error message is cut

### ISSUE THREAD

**Issue by mcetkovsky** [Microsoft/sqlopsstudio#1028]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:17:29.202Z)
- OS Version: Darwin x64 17.4.0
- Extensions: none
---

The error message on the screenshot is not displayed in full and there does not seem to be any UI allowing to expand it or show in full.

<img width="1008" alt="Cut message" src="https://user-images.githubusercontent.com/7315807/38082317-94207324-3346-11e8-849e-f98421c8aef8.png">

Expected: The error message is either expandable so a full message can be seen or the full message is shown somehow after clicking on it (for example as a new tab).

**Comment by kburtram** [comment]
This should be fixed in the latest `insiders` build which contain the new VS Code notification UI.
