### ISSUE TITLE
Combination of errors and selects is not displayed well in results

### ISSUE THREAD

**Issue by GrzegorzLyp** [Microsoft/sqlopsstudio#1029]
- SQL Operations Studio Version: 0.27.3

Steps to Reproduce:

select 1
raiserror('test',16,1)
select 1
raiserror('test2',16,1)

Only first select result is presented in results.

**Comment by GrzegorzLyp** [comment]
Execution is not stopped after first error since there are two error messages in the resukt pane. More probable is that after first error no additional datasets are expected. This is big difference from SSMS.

**Comment by GrzegorzLyp** [comment]
Try call this code on SSMS and You will get following result. This means that execution is not stopped after first error. The same with SQL Ops Studio but only first dataset is in result. These datasets are additional information together with error codes.

-----------
1

(1 row affected)

Msg 50000, Level 16, State 1, Line 2
test

-----------
1

(1 row affected)

Msg 50000, Level 16, State 1, Line 4
test2

**Comment by MattIrv** [comment]
Agreed that this is a bug based on the difference between Ops Studio and SSMS. It's the same root issue as #528, which I already have a fix pending for (Microsoft/sqltoolsservice#596) and I've verified that it solves the problem.

**Comment by MattIrv** [comment]
This is fixed now for our insiders releases and will be included in the April release
