### ISSUE TITLE
Feature Request: Configuration to control cursor focus when running query

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/sqlopsstudio#103]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1) Open new query window
2) Enter query to execute (`select name from sys.databases`)
3) Cursor focus goes to the results pane automatically
4) To change the text of query you have to click back into the editor pane.

Please add a configuration option that controls cursor focus to stay in the editor pane or the results pane.

An example:

The PowerShell extension for VS Code includes a configuration option `"powershell.integratedConsole.focusConsoleOnExecute"` that you can set it to true or false. When set to true, I execute a snippet of code in the editor and the integrated terminal will open, execute, and then put cursor focus at the PowerShell prompt of that terminal. If you set it to false, the same process will happen except the cursor stays in the editor.

**Comment by kburtram** [comment]
@wsmelton in our latest internal build we've updated the behavior to keep focus in the editor window after executing a query.  This was the intended design and current behavior is considered a bug.  

I like the suggestion to make this an option, but I don't know if there is a large group of users that would prefer the current behavior.

**Comment by kburtram** [comment]
We changed the default to keep in focus in the text editor.  Please reactive if this is insufficient.
