### ISSUE TITLE
Can't make a connection

### ISSUE THREAD

**Issue by dwayne-croteau** [Microsoft/sqlopsstudio#1036]
- SQL Operations Studio Version: sqlops 0.27.3 (9474415ad68b5a70e8b851698c8c836664a9d5b5, 2018-03-27T05:34:58.705Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---

Hello,

Fresh installation of High Sierra 10.12.6 , and SQL OPS 27.3 

Steps to Reproduce:

1. Unzip sqlops-macos-0.27.3.zip file
2.Copy "SQL Operations Studio" app extracted from .zip file, by dragging and dropping it into the Applications folder
3. Start the SQL Operations Studio app by double clicking the app in the Applications folder
4. Answer "Open" to popup window asking for permission to allow the application downloaded from the internet to be opened.
 5. Click the blue "Add Connection" button.  Nothing happens.
6. Click the "New Connection" button.  Nothing happens.
7. Disappointment.

**Comment by hoaaah** [comment]
@kburtram I try microsoftSqlToolsServiceLayer and it didn't give any output.

**Comment by kburtram** [comment]
We fixed a similar bug in July release where macOS connections where failing if the user had a case-sensitive file system.  I'll close this as a "duplicate" of that issue.  

Please reactive if this issue persists on the July release.  Thanks!
