### ISSUE TITLE
Feature: auto save query windows to a temp folder

### ISSUE THREAD

**Issue by jacobzed** [Microsoft/sqlopsstudio#104]
It would be great if the app would auto save query windows to a temp folder in case of a crash or reboot (like MSWord).

One of the most annoying things about SSMS is coming back to a windows update reboot and having lost all my query windows that I hadn't gotten around to saving. It happens more than I would like.

Even web browsers save their state and their isn't much work to loose compared to a query editor.

**Comment by kburtram** [comment]
@jacobzed have you tried the VS Code Hot Exit feature?  We're planning to enable that in an upcoming release and I wonder if that would meet your suggestion.  

It reopens unsaved files when editor is closed and reopened.  Here's some notes on that feature which mention crash recovery support https://code.visualstudio.com/blogs/2016/11/30/hot-exit-in-insiders.

**Comment by jacobzed** [comment]
Yes, that feature works perfectly. Looking forward to you adding this here.

**Comment by kburtram** [comment]
Hot exit is available as an option in Jan release.
