### ISSUE TITLE
Feature : Allow Query Tabs To Be Coloured Depending On Server

### ISSUE THREAD

**Issue by gavdraper** [Microsoft/sqlopsstudio#105]
I think it's part of the redgate SSMS pack but I find it very useful to specify at server or group level the tab colour. ie make all my query windows running on a live DB red and staging instances orange, dev green etc....

It looks like you already allow the colouring of server groups so maybe could even use that?

**Comment by ben-moore** [comment]
+1 for this, would be really useful

**Comment by kburtram** [comment]
This is available in the Jan release.  For remaining fit&finish on this feature please add comments to this issue https://github.com/Microsoft/sqlopsstudio/issues/327.
