### ISSUE TITLE
Feature : Allow search for SQL objects

### ISSUE THREAD

**Issue by gavdraper** [Microsoft/sqlopsstudio#106]
On DB's with many tables or procedures some way of finding them or even a goto object feature would be amazing

**Comment by SebastianPfliegel** [comment]
Is this what you're looking for?
![explorer](https://user-images.githubusercontent.com/6133090/32945777-0b0573a0-cb95-11e7-94d9-6ac64f2ab72e.jpg)

You can either peek into objects
![peek](https://user-images.githubusercontent.com/6133090/32945852-4b7c79a6-cb95-11e7-98d3-8f96174de27e.jpg)

and you can go to the definition
![goto](https://user-images.githubusercontent.com/6133090/32945923-9d1c574a-cb95-11e7-8a59-908a4a2413fa.jpg)

**Comment by gavdraper** [comment]
aha yes it is sorry I missed that. Although opening an object from that search seems to take 4+ minutes here until a tab appeared but I guess that is another issue. I'll close this
