### ISSUE TITLE
Dashboard extensions run queries before visible

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#1071]
- SQL Operations Studio Version: 0.28.1

Steps to Reproduce:
1. Open a dashboard page with Server Reports extension installed

Expected: Server Reports queries shouldn't run until the Server Reports tab is initially displayed

Actual: Server Reports queries are executed when dashboard is initially shown and Home page is active.

**Comment by anthonydresser** [comment]
dupe #1189
