### ISSUE TITLE
Object Explorer hangs upon calling findNodes API

### ISSUE THREAD

**Issue by alextercete** [Microsoft/sqlopsstudio#1076]
SQL Operations Studio version: **0.27.3**

![object-explorer-hangs](https://user-images.githubusercontent.com/126538/38361892-d70f6ad4-38c6-11e8-8832-7343a2e81189.gif)

### Steps to reproduce
1. Install the [extension sample from the issue reproduction branch](https://github.com/alextercete/sqlopsstudio/tree/issue/object-explorer-hangs/samples/extensionSamples)
1. Connect to a database (in the example above, it's a containerised copy of WideWorldImporters)
1. Expand a few nodes in the Object Explorer
1. From the command palette, run `Cause Object Explorer to hang` (see [the code for this command](https://github.com/alextercete/sqlopsstudio/blob/issue/object-explorer-hangs/samples/extensionSamples/src/extension.ts#L44-L51))
1. Child nodes of the node found by `sqlops.objectexplorer.findNodes` (in this example, `Databases/WideWorldImporters`), that haven't been expanded prior to calling the API, can no longer be expanded until you restart SQL Operations Studio

**Comment by kburtram** [comment]
@MattIrv could you please take a look at this?

**Comment by MattIrv** [comment]
Looking at this now, it looks like a bug with how we handle children objects when finding nodes:
```
Exception has occurred: CLR/System.NullReferenceException
Exception thrown: 'System.NullReferenceException' in MicrosoftSqlToolsServiceLayer.dll: 'Object reference not set to an instance of an object.'
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.ObjectExplorerService.QueueExpandNodeRequest(ObjectExplorerSession session, String nodePath, Boolean forceRefresh) in /Users/mairvine/code/sqltoolsservice/src/Microsoft.SqlTools.ServiceLayer/ObjectExplorer/ObjectExplorerService.cs:line 405
```

**Comment by MattIrv** [comment]
This bug has been fixed in our latest insiders release
