### ISSUE TITLE
Dashboard details arrow incorrect styling

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#1081]
The Dashboard details arrow is incorrectly styled. 

There's a "down" arrow which says "Expand" when hovered on when the details are already expanded.

![job1](https://user-images.githubusercontent.com/6411451/38385686-593078a0-38c7-11e8-922b-5637680dd3e4.JPG)

The "up" arrow appears when the details are already hidden and says "Collapse".

![agent1](https://user-images.githubusercontent.com/6411451/38385692-5e99512c-38c7-11e8-81e7-81335221cea3.JPG)

The styling should be the other way round.

**Comment by kburtram** [comment]
@MattIrv here's another simple issue you can look at if you have time.

**Comment by MattIrv** [comment]
The arrow is styled correctly for me when first opening the dashboard, but if I then collapse the panel, close the dashboard, and open it again then the arrow is styled incorrectly. I'll take a look
