### ISSUE TITLE
ObjectExplorerNode.nodePath contains display information

### ISSUE THREAD

**Issue by alextercete** [Microsoft/sqlopsstudio#1090]
SQL Operations Studio Version: **0.27.3**

For a few node types (e.g. temporal tables, columns, indexes), the node path contains display information, which makes the use of the `findNodes` API less straightforward.

#### Actual
_localhost,1401/Databases/WideWorldImporters/Tables/**Purchasing.Suppliers (System-Versioned)/Purchasing.Suppliers_Archive (History)/Columns/SupplierID (int, not null)**_

#### Expected
_localhost,1401/Databases/WideWorldImporters/Tables/**Purchasing.Suppliers/Purchasing.Suppliers_Archive/Columns/SupplierID**_

#### Actual

```typescript
const nodes = await sqlops.objectexplorer.findNodes(
  connectionId,
  'Column',
  undefined,
  'SupplierID (int, not null)',
  'WideWorldImporters',
  ['Purchasing.Suppliers (System-Versioned)', 'Purchasing.Suppliers_Archive (History)']);
```

#### Expected

```typescript
const nodes = await sqlops.objectexplorer.findNodes(
  connectionId,
  'Column',
  undefined,
  'SupplierID',
  'WideWorldImporters',
  ['Purchasing.Suppliers', 'Purchasing.Suppliers_Archive']);
```

**Comment by MattIrv** [comment]
This bug has been fixed in our latest insiders release and should behave as expected now
