### ISSUE TITLE
Navigate to procedure definition opens schema definition

### ISSUE THREAD

**Issue by stanac** [Microsoft/sqlopsstudio#110]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. type 'exec schema_name.procedure_name'
2. Set typing cursor on procedure_name
3. Press F12

Expected:
4. Definition of procedure is opened in new query window

Actual:
4. Definition of schema is opened in new query window

**Comment by kevcunnane** [comment]
@llali @abist another candidate for investigation in the general scripting area.

**Comment by llali** [comment]
Fixed in sqltoolservice v1.2.0-alpha.39. It will be in the next release
