### ISSUE TITLE
Peek Definition is not working with SQL 2017 created databases\tables. RTM CU5

### ISSUE THREAD

**Issue by cferdig** [Microsoft/sqlopsstudio#1109]
- SQL Operations Studio Version: 27.3

Steps to Reproduce: SQL 2017 RTM CU5. 
1. Create a new database
2 Create a table and columns
3. Try and use the Peek Definition in a new query window

**Comment by MattIrv** [comment]
I wonder if there's a way we can be smarter about how we cache Intellisense results when doing things like creating databases.

As a workaround you can refresh the cache yourself by opening the command palette (ctrl+p) and running the "Refresh IntelliSense Cache" command

**Comment by kburtram** [comment]
I couldn't repro this on the July release.  I think one key step in the repro is when doing `Try and use the Peek Definition in a new query window` you need to make sure that the new query window is open with a connection to the database created in step 1.

Please reactive with additional repro steps if the problem persists.
