### ISSUE TITLE
Syntax Highlight & Intellisense not working on .sql files stored on disk unless the *.sql file association is removed

### ISSUE THREAD

**Issue by nalexander50** [Microsoft/sqlopsstudio#1112]
- SQL Operations Studio Version: 

Version 0.27.3
Commit 9474415ad68b5a70e8b851698c8c836664a9d5b5
Date 2018-03-27T05:25:59.481Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- Operating System

Microsoft Windows 10 Enterprise
Version 10.0.16299 Build 16299

Steps to Reproduce:

1) Add the following value to SQL Operations Studio settings

```
"files.associations": {
    "*.sql": "SQL Script"
},
```

2) Save a `.sql` file to disk. Recommend using a different text editor just for sanity.

3) Open the newly saved `.sql` file in SQL Operations Studio

![screenshot-1523392783](https://user-images.githubusercontent.com/7144865/38582482-e170f284-3cdd-11e8-9592-fcd59d146850.png)

As you can see, the opened `.sql` file is not being treated as a `.sql` file. It's being treated like a Plaintext file. Notice, even, that the tab icon is not a `.sql` icon. There is not syntax highlighting nor Intellisense. Additionally, the connection bar will sometimes not work. I can't quite find the steps to reproduce that exact issue. But, the connection bar probably shouldn't work for a Plaintext file, so it's likely a nonissue.

4) To demonstrate further, remove the file associations from step 1.

![screenshot-1523392798](https://user-images.githubusercontent.com/7144865/38582564-2e730248-3cde-11e8-9707-0eb41149b15f.png)

Like magic, SQL Operations Studio now recognizes the file as a `.sql` file and everything behaves as expected. Notice the tab icon, syntax highlighting, and Intellisense. Additionally, the connection bar functions as expected as well.

**Comment by nalexander50** [comment]
Follow up: I just noticed that if I remove the asterisk from the file association (change `*.sql` to `.sql`), SQL Operations Studio behaves as expected. It seems that the wildcard character should not be there. This may be an artifact from a recent change or an upcoming change that hasn't been fully released.

**Comment by kburtram** [comment]
It think the correct syntax would be something like the below.  Though I'm not what this would accomplish since .SQL files should already be associated with the SQL language service.  

```JSON
    "files.associations": {
        "*.sql": "sql"
    },
```

This mechanism is inherited from the VS Code shell, so documentation or issues regarding VS Code in this area may also be helpful to troubleshoot.  Please reactive this issue if you're still experiencing problems here.
