### ISSUE TITLE
DB Space Usage UI bug

### ISSUE THREAD

**Issue by Ryukote** [Microsoft/sqlopsstudio#1135]
In Server Reports Extension - DB Space Usage have UI bug when you have a lot of DB. Here is the screenshot of the problem: https://imgur.com/Q1y7kxn

My suggestion would be to put y axis in scroll. It would be a good solution for cases like this when you have a lot of DBs.

**Comment by kburtram** [comment]
@AbbiePetcht could you please take a look at this?  If we don't have the ability to make chart content scrollable we should probably just limit to showing only the `top N` largest DBs

**Comment by AbbiePetcht** [comment]
@anthonydresser Is it a limitation in insight widget? Can we make chart content scrollable?
@kburtram I am planning to add the option for the widget to get the top N data.

**Comment by anthonydresser** [comment]
@AbbiePetcht there might be a way, but it wouldn't be simple, chart.js by default resizes itself to take up the size of its parent.
