### ISSUE TITLE
Cycling through tabs, forgets scroll position

### ISSUE THREAD

**Issue by anton-johansson** [Microsoft/sqlopsstudio#114]
### SQL Operations Studio Version:
Version 0.23.6
Commit 8a3011756318a2ded1e6e84332230a2b2bf9c544
Date 2017-11-05T22:46:14.815Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

### Steps to Reproduce:

* Open a file
* Scroll down a bit
* Cycle to another query (`Ctrl + Tab`)
* Cycle back to the previous query (`Ctrl + Tab`)

The tab has forgotten its scroll position.

**Comment by anton-johansson** [comment]
Seems sort of related to #123.

**Comment by codemonkey1234** [comment]
Is this in regard to the query results grid forgetting its position or something else? I closed #123 for now on assumption that this is about the results grid forgetting its position. If that's not the case then I'll reopen #123. Thanks.

**Comment by anton-johansson** [comment]
> Is this in regard to the query results grid forgetting its position or something else?

The original issue is for actual query tabs, but it feels like the same issue, really, since it's behaving the same way in the results grid.

**Comment by justingrant** [comment]
The messages tab is also affected by this problem.

**Comment by om007** [comment]
Scroll position not preserved when switching over tabs.

**Comment by kburtram** [comment]
Please also look at the Edit Data related problems discussed in https://github.com/Microsoft/sqlopsstudio/issues/299.

**Comment by masta** [comment]
I would be glad if this is fixed as I'm working with multiple files quite often. Note that this is working just fine Visual Studio Code, which I thought sqlopsstudio is based upon...

**Comment by andreusg23** [comment]
A new version (0.31.4) is out but error #114 is still not fixed... or, am I missing something?

**Comment by BobTheGeek** [comment]
Can confirm this error is still occurring and I am currently working between multiple, length files and this is very disrupting.

**Comment by andreusg23** [comment]
thanks for the update.

**Comment by travis79** [comment]
This issue has reappeared in the latest insider build.

Version 0.33.4-insider
Commit c92b88bfaff3bed7c8f6190d33534dc649a39e0c
Date 2018-09-13T07:08:25.140Z
VS Code 1.26.1
Shell 2.0.8
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

**Comment by demyte** [comment]
Hi,

Getting this issue with column sizing and scroll position being lost in:

Version 1.3.7-insider
Commit 5a3087859918b1564d2622b95defa662facdbef6
Date 2018-12-07T02:33:40.014Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64
