### ISSUE TITLE
"Script as create" runs very slowly (~1m) when connected to a remote sql server

### ISSUE THREAD

**Issue by AlexTroshkin** [Microsoft/sqlopsstudio#115]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.14393
---

Steps to Reproduce:

1. connect to a remote sql server
2. on the servers panel, execute "Script as create" command on any stored procedure or table

Perhaps the execution time does not depend on the number of stored procedures or tables, because on the same database but locally the command is executed quickly

**Comment by llali** [comment]
Fixed in sqltoolservice v1.2.0-alpha.39. It will be in the next release
