### ISSUE TITLE
Failed to save results. Error: Failed to save *.csv: Not a directory

### ISSUE THREAD

**Issue by buzz11** [Microsoft/sqlopsstudio#1156]
- SQL Operations Studio Version: sqlops 0.27.3 (9474415ad68b5a70e8b851698c8c836664a9d5b5, 2018-03-27T05:34:58.705Z)
- OS Version: Darwin x64 17.4.0
- Extensions: none
---

Steps to Reproduce:

1. Click Save as CSV icon in upper right corner of results pane
2. Attempt to save, and it will raise an error with message:
 ```Failed to save results. Error: Failed to save *.csv: Not a directory```
 and it in fact fails
3. Repeat the process, no error, and it in fact saves.

**Comment by kburtram** [comment]
@buzz11 thanks for reporting!  I wasn't able to repro, though I do recalling seeing a similar issue previously.  Do you happen to know if there are any additional repro steps that could help us isolate the issue?

**Comment by buzz11** [comment]
Export 13 .csv files one after another ranging between 10KB and 40MB. But it happened the first time then not the second, every time.
