### ISSUE TITLE
SQL Agent extension April remaining items

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#1162]
**Jobs View**
  - [x] Add Jobs View row "on hover" style to indicate it's clickable @aditya
  - [ ] Add a loading indicator while page is loading content
- [x] Fix styling of Jobs button in Page selection panel @aditya
- [x] Add single pixel vertical line between columns header at the resize seperator (if looks better send for PR, if questionable send email for review) @aditya
- [x] Add horizonal rule line after Jobs label to match mock-up
- [x] Remove "Category ID"
- [x] Switch "true/false" to "yes/no" or a simple checkbox icon or something pending UX (optional)
- [x] Add a Tooltip on Hover to Name column (optional)
- [x] Jobs View status indicator color should match status of last run outcome
- [x] No vertical scrollbar on Jobs View grid
- [x] We don't currently handle resize events.  Have a minimum supported size.  Resize to bigger, but not smaller.
- [x] Jobs View "Next Run" column (and really any date column) should not show uninitialized DateTime.  Match SSMS behavior.
- [ ] Follow-up on "Open dashboard extensions" name and description @alan
- [ ] Post-April? add action buttons column that displays on hover
- [ ] Make columns sortable (and filtering), if trivial SlickGrid configuration option 
- [x] Exclude SQL Agent extension on Azure DB connections

**Job History**
- [ ] Jobs with no steps have Jobs Execution detail pane slightly more narrow then otherwise (optional)
- [ ] Make Steps expand and show full error message when clicked.
- [ ] Job History List doesn't work well zoom.  Status label gets unaligned (optional)
- [ ] Use similar font typeface and size for similar elements in all pages (headers, label, row values, etc.)
- [x] Using keyboard with Job History list, enter on element doesn't update Job Execution details
- [x] Up\Down arrows in Job History list should update Job Execution details (i.e., no Enter required)
- [x] Steps list hover background isn't correct for Light Theme
- [x] All error messages, particularly the Job Execution details Message, should be copyable to clipboard.  Either as selectable text or hover action or otherwise.
- [x] Reduce line spacing for Job Execution pane excution details label
- [x] Job History should have scrollbar when content is too big for window
- [x] Job History should respond to resize...use minimum expected size, such as 600px or 800px, but expand to fill larger area if available
- [x] 'No Previous Runs Available' touches the margin. Shift it to the right.

**General**
- [ ] Duration should probably show units
- [x] Need to support keyboard navigation and accessibility scenarios
- [x] Pressing TAB when focus Job History Execution list causes weird styling
- [ ] Need Job Control features on Jobs View

**Comment by kburtram** [comment]
@abist are you still using the "April" tracking item?  Or should we close it now that April is out?

**Comment by abist** [comment]
@kburtram The items remaining from this list are the "optional" or future items for May. I can open a new tracking bug for those issues and close this one.
