### ISSUE TITLE
Extension gallery should have an "all" section or a way to show all available extensions

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/sqlopsstudio#1166]
Currently the extension gallery doesn't have a way to show non-recommended but available extensions without searching. If we add a new extension (for example the SSMSKeymap extension) to the gallery it won't be visible unless you do a search.

Note: this is separate from #1165 which covers search not filtering as expected. 

**Default view**
![image](https://user-images.githubusercontent.com/10819925/38844065-b9523ba0-41a6-11e8-80ab-8f70c7310f9a.png)

**View after searching for "SSMS" or "Keymap"**
- Note how the extension appears.

![image](https://user-images.githubusercontent.com/10819925/38844218-52c2ba26-41a7-11e8-8121-73d767ef3061.png)

**Comment by anthonydresser** [comment]
does searching @all not work?
thats how vscode's works.

**Comment by kevcunnane** [comment]
2 things:
1. #1165 covers the fact that any search will return all results. That needs fixing
2. We don't have a marketplace web page that allows users to organically find extensions. My concern in this bug is that without that, it's non-intuitive for users who want to find all extensions. A solution might be to suggest ways to view all extensions in the viewlet. If enough people think it's intuitive to just search we can close this bug.

**Comment by kburtram** [comment]
@llali I think we need to do something for this scenario relatively soon.  Currently there are issues discovering extensions that aren't in the SQL Ops recommendation list.  I guess a short-term alternative could be to add all extensions to the recommendation list, but I prefer a longer-term solution if possible.

**Comment by llali** [comment]
The menu item "Show Popular Extensions" lists all the extensions but agree we need to fix the search and @ALL 
![image](https://user-images.githubusercontent.com/17187348/39156822-bfcbe786-470c-11e8-9052-32a401c3a897.png)

**Comment by kburtram** [comment]
@llali currently my default Extension Manager looks as below.  This is excluding several of our community contributed extensions, and I suspect many users won't know they exist or how to find them.  I don't think this is what we want.

Until we have a "real marketplace" and dynamic recommendations I think we should error on the side of showing "too many" extension recommendations.  Perhaps a simple solution is to rename the "Recommended" section to "All" and just show everything there, perhaps sorting the recommend extensions first?

![screen](https://user-images.githubusercontent.com/599935/39157449-b606e8a6-470f-11e8-8b81-fa945b5395fa.png)

**Comment by kburtram** [comment]
I'll take a look if there's any easy way to improve this experience.
