### ISSUE TITLE
Connection drops when zooming window

### ISSUE THREAD

**Issue by Jmen** [Microsoft/sqlopsstudio#117]
- SQL Operations Studio Version:

Version 0.23.6
Commit 8a3011756318a2ded1e6e84332230a2b2bf9c544
Date 2017-11-06T21:51:43.232Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Open a new query window
2. Connect to a database
3. Zoom window in or out Ctrl + or -
4. Run query

Error - new connection window opens
Expected - Run query against existing connection

**Comment by kevcunnane** [comment]
I can reproduce this - it disconnects when zoom is used. Will take a look at this is a nasty one.

![image](https://user-images.githubusercontent.com/10819925/33042278-18bc65fe-cdf6-11e7-986d-53a24b011fb3.png)

**Comment by kevcunnane** [comment]
I have a fix for this in review. We will have this resolved in the next release. While testing I discovered a few related issues
- rename in the file viewlet does't update any SQL files that are open, causing us to leave "deleted" files behind
- After saving an untitled SQL file that has results pane visible, the results pane disappears. 

These issues won't be in the initial fix but I hope we'll get them resolved too as they're important.
