### ISSUE TITLE
Doubled, uncloseable tabs for one file when opening multiple files.

### ISSUE THREAD

**Issue by lerchdude** [Microsoft/sqlopsstudio#1175]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Go to File > Open File
2. Highlight 2 .sql files
3. Click on the tab of the file that is not in focus

You will see two tabs that are both in focus. You cannot close either of these tabs while they are in focus.

![image](https://user-images.githubusercontent.com/9547098/38904667-8cea4bd8-4260-11e8-9bb8-2d008b736238.png)

**Comment by kburtram** [comment]
I verified this still repros on the latest build.
