### ISSUE TITLE
Feature Request: Search For Item In Server Explorer

### ISSUE THREAD

**Issue by DianGermishuizen** [Microsoft/sqlopsstudio#1177]
- SQL Operations Studio Version: 0.27.3

Request: Similar to how you have a search bar to search for a specific saved server name, please add a way to search for a specific item in a server e.g. search for a table, a stored procedure, a view etc. 

Thank You!

**Comment by anthonydresser** [comment]
dupe #794

**Comment by hypermagicmountain** [comment]
Actually, #794 asks for a really advanced search option, e.g. search table contents. 

This Feature request duplicates #860 which asks for a simple table search inside the object explorer.
