### ISSUE TITLE
EDIT store procedure

### ISSUE THREAD

**Issue by gbelmm** [Microsoft/sqlopsstudio#118]
- SQL Operations Studio Version:

Steps to Reproduce:
is posible option to edit SP

![captura de pantalla 2017-11-17 a la s 09 58 36](https://user-images.githubusercontent.com/731936/32948615-a1d72db2-cb7e-11e7-8126-fb9cdd6cf95e.png)

**Comment by llali** [comment]
this feature s added to the next release
