### ISSUE TITLE
Edit Data resultset size dropdown is transparent

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#1188]
- SQL Operations Studio Version: `master`

Steps to Reproduce:

1. Open `Edit Data` designer
2. Click the resultset size drop down

Expected: Select box background opaque

Expected: Select box background transparent

![screen](https://user-images.githubusercontent.com/599935/39013714-14a8387e-43cd-11e8-93a8-914d6f1f4546.png)

**Comment by MattIrv** [comment]
Looks the same as https://github.com/Microsoft/sqlopsstudio/issues/1072
