### ISSUE TITLE
Installation experience

### ISSUE THREAD

**Issue by papiermache** [Microsoft/sqlopsstudio#119]
The app installs as 16,819 files !?!

Words fail me in attempting to describe the absurdity of this.

**Comment by Mike-Skinner** [comment]
I extracted sqlops-windows-0.23.6.zip and have 14960 files. 

![image](https://user-images.githubusercontent.com/5193568/32974045-63c2e7f6-cc4f-11e7-9077-8b7faf592912.png)

The resources directory seems to be the culprit.

Hopefully some kind of bundling/resource packaging can be implemented in the future. This is just a preview... so I realise that working features are more important.

Thanks for the preview - and cross platform too :-)

**Comment by SebastianPfliegel** [comment]
Relax, this is just a preview ;)
It was the same with the early VS Code releases.

**Comment by papiermache** [comment]
yeah I know, Code is now a slim and trim editor cormprised of just 3,910 files and 837 folders.
