### ISSUE TITLE
Connection Information Not Visible In a Query Tab

### ISSUE THREAD

**Issue by jirish0818** [Microsoft/sqlopsstudio#1203]
- SQL Operations Studio Version:
Version 0.27.3
Commit 9474415ad68b5a70e8b851698c8c836664a9d5b5
Date 2018-03-27T05:25:59.481Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
Open a query to a Database or Open a Query File and connect to a Database. The information about what you are connected to is displayed in the lower right corner, but the same information is not available in the Window Title at the top or if you hover your mouse over the tab. This is a feature that is available in SSMS and I often have multiple tabs open to different Databases on the same and different Servers. I need a means to be able to tell quickly where my focus is.

**Comment by anthonydresser** [comment]
dupe #1193
