### ISSUE TITLE
Feature Request: Add ability to parse SQL code in the query editor

### ISSUE THREAD

**Issue by brandochn** [Microsoft/sqlopsstudio#1209]
- SQL Operations Studio Version:  0.27.3

Like in SSMS have the ability to parse SQL code to validate SQL syntax.

![image](https://user-images.githubusercontent.com/32686301/39148961-3ee66a46-4703-11e8-9472-a114d97d5bab.png)

Thank you.

**Comment by kburtram** [comment]
@brandochn SQL Ops Studio will automatically parse SQL statements in the query editor and display syntax errors in the Error Message Pane.

It looks like the Parse option is sending the query to the engine to parse which is a little more accurate than the T-SQL parser we use in the IntelliSense service.  

Do you know of any cases where the `Parse` command is showing errors that the language service parser is missing?  Or what the other benefits of the SSMS "Parse" vs. the one currently available?  Thanks!

**Comment by brandochn** [comment]
Hi @kburtram ,

Well,  I have a case where the language service parser is showing errors that the Parse command is missing.

here is the case:

If I parse the following dummy script by using SSMS Parse I don't get any errors.


```
CREATE PROCEDURE dbo.test
(
    @Id int
)
AS
BEGIN
    
    IF OBJECT_ID('tempdb..#dummyTable') IS NOT NULL DROP TABLE #dummyTable
	CREATE TABLE #dummyTable
	(
		Id						int identity (1,1),
		dummyInt				int,
		dummyChar				nvarchar(50)
	)
	
	IF OBJECT_ID('tempdb..#dummyTable2') IS NOT NULL DROP TABLE #dummyTable2
	CREATE TABLE #dummyTable2
	(
		Id						int identity (1,1),
		dummyInt2				int,
		dummyChar2				nvarchar(50)
	)

	insert into #dummyTable (dummyInt,dummyChar)
	values (1,'A')

    IF EXISTS(select 1 from #dummyTable2) 
        DROP TABLE #dummyTable2

	update #dummyTable
	set dummyChar = (select dummyChar2 from #dummyTable2 where Id = #dummyTable.Id)
	where Id = 1


    RETURN 0
END
```

But if I do the same by using SQL Ops I get these error messages:

![image](https://user-images.githubusercontent.com/32686301/39277700-b353dd52-48b4-11e8-9bf3-82d15ac5a6a7.png)

Besides, there is interesting thing here  SSMS query editor shows the same error but the parser command  works as expected.

![image](https://user-images.githubusercontent.com/32686301/39277779-3316192e-48b5-11e8-8c6d-04a8330477b8.png)

That's why we should have the two options I think.

Thanks.

**Comment by kburtram** [comment]
@brandochn thanks for explanation!  This is a nice parser test case snippet.

It looks like the below lines in the script are confusing the language service parser into thinking the tables must have been dropped.  We use the same parser as SSMS hence the same syntax errors.

```SQL
    IF EXISTS(select 1 from #dummyTable2) 
        DROP TABLE #dummyTable2
```

I'll move this issue to the June Milestone to see if this is something we can quickly add.

**Comment by kburtram** [comment]
@abist I think you recently added a parse command for SQL Agent job step.  Could we reuse that message here?

**Comment by abist** [comment]
@kburtram Yes, we certainly can. Adding this should be very minimal cost as well.
