### ISSUE TITLE
SQL Agent extension shouldn't be available when connected to Azure DB

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#1213]
- SQL Operations Studio Version: 0.28.4

Steps to Reproduce:
1. Install SQL Agent extension
2. Connect to Azure DB

Expected: Don't show SQL Agent tab

Actual: Shows SQL Agent tab

**Comment by kburtram** [comment]
@abist if possible, could you please look at this today?  It should be a quick update to `package.json`.  Chat with @AbbiePetcht if you don't know how to add the visibility expressions for dashboard tabs.

**Comment by abist** [comment]
Fixed in https://github.com/Microsoft/sqlopsstudio/pull/1233
