### ISSUE TITLE
SQL Agent extension and the status bar

### ISSUE THREAD

**Issue by bigleka** [Microsoft/sqlopsstudio#1215]
- SQL Operations Studio Version:
Version 0.28.4-insider
Commit 3d6fb7a8fa8e941306109f69bc094e307b9ff8c2
Date 2018-04-23T05:43:47.587Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Steps to Reproduce:
Open the SQL AGENT extension and roll the roll bar until the end, the last job are just partial display

**Comment by kburtram** [comment]
@abist could you please take a look at this?  If it's a simple style update let's try to get in for April, otherwise, we can take for the next update.

**Comment by abist** [comment]
This should be fixed now.

**Comment by bigleka** [comment]
The problem continue... on version 0.29.2
![image](https://user-images.githubusercontent.com/13354954/39583796-496195ce-4ec7-11e8-887a-f6a435232911.png)

**Comment by bigleka** [comment]
@abist it´s normally show, on full screen, resizing or put on other monitor with different resolution.
