### ISSUE TITLE
SQL Agent Job History tree view has too small minimum size

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#1221]
- SQL Operations Studio Version: 0.28.4

Steps to Reproduce:
1. Open SQL Agent Job History and make window "medium size" (maybe ~800px?)

Expected: A good default size for tree view and details pane.  With tree view having a reasonable minimum size so that content is normally visible.

Actual: Tree view is too small, tree view section is not resizable, no horizontal scrollbar

![screen](https://user-images.githubusercontent.com/599935/39151819-2f0ac1ec-46fb-11e8-86ea-75ff73a6194c.png)

**Comment by abist** [comment]
Closed with https://github.com/Microsoft/sqlopsstudio/pull/1237
