### ISSUE TITLE
The legend in vertical data is incorrect (vertical bar chart)

### ISSUE THREAD

**Issue by AbbiePetcht** [Microsoft/sqlopsstudio#1228]
When use columns name as labels, it should not include the first column
![image](https://user-images.githubusercontent.com/25463959/39154312-a33612cc-4702-11e8-90fd-df29f6361fb4.png)

**Comment by kburtram** [comment]
@AbbiePetcht is this something you're looking at to fix today?  Or should I try to see if anyone else can help pick it up?  I'd like to start the final planned April Public Preview build around 7pm tonight.
