### ISSUE TITLE
Query results grid resets to row one on switch to another tab/switch back

### ISSUE THREAD

**Issue by codemonkey1234** [Microsoft/sqlopsstudio#123]
Execute a query then navigate to/select a row far down results in query grid. Switch to another tab then come back to original window and query results grid is reset to row one and prior selection is lost. Expected behavior would be that the query results stay on row that was previously selected rather than losing selection and going back to top of results.

Version is 0.23.6

**Comment by anton-johansson** [comment]
Sort of related to #114.

**Comment by codemonkey1234** [comment]
Yes, sounds like they are the same, I'll close mine. Thank you.

**Comment by anton-johansson** [comment]
I wasn't implying that you should close it, more to state that they can probably be solved in similar ways. :)

**Comment by codemonkey1234** [comment]
Yeah but I'm pretty sure it's the same problem. It sure sounds like it, though #114 doesn't mention the query results grid explicitly. I'll ask about that on #114 and reopen if it's not. Thank you!

**Comment by saurabh500** [comment]
I will keep this opened so that we can track the progress of the reset of query editor and the results of query separately.

**Comment by kburtram** [comment]
I'll close as a duplicate to keep the number of active issues more manageable.  https://github.com/Microsoft/sqlopsstudio/issues/114
