### ISSUE TITLE
@ sign not working

### ISSUE THREAD

**Issue by SebastianPfliegel** [Microsoft/sqlopsstudio#1238]
- SQL Operations Studio Version: 0.28.4 and 0.28.5

Steps to Reproduce:
When trying to declare variables I fail to type an `@` sign in the query editor. I'm using the German keyboard layout and trying to push `Alt + q`. I can't even use the Windows screen keyboard. However, I'm able to paste the sign into the query editor from a different source.

**Comment by kburtram** [comment]
@AbbiePetcht @anthonydresser could you please help investigate this?  Particularly, we need to determine if this is a recent regression possibly from one of the keyboard-related accessibility changes.

**Comment by kburtram** [comment]
I think this is probably related to this commit https://github.com/Microsoft/sqlopsstudio/commit/13fb9fdfd24254281841db71f8cb3b2fd125304 which adds a new keyboard shortcut that uses Alt and Q characters for the `FocusOnCurrentQueryKeyboardAction`.  Could you please try unmapping this keyboard shortcut?

**Comment by AbbiePetcht** [comment]
@kburtram I can use different keyboard shortcut

**Comment by SebastianPfliegel** [comment]
Thanks @AbbiePetcht, works like a charm again! :)
