### ISSUE TITLE
DB Space usage report doesn't work if there's a space in a database Name.

### ISSUE THREAD

**Issue by sbandarla** [Microsoft/sqlopsstudio#1247]
DB Space usage report returns blank when there's a space in the database name.
- SQL Operations Studio Version:

Steps to Reproduce:
Create a test database with a space on your SQL Instance and refresh Server Reports extension.

**Comment by kburtram** [comment]
@sbandarla I think this should be fixed by https://github.com/Microsoft/sqlopsstudio/pull/1023.  We will release an updated Server Reports extension with the April Public Preview planned for tomorrow morning.

**Comment by kburtram** [comment]
This appears to be fixed in `Server Reports 1.1` which is now available in the Extension Manager Marketplace.  Please reactive if the problem persists.
