### ISSUE TITLE
Missing scrollbar when looking at the store procedures

### ISSUE THREAD

**Issue by rednaxel22** [Microsoft/sqlopsstudio#125]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. Open a database
2. Check the Programmability -> StoresProcedures
3. Not able to see the full SP names unless I expand the Servers Window, should have an scrollbar to avoid expanding the servers window.

**Comment by kburtram** [comment]
Please reactive if this repros on Jan release.
