### ISSUE TITLE
Implement HIDE Results Like Ctrl+R On SSMS

### ISSUE THREAD

**Issue by shpsyte** [Microsoft/sqlopsstudio#1259]
- SQL Operations Studio Version: 0.27.3

Steps to Reproduce:
Implement Hide Results Like CTRL+R on SSMS
  If run any query then Results Tab Show Again

It's fantastic feature

**Comment by kburtram** [comment]
@shpsyte we provide a command `Toggle Query Results` which should hide the query results pane.  Could you please verify if there is a gap between that feature and this suggestion?  Thanks!

**Comment by shpsyte** [comment]
That's right !
Tks! It's a great feature
