### ISSUE TITLE
Missing funcionality to filter stored procedures

### ISSUE THREAD

**Issue by rednaxel22** [Microsoft/sqlopsstudio#126]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. Open a database
2. Check the Programmability -> StoresProcedures
3. Not seeing the filter option when right click on Store Procedures, the user should be able to filter this, there are multiple cases when this is required to work smoothly,

**Comment by davidmdem** [comment]
I have a similar situation with a database containing an absurd number of DB objects.  I am unable to expand the Stored Procedure node for this database without getting an error: `Object Explorer task didn't complete within 45 seconds.`

**Comment by erickangMSFT** [comment]
@rednaxel22 @davidmdem can you try Search widget on the dashboard (setting aside the perf case while it's being investigated) and let us know if the behavior / perf meets your need for search / filtering sp?

**Comment by erickangMSFT** [comment]
let's track it with https://github.com/Microsoft/sqlopsstudio/issues/69 
Performance issue is being investigated currently.
