### ISSUE TITLE
keyword 'distinct' not highlighted

### ISSUE THREAD

**Issue by need47** [Microsoft/sqlopsstudio#1260]
- SQL Operations Studio Version: 0.28.4-insider

Steps to Reproduce:

-- 'distinct' not highlighted
select count(distinct id) from MyTable

-- vs. 'distinct' highlighted below
select distinct id from MyTable

**Comment by abist** [comment]
Fixed in https://github.com/Microsoft/sqlopsstudio/pull/1270#issuecomment-384461283
