### ISSUE TITLE
Tabbing in data view does not move cursor until arrow button is pressed

### ISSUE THREAD

**Issue by dparvin** [Microsoft/sqlopsstudio#127]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Run a Select statement against some table in some database
2. Click into the grid of data
3. Press the tab key twice (Notice that the focus does not change)
4. Press the right arrow (notice that the focus moves over three columns, skipping two because of the tabs)

Tabbing does move the square around the cell and will scroll the window, but the highlight on the cell does not move unless you use the arrow key.

**Comment by kburtram** [comment]
The grid currently tracks both selection (blue background color) and focus (highlight around cell).  I'll leave this issue active to track the suggestion to track these as a single state.

**Comment by alanrenmsft** [comment]
@kburtram , I just tried this on the latest release 0.32.3, selection and focus are being tracked as a single state now, i don't see any difference visually now. closing the issue.
