### ISSUE TITLE
[Feature Request] Save Results as Insert Statements

### ISSUE THREAD

**Issue by nalexander50** [Microsoft/sqlopsstudio#1277]
Currently, we have the option to export query results as JSON, CSV, and an Excel spreadsheet. In some scenarios, it would be useful to have an export as insert statements function. For example, seeding a production environment with static data from a staging environment; or, when you want to change the definition of a table but want to keep the data.

**Comment by schallm** [comment]
I opened a [request](https://github.com/Microsoft/vscode-mssql/issues/566) like this for the VS Code extension before opsstudio was announced.  Update statements by primary key would also be helpful to update environments.

**Comment by nalexander50** [comment]
Curious as to why this has been tagged as a bug since I've never seen this functionality in SQL Operations Studio. Perhaps an accident?

I think I may look into adding the functionality myself. I've always wanted to contribute something worthwhile to one of these projects. Sounds like it might be a good stepping stone.

**Comment by kburtram** [comment]
@nalexander50 you're correct, this was incorrectly tagged as Bug as triage oversight.  This would be a great candidate for a community contribution.  We'd be happy to help you get started if you're interested in contributing this feature.  Thanks!

**Comment by kburtram** [comment]
We're tracking this request in this issue https://github.com/Microsoft/sqlopsstudio/issues/459.  I'll make a note in that issue to review this one while resolving.   Please add additional comments there is desired.
