### ISSUE TITLE
No script was returned when scripting as Create on object StoredProcedure

### ISSUE THREAD

**Issue by rednaxel22** [Microsoft/sqlopsstudio#128]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. Connect to a VM 
2. Open a database existing in the VM
3. Check the Programmability -> StoresProcedures
4. Right click an stored procedure and click on "Script as Create"

**Comment by erickangMSFT** [comment]
@rednaxel22 This is under investigation. Can you confirm that the SP is not encrypted?

**Comment by rednaxel22** [comment]
Is not encrypted.

**Comment by llali** [comment]
This is a duplicate of #115
