### ISSUE TITLE
Updating causes application icon to be removed/replaced in Windows

### ISSUE THREAD

**Issue by JoshuaGarrison27** [Microsoft/sqlopsstudio#1285]
Issue Type: <b>Bug</b>

When the application is updated the following items occur:

- A new icon is added to the desktop (aka if you dont want the icon, you have to delete it after the update)
- If the application is in the start menu (on windows) then it gets removed

**Expected result:**
No new icon is created on the desktop and the shortcut is not removed from the start menu on windows.

---------------------------------------------------------------

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|Memory (System)|31.93GB (18.88GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by kburtram** [comment]
@abist I'm still getting the desktop icon when updating to the latest insider build which contains #2155.  Could you please see what's happening?

**Comment by abist** [comment]
@kburtram I'll take a look again
