### ISSUE TITLE
autocomplete stopped working after update

### ISSUE THREAD

**Issue by tekken22** [Microsoft/sqlopsstudio#1286]
Issue Type: <b>Bug</b>

after todays update autocomplete no longer works when typing query, no table name no column names

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2623 v4 @ 2.60GHz (8 x 2594)|
|Memory (System)|15.89GB (8.74GB free)|
|Process Argv|D:\3partyPrograms\micrsosft\sqlops\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by kburtram** [comment]
@tekken22 I'm not able to repro this issue internally.  Do you happen to have any other details that could help us isolated the issue?  Are you seeing any errors in the `Help -> Toggle Developer Tools` Console pane?  Did you verify the editor window has an active connection (if the editor is disconnected you'd only get keyword suggestions without tables\columns?

**Comment by tekken22** [comment]
never mind, it started working, by some reason it did not work for about 2 hours after I updated  even though there were no issues like that at the same time from SQL Server Management Studio connected to the same database. The only additional detail I have is that sqlopsstudio was hanging before while trying to connect to db, then after that issue disappeared, it seemed to be connecting fast but autocomplete stopped working.  I did verify that window was connected. Thank you.

**Comment by kburtram** [comment]
@tekken22 sounds good.  It's possible the initial IntelliSense connection failed for some reason and we don't have good retry/reconnect logic.  I'll double-check the code.  Please reactive if you hit this issue again. Thanks!

**Comment by tekken22** [comment]
autocomplete on column names basically stopped working at all last several days, I am not sure if this relates to connection issues, we do have connectivity issues from time to time but autocomplete works instantly in SQL Management Studio and also in Visual Studio data tools at exact the same time when it does not in sqlopsstudio .  It does  start working after a long while, may be several minutes but that is too slow, also even after it starts working in one tab and then I open new tab on the same connection it still will take the same long time. Let me know if there any info I can provide to help you replicate this.

![image](https://user-images.githubusercontent.com/36925936/39586438-09819fbe-4ec5-11e8-8e75-36b0b591109e.png)

**Comment by llali** [comment]
Hi @tekken22 
Can you please verify if there's any error in the log? Follow the steps here to enable the log and fine the location of the log file: https://github.com/Microsoft/sqlopsstudio/wiki/Troubleshooting-Issues

Thanks,
Leila

**Comment by llali** [comment]
@tekken22  I'm going to close this issue. If you still can repro it, please send me the logs. Thanks
