### ISSUE TITLE
Ability to edit Server level dashboard settings

### ISSUE THREAD

**Issue by Adikota** [Microsoft/sqlopsstudio#129]
- SQL Operations Studio Version:

Steps to Reproduce:

Ability to edit Server level dashboard settings with custom insights

**Comment by kevcunnane** [comment]
@Adikota could you explain more? It's possible to do this by editing the `dashboard.server.widgets` user / workspace setting

**Comment by erickangMSFT** [comment]
@Adikota This is supported feature as Kevin commented. I would propose it as a document enhancement.

**Comment by Adikota** [comment]
Got it Thanks!
