### ISSUE TITLE
SQL Operations studio SQL Agent Failed jobs just shows "Loading Error"

### ISSUE THREAD

**Issue by ndwivedi** [Microsoft/sqlopsstudio#1293]
- SQL Operations Studio Version:0.28.6
![image](https://user-images.githubusercontent.com/9135814/39397278-b1c88f1a-4aca-11e8-86a3-923b66100837.png)

Steps to Reproduce: Mange--> SQLAgent.
After clicking on "Loading Error", it shows the detail but I cannot look at the details in steps. No scroll bar visible.
![image](https://user-images.githubusercontent.com/9135814/39397386-6088fcfa-4acc-11e8-865d-1d18d13b18f9.png)
This is the most I see in steps. 

OS is Mac.
![image](https://user-images.githubusercontent.com/9135814/39397320-70ae2890-4acb-11e8-8f5a-dd974485c6e2.png)

**Comment by ndwivedi** [comment]
Just fyi.. its same on windows too. OS windows 10.

**Comment by kburtram** [comment]
@abist do you know if this is fixed in the latest round of agent changes?

**Comment by abist** [comment]
@kburtram I'll investigate the issue
