### ISSUE TITLE
No horizontal scrollbar when increasing width of columns

### ISSUE THREAD

**Issue by SvenVandenbrande** [Microsoft/sqlopsstudio#1294]
SQL Operations Studio Version: 0.28.6
SQL Agent extension Version: 0.28.1

Steps to Reproduce:
Increase the width of a column, like Name, Last Run,...

You can't see the last one(s) anymore. But you also don't have any scrollbar to scroll...

**Comment by kburtram** [comment]
@abist do you know if this is fixed in the latest round of agent changes?

**Comment by abist** [comment]
Fixed in https://github.com/Microsoft/sqlopsstudio/pull/1335
