### ISSUE TITLE
Sp_help is not displaying Table Referential constraints and Table Dependencies- Screenshots provided

### ISSUE THREAD

**Issue by lakshmanmadala** [Microsoft/sqlopsstudio#1305]
Version 0.28.6
Commit 3abbc8fd9713cdf847dcde703402d10a09eaa4ec
Date 2018-04-24T21:19:12.047Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

## _**SSMS**_
![image](https://user-images.githubusercontent.com/9732900/39477252-bb2ff322-4d2c-11e8-9a86-d3382f787c38.png)

## **_SQL Server Operations Studio_**
![image](https://user-images.githubusercontent.com/9732900/39477308-ead4a3ca-4d2c-11e8-98be-1d85cae6d6e0.png)

**Comment by kevcunnane** [comment]
@anthonydresser - can you look into this as a couple of users have reported this? It's just showing the results from multiple result sets coming back from 1 query, so it's no sp_help specific. I am wondering if this is either a bug in SlickGrid visualization or if it's something about multiple result sets from a single statement not being handled in the back end.

**Comment by kevcunnane** [comment]
I'm going to let #1118 track this since they both refer to the same issue. Closing this as a duplicate - @lakshmanmadala we'll use the other issue for tracking
