### ISSUE TITLE
Insight details adds new button each time you open the dialog

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/sqlopsstudio#1311]
- SQL Operations Studio Version:

Steps to Reproduce:
- Click Manage on any database
- on the "Backup Status" widget, click the `...` and choose `Show Details`
- Close the dialog
- Choose `Show Details` again.

Expected:
- Dialog shows up with 1 backup button
Actual:
- Each time you open the dialog, an additional `Backup` button is added

![image](https://user-images.githubusercontent.com/10819925/39497546-b0e52fe6-4d58-11e8-9123-9f3530ba4b3c.png)

**Comment by MattIrv** [comment]
This doesn't repro for me if I click the close button to close the dialog but it does if I use the escape button
