### ISSUE TITLE
SQL Agent loading indicator doesn't go away when there are no jobs

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#1327]
- SQL Operations Studio Version: `master`

Steps to Reproduce:
1. Connect to a server with no jobs.  Like an Azure DB instance

Expected: Loading indicator goes away

![screen shot 2018-05-02 at 12 17 50 pm](https://user-images.githubusercontent.com/599935/39546804-789604c8-4e0a-11e8-9b20-ddd89812c7bd.png)

**Comment by kburtram** [comment]
@abist this is on a server that doesn't supported SQL Agent (like Azure SQL), so there are not any jobs to load.  Does your hypothesis make sense in this context?

**Comment by abist** [comment]
@kburtram I'll confirm this and fix if this is an actual issue
