### ISSUE TITLE
Invalid object name '#sessions' when running EXEC sp_WhoIsActive

### ISSUE THREAD

**Issue by AbbiePetcht** [Microsoft/sqlopsstudio#1336]
1. install sp_whoisactive
2. run EXEC sp_WhoIsActive

Actual:

	Started executing query at Line 1
Warning: The join order has been enforced because a local join hint is used.
(0 rows affected)
(0 rows affected)
(0 rows affected)
(0 rows affected) 
Msg 208, Level 16, State 0, Procedure sp_WhoIsActive, Line 3418
Invalid object name '#sessions'. 
Warning: The join order has been enforced because a local join hint is used.
Warning: Null value is eliminated by an aggregate or other SET operation.
Warning: Null value is eliminated by an aggregate or other SET operation. 
Total execution time: 00:00:00.328

**Comment by corivera** [comment]
@AbbiePetcht What's the expected output here?

**Comment by AbbiePetcht** [comment]
@corivera It should run successfully. The output is empty because there is nothing running. 

![image](https://user-images.githubusercontent.com/25463959/39556966-20974ca8-4e39-11e8-853f-0ab8d05c9e36.png)

If you run WAITFOR delay '10:10:10' in another editor and then run EXEC sp_WhoIsActive. You should see this output

![image](https://user-images.githubusercontent.com/25463959/39556998-5321ea3e-4e39-11e8-97ce-def3999ee25d.png)

You can see the expected output in latest release build.
