### ISSUE TITLE
Import CSV Tool Would Be Great

### ISSUE THREAD

**Issue by bobbyxray** [Microsoft/sqlopsstudio#1338]
- SQL Operations Studio Version:

Version 0.28.6
Commit 3abbc8fd9713cdf847dcde703402d10a09eaa4ec
Date 2018-04-24T21:22:32.458Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

SSMS has a handy CSV importer. Could really use this for the SQLOPS STUDIO too.

**Comment by kburtram** [comment]
@bobbyxray we're currently tracking this request with issue https://github.com/Microsoft/sqlopsstudio/issues/785.  We are looking at the Import scenario as one of the next set of features we add to SQL Ops Studio.  Thanks for the suggestion!
