### ISSUE TITLE
Source Control Provider

### ISSUE THREAD

**Issue by warwickrudd** [Microsoft/sqlopsstudio#1350]
Issue Type: <b>Bug</b>

I recently downloaded an upgraded to version 28.6 and now under the source control tab i only receive the message "There are no active source control providers". This was working under previous versions. I have git 2.16.2 installed with an active repository. Any assistance would be appreciated.

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2295)|
|Memory (System)|32.00GB (28.80GB free)|
|Process Argv|C:\Installation Media\SQL Operations Studio\sqlops-windows-0.28.6\sqlops-windows\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql-instance-insights|mat|0.2.1
agent|Mic|0.28.1
server-report|Mic|0.1.1
whoisactive|Mic|0.1.0

</details>
Reproduces only with extensions

**Comment by kburtram** [comment]
@warwickrudd can you please confirm that you have a folder open that is currently a git repo (i.e. with a `.git` subdirectory)?  This is the message you'd typically get if there is no folder open.

**Comment by kburtram** [comment]
@warwickrudd we haven't altered the VS Code source control experience in SQL Ops Studio.  Their design is that the SCC providers are only available when a folder is open.  Probably it would be more intuitive to be able to initialize a new repo and have the folder auto-opened from the SCC viewlet, but the behavior hasn't changed from previous releases.  Thanks for reporting!
