### ISSUE TITLE
Incorrect column value while inserting Cyrillic characters

### ISSUE THREAD

**Issue by shelland** [Microsoft/sqlopsstudio#1358]
- SQL Operations Studio Version: 0.28.6

Steps to Reproduce:

1. Execute any simple INSERT statement using SQL OpStudio, e.g.:

`insert into MyTable(name) values('Это просто текст');`

2. Make a select from this table using SQL Server Management Studio.

3. Output result will be as '??? ?????? ?????'

_OS: Windows 10 (1709), Russian locale_
_SQL Server 2016 Standard, v. 14.0.1000.169_

**Comment by anthonydresser** [comment]
This seems like a mssql problem in general, the same thing happens in ssms

**Comment by shelland** [comment]
Sounds weird because I don't have such issues while using SSMS or ADO.NET library to insert a data.

**Comment by anthonydresser** [comment]
When i select the russian text in ssms it return ????? for me.
![image](https://user-images.githubusercontent.com/4324725/42399427-9a28c116-8122-11e8-978c-61b1472066c5.png)
Not sure what the underlying problem is, but that is what makes me think is a underlying engine issue.

**Comment by shelland** [comment]
Seems like this issue is tied with OS collation or something else because I have two SQL Server instances with the same collations (Cyrillic_General_CI_AS) running on different Windows systems and the SQL query results are also different. To fix this issue we just need to add a 'N' literal (e.g. N'Это мой текст') before the localized string. This issue can be closed.
