### ISSUE TITLE
The search box is too small

### ISSUE THREAD

**Issue by gandarez** [Microsoft/sqlopsstudio#1362]
Issue Type: <b>Bug</b>

The list view where the items are shown is too small. 

I'm finding for a procedure with 30 chacteres and it shows only the first 26.

![image](https://user-images.githubusercontent.com/782854/39714913-e6e2e5e0-5201-11e8-97a8-2e603283410d.png)

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|11.95GB (3.16GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces only with extensions

**Comment by kburtram** [comment]
@gandarez have you tried using the `Edit` button which should let you manually resize the widget?

![screen](https://user-images.githubusercontent.com/599935/39772715-d0cf175c-52aa-11e8-9a34-547edef4c46c.png)

**Comment by gandarez** [comment]
I didn't realize there was a button on the corner. Thanks
