### ISSUE TITLE
[loc][query] Need context for "&nbsp;Help configuring Kerberos is available at"

### ISSUE THREAD

**Issue by jiangsheng** [Microsoft/sqlopsstudio#1364]
Working on community translation but found "&nbsp;Help configuring Kerberos is available at" in the list of source string at aka.ms/loccommunity. Is this part of HTML code?

**Comment by kevcunnane** [comment]
Hi, this is shown if you try to connect to a server using `Windows Authentication` and do not have a Kerberos token. You then get the following error message:
![image](https://user-images.githubusercontent.com/10819925/39770981-81a2d2fe-52a5-11e8-9581-e63650425fe7.png)

```
Connection failed due to Kerberos error.
 Help configuring Kerberos is available at https://aka.ms/sqlopskerberos
 If you have previously connected you may need to re-run kinit.
```

**Comment by jiangsheng** [comment]
Looks like the translate engine did not recognize the HTML encoding of the space character should not be a part of localizable string. I'll raise an issue with the localization team.

**Comment by kburtram** [comment]
Closing this to track on localization team's backlog
