### ISSUE TITLE
Feature Requests - Command to inspect stored procedures, functions, etc.?

### ISSUE THREAD

**Issue by thebitguru** [Microsoft/sqlopsstudio#1365]
- SQL Operations Studio Version: Version 0.29.3 (0.29.3)

I am excited about this project and really glad to see all the effort being put on it.  When troubleshooting issues with projects I need to look at the stored procedures, functions, etc.  In some cases, I need to jump to an object that might not be in the current query.  I believe this is the intention for the peek definition functionality (which works for tables).  Will it support stored procedures and functions (request 1)?  If so, will it be possible to allow searching for objects (tables, stored procedures, functions, etc.) in something like the Cmd+P dialog (request 2)?

**Comment by kburtram** [comment]
@thebitguru Peek Definition\Go to Definition is supposed to work with sprocs and functions (see screen below).  Though I think there are some parsing errors that may cause it to fail in some situations.  These would be functional bugs we'd like to fix.  Please let us know if you have a specific example that's failing.

<img src='https://user-images.githubusercontent.com/599935/39771803-40db4b0e-52a8-11e8-9d7f-b15bdc144b1a.png' width='500px'
 />

You should be able to locate the sproc in Object Explorer and run the `Script as Create` to view the definition if `Peek Definition` isn't working in a particular case.

For searching database objects we recommend trying out the `Redgate SQL Search` extension.

**Comment by thebitguru** [comment]
Thanks for the quick response, @kburtram.  Interesting.   This might be a bug then.

I have tried a few variations as shown in the screenshot, but no luck.  I also tried select the name with an without the schema and had the same outcome.  It does seem to work with sys.sp_who, though.

![image](https://user-images.githubusercontent.com/163550/39773910-fdaac636-52be-11e8-9d04-0f8e46bd098d.png)

For my second request, is there a dialog where I can search for object to peek?

**Comment by kburtram** [comment]
@thebitguru for the issue in the screenshot, I think that is the same as https://github.com/Microsoft/sqlopsstudio/issues/120.  This looks like a bug parsing out the sproc name and getting mixed up with the schema name.

We don't have a built-in dialog to find an object and peek its definition.  Though `Redgate SQL Search` does provide this functionality using a document window.  You can search across all databases on the active connection, then there is a context menu that allows you to get to the objects definition.

**Comment by thebitguru** [comment]
Yes, you are right, #120 is likely the culprit here.

I will try out the Redgate extension.  I do feel like this would have been awesome part of the core SQL Ops.  I will go ahead and close the issue.

Thanks for all the quick replies!
