### ISSUE TITLE
Missing SQL keyword "BETWEEN"

### ISSUE THREAD

**Issue by lmfs** [Microsoft/sqlopsstudio#1372]
Issue Type: <b>Bug</b>

Keyword BETWEEN in SQL editor is missing. Intellisense/autocomplete does not find it and syntax coloring does not work for keyword.

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz (12 x 3200)|
|Memory (System)|15.94GB (6.04GB free)|
|Process Argv|C:\__APPS\sqlops-windows-0.28.6\sqlops-windows\sqlops.exe -n|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
whoisactive|Mic|0.1.1

</details>
Reproduces without extensions

**Comment by naimsulejmani** [comment]
Also on version 0.29.3 the BETWEEN keyword doesn't suggest, autocomplete and syntax isn't colored

**Comment by abist** [comment]
Closing as this seems fixed.
