### ISSUE TITLE
Document inherited VSCode Shell Version along with Electron Shell version

### ISSUE THREAD

**Issue by pradm** [Microsoft/sqlopsstudio#1376]
- SQL Operations Studio Version:
Version 0.29.3
Commit 7099922c35bc3b3e223228c972cc03cee5abbe25
Date 2018-05-04T05:46:24.032Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
Similar to the Electron Shell version can we also print the VSCode Shell version inherited; This would be useful while troubelshooting issues which might be in VSCode shell impacting SQLOps and could have been resolved in the latest version of VSCode releases or documented already.

Version 0.29.3
Commit 7099922c35bc3b3e223228c972cc03cee5abbe25
Date 2018-05-04T05:46:24.032Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by kburtram** [comment]
The VS Code version will be in the About dialog in the next `insiders` and `stable` builds.
