### ISSUE TITLE
Extension Manager isn't showing

### ISSUE THREAD

**Issue by mackenziemi** [Microsoft/sqlopsstudio#1382]
- SQL Operations Studio Version: May Release version  0.28.6

Steps to Reproduce:

Download and install the May release of Sql Ops Studio
Open Sql Ops Studio

There isn't an icon for the Extension Manager. =(

**Comment by MattIrv** [comment]
@mackenziemi did the previous version show it? It sounds like it may have gotten manually disabled somehow - to reenable it, you should be able to right click in the bar where the icon should be and click on "Extensions". If that doesn't work please let us know

**Comment by mackenziemi** [comment]
Right clicking on the bar did the trick, don't know why I didn't think to
try that. Thank you for your help and your patience.

Thanks
-MacK

**Comment by mackenziemi** [comment]
I don't know why I didn't think to right click on that bar but that did the trick. Thank you for your help and your patience!
