### ISSUE TITLE
SQL Job Name is not showing properly SQL Agent

### ISSUE THREAD

**Issue by nivGandhi** [Microsoft/sqlopsstudio#1386]
- SQL Operations Studio Version:

Steps to Reproduce:

Hello Team,

I am using the SQL Agent and i found that if your Job name is long, it's not showing properly and the scroll buttons is not working properly.

![image](https://user-images.githubusercontent.com/6292140/39866707-59da4de4-546f-11e8-8923-74cf8fb159cb.png)

**Comment by kburtram** [comment]
@abist could you please look at this?  I also noticed that the column sizes now seem to be constrained by the size of the dashboard window.  The user should be able to make the table columns wider than the size of the dashboard window so the entire column values are visible (of course with correct scroll behavior).

**Comment by abist** [comment]
@nivGandhi Could you tell us which version of SQL Ops you're using?

**Comment by nivGandhi** [comment]
Version 0.29.3- Latest version

**Comment by nivGandhi** [comment]
Version 0.29.3
Commit 7099922c35bc3b3e223228c972cc03cee5abbe25
Date 2018-05-04T05:46:24.032Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
