### ISSUE TITLE
The context menu shows "disconnect" when the connection is already disconnected

### ISSUE THREAD

**Issue by AlexTroshkin** [Microsoft/sqlopsstudio#139]
- SQL Operations Studio Version: sqlops 0.23.6 (85fd52b50a4bf6dec0f5314d22535317fd5167b2, 2017-11-02T12:00:00.000Z)
- OS Version: Windows_NT x64 10.0.16278
---

Steps to Reproduce:

1. Add any connection
2. Call context menu at the connection and click "Disconnect"
3. Call context menu again

![capture](https://user-images.githubusercontent.com/11016542/32983673-636b5ce8-cca9-11e7-9141-afa9bcc5dd87.PNG)

Expected: do not show "Disconnect" or add "Connect"

**Comment by llali** [comment]
this is fixed and will be in the next release
