### ISSUE TITLE
Title Bar and Toolbox Controls ghosted

### ISSUE THREAD

**Issue by cjquest** [Microsoft/sqlopsstudio#1394]
Issue Type: <b>Bug</b>

When the application runs it is full screen. When clicking where the Title Bar and the Toolbox controls are results in actually clicking on the desktop, this extends down about 2 cm where double clicking on SQL Operations Studio executes icons on the desktop.

![image](https://user-images.githubusercontent.com/39195628/39931823-704be2be-5536-11e8-80af-fc8987c517f9.png)

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz (8 x 3000)|
|Memory (System)|31.83GB (22.44GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by kburtram** [comment]
@cjquest do you have any additional repro steps?  I was unable to repro this issue.

**Comment by cjquest** [comment]
@kburtram I haven't been able to reproduce it since. After rebooting the PC it hasn't occurred again so may be related to Windows 10, although I haven't seen any other application do this. At the time no other applications exhibited this behaviour.
