### ISSUE TITLE
Copy from cell in results window does not work

### ISSUE THREAD

**Issue by mattneerincx** [Microsoft/sqlopsstudio#14]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Run a query.
2. In output result, select some cell.
3. Hit  Ctrl-C to copy value
4. Go to query window and paste.

Does not work.   In order to copy from cell you have to right-click on cell and select Copy

**Comment by praveenksharma** [comment]
Is it fixed? I was able to reproduce it today morning.

**Comment by praveenksharma** [comment]
Strange. It's working now.
