### ISSUE TITLE
Problems on install SQLops on CentOS 7

### ISSUE THREAD

**Issue by lafs0501** [Microsoft/sqlopsstudio#1411]
- SQL Operations Studio Version:

Steps to Reproduce:
the error message is : file not support ?

I have install SQL Server 2017 without any problems, but I cannot be able to install SQLOPS version 0.29.3 and i don know why.
Someone could give me helps because i am a beginner on Linux world.
Best regards,
LS

**Comment by kburtram** [comment]
@lafs0501 have you tried the RPM installation instructions at https://docs.microsoft.com/en-us/sql/sql-operations-studio/download?view=sql-server-2017.  That is the easiest way to install on CentOS, though the tar.gz installation also should work.

**Comment by kburtram** [comment]
@lafs0501 there are instructions for installing from tar.gz in the above docs links.  Please let me know if those steps are unclear.

**Comment by kburtram** [comment]
@lafs0501 please let me know if you still are having issues installing on Linux.  I'll close this issue for now since there aren't recent updates.

**Comment by lafs0501** [comment]
Hello Karl,

I apologize for answering you just now.
Your reply solve the problem.

Best regards,
Luís Santos


Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
