### ISSUE TITLE
objects in tempdb have incorrect highlighting

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/sqlopsstudio#142]
- SQL Operations Studio Version:

Steps to Reproduce:
Enter: CREATE TABLE #foo (bar int);

Everything from the number sign (hash for the UK) is green, but should be the same colors as;
CREATE TABLE foo (bar int);

**Comment by abist** [comment]
Duplicate of https://github.com/Microsoft/sqlopsstudio/issues/98
