### ISSUE TITLE
Dropdown components only show 1 value

### ISSUE THREAD

**Issue by AbbiePetcht** [Microsoft/sqlopsstudio#1422]
let dropdown = view.modelBuilder.dropDown()
                        .withProperties({
                        value: 'Full',
                                                                                                values: ['Full', 'Differential', 'Transaction Log']
                    })
                        .component();

Actual:
In the dialog it only show value in the dropdown.
![image](https://user-images.githubusercontent.com/25463959/40074421-6d254044-582e-11e8-89f9-bc770748e750.png)

Expected:
It should show all options.

**Comment by llali** [comment]
This is how editable drop down designed. The list gets filtered by the value in the input box and gets reset if the value is removed. we should create a separate bug for the editable drop down if different behavior is expected. For the model view I changed the drop down to be editable and not editable. so by setting the drop down property editable to false, the list will be a regular drop down
