### ISSUE TITLE
Extension Manager - extensions are not sorted in the Market Place panel

### ISSUE THREAD

**Issue by llali** [Microsoft/sqlopsstudio#1426]
- SQL Operations Studio Version:

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/17187348/40076358-8e110b58-5833-11e8-83a3-4de6b5ec206f.png)

**Comment by kburtram** [comment]
@llali the current sorting behavior is that recommended extensions are sorted above other extensions.  Within the two groups the extensions should be sorted alphabetically.  I think the screenshot shows this sorting behavior.
