### ISSUE TITLE
double clicking a @local_variable does not select the @ symbol

### ISSUE THREAD

**Issue by initram** [Microsoft/sqlopsstudio#1432]
- SQL Operations Studio Version: 0.29.3

Steps to Reproduce:
enter the following into a query editor window:
`DECLARE @updateId INT = 2798`
double click on the variable name (updateId), only the name and not the @ are selected

This is a pain when I want to copy paste a variable around in my sql query. I have to do a drag select instead of double clicking. This works as expected in Visual Studio and in SQL Management Studio.

**Comment by kburtram** [comment]
This looks like a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/143.  This is something we're looking at, but I think the issue may be in the VS Code editor code.
