### ISSUE TITLE
Edit Data throws a bunch of errors on Adventure works person.address table

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#1438]
- SQL Operations Studio Version: `master`

Steps to Reproduce:

1. Edit Data AdventureWorks `Person.Address` table

![screen](https://user-images.githubusercontent.com/599935/40191633-e9515002-59b6-11e8-8199-fe0248f6540d.png)

**Comment by MattIrv** [comment]
Confirmed this was fixed by Karl's Tools Service change linked above
