### ISSUE TITLE
Autocomplete should ignore case sensitivity

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/sqlopsstudio#144]
- SQL Operations Studio Version:
Steps to Reproduce:
DECLARE @var in = 42;

Start typing PRINT @v -- lowercase 'v'
Autocomplete does not suggest @var

Do it again PRINT @v -- uppercase 'V'
Autocomplete suggests @var

Unless db collation is set to CS, Autocomplete should work with both statements.

**Comment by kburtram** [comment]
Please reactive if this still repros.
