### ISSUE TITLE
Setting sql.intelliSense.lowerCaseSuggestions to true has no effect

### ISSUE THREAD

**Issue by szabolcsx** [Microsoft/sqlopsstudio#145]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299 / Ubuntu 17.10

Steps to Reproduce:
1. Open User settings
2. Insert the following line: `"sql.intelliSense.lowerCaseSuggestions": true`
3. Start typing `select` in an open file

As the title says, setting the `sql.intelliSense.lowerCaseSuggestions` to `true` doesn't have any effect, I still get UPPERCASE IntelliSense.

Using the `Format Document` does make everything lowercase.

Here is a GIF demonstrating the issue (The settings are unsaved because I removed the SQL server password while recording):
![casing_bug](https://user-images.githubusercontent.com/2766129/32991108-28fd22ea-cd3e-11e7-98e0-da25bfc754f4.gif)

**Comment by kburtram** [comment]
@szabolcsx this is a bug in the settings metadata.  The setting name is actually `mssql.intelliSense.lowerCaseSuggestions`.  We'll fix this in the next release.

**Comment by szabolcsx** [comment]
@kburtram thanks for the update! I updated my settings and now it works.
