### ISSUE TITLE
Cancel change connection disconnects current connection

### ISSUE THREAD

**Issue by robg37** [Microsoft/sqlopsstudio#1474]
Issue Type: <b>Bug</b>

Open a database connection.  Create a new query.  Select "Change Connection."  Cancel the Connection dialog.  The query will now be disconnected.

The expected behavior would be to keep the current connection open until a new connection is actually selected.

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|Memory (System)|15.91GB (0.95GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by MattIrv** [comment]
This is fixed in master now so it will be included in our next release
