### ISSUE TITLE
Dialog pane should have a scroll bar if the content is bigger than the size of the dialog pane

### ISSUE THREAD

**Issue by AbbiePetcht** [Microsoft/sqlopsstudio#1485]
- SQL Operations Studio Version:

Steps to Reproduce:

**Comment by MattIrv** [comment]
@AbbiePetcht can you give an example of when there should be a scrollbar? As far as I know this already works correctly, for example if you open a dialog with a form input component wider than the dialog:

![Dialog with a very wide form component forcing a scrollbar to appear](https://user-images.githubusercontent.com/3758704/40517316-7b70affc-5f69-11e8-941f-fc352bbdfe4d.png)

**Comment by llali** [comment]
@AbbiePetcht  the dialog has the scroll bar, I think we should fix this by adding the scroll bar to the editor

**Comment by AbbiePetcht** [comment]
@MattIrv @llali I have checked in sample in sqlservice
use command 'sqlservices.openEditorWithWebView2'
Minimize the window size - There is no scroll

In doUpdateContainer in src\sql\parts\modelComponents\modelEditor\modelViewEditor.ts I added modelViewContainer.style.overflow = 'scroll'; I get double scroll.

![image](https://user-images.githubusercontent.com/25463959/40746890-7cdbf9b8-6410-11e8-8603-f2f9af549510.png)

**Comment by llali** [comment]
@AbbiePetcht  can you verify this is still happening?

**Comment by AbbiePetcht** [comment]
It doesn't repro. I will close this issue
