### ISSUE TITLE
No response to Add Connection on macOS  - zone.js error in console

### ISSUE THREAD

**Issue by poojanarayanan28** [Microsoft/sqlopsstudio#1486]
- SQL Operations Studio Version: 
Version 0.29.3 (0.29.3)

Steps to Reproduce:

1. Open SQL Operations Studio in macOS
2. Click on Add Connection

I checked the developer console (Help -> Toggle Developer Tools, Console tab) and found the below 

**Error: Unsupported platform 
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js :2251** 

Kindly help, none of the forums have a solution for this

**Comment by MattIrv** [comment]
@poojanarayanan28 which version of macOS are you using? We throw this error for versions of macOS older than Sierra (10.12.0) because we use .Net Core, which doesn't work on older versions.

**Comment by poojanarayanan28** [comment]
I'm using Mac OS Yosemite ( version 10.10.5),  so would upgrading my OS to the latest( Sierra) resolve my problem?

**Comment by MattIrv** [comment]
Yes, it should work if you upgrade to Sierra or newer (High Sierra is the current version)

**Comment by poojanarayanan28** [comment]
Thanks, it worked!
