### ISSUE TITLE
Widget Template Query Problem with Turkish Language

### ISSUE THREAD

**Issue by rcavusoglu** [Microsoft/sqlopsstudio#149]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
I enabled "table space for insight". But I countered an error because "Indexes" and "indexes" are different in my language (Turkish). I solved this problem by changing the default sql code.

The application should consider this kind of Character problem.

![image](https://user-images.githubusercontent.com/30176086/32993308-3f5ecc90-cd67-11e7-9480-807d1edede71.png)

**Comment by kevcunnane** [comment]
This looks like the same issue as #154 where it's case-sensitive collation on the server that's causing the error. I'll look to fix internally. @erickangMSFT  we need to be careful in the future to have exact casing for any system object references so this doesn't happen in the future.

**Comment by rcavusoglu** [comment]
@kevcunnane 
This is not only about case-sensitivity. My collation is Turkish CI-AS and that is insensitive. This is about Turkish Latin Based alphabet. Problem is English alphabet haven't 'ı' and 'İ' character.  Upper case of 'i' is 'İ', it is not 'I'. ('ı','I') and ('i','İ') is very different. That is every time problem for English language base program with Turkish based Collacation.
