### ISSUE TITLE
Rename Connection Feature

### ISSUE THREAD

**Issue by VikasShinde** [Microsoft/sqlopsstudio#1491]
Issue Type: <b>Feature Request</b>

When i Connect To my Database Connection Name look like ugly so I request to add Change And rename connection name for better find to which connection is that

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 10.0.17134

**Comment by MattIrv** [comment]
Thanks for the feedback! This in on our roadmap for an upcoming release and we're tracking it at https://github.com/Microsoft/sqlopsstudio/issues/66, so I'm going to mark this issue as a duplicate and close it. Please let me know if you have any questions
