### ISSUE TITLE
Copy (Ctrl-C) from query result window does not work

### ISSUE THREAD

**Issue by mattneerincx** [Microsoft/sqlopsstudio#15]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:

1. Run some query that produces results.
2. Select some cell and press Ctrl-C
3. Open notepad and paste

Result: nothing is copied.  Right-click on Cell and select Copy does work.

**Comment by kevcunnane** [comment]
@anthonydresser could you take a look? I know we had an issue with single-cell copy before. @mattneerincx if you select multiple cells will that work? Just trying to scope the issue, thanks!

**Comment by kevcunnane** [comment]
Following up on this - I think the real issue is that we show the cell as selected.
- On executing a query, we put the focus back in the query editor window just like in SSMS, but the cell shows as selected
- Ctrl+C will be focused in the query window
- If I actually click on a specific cell and do Ctrl+C, it copies as expected

So this is really the issue where we should clear out the selection state from the results view, especially on 1st view.

**Comment by felipeff** [comment]
I don't know if it should be a new issue or what but if you select the entire column by clicking the column header, then hold control or shift to select multiple columns. Then try to copy, it copies only 1 column always.

**Comment by kevcunnane** [comment]
@felipeff separate issues would be great. It'll let us keep track more effectively.

**Comment by PierreRossouw** [comment]
Yea I have the same issue:

Version 0.23.6 on Windows 10

Selecting a single cell in the result set and hitting Ctrl C does not place anything on the clip board.

Same thing for selecing a row or a column, nothing is copied.

Also Ctrl+A doesn't select anything either in the results grid. Right-click Select All does work. Also clicking in the top left corner of the results grid does not work - nothing happens. I'd expect it to select the entire results grid same as Ctrl+A

**Comment by kevcunnane** [comment]
We should have a fix for this internally thanks to @anthonydresser. At least for the rangy error part, and we believe this should resolve the remaining issues here.

**Comment by kburtram** [comment]
This should be fixed in this build https://github.com/Microsoft/sqlopsstudio/releases/tag/v0.24.1.  If not, please reopen this issue.  Thanks!
