### ISSUE TITLE
Edit data cells need to be clicked twice before being editable

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#1500]
- SQL Operations Studio Version: master 8fce79f

Steps to Reproduce:
1. Open edit data
2. Click on a cell and try to edit it

Actual behavior: You have to click again in order to edit it. When you click again, the current value is not selected
Expected behavior: You should only have to click once to edit the cell, and when you click on the cell its text should be selected so that you can easily replace it (like SSMS)

First click:
![The cell is selected but there is no cursor to edit](https://user-images.githubusercontent.com/3758704/40570059-e313e0fc-603b-11e8-85ed-b872fdc395a6.png)

Second click:
![The cell is selected an an edit cursor is available](https://user-images.githubusercontent.com/3758704/40570062-eb37de0a-603b-11e8-817c-cd4267ba46f5.png)

**Comment by kburtram** [comment]
@MattIrv as you mentioned, I opened a duplicate issue for this bug at https://github.com/Microsoft/sqlopsstudio/issues/1613.  Since there is already discussion there I close this one.  Thanks!
