### ISSUE TITLE
Agent fails to relayout when resized offdom

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/sqlopsstudio#1513]
Different tabs on the dashboard display odd behavior on window resize.

- Home, Server Reports, and sp_whoisactive do not snap back to a larger window size after sizing down
- SQL Agent loses all content even if it is not the active tab during resize

![image](https://user-images.githubusercontent.com/8250560/40736821-e9675d74-63f3-11e8-9ffd-7fafc221a134.png)

![image](https://user-images.githubusercontent.com/8250560/40736772-ca19c7f4-63f3-11e8-9ad4-c5f51fe355bd.png)

![sql ops resize](https://user-images.githubusercontent.com/8250560/40737117-ab5921ba-63f4-11e8-9728-bdd4a0e8434d.gif)

- SQL Operations Studio Version: 
Version 0.30.2-insider
Commit 6aac0b6056b9f45d6988d2d3796e65e6c9078eb6
Date 2018-05-22T00:19:22.794Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by anthonydresser** [comment]
The resize issue is a known issue, although I can't find the issue ticket for it, so I recreated it here #1560 its a library issue thats been around since we started the dashboard. I'm going to rename this to reflect the problems noted with agent.
