### ISSUE TITLE
Model view select box doesn't have selected value or hover effect

### ISSUE THREAD

**Issue by AbbiePetcht** [Microsoft/sqlopsstudio#1530]
Looking it is themeing issue
![image](https://user-images.githubusercontent.com/25463959/40808806-2f63c7f6-64dd-11e8-9c07-52ca3d5bc982.png)

**Comment by MattIrv** [comment]
I just merged vs code 1.23.1 which I think fixed this problem. Can you take a look to verify when you get a chance?
