### ISSUE TITLE
Need the Ability to Use Sql on Edit Data

### ISSUE THREAD

**Issue by chadwillson** [Microsoft/sqlopsstudio#1536]
Hello,

I am excited about sql ops studio.

I will need the ability to write sql on "Edit Data" to find the data I need.

This is a feature in ssms (right click > pane > sql)

After this update I will switch over from ssms.

Thanks and let me know.

**Comment by MattIrv** [comment]
@chadwillson you'll be glad to know that this feature is included in the latest insiders releases and is planned to be included in our June stable release later this month.

You can find more discussion on the issue at https://github.com/Microsoft/sqlopsstudio/issues/78 and grab the latest insiders build from https://github.com/Microsoft/sqlopsstudio/releases/tag/0.30.2 if you'd like to check it out.
