### ISSUE TITLE
Intellisense not working for database schema / table

### ISSUE THREAD

**Issue by DerekSMorin** [Microsoft/sqlopsstudio#154]
- SQL Operations Studio Version:

Steps to Reproduce:

Intellisense is not working here:

![image](https://user-images.githubusercontent.com/7568856/33015841-37419e04-cdba-11e7-94b8-7745754b810e.png)

**Comment by kburtram** [comment]
I'll close this as "no repro".  Please reactive if you're still hitting this issue.
