### ISSUE TITLE
Unsupported Platform on Mac

### ISSUE THREAD

**Issue by ndunn219** [Microsoft/sqlopsstudio#1540]
Issue Type: <b>Bug</b>

Open sqlopps
Toggle Developer Tools
Error reads:
Unsupported platform
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:33:06.510Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv|/Applications/SQL Operations Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by kburtram** [comment]
@ndunn219 SQL Ops Studio has a dependency on .Net Core 2.0 which unfortunately is only supported on macOS Sierra (and later) OS versions.  I think that `Darwin x64 15.6.0` is `El Capitan` release.

To help us understand the impact, is there anything that's blocking you upgrading the OS (such as hardware or software compatibility issues)?

**Comment by ndunn219** [comment]
Upgrading to macOS Sierra did the trick. Thanks.
