### ISSUE TITLE
Intellisense Refresh

### ISSUE THREAD

**Issue by pavinan** [Microsoft/sqlopsstudio#155]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.10586
---

Steps to Reproduce:

1. Use sp_rename to rename a column.
2. Editor still shows old name.

Add Ctl + Shift + R functionality.

**Comment by kevcunnane** [comment]
There is a `Refresh Intellisense Cache` command. You should be able to set a keybinding for this using the Keyboard Shortcuts (Click `Ctrl+Shift+P` -> Type `Refresh Intellisense Cache`). Does this solve your issue?

**Comment by pavinan** [comment]
Yes, Is there any documentation site for these commands.

**Comment by erickangMSFT** [comment]
@pavinan https://docs.microsoft.com/en-us/sql/sql-operations-studio/keyboard-shortcuts let's improve the doc and list all supported commands and shortcuts.

Shortcuts are all customizable too.
