### ISSUE TITLE
Authentication Types in Linux

### ISSUE THREAD

**Issue by estebanbermudez** [Microsoft/sqlopsstudio#1558]
- SQL Operations Studio Version: 0.28.6

Steps to Reproduce: 
I notice that the Linux version have the “windows auth” authentication type. Shouldn’t this be remove from the Linux version, since it is not allow win auth for [Linux?](url)

this can be reproduce when opening a new server connection.

**Comment by anthonydresser** [comment]
I believe the windows auth is really integrated auth. I remember there being some support for mac os for integrated auth, but I'm not sure what the status was for Linux. 

@kburtram are there updates on this? Should we remove this option for some OSs or should we rename it to be more descriptive of what it actually is?

**Comment by kevcunnane** [comment]
This works on all supported OSes. The decision was to keep the name `Windows Authentication` though it's technically more accurate to call it `Integrated Authentication` or `Kerberos Authentication` on non-Windows systems. Instructions for configuring authentication are at https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication?view=sql-server-2017

**Comment by estebanbermudez** [comment]
thanks. will try that.

**Comment by kburtram** [comment]
I'll close this based on @kevcunnane's response.  Please reopen if there are further questions.
