### ISSUE TITLE
Caracteristica

### ISSUE THREAD

**Issue by luisalberto1192** [Microsoft/sqlopsstudio#1567]
- SQL Operations Studio Version:

Steps to Reproduce: Editar campos de una tabla con interfaces

**Comment by kburtram** [comment]
@luisalberto1192 when I translate the above text I get the following "Edit fields in a table with interfaces".  I'm unclear please what's the bug or suggestion from the information provided.  Could you please reactive this issue with additional details if you're still experiencing the issue?
