### ISSUE TITLE
Results grid should resize to its content

### ISSUE THREAD

**Issue by salarcode** [Microsoft/sqlopsstudio#1570]
Results grid should resize to its content just like SQL Management studio.
There can be more options to control the behavior like: 
'Limit shrinking to column name length'
'Limit growing to x characters'

**Comment by kburtram** [comment]
@salarcode thanks for the suggestion.  I think this is the same issue we're tracking in https://github.com/Microsoft/sqlopsstudio/issues/172.  Please reopen if this is a different issue, or add additional comments on that issue.  Thanks!
