### ISSUE TITLE
Feature request : Rename query tabs without having to save files

### ISSUE THREAD

**Issue by netcrawler00** [Microsoft/sqlopsstudio#1571]
- SQL Operations Studio Version:
Version 0.29.3
Commit 7099922c35bc3b3e223228c972cc03cee5abbe25
Date 2018-05-04T05:46:24.032Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
When working, we often end up with many tabs with sequential names, and today, the only way to change this is to save the query in a file.

As a query builder, 
I want to be able to rename my query windows
so that I can easily get back to a query without browsing all tabs nor saving all files.

**Comment by anthonydresser** [comment]
dupe #956
