### ISSUE TITLE
Cannot Alt + select text

### ISSUE THREAD

**Issue by Ravi5ingh** [Microsoft/sqlopsstudio#1572]
Issue Type: <b>Bug</b>

Text columns cannot be selected and this is a major issue when dealing with SQL. ie. When we press down on the Alt key and select text, it should select only the column like you can do with SQL Server Management Studio, notepad++ and other editors

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 10.0.17134

Reproduces without extensions

**Comment by kburtram** [comment]
@Ravi5ingh the box select keyboard shortcut in SQL Ops Studio is SHIFT+ALT+"drag mouse".  Please reopen if that doesn't do what you expect.
