### ISSUE TITLE
Dropdown for change database shows up in corner of window

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/sqlopsstudio#1573]
- SQL Operations Studio Version:
0bf642d release build

probably caused by the vscode merge

Steps to Reproduce:
The first time you use the dropdown when you open sqlops it shows up in the corner

![image](https://user-images.githubusercontent.com/4324725/41112560-2dc56b00-6a34-11e8-9403-2dd94e87d81a.png)

**Comment by kburtram** [comment]
@anthonydresser I wasn't able to repro on the latest builds in `master`.  Could you please confirm if this still repros for you?
