### ISSUE TITLE
Switching tabs doesn't pick the first panel tab any more

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#1582]
When you first open dashboard, switch to the SQL Agent tab. The jobs tab from the component should be selected automatically, but doesn't any more. Screenshot - 

![basicgraph](https://user-images.githubusercontent.com/6411451/41125255-b347e414-6a58-11e8-8a77-eca1bd3132e1.JPG)

**Comment by anthonydresser** [comment]
Whats the commit this repros on?

**Comment by abist** [comment]
@anthonydresser I tried it on master
