### ISSUE TITLE
Results grid text display is messed up by international characters

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#1612]
- SQL Operations Studio Version: `master`

Steps to Reproduce:
1.  Use AdventureWorks sample database and run the below query.

```SQL
SELECT TOP (1000) [JobCandidateID]
      ,[BusinessEntityID]
      ,[Resume]
      ,[ModifiedDate]
  FROM [AdventureWorks].[HumanResources].[JobCandidate]
```

<img width="377" alt="screen" src="https://user-images.githubusercontent.com/599935/41273052-b0705448-6dcc-11e8-809c-5325cd283bc6.png">

**Comment by anthonydresser** [comment]
It looks like this was caused by the same problem as the other html issues.
