### ISSUE TITLE
Edit Data cells not editable when using TAB to navigate

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#1613]
- SQL Operations Studio Version: `master`

Steps to Reproduce:
1. Open Edit Data window
2. Tab between cells

Expected:
Non-readonly cells will be editable with content selected to be overwritten.  This is behavior in `0.29.3`.

Actual: 
Cells are not editable and content is not selected.  Cells still writable if cell is clicked on.

**0.29.2**
<img width="446" alt="0 29 3" src="https://user-images.githubusercontent.com/599935/41273469-7b1429d0-6dce-11e8-9e3f-4e23fcdd54e1.png">

**master**
<img width="450" alt="master" src="https://user-images.githubusercontent.com/599935/41273480-8185ac6c-6dce-11e8-9ab6-b46406d7af87.png">

**Comment by anthonydresser** [comment]
This is probably caused by the changes to the accessibility focusing behavior, which we need. We should rethink out keyboard nav anyways, since tab is not supposed to navigate inside of a grid anyways (at least traditionally) it is supposed to go to the next none grid element on the page.

**Comment by MattIrv** [comment]
Looks like it may be the same issue as #1500

**Comment by kburtram** [comment]
@anthonydresser how is the user supposed to edit a cell without clicking on the cell?  This is a scenario we absolutely need to support.

Could you please identify the specific change that is causing this behavior?  If we don't have a quick fix we should revert in the release branch for June release.

**Comment by kburtram** [comment]
@anthonydresser it looks like reverting SlickGrid back to 2.3.16 resolves resolves this issue back to May Public Preview behavior.  I imagine that this would also make us lose various other improvements?

The current Edit Data behavior is fundamentally broken as far as I can tell, so this issue will block the June release.  Do we have a better short-term option than revert the SlickGrid update?  Do we know what will be broken\regressed from reverting SlickGrid update?

**Comment by anthonydresser** [comment]
We'll loose the accessibility updates for the grid

**Comment by kburtram** [comment]
@anthonydresser unfortunately we can't accessibility changes that break basic functionality in our core scenarios.  We'll need to find another way to satisfy accessibility requirements.  

Please let me know if you can find a better fix than reverting in the short-term, otherwise, we should pull back that change until we have accessibility fixes that don't introduce significant regressions.  Thanks!

**Comment by kburtram** [comment]
I've switched back to 2.3.16 in release/0.30 for June Public Preview and moved this issue to July milestone.
