### ISSUE TITLE
Specify Windows Auth credentials when workstation on a different domain than client

### ISSUE THREAD

**Issue by ethanbergstrom** [Microsoft/sqlopsstudio#162]
Can't log in from workstation on different domain than server - SQL Operations Studio Version: 0.23.6

Steps to Reproduce:

1. Workstation on Domain A
2. Server on Domain B
3. Try to launch Ops Studio from Workstation using Windows credentials
4. Unable to specify credentials in Domain B to authenticate

**Comment by erickangMSFT** [comment]
@calan89 try runas command and start sqlopsstudio with Domain B authentication user. https://technet.microsoft.com/en-us/library/cc771525(v=ws.11).aspx 

Asking to all community: any suggestion or better solution than runas?

**Comment by erickangMSFT** [comment]
@calan89 it seems runas is not working for sql ops studio. Testing...

**Comment by erickangMSFT** [comment]
marked as 'bug' for RunAs part.

**Comment by sahilNaran** [comment]
How would I do this on a mac?

**Comment by MikePitt** [comment]
Ability to enter Windows credentials when using this on a Mac or Linux is essential.  This is possible in other similar tools so hopefully Microsoft will make this happen.

**Comment by wiltshih** [comment]
Not sure if this is still an active bug - but on windows I have been able to runas using -
runas /netonly /user:domain\user "C:\..pathToOps..\sqlops.exe"

**Comment by genio** [comment]
@wiltshih As the others have pointed out, you can't do this on a Mac or Linux. We'd need a way to provide credentials.

**Comment by sahilNaran** [comment]
Any progress on this?

**Comment by eaglearchbvi** [comment]
This appears to still be a problem since runas won't let it open or connect to the db

**Comment by kburtram** [comment]
We're tracking "multiple Windows Auth from single machine" suggestions in this issue https://github.com/Microsoft/sqlopsstudio/issues/112.  Please reactive if this suggestion is significantly different than what we're tracking there.
