### ISSUE TITLE
Feature Suggestion: Get Connection String for existing connection

### ISSUE THREAD

**Issue by julielerman** [Microsoft/sqlopsstudio#1620]
- SQL Operations Studio Version: 0.29.3

I am connected to a SQL Server database which I did by supplying the connection string pieces to SQL Ops. Now I want to use that same database in an app and ...like most people, after decades working with SQL Server, I cannot write a SQL Server connection string off the top of my head ...so would love it if I could get the string somehow from the existing connection without heading to connectionstrings.com.  Maybe on the context menu of a database along with Manage, etc. :)

**Comment by kburtram** [comment]
This should be available in the next `insiders` build later this week.  Please reactive if the implementation doesn't match-up with the suggestion.  There's some details in the related PR (https://github.com/Microsoft/sqlopsstudio/pull/2108).
