### ISSUE TITLE
Extensibility: Dropdown should support objects with labels just like `showQuickPick` in vscode namespace

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/sqlopsstudio#1621]
This is a common scenario: I want a user-readable display name for a set of options in the dropdown, but to actually receive back an object with additional info (like an ID) when doing logic operations. Can we have 2 methods just like `vscode.window.showQuickPick`? It has 2 overloads:
- default method accepts `items: string[]`, but has `showQuickPick<T extends QuickPickItem>(items: T[] | Thenable<T[]>` overload.

Note I don't necessarily think we need the QuickPickItem as we don't need description / detail, but having an object with a label property (and ability to extend with extra info) is important.

**Comment by llali** [comment]
@kevinvngo dropdown now supports values which are {displayName: string, name: string} 
and value is the name of each item. It's not the same format you requested but it supports having display name for items. if you still want to have this feature please reopen

**Comment by kevcunnane** [comment]
Wrong Kevin, but thanks for implementing 😄 this will make it much easier to display localized strings and map back using an ID.

**Comment by llali** [comment]
oops sorry :)
