### ISSUE TITLE
Wizard: Error messages appear behind wizard pane

### ISSUE THREAD

**Issue by corivera** [Microsoft/sqlopsstudio#1626]
@MattIrv 

Example: When getting an exception during page validation, the user has to close the wizard in order to view the message.

**Comment by kevcunnane** [comment]
Is the right thing here to build in an area for displaying general error messages?

**Comment by MattIrv** [comment]
Closing this now that errors can be shown in wizards and dialogs. I played around with putting the existing error notification elements in front of wizards and dialogs but it didn't look very good. If that's something you think would be helpful though let me know
