### ISSUE TITLE
Backup Status widget: duplicate backup buttons?

### ISSUE THREAD

**Issue by KoalaBear84** [Microsoft/sqlopsstudio#1632]
Issue Type: <b>Bug</b>

1. Click Manage on a database
2. Go to Backup Status widget
3. Click on menu of widget and click Show Details

Here you get a panel on the right which have two buttons "Backup". These also does not have a tooltip to see if anything is different with the two.

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 10.0.14393

Reproduces without extensions

![image](https://user-images.githubusercontent.com/5886900/41403599-8d42bcb8-6fc5-11e8-9d39-a97277741e84.png)

**Comment by MattIrv** [comment]
Looks similar to #1311, though that was fixed for 0.29.3. Maybe something else is also causing extra buttons to get added

**Comment by KoalaBear84** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/q9V6gt6"><a href="//imgur.com/q9V6gt6"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
