### ISSUE TITLE
SP_HELP

### ISSUE THREAD

**Issue by OJ13** [Microsoft/sqlopsstudio#1644]
Issue Type: <b>Bug</b>

SP_HELP is not working properly.

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|Memory (System)|3.91GB (0.58GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by kburtram** [comment]
@OJ13 when I run `EXEC sp_help` I'm getting the below output.  Could you please provide some details on what you encountered running sp_help and what you expected?  Thanks.

![screen](https://user-images.githubusercontent.com/599935/41569989-d14d3f6e-7321-11e8-9029-ccb6e18a6f00.png)

**Comment by llali** [comment]
@kburtram I closed a similar issue yesterday: https://github.com/Microsoft/sqlopsstudio/issues/1118
seems to be a rendering issue with slick grid when there are more than one result sets. @anthonydresser is working on the rendering issue which will fix this one also

**Comment by kburtram** [comment]
Please reactive with additional repro steps if there is a issue in this scenario.
