### ISSUE TITLE
Restore fails

### ISSUE THREAD

**Issue by tfenster** [Microsoft/sqlopsstudio#166]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce: Try to restore a .bak file

I get the following error if I try to restore a .bak. Client is Windows Server 2016, Server is SQL Server 2014
![image](https://user-images.githubusercontent.com/15346084/33069707-a54a4dfa-ceb5-11e7-904a-eed1766d111e.png)

If I try to restore the same .bak from the same client machine to the same server instance using the old SQL management studio, it ~~fails~~ works . The .bak actually is the demo database from MS Dynamics NAV 2017 CU5, so you might be able to easily get a copy

Please let me know if you need more information

**Comment by erickangMSFT** [comment]
@tfenster Can you please confirm whether the backup file is actually restorable to SQL Server 2014 but fails only through SQL Ops Studio? If it's backup file and SQL Server issue, we can move this topic to MSDN forum.

**Comment by tfenster** [comment]
sorry, I got the one word wrong that was important :( I meant to write "If I try to restore the same .bak from the same client machine to the same server instance using the old SQL management studio, it **works**"

**Comment by erickangMSFT** [comment]
@tfenster That's very important word 😄  Can you please let us know the download link to the .bak if it's handy? I will search web to find the backup file.

**Comment by tfenster** [comment]
Download "CU 5 NAV 2017 DE.zip" from https://www.microsoft.com/en-us/download/details.aspx?id=55037. Extract it and then you will find NAV.10.0.16177.DE.DVD\SQLDemoDatabase\CommonAppData\Microsoft\Microsoft Dynamics NAV\100\Database\Demo Database NAV (10-0).bak

**Comment by kevcunnane** [comment]
I can't reproduce this using that bak file. I was able to successfully recreate it as a new DB with the same name, different name, and different name with the existing one already there. I could also restore over itself (e.g. restore once, then restore again to same DB). Anything I'm missing?

Issues I encountered:
- In SSMS if you have a query open, recreating to a new DB if the existing DB is already on the server fails due to tail log backup. This actually doesn't happen on Ops Studio (we must be correctly closing the query?)

**Comment by tfenster** [comment]
Hm, interesting. Any ideas what might cause the problem on my side or how I might be able to narrow it down? Which SQL Server version and OS (client and server) did you use?

**Comment by kevcunnane** [comment]
SQL Server 2014. Client was Win10 fall creators update but shouldn’t matter.

**Comment by tfenster** [comment]
I tried again and now it works, not sure why...
