### ISSUE TITLE
Flexbox: justifyContent doesn't work

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#1672]
The layout property justifyContent for flexbox doesn't work. It's always centered, and thus positioning items is hard. In addition, I saw in the `sqlops.proposed.d.ts` that the FlexLayout properties matches the CSS property. However, in the `mainController.ts` for sqlservices, I noticed an `alignItems: 'left'`. Is this a bug or the properties have styles that we don't know about?

**Comment by llali** [comment]
I cannot repro the issue. the justifyContent seems to work fine. to make the UI you want you might need to use other options as well (width, textAlign, itemAlign ...)
