### ISSUE TITLE
Right-click rows then select Create Insert Statements

### ISSUE THREAD

**Issue by mobsoftware** [Microsoft/sqlopsstudio#1687]
Right-click rows then select Create Insert Statements

**Comment by kburtram** [comment]
@mobsoftware I think this is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/1194.  This is a really nice feature that we'd like to support in a future release.  Please reactivate if this is a different suggestion than https://github.com/Microsoft/sqlopsstudio/issues/1194.

**Comment by mobsoftware** [comment]
Thanks. It is a duplicate, I should have searched first.
