### ISSUE TITLE
SQL Agent Jobs - add sorting, filtering scrolling

### ISSUE THREAD

**Issue by yellatpt** [Microsoft/sqlopsstudio#1688]
- SQL Operations Studio Version: 0.30.6
Enhancement request - 
When looking at SQL Agent Jobs, it would be nice to sort by date in the history for a particular job.  If you have too much history, there's no way to scroll to the bottom. Maybe add a way to change how much history to retrieve.

Steps to Reproduce:
Click on "Manage", Click "SQL Agent" tab, click on a Job that has a lot of history.

**Comment by kburtram** [comment]
@abist could you please review this request and determine how it aligns with remaining work planned in the Job History view.  These sound like pretty basic suggestions.
