### ISSUE TITLE
Can not can not connect to Dbs on mac

### ISSUE THREAD

**Issue by Davorak** [Microsoft/sqlopsstudio#1692]
Issue Type: <b>Bug</b>

Using SQL login method.

On mac:
Use either FQDN or ip address for ms sql server.  Try either ms sql 2014 or 2016.

The spinner spins for over 5 minutes and nothing ever happens.
![image](https://user-images.githubusercontent.com/810921/41686131-90ff7a70-74a8-11e8-9020-39cc4a840c0c.png)

Windows:
Try the same when installed in windows ~0.5-2sec pause and then it connection.

Expected results: Be able to connect on mac

Error in developer console present at startup:

```
/Users/pjw/Downloads/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 Unsupported platform
```

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:34:32.192Z)
OS version: Darwin x64 14.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Users/pjw/Downloads/SQL Operations Studio.app/Contents/MacOS/Electron -psn_0_3007198|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by abist** [comment]
Hi @Davorak, this is actually not a bug. In the downloads page [here](https://docs.microsoft.com/en-us/sql/sql-operations-studio/download?view=sql-server-2017), the supported OS Versions for macOS are Sierra and High Sierra (16.0+). Your version here is Darwin 14.5, so it seems you have OS X Yosemite on your machine, which is not supported. Please let us know if you have any other questions.

**Comment by Davorak** [comment]
> Hi @Davorak, this is actually not a bug.
> he supported OS Versions for macOS are Sierra and High Sierra (16.0+).

@abist - Thanks I missed that. I would have expected a warning message at startup if the program was not compatible.

I am going to close out the issue since my initial issue has been resolved.
