### ISSUE TITLE
Backup dialog: File browser UI is broken

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#1693]
When clicked on the `+` button to add new paths to backup, the dialog looks broken. Screenshot - 

![backup](https://user-images.githubusercontent.com/6411451/41687081-520e7170-749b-11e8-9615-4c7c4d9c26d7.JPG)

Steps to reproduce -

1. Open backup dialog and press the `+` button to show the File Browser.
2. Close the dialog and repeat step 1.

**Comment by kburtram** [comment]
@abist I couldn't repro.  Please reactive with additional repro steps if you're still hitting this.
