### ISSUE TITLE
Adding default shortcut for SQL Server Profiler

### ISSUE THREAD

**Issue by yualan** [Microsoft/sqlopsstudio#1695]
Hi Team,

As one of our goals is to make launching Profiler in as minimal clicks as possible, let's add a default shortcut to launch Profiler.

![image](https://user-images.githubusercontent.com/30873802/41691044-5b032502-74ad-11e8-851b-90532987e6ab.png)

Currently, SSMS launches the deprecated SQL Profiler with Ctrl+Alt+P. I believe we should use this convention since this is what SSMS users are used to and is the feedback we have received for things like toggling results. However, Ctrl+Alt+P is a default shortcut in SQL Operations Studio already, most likely inherited from VS Code.

![image](https://user-images.githubusercontent.com/30873802/41690983-fd99ebc6-74ac-11e8-96e2-43849a4cffee.png)

After discussing with Matt, I couldn't see the value of the existing shortcut compared to helping users launch Profiler in a familiar pattern and quickly without having to set the shortcut themselves.

If the team agrees with this overriding default, I think we should also have a default to start and stop Profiler so that user can easily launch and start Profiler without ever touching the mouse. At minimum, it would be great to at least have a keyboard shortcut option where the user can configure for themself since it appears to not be an option right now.

Thank you,
Alan

**Comment by madelinemacd** [comment]
I've added ctrl+alt+p as a default keybinding, and both starting and stopping the profiler can now be configured with keybindings by the user.

**Comment by yualan** [comment]
After discussing with Kevin and Vicky, let's instead use alt+p as the default keybinding. alt+p is currently not reserved, and helps avoid any warnings on Windows since ctrl+alt+ something is a default shortcut for Windows specific functions. To avoid that, let's use alt+p.

I know you mentioned you added starting and stopping profiler. What shortcut do you have set by default at the moment?

**Comment by madelinemacd** [comment]
Sounds good, I'll switch that now to alt + p.

I don't have any default value for starting and stopping, I leave the keybindings for that entirely up to the user. Should we add defaults?
