### ISSUE TITLE
Add SQL Server Agent Job - dialog is just black with no text

### ISSUE THREAD

**Issue by mrgrieves4** [Microsoft/sqlopsstudio#1697]
Issue Type: <b>Bug</b>

Go to SQL Server Agent and click the "+" to add a new job.   A dialog pops up which is entirely black - there is no text visible on it at all.  I can't use it so have to close it.

I also can't see the option to Edit a job, but maybe that hasn't been implemented yet.

I had a similar problem when i tried to update to the new version using Operations Manager.  The installation dialog popped up but it was just black.  I managed to click the bottom right corner hoping it was "Next", but it popped up with another dialog that I couldn't see so I had to abort and download/install the whole app again.

My settings are:

{
    "files.autoSave": "onFocusChange",
    "editor.fontSize": 14,
    "editor.fontFamily": "Fira Code, Consolas, 'Courier New', monospace",

    // Enables font ligatures
    "editor.fontLigatures": true,
    "editor.mouseWheelZoom": true,
    "editor.smoothScrolling": true,
    "window.zoomLevel": 1,
    "workbench.colorTheme": "Default Dark SQL Operations Studio",
    "workbench.colorCustomizations": {
        "editor.background": "#000000",
        "sideBar.background": "#191919"
    },

And some other diagnostics:

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (5.15GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.29.0

</details>

**Comment by kburtram** [comment]
@mrgrieves4 this "Create Job" experience isn't planned until the July release.  We should have disabled that button until the feature is ready.  Sorry for the inconvenience..

**Comment by alanrenmsft** [comment]
@mrgrieves4 , Could you please share a screenshot?

**Comment by mrgrieves4** [comment]
When I try it today I get a window saying "open dashboard extension" and it lists SQL Agent.  Clicking OK/Cancel dismisses the dialog m but I guess that's because its not implemented yet.

I'm sure the dialog didn't look like this yesterday, but I am quite badly visually impaired and can sometimes miss what would otherwise be obvious so I can't guarantee it.  It's a shame I didn't take a screenshot of it yesterday.  I'll attach what I'm seeing today anyway, and if it opens completely dark again I'll capture ti and attach itoo.
![sqlagent](https://user-images.githubusercontent.com/39165063/41764217-6236d1f6-75f8-11e8-8454-245f3b68b160.png)

The update dialog was definitely not showing though because I was successfully clicking where buttons should be and they were doing something - I just couldn't tell what.  Next time there's an update I'll take a screenshot and attach it.

**Comment by kburtram** [comment]
I couldn't repro this on the latest build.  Please reactive if you continue to see this problem.
