### ISSUE TITLE
SQL Server Profiler for Azure DB fails

### ISSUE THREAD

**Issue by CrunchTech** [Microsoft/sqlopsstudio#1700]
- SQL Operations Studio Version: 0.30.6, SQL Server Profiler 0.1.1

Steps to Reproduce: Connect to database located in Azure, open profiler, click on start. 

This will not provide any output or error messages. However, the debugger console shows these errors:
 C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2251 [Extension Host] [Error - 11:57:30 AM] Request profiler/start failed.
C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2251 [Extension Host]   Message: An exception occurred while executing a Transact-SQL statement or batch.
  Code: -2146233088 

Note that connecting to a on-premise SQL Server 2008 R2 database does not produce results either, in this case the console shows:
Message: Operation not supported on version 10.50.4042.   Code: -2146233088 

I would really appreciate support for Azure databases, is there any way to get around the exception?

Thanks,

Ton

**Comment by madelinemacd** [comment]
Hi Ton,

Thanks for raising this issue. I've been working on this extension and I'm investigating this, currently there isn't a workaround for the issues you're facing. I appreciate you installing the extension and testing it out, and I'm sorry your experience with it hasn't been positive! I'll make sure to update if I figure out a workaround, or when there's a fix out in an upcoming insider build.

Thanks,
Madeline
