### ISSUE TITLE
Functionaluty for Open New Query with connection active in Explorer

### ISSUE THREAD

**Issue by mauriliofilho** [Microsoft/sqlopsstudio#171]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.17040
---

Steps to Reproduce:

1.Select DataBase Active in Explorer
2. Press CTRL+N (Windows) open new tab with not connection enable!

Necessary activate this option for facility operation with many tabs work!! CRTL+N open new tab with same database connecting active and selected in explorer.

**Comment by erickangMSFT** [comment]
We have an issue for this request. https://github.com/Microsoft/sqlopsstudio/issues/6
