### ISSUE TITLE
Improve the dialog validation feature

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/sqlopsstudio#1716]
current implementation only asks for the extension to provide a boolean value whether the data in the dialog is valid and it is up to the extension to show the validation error messages, I think this needs to be pushed to the extension framework, and the extension shall provide the isValid boolean along with the error messages: {valid:boolean, errorMessages: string[]}.

**Comment by MattIrv** [comment]
We'll track this under #1444 so I'll close this one as a duplicate
