### ISSUE TITLE
TypeError when Connecting to Server

### ISSUE THREAD

**Issue by ss-coder** [Microsoft/sqlopsstudio#1719]
![screen shot 2018-06-24 at 1 05 26 pm](https://user-images.githubusercontent.com/37033657/41823319-003d9d88-77b3-11e8-8636-88ec1c5ebec7.png)
Issue Type: <b>Bug</b>

I recently installed "SQL Operations Studio" on my MacBook Pro (Yosemite). When I try to add a new connection, I am getting an error in a pop up dialog box....

The title of the dialog box says: 
Connection error

The error message says: 
TypeError: Cannot read property 'onReady' of undefined

There is no further information. I have tried several different connection credentials (Server, User Name, Password) that I can connect to from my PC with no problem using SSMS.

Any feedback would be greatly appreciated. Thank you!

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:34:32.192Z)
OS version: Darwin x64 14.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|8.00GB (2.58GB free)|
|Process Argv|/Applications/SQL Operations Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by abist** [comment]
Hi @ss-coder , this is actually not a bug. In the downloads page here, the supported OS Versions for macOS are Sierra and High Sierra (16.0+). Your version here is Darwin 14.3, so you have OS X Yosemite on your machine, which is not supported. Please let us know if you have any other questions.

**Comment by ss-coder** [comment]
Hello Abist, 
I did overlook that when I downloaded SQL Operations Studio. Thank you so much for taking the time to clear that up for me.
