### ISSUE TITLE
Cursor position lost when changing file

### ISSUE THREAD

**Issue by masta** [Microsoft/sqlopsstudio#1721]
- SQL Operations Studio Version: 0.30.6

**Steps to Reproduce:**
1. Start SQL Operations Studio
2. Create a new query file (CTRL+N)
3. Type some text (leave the cursor at end of line)
4. Create another query (CTRL+N)
5. Open query from step 2 again

**Actual result:**
The cursor is at the start of the file.

**Expected result:**
The cursor should be at the position as left at step 3.

**Comment by kburtram** [comment]
@masta we're tracking this issue in https://github.com/Microsoft/sqlopsstudio/issues/114.  The basic issue is that the shell tears down the DOM elements for a page when it's switched to the background and then rebuilds the page when it's brought back to the foreground.  The scroll state isn't correctly being reapplied when the page is rebuilt.  We plan to fix in a future release.  I'll close this as a duplicate.
