### ISSUE TITLE
Text selection should select also @ for variables

### ISSUE THREAD

**Issue by masta** [Microsoft/sqlopsstudio#1722]
- SQL Operations Studio Version: 0.30.6

**Steps to Reproduce:**
1. Double-click on a variable in a query editor

**Actual result**
The variable is selected **without** the @ symbol, which is part of it's name.
![sqlops_0.30.6](https://user-images.githubusercontent.com/69071/41850787-30916040-7886-11e8-9b89-4712d3590198.gif)

**Expected result**
The variable should be selected **with** the @ symbol, just like in SSMS.
![ssms_17.7](https://user-images.githubusercontent.com/69071/41850819-445e3c4c-7886-11e8-9f21-292cc0997fa6.gif)

**Comment by abist** [comment]
Hi @masta, closing this issue as the same issue is being tracked here - https://github.com/Microsoft/sqlopsstudio/issues/143. Feel free to join that thread for questions/updates.

**Comment by masta** [comment]
Oh sorry for that @abist. My search skills must have failed me. I could fix it with the discussion in #143. Thanks for the link and closing this one.
