### ISSUE TITLE
Select All

### ISSUE THREAD

**Issue by josepd247** [Microsoft/sqlopsstudio#1723]
- SQL Operations Studio Version:
Can "Select All" be added to the Edit menu to select all text for a present sql query?

**Comment by kburtram** [comment]
I see VS Code sticks this command in the `Selection` menu, which we remove to reduce UI clutter.  I agree we should add `Select All` to `Edit` as it's a pretty standard command.

**Comment by kburtram** [comment]
This is fixed by https://github.com/Microsoft/sqlopsstudio/pull/1988.  The fix will be available in the next `insiders` build later this week.
