### ISSUE TITLE
cursor moving to top of query when switching queries

### ISSUE THREAD

**Issue by andreusg23** [Microsoft/sqlopsstudio#1729]
Issue Type: <b>Bug</b>

I am working on row 2000+ on Quesry A and then I switch to also open Query B.  When I return to Query A, I am no longer at row 2000+, instead I am at row 1.

This happens with all queries open.  i.e. I miss the row I am working as soon as I temporarily switch to other queries.

Very annoying.

please help.

thanks,
Andreu

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.56GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
server-report|Mic|0.1.2

</details>

**Comment by kburtram** [comment]
@andreusg23 we're tracking this issue in https://github.com/Microsoft/sqlopsstudio/issues/114.  The basic issue is that the shell tears down the DOM elements for a page when it's switched to the background and then rebuilds the page when it's brought back to the foreground.  The scroll state isn't correctly being reapplied when the page is rebuilt.  We plan to fix in a future release.  I'll close this as a duplicate.
