### ISSUE TITLE
Can't Copy from Grid

### ISSUE THREAD

**Issue by GabrielBarriosT** [Microsoft/sqlopsstudio#173]
- SQL Operations Studio Version:
0.23.6
Steps to Reproduce:
Run Any query, from the results grid try to copy a cell text using Keyboard shortcut Ctrl + C, the Text is not getting copied to the clipboard.

The contextual menu to copy does work as expected.

**Comment by erickangMSFT** [comment]
@GabrielBarriosT I can see this issue as well. 
![image](https://user-images.githubusercontent.com/11077282/33089632-1769afc6-cea6-11e7-9046-192aedd0736f.png)

**Comment by erickangMSFT** [comment]
https://github.com/Microsoft/sqlopsstudio/issues/161

**Comment by kevcunnane** [comment]
We have a fix for this internally thanks to @anthonydresser. At least for the rangy error part, and we believe this should resolve the remaining issues here

**Comment by anthonydresser** [comment]
This should be resolved, please reopen if not the case.
