### ISSUE TITLE
Cannot filter Objects - nice to have...

### ISSUE THREAD

**Issue by GabrielBarriosT** [Microsoft/sqlopsstudio#174]
- SQL Operations Studio Version:
0.23.6
Steps to Reproduce:
From the left objects pane, let's say for example if you do a right click on the Stored Procedures Folder, SSMS had an option to filter the objects by name or scheme. 

Also, SQLOps doesn't have any options to search objects within a database, another nice to have

**Comment by erickangMSFT** [comment]
@GabrielBarriosT SQL Ops Studio comes with object search feature built in. :) Try this. Open Dashboard from a database and search objects using Search widget.

![image](https://user-images.githubusercontent.com/11077282/33083682-e5c9f7fc-ce94-11e7-951e-8d93ebd6d08e.png)

**Comment by erickangMSFT** [comment]
let's track this case with OE with https://github.com/Microsoft/sqlopsstudio/issues/69

**Comment by cocis48** [comment]
The search is nice, but the table filter within the database is a must like SSMS, is very helpful, if you allow move the result window to a place where we can see it at the time of writing the query so we don't have to go back to the search to use another table and this does not show the columns of a particular table either, the filter in SSMS is a huge tool for me.
