### ISSUE TITLE
Bug: Error message when saving Excel file second (and subsequent) time

### ISSUE THREAD

**Issue by JohnyL** [Microsoft/sqlopsstudio#1748]
- SQL Operations Studio Version: 0.30.6

When I save result for the first time into Excel file, everything is OK. But when I try to save it second (and subsequent) time, then error appears:

![SQLOPS_SAVING_FILE_ERROR](https://i.imgur.com/g32Lu91.png)

#### Further info:
1) It is in the same tab, but sometimes error appears when saving data in another tab (I couldn't figure out the connection).
2) You can also run another query in this tab - error appears over and over again.
3) The error goes away (in the next time), if you press *Cancel* in **Choose Results File** dialog box, but appears again if you save a file.
4) When error message box is closed, the file can be saved successfully (as if error never appeared).

**Comment by JohnyL** [comment]
@kevcunnane Yes, it's on Windows.

**Comment by MattIrv** [comment]
I just merged in some code to address this issue so it will be fixed in our next release
