### ISSUE TITLE
BUG: HTML data in a column gets interpreted

### ISSUE THREAD

**Issue by bciesielski** [Microsoft/sqlopsstudio#1749]
- SQL Operations Studio Version:
0.30.6

Steps to Reproduce:
select from a varchar column with HTML data gets interpreted in the result grid

![image](https://user-images.githubusercontent.com/36210825/41978871-0332535e-7a23-11e8-992d-67b99f04388a.png)

**Comment by kburtram** [comment]
@MattIrv I recall you may have looked at a similar issue?

**Comment by anthonydresser** [comment]
@bciesielski can you give me an example of cell text that will cause this problem?

**Comment by bciesielski** [comment]
There seems to be a problem when multiple html tags with styles exist in the string.

select '<div style="background-color: red">test</div>'  -- OK
select '<div style="">txt</div> <div style="background-color: red">test</div>'  -- cell's background filled red

![image](https://user-images.githubusercontent.com/36210825/42191042-dd923168-7e60-11e8-8529-6ca1eacc1e8b.png)

**Comment by anthonydresser** [comment]
This should be fixes as of #1838 look out for this in the next release, and please reopen if it continues to occur.

**Comment by bciesielski** [comment]
ok, thanks Anthony, I will
