### ISSUE TITLE
Save As in Open Editors Doesn't Do Anything

### ISSUE THREAD

**Issue by chadwillson** [Microsoft/sqlopsstudio#1756]
Create query > go to Open Editor > right click on unsaved file > select Save As [nothing happens]

![image](https://user-images.githubusercontent.com/39832132/41990595-d7477fce-7a10-11e8-9048-48ac21f69a29.png)

**Comment by alanrenmsft** [comment]
@chadwillson I am not able to reproduce this, could you please try the latest release 0.32.5 here: https://github.com/Microsoft/sqlopsstudio/releases
