### ISSUE TITLE
Extensibility: Add Feature from SSMS Hold ATL + Click and Drag Cursor

### ISSUE THREAD

**Issue by JASM2007** [Microsoft/sqlopsstudio#1757]
- SQL Operations Studio Version: 0.30.6
Add in the SSMS feature where when you hold the ALT button + click and drag in order to write multiple lines of code at the same time..

**Comment by kevcunnane** [comment]
This is supported using Alt+Click. We have all the Visual Studio Code keybindings and mouse accelerators - see https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf for the Windows version, or https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference for all versions.

I've included a screenshot of the multi-cursor options below. Please reopen this if you find one that's missing, but up to now these seem to suffice. 

![image](https://user-images.githubusercontent.com/10819925/41991026-f995afd2-79f8-11e8-9e85-2b482276fab3.png)

**Comment by JASM2007** [comment]
Hi thanks,

I was wanting the ability to do Shift+Alt+(drag mouse) for multiple line edits. It looks like it's working on SQL Operation Studio just different hot keys than I am use to. On my current SSMS I just hold ALT+(drag mouse) and it does the same thing not sure why it's different because I never change any hot keys.  That's fine as long the feature is there then I am happy.

Here is a link I found so what I was talking about:
https://blogs.msdn.microsoft.com/sql_pfe_blog/2017/04/11/quick-tip-shiftalt-for-multiple-line-edits/
