### ISSUE TITLE
Need Azure AD MFA login support

### ISSUE THREAD

**Issue by paschott** [Microsoft/sqlopsstudio#176]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Launch SQL Ops Studio
2. Try to login to an Azure SQL DB that uses Azure AD MFA for authentication
3. Notice the option is not available.
4. Close SOS and return to SSMS.

**Comment by erickangMSFT** [comment]
@paschott  Let's use https://github.com/Microsoft/sqlopsstudio/issues/13 as the tracking issue.
