### ISSUE TITLE
Export CSV : add ability to change the delimiter in the settings

### ISSUE THREAD

**Issue by JeyDi** [Microsoft/sqlopsstudio#1771]
- SQL Operations Studio Version: 0.30.6

Steps to Reproduce:
In the app settings, please add the possibility to change the csv export delimiter and the decimal character not using the default machine locale.

**Comment by kburtram** [comment]
A fix should be available in the latest builds that contain this commit https://github.com/Microsoft/sqlopsstudio/pull/2099.  The fix will be in future `insiders` and `stable` builds.
