### ISSUE TITLE
Dashboard: Insight details have strange dotted outline

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/sqlopsstudio#1776]
- SQL Operations Studio Version: daily

Steps to Reproduce:
- Open manage dashboard and click on Details for the backup widget
- Select a row

Expected: In most themes, should have a solid line outlining the selected row
Actual: Have dotted line. Is this for accessibility? This seems like it should only be set in accessible themes as it looks "wrong" in default theme

![image](https://user-images.githubusercontent.com/10819925/42051246-55c7f0ea-7ac0-11e8-90e5-d3d3be932ff7.png)

![image](https://user-images.githubusercontent.com/10819925/42051256-5f3031ba-7ac0-11e8-9f8d-59f3d4084b33.png)

**Comment by kburtram** [comment]
@anthonydresser I believe this is related to accessibility changes you made in SlickGrid.  If so, could you please provide a little background on why we need this?

**Comment by anthonydresser** [comment]
Its probably the default css styles for a properly attributed data grid. I'll look like removing them.

**Comment by anthonydresser** [comment]
I know i've seen this before, but i'm having problems reproing it.

**Comment by kevcunnane** [comment]
I tested against latest drop from the VSTS repo. Downloaded it last night and installed
