### ISSUE TITLE
Format the TSQL code

### ISSUE THREAD

**Issue by JeyDi** [Microsoft/sqlopsstudio#1794]
- SQL Operations Studio Version: 0.30.6

Steps to Reproduce:
Please add the possibility to format the TSQL code like visual studio code.
Or with a particular extension like: 
https://marketplace.visualstudio.com/items?itemName=TaoKlerks.poor-mans-t-sql-formatter-vscode

**Comment by kburtram** [comment]
@JeyDi have you tried the `Format Document` or `Format Selection` commands.  There are also a few user settings that start with `mssql.format.` that control the formatting behavior.

![screen](https://user-images.githubusercontent.com/599935/42113018-b20b604c-7b9e-11e8-8759-62c866a065ca.png)

**Comment by kburtram** [comment]
@JeyDi please reactive if my previous response didn't address your question.  Thanks!
