### ISSUE TITLE
Profiler and Results view visual bugs

### ISSUE THREAD

**Issue by yualan** [Microsoft/sqlopsstudio#1818]
- SQL Operations Studio Version: v0.31.1-insider

Steps to Reproduce:

In the latest insider build, there appears to be some visual bugs. Working on a consistent repo.

1. When you open and start Profiler, and then press Ctrl+F in the context of Profiler, the Find menu does not display additional actions like closing out. This is only an issue in Dark Mode.
![image](https://user-images.githubusercontent.com/30873802/42179002-45b1bd88-7de7-11e8-8d29-e58e4eb49adc.png)

2. When I run Profiler a long time, I start to get these visual bugs.

![image](https://user-images.githubusercontent.com/30873802/42177739-bc113968-7de2-11e8-8a2c-1efaaa59b68a.png)

![image](https://user-images.githubusercontent.com/30873802/42177765-d10fcf00-7de2-11e8-96d6-7c2d8c9f689b.png)

Might be my machine, but might be worth investigating in case this wasn't happening in the last stable build.

**Comment by kburtram** [comment]
I've been seeing this too.  Also in the results grid some time.  I think the cell values may need to HTML escaped.

@anthonydresser do you have an idea where we would need to put the HTML escape call (assuming that the problem)?

**Comment by anthonydresser** [comment]
The icon issue: the icons are there, they are just INCREDIBLY hard to see.

**Comment by yualan** [comment]
Yup, the buttons are still functional in dark mode. Madeline is going to take a look at making them more visible in dark mode.

**Comment by anthonydresser** [comment]
@yualan @madelinemacd i already have a fix for it here https://github.com/Microsoft/sqlopsstudio/pull/1826

**Comment by anthonydresser** [comment]
this should be fixed post #1838

**Comment by anthonydresser** [comment]
This should be fixed, please reopen if it continues to appear
