### ISSUE TITLE
Restore Default Settings

### ISSUE THREAD

**Issue by daniel04061** [Microsoft/sqlopsstudio#182]
It would be nice to have a "Restore Default Settings" option in the user settings. I was in there playing around and messed something up and it took *forever* to find the problem when it would have been easier to simply restore whatever the defaults were.

**Comment by erickangMSFT** [comment]
@daniel04061 The current mechanism is that the default setting is copied into user settings file where user can customize settings. if an equivalent user setting (json object) is deleted then ops studio applies the default (built-in) settings. Can you try removing all contents in user settings and check if it's a desired behavior?
