### ISSUE TITLE
Lost a Server Group, but still exists

### ISSUE THREAD

**Issue by snelljef** [Microsoft/sqlopsstudio#1835]
Issue Type: <b>Bug</b>

I was starting to organize server groups by project/environment:
Project1/PROD
Project1/QA
Project2/PROD
Project2/QA
etc

And I accidentally moved a Projects root folder into another.

Project2/QA/Project1/PROD

Ooops! So I tried to drag and drop Project1/PROD back outside of the group to be at the bottom of the list (basically I was trying to sort by Alphabetical order) and then it disappeared from the list completely.

Since I figured it wasn't actually wiped, I tried to make another group of the same name and it tells me it already exists. Basically I somehow managed to orphan it.

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz (8 x 3792)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.93GB (53.00GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|50%|

</details>Extensions: none

**Comment by kburtram** [comment]
@snelljef we'll try to get a repro for this issue.  In the meantime, the group hierarchy is saved in the User Settings file.  You maybe able to see what's going on by inspecting that metadata.

**Comment by alanrenmsft** [comment]
I am able to reproduce the issue and fix it

**Comment by kburtram** [comment]
Closing as fixed based on merged PR.  The fix should be in the next build.
