### ISSUE TITLE
Better Table organisation

### ISSUE THREAD

**Issue by OFark** [Microsoft/sqlopsstudio#1843]
- SQL Operations Studio Version: 0.30.6

Steps to Reproduce: Open an SQL Database and look at the tables.

In order to organise and understand the structure of my tables, I put them in different schemas. It would be useful that instead of seeing schema.table name, the schema could be a subfolder under the table folder if it's not dbo.

**Comment by kevcunnane** [comment]
Thanks for this feedback. We're tracking this request in #7. It does require some redesigns to the code to allow this kind of flexibility, so while it's in our long-term plans it's not on our immediate roadmap. Please track #7 to see the progress of this request - I'll close this issue as a duplicate.
