### ISSUE TITLE
Typing N'' autocompletes to N'''

### ISSUE THREAD

**Issue by Thallerich** [Microsoft/sqlopsstudio#1850]
Issue Type: <b>Bug</b>

When typing N' (N begin the prefix to denote a unicode string) autocomplete ist not working, meaning the closing ' is not automatically added.

Now if the string constant is an empty string N'' then the second ' entered autocompletes and the resulting input looks like N''' - which is obviously wrong.

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 10.0.17704

**Comment by kburtram** [comment]
This should be fixed in the latest `insiders` build.  Please reactive if the problem persists with current builds.
