### ISSUE TITLE
Extensibility: table component not visible when placed directly under dialog

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/sqlopsstudio#1860]
Branch: Agent/Dialogs
code: sqlopsstudio\extensions\agent\client\src\dialogs\schedulePickerDialog.ts

To invoke to dialog: Agent tab/new job/schedules tab/ pick... 

![image](https://user-images.githubusercontent.com/13777222/42367699-e840455e-80b9-11e8-8ec0-c8a8d1e6fbb8.png)

**Comment by llali** [comment]
@alanrenmsft the reason table is not rendering is an error happens in the component but you don't see it in the console. The data for the table should be a 2D array but your code is generating 1D. if you fix the code the table should render correctly. I'll fix the table component to fail with better error.

**Comment by alanrenmsft** [comment]
thanks!


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
