### ISSUE TITLE
I could not connect to SQL server using SQL operations studio 

### ISSUE THREAD

**Issue by deBroglieeeen** [Microsoft/sqlopsstudio#1869]
Issue Type: <b>Bug</b>

I could not connect to SQL server using SQL operations studio. In firewall, I already add my IP address but this software does not detect it.

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:34:32.192Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|4.00GB (0.03GB free)|
|Process Argv|/Applications/SQL Operations Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@deBroglieeeen I haven't been able to repro this issue.  Are you able to successfully connect to the server with other tools from your machine?  Please reactive with additional connection details if the problem persists.

**Comment by deBroglieeeen** [comment]
I still could not connect to the azure DB using sql operations studio.
I set all my server data sources server,user name , password.
And I was required that I set my firewall.
I set my firewall but it did not work.
Then I tried to add my azure account in the sql operations studio
But it did not work too like below.
