### ISSUE TITLE
Comments on top of object does not appears

### ISSUE THREAD

**Issue by gabcastro** [Microsoft/sqlopsstudio#188]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
OS Version: Windows_NT x64 6.3.9600

- Steps to Reproduce:
1. Create a Function, Store Procedure or View;
2. Put comments before CREATE [object];
3. Execute;
4. Open the same script created before, with "Script as Create";
5. See that does not appear comments created on top of script;

I don't know if not implemented still, but I found this strange.

Regards,

**Comment by kevcunnane** [comment]
I believe @llali is fixing this right now as part of the scripting improvements

**Comment by llali** [comment]
yes this is already fixed as part of my changes

**Comment by llali** [comment]
Fixed in sqltoolservice v1.2.0-alpha.39
