### ISSUE TITLE
Cursor go to top when change query file

### ISSUE THREAD

**Issue by HuyNLQ2** [Microsoft/sqlopsstudio#1882]
- SQL Operations Studio Version: 0.31.2

(Sorry my english)

**Comment by MattIrv** [comment]
Steps to reproduce:
1. Open two query editors with text in them
2. Put the cursor somewhere other than the start in one file
3. Switch tabs to another file then back to the original file

Actual behavior: The cursor goes back to the first line
Expected behavior: The cursor stays in the same place

**Comment by teemurgroup** [comment]
In addition to the cursor returning to the top of the screen the editor unfolds any folded sections.

**Comment by K0sM1c** [comment]
And the size of the columns in the results grid have also been reset to the default size when reopening the tab.

**Comment by kburtram** [comment]
This issue is fixed for the query editor scroll position while switching tabs in the latest insiders build at https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.1.  We have other active issues tracking similar problems in the results grid and elsewhere.
