### ISSUE TITLE
Cannot access a database with AUTO_CLOSE=ON

### ISSUE THREAD

**Issue by jovanpop-msft** [Microsoft/sqlopsstudio#189]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Create a database and set AUTO_CLOSE=ON
2. Connect to server and you will see that you cannot access AUTO_CLOSE database. I can access the database via SSMS.

NOTE: I have tried this on SQL2017 Express Edition where AUTO_CLOSE=ON is default, and I cannot open any database until I remove this setting via SSMS. The same problem happens with a database in Recovery pending state.
![auto_close](https://user-images.githubusercontent.com/20593304/33127678-cd292376-cf89-11e7-9fa8-6c575ecc0ffb.PNG)

**Comment by MattIrv** [comment]
The code for this is ready and it will be fixed in the next release, so I've closed this issue. Thanks for reporting it
