### ISSUE TITLE
Running query/hitting F5, query window looses focus

### ISSUE THREAD

**Issue by framm** [Microsoft/sqlopsstudio#19]
- SQL Operations Studio Version: 0.23.6 (Windows)

Steps to Reproduce: 
- Open new query tab, write a SQL statement and hit run or F5. I would expect to still be able to type in the query window, but I actively have to mouse-click or just tab to get focus in query window again

**Comment by kevcunnane** [comment]
@kburtram do we have this fixed internally? I believe you mentioned this didn't make the public preview release.

**Comment by kburtram** [comment]
@kevcunnane yes this should be in the Dec. release.

**Comment by kburtram** [comment]
This should be fixed in this build https://github.com/Microsoft/sqlopsstudio/releases/tag/v0.24.1.  If not, please reopen this issue.  Thanks!
