### ISSUE TITLE
Choosing scatter chart results in lost results

### ISSUE THREAD

**Issue by devkws** [Microsoft/sqlopsstudio#190]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.1.7601
---

When switching chart types to scatter, results and charts will disappear. You must re-run the query to fix this. Changing chart types does not fix this.

Steps to Reproduce:

1. run query
2. click view as chart
3. change chart type to scatter
4. results and chart will disappear
5. change chart type again to verify results and charts are lost.

**Comment by anthonydresser** [comment]
This is all most likely related to #37
