### ISSUE TITLE
The auto identify of encoding not work.

### ISSUE THREAD

**Issue by macedo123** [Microsoft/sqlopsstudio#1907]
Issue Type: <b>Bug</b>

- Alter parameter of setings "files.autoGuessEncoding" for true
- Create a file with "ãáâç" for exemple int the encoding  ISO 8859-1.
- Save and close the file.
- Reopen the file.
- The enconding select not is correct

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 6.1.7601

Extensions: none

**Comment by MattIrv** [comment]
Thanks for reporting this. It may be related to #1849 which looks similar

**Comment by alanrenmsft** [comment]
this is an upstream issue in VSCode.
https://github.com/Microsoft/vscode/issues/33720
