### ISSUE TITLE
Unable to connect from Mac SQL Operations Studio to SQL Server on a Windows server

### ISSUE THREAD

**Issue by AnF5** [Microsoft/sqlopsstudio#1924]
- SQL Operations Studio Version:

Steps to Reproduce:
We have SQL Operations Studio installed on Mac laptop. 
We are trying to connect to _SQL Server named instance_ on Windows Server. 

Error:
System.Data.SqlClient.SqlException (0x80131904): Cannot access Kerberos ticket. Ensure Kerberos has been initialized with 'kinit'.

**Comment by kburtram** [comment]
@AnF5 have you verified that Kerberos authentication is correctly configured on both the client and server?  There are several issues that have context on how to investigate (for example, https://github.com/Microsoft/sqlopsstudio/issues/23 or try searching closed issues for `kinit`).

**Comment by kburtram** [comment]
@AnF5 please take a look through the issues I referenced above and reactive with additional details if the problem persists.

**Comment by AnF5** [comment]
Thank you I will check it out and post the update
