### ISSUE TITLE
Wizard: GenerateScript button not being hidden on Windows

### ISSUE THREAD

**Issue by corivera** [Microsoft/sqlopsstudio#1941]
When setting wizard.generateScriptButton.hidden=true on Windows, the button is still displayed. The wizard's doneButton gets correctly hidden when setting hidden=true, though.

**Comment by MattIrv** [comment]
I wasn't able to repro this but just opened #1945 to fix a display bug I noticed while investigating

**Comment by MattIrv** [comment]
@corivera any chance you can share a code snippet that reproduces this issue or demo it to me in person at some point? I looked into this a bit but it seemed to work fine for me

**Comment by MattIrv** [comment]
Verified that this bug only appears in packaged builds and was fixed by #1945
