### ISSUE TITLE
Cannot search objects

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/sqlopsstudio#197]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. click the magnifying glass to search
2. type in an object name
3. Program searches for files, not database objects

**Comment by erickangMSFT** [comment]
@gbritton1 Database search in Object Explorer / Search side bar is not implemented functionality yet. For the public preview, try Explore widget on Manage dashboard it has the database object search functionality.

**Comment by kburtram** [comment]
Please use the `Redgate SQL Search` extension for searching SQL database metadata.
