### ISSUE TITLE
Automatic scroll up

### ISSUE THREAD

**Issue by franciscocarrasco** [Microsoft/sqlopsstudio#1972]
- SQL Operations Studio Version: 0.31.4

From one day to the other, every time I change of tabs and then return to any of them, the query  automatically scrolled up to beginning. How can I disable this? I want to go back to my query and be in the same line where I left it

**Comment by MattIrv** [comment]
This is a bug and unfortunately I don't think there's a workaround for it. We're tracking it in #114 so I'll close this one as a duplicate
