### ISSUE TITLE
Cursor moves to top left of tab when focus is taken away from then back to tab

### ISSUE THREAD

**Issue by samalex1701** [Microsoft/sqlopsstudio#1976]
- SQL Operations Studio Version: 0.31.4

Steps to Reproduce:
Open SQLQuery1 Tab with TSQL code with about 100 lines.  Go to line 80.
Open new tab SQLQuery2 Tab with TSQL Code with also about 100 lines.  Go to line 90.
Go back to SQLQuery1 and cursor is back to line 1 column 1.  Move cursor to someplace in any line again then move to SQLQuery2. Cursor is back to Line 1 Column 1. 
Move back to SQLQuery1.  Cursor is back to Line 1 Column 1. 

Issue is the cursor doesn't stay where it's left when moving between tabs.  Select a block of code in SQLQuery1, move to SQLQuery2 then back to SQLQuery1.  Nothing is highlighted and cursor is back to top left.  This makes editing large queries difficult when having to move between tabs.

**Comment by MattIrv** [comment]
Thanks for your report. We're tracking this bug in #1882 so I'll close this one as a duplicate

**Comment by samalex1701** [comment]
Thanks MattIrv, I'll monitor bug 1882 for progress.
