### ISSUE TITLE
Remove Desktop Shortcut

### ISSUE THREAD

**Issue by Chiramisu** [Microsoft/sqlopsstudio#1977]
Issue Type: <b>Feature Request</b>

Please do not add the Desktop Shortcut back every time I update the software. I find this to be very annoying. :(

A shortcut should only be added when the user desires it. Have it checked by default, fine, but give us the option to opt-out.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Chiramisu** [comment]
So as not to leave on a negative note, I **LOVE** the tool. I really appreciate the more modern VS Code-like extension based design and hope that it will some day come with all the power of SSMS. 😄

**Comment by abist** [comment]
The same issue is being tracked here - https://github.com/Microsoft/sqlopsstudio/issues/1285. I'm closing this issue as it's a duplicate.
