### ISSUE TITLE
Won't connect to my databases (which reside on Windows Server 2016 Standard OS)

### ISSUE THREAD

**Issue by XpertDBA** [Microsoft/sqlopsstudio#198]
- SQL Operations Studio Version: sqlops-windows-0.23.6

Steps to Reproduce:

Doesn't work for anyone in my company.  Can't get it to connect using Windows Authentication.  Gives the message:

System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx). at System.Guid.GuidResult.SetFailure(ParseFailureKind failure.......

**Comment by kburtram** [comment]
@XpertDBA do you know if there is the entire call stack provided in the error message?  Are there any other details about the server config or connection settings you could provide?

**Comment by XpertDBA** [comment]
Since the tool won’t let me copy/paste, I took a Snip of the entire call stack trace in 2 sections:

[cid:image001.png@01D36922.3C44C220]



[cid:image002.png@01D36922.3C44C220]


As far as a connection goes, I’m using the same instance name I use successfully in SSMS for my remote connection:

[cid:image003.png@01D36922.3C44C220]


Let me know if you need any further information.

Robert West

**Comment by kburtram** [comment]
@XpertDBA could you please confirm if this is still any issue?  If it is still an issue in current releases could you please try to provide the callstacks again.  They didn't seem to get into the issue comments above.  Thanks!
