### ISSUE TITLE
SQL editor can execute content removed from text document

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#1982]
- SQL Operations Studio Version: `master`
 
Steps to Reproduce:

Type:
```
CREATE TABLE C1
(
    c2 varchar(100)
)

INSERT INTO C1 VALUES('2018-04-27T18:33:55.870Z')

SELECT * FROM C1;
```

Delete the CREATE and INSERT then run SELECT.  Query executor tries to run create even after removed from buffer.

**Comment by kburtram** [comment]
I haven't been able to repro yet.  When I inspected the state of the `ScriptFile` object in the tools service it looks like the content of the text buffer was duplicated for some reason at the end of the `INSERT` line, so the content was as below.

```


CREATE TABLE C1
(
    c2 varchar(100)
)

INSERT INTO C1 VALUES('2018-04-27T18:33:55.870Z')


CREATE TABLE C1
(
    c2 varchar(100)
)

INSERT INTO C1 VALUES('2018-04-27T18:33:55.870Z')
```

**Comment by kburtram** [comment]
I was able to repro this, but you have to type out the actual content char-by-char and paste `2018-04-27T18:33:55.870Z` between the '' quotes.  This could have bad side-effects, so let's root cause today, and then we can decide if this requires a hotfix once we understand impact and repro frequency.

**Comment by MattIrv** [comment]
This bug should be limited to pasting timestamps and maybe a few other limited edge cases. When you paste '2018-04-27T18:33:55.870Z' it gets sent to the service as '04/27/2018 18:33:55', causing it to lose track of your subsequent changes. I'm looking into the exact problem now

**Comment by kburtram** [comment]
Thanks Matt!  That sounds like a pretty limited repro.

**Comment by MattIrv** [comment]
Definitely, especially since it won't happen if the date is part of a larger string or is typed character by character.
