### ISSUE TITLE
Copy from query results grid is off by 1 column

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#1985]
- SQL Operations Studio Version: `master`

Steps to Reproduce:
1. Run a query
2. Select a value in the results grid and copy it to the clipboard

Expected: selected value is copied to clipboard

Actual: copied cell is off by 1.  if selection is column 2 the copied value is in column 3.

**Comment by kburtram** [comment]
@anthonydresser can you check if this is related to the slickgrid vbump?

**Comment by anthonydresser** [comment]
It probably is, I removed the need for unneeded off by one accommodation. I
can do a scan through the code and check for these.

**Comment by kburtram** [comment]
@anthonydresser thanks!
