### ISSUE TITLE
Import Wizard Tasks

### ISSUE THREAD

**Issue by yualan** [Microsoft/sqlopsstudio#1987]
### Fast Debugging
- [x] Faster debugging stuff.
### General / Accessibility
- [x] I CAN see all UI in Light, Dark, and High Contrast Mode
- [x] I CAN click previous and next 
- [x] I CAN go back to previous steps and forward to already completed steps 
- [ ] [Stretch] I CAN see a help button on each page to go to https://docs.microsoft.com/en-us/sql/relational-databases/import-export/import-flat-file-wizard?view=sql-server-2017  
- [x] I CAN exit wizard any time without actually importing 
- [ ] [Stretch] Remove vertical and hortizontal wizard bars.
### UI Entry Point
- [x] I CAN activate the Import Flat File command through the command palette
- [x] I CAN see a suggestion to make a connection if no servers are currently connected.
- [ ] [Stretch]I CAN activate the Import Flat File command through the Database Dashboard as an Extensions tasks
### Initial File Configuration
- [x] Needs API support to expose databases.
- [x] I CAN select a server from a list of actively connected servers. 
- [x] I CAN select a database from a list of databases from the selected server. 
     - [ ] [Stretch]If entry point is from database dashboard, automatically fills server and database. 
- [x] I CAN select a .CSV or .TXT file from a file location. 
- [x] I CAN set a table name for my new SQL table. 
- [x] I CAN auto-fill table name and jump cursor to schema. 
- [x] I CAN set the schema to attach my new SQL table. 
- [x] I CAN see an error if table name already exists in database. 
### PROSE Preview 
- [x] I CAN see error message if file could not be read by PROSE. 
- [x] I CAN see a read-only view by PROSE which is run on the first 100 rows of the flat file. 
- [x] I CAN see all column names in the view, and horizontally scroll to see more column names. 
- [x] I CAN see all data preview in first 100 rows. 
- [x] I CAN go back to previous page to select a different flat file. 
### Modify Columns 
- [x] I CAN modify columns in an editable grid 
    - [x] Column name 
    - [x] Any string 
    - [x] Data Type 
        - [x] Dropdown pulls from: https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-types-
transact-sql?view=sql-server-2017
        - [x] Set any varchar (1-8000) 
    - [x] Primary Key 
        - [x] Binary (checkbox) 
    - [x] Allow Nulls 
    - [x] Binary (checkbox) 
    - [ ] [Stretch] Add Clusterable checkbox
    - [ ] [Stretch] Add ColumnStore (checkbox)

**Import Flat File Summary page and running** 
- [x] I CAN see summary of import information 
    - [x] Server name 
    - [x] Database name 
    - [x] New table name 
    - [x] Table Schema 
    - [x] File to be imported 
- [x] I CAN see whether PROSE successfully imported the data 
- [ ] [Stretch]I CAN see number of rows successfully inserted 
- [x] I CAN see error message whether PROSE was unable to import all data 
- [x] I CAN have option to import another file. 
- [x] I CAN click done to exit wizard.

**Comment by kburtram** [comment]
Closing since @aaomidi internship project is complete.  Let's track remaining Import work as bug-level issues.
