### ISSUE TITLE
add friendly name to connections

### ISSUE THREAD

**Issue by sivey42** [Microsoft/sqlopsstudio#1996]
- SQL Operations Studio Version: 0.31.4

Steps to Reproduce:
When adding a new connection, or (in the future) editing a connection, it'd be great to be able to add a friendly name to the connection. For example, if my server name is either an IP address, or a long fqdn, it'd be nice to be able to add a short nickname for the server in the list.

**Comment by kburtram** [comment]
@sivey42 thanks for opening this issue!  We're currently tracking this suggestion in https://github.com/Microsoft/sqlopsstudio/issues/1020.  Please add any additional requirements for this feature into that issue.

**Comment by sivey42** [comment]
crap, sorry - searched for similar but didn't find one :)
