### ISSUE TITLE
Html in stored in columns may draw over results table

### ISSUE THREAD

**Issue by owen2** [Microsoft/sqlopsstudio#1999]
Issue Type: <b>Bug</b>

I have a table that stores html in a column and the values draw on top of the entire results area. The results area is basically completely white. 
![capture](https://user-images.githubusercontent.com/618275/43157367-74dbc10a-8f42-11e8-9e43-8635e4ec46fa.PNG)

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.68GB (6.61GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by anthonydresser** [comment]
This should be fixed in the insiders build and will be in the next release

**Comment by owen2** [comment]
looks like this is a duplicate of #1971, which is already closed.
