### ISSUE TITLE
Missing labels for Database Size Chart

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#2017]
- SQL Operations Studio Version: 0.32.1

Steps to Reproduce:

1. Open any server dashboard. It should have a `Database Size` widget. 
2. Click on the `...` on the top-right of the widget and click on `Run Query`.
3. Click on `View as Chart` in the Query Results window.

**Expected**:  We should be able to see the same graph (scaled).
**Actual**:  The units on the graph are all `undefined`.

Screenshots added -
![capture](https://user-images.githubusercontent.com/6411451/43170786-bfeb6d76-8f5b-11e8-820c-484395878227.JPG)

![conndialog](https://user-images.githubusercontent.com/6411451/43170800-d6018636-8f5b-11e8-8e8c-22c62b323d94.JPG)

**Comment by kburtram** [comment]
I merged @AlexFsmn  related PR yesterday so closing based on that.
