### ISSUE TITLE
Multi line comment colouring

### ISSUE THREAD

**Issue by rwlpf** [Microsoft/sqlopsstudio#2026]
Issue Type: <b>Bug</b>

The multi line comment does not seem to display correctly I used to to comment out the statements at the end.  The colour looks like the statement will run, which it it does not :-)

Query I noted this issue in

/*Step 1 - run query to list permissions allocated
to the Extended Stored Procedure list in WHERE
clause*/

SELECT
    OBJECT_NAME([major_id]) AS 'extended_procedure'
  , [permission_name]
  , 'PUBLIC'                AS 'to_principal1'
FROM
    [sys].[database_permissions]
WHERE
    OBJECT_NAME([major_id]) LIKE 'XP_%'
    AND [type] = 'EX'
    AND [grantee_principal_id] = 0
	AND OBJECT_NAME([major_id]) IN ('xp_dirtree','xp_fileexist','xp_subdirs')
ORDER BY
    'extended_procedure'
;

/*Step 2 - Remove permission from the PUBLIC role
to run these Extended Stored Procedures */
REVOKE EXECUTE ON xp_dirtree TO PUBLIC;
REVOKE EXECUTE ON xp_fileexist TO PUBLIC;
REVOKE EXECUTE ON xp_subdirs TO PUBLIC;

/*Step 3 - run query to list permissions allocated
to the Extended Stored Procedure list in WHERE
clause
Note this should return ZERO rows, if Step 2 has
been run successfully*/
SELECT
    OBJECT_NAME([major_id]) AS 'extended_procedure'
  , [permission_name]
  , 'PUBLIC'                AS 'to_principal2'
FROM
    [sys].[database_permissions]
WHERE
    OBJECT_NAME([major_id]) LIKE 'XP_%'
    AND [type] = 'EX'
    AND [grantee_principal_id] = 0
	AND OBJECT_NAME([major_id]) IN ('xp_dirtree','xp_fileexist','xp_subdirs')
ORDER BY
    'extended_procedure'
;

/*Step 4 - Add permission from the PUBLIC role
to run these Extended Stored Procedures 
ONLY TO BE RUN IF REQUIRE ADD PERMISSIONS BACK
ROLL BACK SCRIPT
*/
/*
GRANT EXECUTE ON xp_dirtree TO PUBLIC;
GRANT EXECUTE ON xp_fileexist TO PUBLIC;
GRANT EXECUTE ON xp_subdirs TO PUBLIC;

/*Step 5 - run query to list permissions allocated
to the Extended Stored Procedure list in WHERE
clause
If ran Step 3 this this should return THREE rows
indicating permission has been granted ot the 
PUBLIC role for these stored proceedures*/

SELECT
    OBJECT_NAME([major_id]) AS 'extended_procedure'
  , [permission_name]
  , 'PUBLIC'                AS 'to_principal2'
FROM
    [sys].[database_permissions]
WHERE
    OBJECT_NAME([major_id]) LIKE 'XP_%'
    AND [type] = 'EX'
    AND [grantee_principal_id] = 0
	AND OBJECT_NAME([major_id]) IN ('xp_dirtree','xp_fileexist','xp_subdirs')
ORDER BY
    'extended_procedure'
;
*/

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.89GB (12.15GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|0.2.0
agent|Mic|0.31.4
profiler|Mic|0.1.2
server-report|Mic|0.1.2
whoisactive|Mic|0.1.1
sql-search|Red|0.2.0

</details>
.

**Comment by abist** [comment]
@rwlpf Thanks for filing the issue. I tried copy-pasting this into SQL Ops Studio, and realized that there were mistakes in the comment blocks in the code snippet, rather than there being a bug. Can you try using the following snippet and see if you still see the problem?

```
/* Step 1 - run query to list permissions allocated
to the Extended Stored Procedure list in WHERE
clause */

SELECT
OBJECT_NAME([major_id]) AS 'extended_procedure'
, [permission_name]
, 'PUBLIC' AS 'to_principal1'
FROM
[sys].[database_permissions]
WHERE
OBJECT_NAME([major_id]) LIKE 'XP_%'
AND [type] = 'EX'
AND [grantee_principal_id] = 0
AND OBJECT_NAME([major_id]) IN ('xp_dirtree','xp_fileexist','xp_subdirs')
ORDER BY
'extended_procedure'
;

/*Step 2 - Remove permission from the PUBLIC role
to run these Extended Stored Procedures */
REVOKE EXECUTE ON xp_dirtree TO PUBLIC;
REVOKE EXECUTE ON xp_fileexist TO PUBLIC;
REVOKE EXECUTE ON xp_subdirs TO PUBLIC;

/* Step 3 - run query to list permissions allocated
to the Extended Stored Procedure list in WHERE
clause
Note this should return ZERO rows, if Step 2 has
been run successfully */
SELECT
OBJECT_NAME([major_id]) AS 'extended_procedure'
, [permission_name]
, 'PUBLIC' AS 'to_principal2'
FROM
[sys].[database_permissions]
WHERE
OBJECT_NAME([major_id]) LIKE 'XP_%'
AND [type] = 'EX'
AND [grantee_principal_id] = 0
AND OBJECT_NAME([major_id]) IN ('xp_dirtree','xp_fileexist','xp_subdirs')
ORDER BY
'extended_procedure'
;

/*Step 4 - Add permission from the PUBLIC role
to run these Extended Stored Procedures
ONLY TO BE RUN IF REQUIRE ADD PERMISSIONS BACK
ROLL BACK SCRIPT
/
*/
GRANT EXECUTE ON xp_dirtree TO PUBLIC;
GRANT EXECUTE ON xp_fileexist TO PUBLIC;
GRANT EXECUTE ON xp_subdirs TO PUBLIC;

/*Step 5 - run query to list permissions allocated
to the Extended Stored Procedure list in WHERE
clause
If ran Step 3 this this should return THREE rows
indicating permission has been granted ot the
PUBLIC role for these stored proceedures */

SELECT
OBJECT_NAME([major_id]) AS 'extended_procedure'
, [permission_name]
, 'PUBLIC' AS 'to_principal2'
FROM
[sys].[database_permissions]
WHERE
OBJECT_NAME([major_id]) LIKE 'XP_%'
AND [type] = 'EX'
AND [grantee_principal_id] = 0
AND OBJECT_NAME([major_id]) IN ('xp_dirtree','xp_fileexist','xp_subdirs')
ORDER BY
'extended_procedure'
;
```

**Comment by rwlpf** [comment]
Thanks the script you adjusted is *not* what I intended, and would *not*
work as I intended.

*The last two steps 4 & 5 should not be run*.  The purpose of placing the
start of multi line comment at line 45 and the end of the multi line
comment at line 76.  Means that the all the lines in between* line 45 and
line 76 should appear coloured comments,* they do not.  This bug is only
related to the interpretation of multi line comments.  Note if this same
script was placed into SSMS v17 the script is interpreted correctly.  As
you can see in the picture below SSMS does interpret the same code
differently and renders the code from line 45 to line 76 as comments which
is the original intention.
[image: image.png]

Compare the above picture from SSMS v17 (above) with that from SQL Ops
Studio.  As can be seen from the screen shot below from SQL Ops Studio the
text from line 45 to line 76 is not interpreted as comments.   In other
words is is not coloured as a comment.
[image: image.png]
Yes this is a minor and not a significant bug.  Hopefully this makes my
original comments clearer?

**Comment by abist** [comment]
@rwlpf This is a valid bug that has been reported before. It's being tracked here - https://github.com/Microsoft/sqlopsstudio/issues/848 , if you want to follow it.
