### ISSUE TITLE
View moves to top of document on window switch

### ISSUE THREAD

**Issue by MrSandvik** [Microsoft/sqlopsstudio#2028]
Issue Type: <b>Bug</b>

When you switch from one query tab to another and then back again, the editor places the cursor all the way at the top of the document/query. Very cumbersome!

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

**Comment by abist** [comment]
Hi @MrSandvik, this issue should be fixed in the latest insider build. Here's the main issue thread for this particular bug if you want to follow it - https://github.com/Microsoft/sqlopsstudio/issues/114. I'm going to close this issue as it's a duplicate.
