### ISSUE TITLE
Configure saveAsCsv

### ISSUE THREAD

**Issue by SebastianPfliegel** [Microsoft/sqlopsstudio#203]
- SQL Operations Studio Version: 0.23.6

Currently only "sql.saveAsCsv.includeHeaders" is available as setting. I recommend following additional settings:

- [x] field separator (e.g. semicolon instead of comma)
- [ ] text identifier (e.g. double quotation marks)
- [ ] encoding (e.g. 1252 instead of UTF-8)
- [ ] line separator (LF instead of CRLF)

**Comment by trpalmer** [comment]
👍

**Comment by kburtram** [comment]
We recently added field separator option as a community contribution.  I'll leave this active to track the other options.

**Comment by SebastianPfliegel** [comment]
Great! I adjusted my first comment. Maybe I'll be able to add the other features. The code is placed in SQLTools and not in SQLOps, right, @kburtram?

**Comment by SebastianPfliegel** [comment]
@kburtram: I created some PRs. Might wanna check them out? :)

**Comment by kburtram** [comment]
@SebastianPfliegel thanks for publishing the PRs!  

@abist could you please work with @SebastianPfliegel to get these changes merged?
