### ISSUE TITLE
New Connection not working

### ISSUE THREAD

**Issue by Rob-S** [Microsoft/sqlopsstudio#204]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:46:54.710Z)
- OS Version: Darwin x64 15.6.0
---

When trying to create a new connection in the Mac version of SQL Operations Studio, the option to create a New Connection is ignored.

Steps to Reproduce:

1. Click "New Connection" icon --or-- right click a group name and select New Connection from the context menu.
2. The dialog to add a new connection does not appear.

**Comment by kburtram** [comment]
When the connection dialog isn't opening I would suspect the out-of-proc .Net Core service component isn't running.  Unfortunately .Net Core 2.0 is only supported on Sierra (Darwin 16.0.0) and up.  If possible, you'll need to update to a newer macOS version to use this tool.  Sorry for the inconvenience.

**Comment by kburtram** [comment]
I'll close this issue now since it's reported against El Capitan which is an unsupported version of macOS.  Please reactive if the issue persists on Sierra+ OS version.
