### ISSUE TITLE
Result - copy column value is mistalk

### ISSUE THREAD

**Issue by kkbruce** [Microsoft/sqlopsstudio#2045]
Issue Type: <b>Bug</b>

1. Select a table, if get firstName and lastName colume values.
2. Select fitstName a column value, use `Ctrl+C` or mouse `Copy`
3. You will get next lastName column value.

SQL Operations Studio version: sqlops 0.32.1-insider (4bfa6b3a5d290049ebbbf3e2c269ac46fc9ef200, 2018-07-20T15:05:39.530Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (4.04GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|33%|

</details>Extensions: none

**Comment by abist** [comment]
@kkbruce This bug was being tracked and fixed in https://github.com/Microsoft/sqlopsstudio/pull/2009. Please try the latest insider build with the fix that comes out tomorrow and let us know if you encounter any other issues!

**Comment by kkbruce** [comment]
Ok, wait release.
thanks.
