### ISSUE TITLE
Inconsistent search results

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/sqlopsstudio#206]
- SQL Operations Studio Version:

Steps to Reproduce:
See attached screenshots

SQL Operations Studio 

![image](https://user-images.githubusercontent.com/12263288/33191150-1f236358-d084-11e7-8022-253262ebb590.png)

SSMS

![image](https://user-images.githubusercontent.com/12263288/33191153-2a2397b4-d084-11e7-87de-0d9d316e19ba.png)

**Comment by erickangMSFT** [comment]
@gbritton1 I think this issue is resolved in the latest release (Dec 2017 and Jan 2018 release) Let's confirm it.

**Comment by kburtram** [comment]
This should be fixed in latest release.
