### ISSUE TITLE
Cursor control in results table

### ISSUE THREAD

**Issue by oraclebhoy** [Microsoft/sqlopsstudio#2065]
Issue Type: <b>Bug</b>

query table with more columns than will be displayed in results screen so that you have the scroll bars.
click in the results screen and using your cursor move up and down / side to side through the result cells, you can do this until you start to move to cells that are not visible, the cursor stops responding until you click back in the results table.
Have been able to repeat this issue. problem only happens when the scroll bars have to move at the bottom of the results table, maybe focus is getting place on them rather than were the cursor is in the results table.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (11.08GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2
server-report|Mic|0.1.2
whoisactive|Mic|0.1.1

</details>

**Comment by abist** [comment]
Hi @oraclebhoy , this issue is being tracked and should be fixed in the next coming insider release. Please try it out and let us know if you still see the problem. I'm going to go ahead and close this issue for now.
