### ISSUE TITLE
SQL Agent: Job Steps Missing

### ISSUE THREAD

**Issue by Tarig0** [Microsoft/sqlopsstudio#2069]
- SQL Operations Studio Version: 0.31.4
- SQL Server Agent: 0.31.4
- SQL Server : 13.0.5026.0
Steps to Reproduce:

1.Edit Job

Expected: Steps to be displayed
Actual: Only the General tab is filled in

Validated that the same user can see the steps in SSMS

**Comment by abist** [comment]
Closing this as the same issue is being tracked here - https://github.com/Microsoft/sqlopsstudio/issues/2064

**Comment by Tarig0** [comment]
Not the same issue, that looks like a partial load this is no steps are displaying at all

![image](https://user-images.githubusercontent.com/4108180/43963828-6aae719c-9c89-11e8-987a-db7c9414ce80.png)

**Comment by abist** [comment]
@Tarig0 You're right, this feature is still in preview (should be indicated in next insider build), and thus isn't fully functional. Sorry about the confusion.
