### ISSUE TITLE
Scroll position is forgotten in SQL editor

### ISSUE THREAD

**Issue by mrlife** [Microsoft/sqlopsstudio#2071]
SQL Operations Studio Version: 0.31.4 (0.31.4)

Steps to Reproduce:

Create 2 SQL/query editor tabs
Create a query or enter any text into one of the tabs
Scroll down
Switch to the other tab
Switch back to the first tab

Expected result:

Scroll position is remembered

Actual result: 

Scroll position is the top of the file

**Comment by aaraucod** [comment]
The same happens with the results pane, it goes back to the first row

**Comment by abist** [comment]
Hi @mrlife and @aaraucod, this issue should be fixed in the latest insider build. Here's the main issue thread for this particular bug if you want to follow it - #114. I'm going to close this issue as it's a duplicate.
