### ISSUE TITLE
Preserve cursor positions when switching tabs

### ISSUE THREAD

**Issue by snympi** [Microsoft/sqlopsstudio#2072]
Issue Type: <b>Bug</b>

Steps:
1. Open 2 tabs or .sql files
2. Make sure both tabs contain lines that require scrolling on both files to the SQL code that will be run
3. On tab 1, scroll to the bottom of the file. Select the SQL query to run and run the query to produce the table as output as the bottom part of the tab. Then scroll down a number of rows in the table.
4. Click on tab 2 and then back to tab 1
5. You will find that the cursor position in .sql file and the cursor in the table, would both have been reset to line 1 and row 1 in each.

The effect on useability is that when working across multiple tabs, you loose your position in any tab you switch away from and then back. This is disruptive if the files grow in length.

The same does not happen in VS Code.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17713

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (20.65GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2
server-report|Mic|0.1.2
whoisactive|Mic|0.1.1

</details>

**Comment by abist** [comment]
Hi @snympi, this issue should be fixed in the latest insider build, which comes out today. Here's the main issue thread for this particular bug if you want to follow it - #114. I'm going to close this issue as it's a duplicate.
