### ISSUE TITLE
When choosing "change all occurrences" the keyboard layout defaults to another layout

### ISSUE THREAD

**Issue by ChrisOlivierCubed** [Microsoft/sqlopsstudio#208]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1.Write a script with a few of the same values underneath each other
2.Choose "Change all occurrences"
3.Try to type special characters, the characters are different from the keyboard layout
4.Type of keyboard used: UK

**Comment by kburtram** [comment]
Please reactive if this issue persists in current builds.
