### ISSUE TITLE
Results pane shows untruncated HTML values 

### ISSUE THREAD

**Issue by philoushka** [Microsoft/sqlopsstudio#2081]
SQL Operations Studio Version
- MacOS
- SQL Ops Version 0.31.4 (0.31.4)

Steps to Reproduce:

1. Have a table with a varchar column containing HTML values.

2. Query the table within SQL Ops Studio.
  
**Expected:**
The columns show in the results pane with the column containing HTML showing only a truncated portion of the HTML string value.

**Actual:**
The entire HTML value is shown in the results pane, and it makes a mess.

![image](https://user-images.githubusercontent.com/930731/43359289-d86f55dc-9254-11e8-952e-29ca5a0627c4.png)

**Comment by zhuochen83** [comment]
I have the same issue

System
- Windows 10
- SQL Ops Version 0.31.4 (0.31.4)

**Comment by abist** [comment]
@anthonydresser Was this fixed?

**Comment by anthonydresser** [comment]
Should be fixed as of 0.32.1

**Comment by abist** [comment]
@philoushka @zhuochen83 You can try out the latest insider release in the Releases section. This issue should be fixed. Please feel free to reopen the issue if you still find it in the latest release.

**Comment by kburtram** [comment]
This should be fixed in the latest `insiders` build at https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.2.1.  We'll include this fix in the next `stable` build later in August.  Please reactive if you still hit the issue with these builds.
