### ISSUE TITLE
Cursor always moves to the beginning of the file after tab switch

### ISSUE THREAD

**Issue by bciesielski** [Microsoft/sqlopsstudio#2082]
[BUG]

- SQL Operations Studio Version:
Version 0.31.4
Commit e026ab85a72c190cc4ccc834503aa9fe36dd6407
Date 2018-07-18T02:14:21.826Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
- open two tabs with multiple rows in file 1
- got to file 1, move cursor to e.g. line 5
- switch to file 2 and back to file 1 again
- the cursor is back at line 1, but should be where you left it

**Comment by abist** [comment]
Hi @bciesielski, this should be fixed in the new insider builds. Please feel free to re-open the issue if you still see the problem.

**Comment by bciesielski** [comment]
Hi,
Thanks @abist, I will have a look at the IB
