### ISSUE TITLE
The cursor position is lost

### ISSUE THREAD

**Issue by MrAlex6204** [Microsoft/sqlopsstudio#2087]
Issue Type: <b>Bug</b>

The current cursor position is lost in the tap when I switch from one tap to other tap. 
This problem cause me to scrolldown every time I switch and is very
problematic when I have a long file.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.13GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.1.2

</details>

**Comment by kburtram** [comment]
@MrAlex6204 this issue should be fixed in the latest `insiders` build available at https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.2.1.  This will be in the next `stable` build later in August.  Please reactive if the issue persists on these builds.  Thanks!

**Comment by MrAlex6204** [comment]
Congrats this tool is awesome, I hope the graphs section can be more flexible in the future, is very useful.

SQuirreL is a DataBase client that has some useful things, I hope can be used as reference.

Regards
