### ISSUE TITLE
Included server and database name in tab

### ISSUE THREAD

**Issue by stevieg402** [Microsoft/sqlopsstudio#209]
- SQL Operations Studio Version:0.23.6 (Windows)

When working across a number of different servers and databases it would be helpful to have the server and database name in the tab and it's tooltip e.g. SQLQuery2 - _server\database_

![sqlops_tabs](https://user-images.githubusercontent.com/12466847/33214802-4971e44e-d125-11e7-957e-2b6a80fa107d.png)

**Comment by erickangMSFT** [comment]
@stevieg402 why did you close this? it's a valid suggestion 😄

**Comment by stevieg402** [comment]
I noticed, after I'd raised the issue, that the server and database name are visible towards the right hand side of the status bar and thought that this may suffice. But, whilst this helps somewhat, it would be useful to also have the server and database name in the tab and it's tooltip in a number of scenarios (e.g. ALT+TAB through open tabs, hovering over inactive tabs) so happy to re-open.

![sqlops_statusbar](https://user-images.githubusercontent.com/12466847/33319582-2a6e2e3a-d437-11e7-9848-dfbcf57542cb.png)

**Comment by af4jm** [comment]
Yes, this is definitely needed, so when working with multiple servers we don't need to activate the tab to see which server it's pointing at.

**Comment by psimoneau22** [comment]
also see this issue https://github.com/Microsoft/sqlopsstudio/issues/327

**Comment by kburtram** [comment]
This feature is available in the current `insiders` build by enabling the `sql.showConnectionInfoInTitle` option.
