### ISSUE TITLE
Can't use Ctrl+C shortcut to copy from result pane

### ISSUE THREAD

**Issue by DianGermishuizen** [Microsoft/sqlopsstudio#2091]
Issue Type: <b>Bug</b>

After running a query, I cant use the Ctrl+C keybaord shortcut command to copy a value from the results pane. I have to: right click on cell > Copy. 

I assume this is a bug, not a feature request. 

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|15.90GB (8.03GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2
server-report|Mic|0.1.2
whoisactive|Mic|0.1.1

</details>

**Comment by brandochn** [comment]
Additionally for this bug if I run two queries o more than one at the same time, I will get some query result windows accordingly however if I maximize one of them I am not available to copy any value from the results by using  Ctrl+C or right click on cell > Copy.

**Comment by kburtram** [comment]
I think this may be a confusion in the current selected state.  We should be more clear in the UI what is the currently selected element.  For example, in the below screenshot it is hard to tell which selected cell has focus.

<img width="283" alt="screen" src="https://user-images.githubusercontent.com/599935/43477104-2a9ec534-94af-11e8-9745-9088373d0151.PNG">

**Comment by kburtram** [comment]
Also copying with the resultset maximized throws and breaks copy\paste.

**Comment by carlowahlstedt** [comment]
Similarly, I found that if I try to copy a value in a column where there are multiple columns it is copying the column to the left. So I copied column 4 in order to get the value from column 5.
