### ISSUE TITLE
Table temporary

### ISSUE THREAD

**Issue by JoseFloresDW** [Microsoft/sqlopsstudio#210]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.2.9200
---
Comments are not distinguished

Steps to Reproduce:

1. definite a create table temporariy and add comments 
2. Set enviroment theme: Monokai

**Comment by erickangMSFT** [comment]
Duplicate of https://github.com/Microsoft/sqlopsstudio/issues/98
