### ISSUE TITLE
Feature Request: Make keywords non-capital

### ISSUE THREAD

**Issue by JohnyL** [Microsoft/sqlopsstudio#214]
- SQL Operations Studio Version: 0.23.6

Missing feature:
Could you create an option to make keywords non-capital after selecting it in IntelliSense?

**Comment by erickangMSFT** [comment]
Note: the ask is about keyword. Currently sql ops studio's intellisense option applies to schema objects only.

**Comment by kburtram** [comment]
@JohnyL could you try adding `"mssql.intelliSense.lowerCaseSuggestions": true` to your settings file.  This should enable the scenario you've mentioned.

The settings auto-complete is incorrectly putting this into the `sql.intelliSense` settings group.

**Comment by JohnyL** [comment]
@kburtram Thanks, this works! But there's one thing: in settings there's sql.intelliSense.lowerCaseSuggestions - without ms in the beginning, which doesn't work. But when I use "mssql", then all is OK. However, squiggles appear with message "Unknown configuration setting".

**Comment by kburtram** [comment]
This issue should be fixed in the Dec. release.  The settings autocompletion should match the actual settings names now.
