### ISSUE TITLE
Alter Table UI

### ISSUE THREAD

**Issue by abdullah-abunada** [Microsoft/sqlopsstudio#2149]
Hi All,

First thanks for you works, I suggest important feature we need it, it's UI to Alter Table structure.

Best.

**Comment by kburtram** [comment]
@abdullah-abunada thanks for the suggestion!  We're tracking adding a Table Designer UI with this issue https://github.com/Microsoft/sqlopsstudio/issues/1712.  Please leave any related comments on that issue.
