### ISSUE TITLE
Integrated with Visual Studio Code as a plugin

### ISSUE THREAD

**Issue by SQLHorizons** [Microsoft/sqlopsstudio#216]
- SQL Operations Studio Version: 0.23.6

Would be nice to see this integrated with Visual Studio Code as a plugin.
clearly a lot of the interface is browed from Visual Code, so why have a stearate app, other than for other platforms.

**Comment by erickangMSFT** [comment]
@SQLHorizons mssql extension for Visual Studio Code is the SQL server plug in. https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql Visual Studio Code as an editor will not receive UI parts that SQL Operations Studio provides.
