### ISSUE TITLE
Close Messages/Results Panes

### ISSUE THREAD

**Issue by pdsobolik** [Microsoft/sqlopsstudio#2165]
Issue Type: <b>Feature Request</b>

After you run a query, and the Results and Messages panes are opened, it would be nice to be able to close (not just collapse) them again, to get the largest edit window possible.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.16299

**Comment by dzsquared** [comment]
@pdsobolik in the command palette there is an option for "Toggle Query Results"
I have the SSMS keymap extension added so I'm not sure if this is stock, but ctrl-R toggles this command on my machine
