### ISSUE TITLE
Script to alter does not automatically connect

### ISSUE THREAD

**Issue by cstech-carlcamilleri** [Microsoft/sqlopsstudio#2167]
- SQL Operations Studio Version:
0.31.4
Steps to Reproduce:
1. Alter stored procedure from the servers toolbar or by pressing F12
2. Stored procedure gets scripted in a new query window but does not retain the connection (and database)

**Comment by kburtram** [comment]
@cstech-carlcamilleri thanks for the suggestion.  This looks like a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/825 which is resolved in the latest `insider` build at https://github.com/Microsoft/sqlopsstudio/releases.
