### ISSUE TITLE
ctrl+tab loses cursor position

### ISSUE THREAD

**Issue by straypointer** [Microsoft/sqlopsstudio#2173]
Issue Type: <b>Bug</b>

Open two text editors with .sql scripts. Scroll the cursor down a page or two, then ctrl+tab to another file. When you ctrl+tab back to the original, the cursor will be back at the top of the file, instead of where you left it.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|15.91GB (8.67GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by yualan** [comment]
Hi @straypointer, it looks like this behavior is fixed in the latest insider build: https://github.com/Microsoft/sqlopsstudio/releases 

Feel free to try it out. You can also wait for our next stable build on August 23rd.

**Comment by kburtram** [comment]
Please reactive if the problem persists on the latest builds.
