### ISSUE TITLE
Error message in console from Profiler

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#2178]
- SQL Operations Studio Version: master

The app has this error in the debug console now, something I didn't notice earlier -

```

SQL_Tools\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2251 [SQL_Tools\sqlopsstudio\extensions\profiler]: property `title` is mandatory and must be of type `string` or `object`
```

**Comment by kburtram** [comment]
Looks like I beat you to it 😄 .  Bug https://github.com/Microsoft/sqlopsstudio/issues/2177 and fix https://github.com/Microsoft/sqlopsstudio/pull/2176.
