### ISSUE TITLE
`Microsoft.import` failed error in console log

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#2183]
- SQL Operations Studio Version: master

I'm seeing minor errors in the console log -

![asdasd](https://user-images.githubusercontent.com/6411451/43855590-f81a49e2-9afa-11e8-8322-3640608fb715.JPG)

**Comment by MattIrv** [comment]
Amir merged in the flat file import extension code yesterday afternoon. Are you seeing this error after running a full build (`yarn` and `yarn run watch`) since pulling from master?

**Comment by abist** [comment]
I get a bunch of other errors now. Though the original one is gone.

![capture](https://user-images.githubusercontent.com/6411451/43855550-d075e022-9afa-11e8-888f-1cabee0a81f8.JPG)

**Comment by MattIrv** [comment]
Only the first error and the one about `dark_icon.svg` look relevant to importer there, the rest I think we've seen before. Does the extension work now regardless of the errors?

**Comment by aaomidi** [comment]
Closing issue, please reopen if the issue wasn't resolved.
