### ISSUE TITLE
SQL Operations Studio will not update when clicking "Update now"

### ISSUE THREAD

**Issue by myhreman** [Microsoft/sqlopsstudio#2195]
Issue Type: <b>Bug</b>

## Reproduce
1) Open SQL Operations Studio
1) Go to the Help menu
1) Click Check for updates
1) When an update is found a menu in the lower right corner appears, click Update now
1) SQL Operations Studio closes and a dialog appears "...will you allow making changes to this computer...", click Yes
1) Then a setup dialog appears, "Preparing to Install", and this dialog is hanging. Clicking Cancel is not possible. The whole dialog is hanging. 
1) When closing the dialog from Task Manager and restarting SQL Operations Studio, SQL Operations Studio works as before, but is not updated in anyway

## Excpected result
1) SQL Operations Studio uninstalls
1) New version of SQL Operations Studio is installed

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|15.85GB (4.73GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by abist** [comment]
@myhreman The update can take a little time. How long was the dialog stuck at "Preparing to Install"? I cannot repro this issue since the update works fine for me. Although, I agree that the installation phase cannot be canceled, which is a valid issue.

**Comment by myhreman** [comment]
Thx for the help!

I've tried it again, but now I was waiting longer. After about 8 minutes the installation process moved on and everything worked just fine. It seems like the uninstall takes quite a long time. But the install is quite fast.

The uninstall/install experience would be better with any indication/progressbar or information that something is actually happening. Now there is a spinning wheel when hovering the dialog, and that is the same spinning wheel as you get when a program/process is actually hanging.
