### ISSUE TITLE
copy data  from empty grid in result grid turn to null

### ISSUE THREAD

**Issue by swtmath** [Microsoft/sqlopsstudio#220]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. query from table that has empty data
2. copy data from result grid
3. paste to anther application (excel, notepad)

the resulting data from paste is null. this is supposed to be still empty. otherwise we unable to differentiate which is empty an which is null after we copied.

**Comment by anthonydresser** [comment]
This was fixed by #906. Empty cells will not copy an empty string which should result in expected behavior
