### ISSUE TITLE
All the charts are blank

### ISSUE THREAD

**Issue by perbauer** [Microsoft/sqlopsstudio#2205]
Issue Type: <b>Bug</b>

https://i.imgur.com/R9PisfM.png
All the Dashboard charts look like the one in the picture. All have the same values on the bottom too, with zero in the middle. When running the query I get all the data from the db. 
Is the computer missing some pre-requirements? Some tool that is needed to render graphics? 

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (22.65GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe C:\Users\PerB\Desktop\new users in PAS.sql|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2
server-report|Mic|0.1.3

</details>

**Comment by anthonydresser** [comment]
Do you see any errors in the console? (Help menu -> Toggle developer tools)

**Comment by perbauer** [comment]
Sorry, no, under Problems in the console it says; "No problems have been detected in the workspace so far"

**Comment by alanrenmsft** [comment]
@perbauer The issue should have been fixed now. Could you please try the latest release? https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.5

**Comment by perbauer** [comment]
Yes! It is. Excellent!
