### ISSUE TITLE
Scroll position lost in one tab after going to another tab

### ISSUE THREAD

**Issue by kofoide** [Microsoft/sqlopsstudio#2206]
- SQL Operations Studio Version:
0.31.4 (Mac)
Steps to Reproduce:

1) Have 2 tabs open
2) Run SQL statement that produces many resulting rows
3) Scroll down the result set and highlight a row
4) Go to the other tab
5) Come back to original tab
6) The result set is back at the top again

The same thing happens in the file editor too. Visual Studio Code doesn't do this at least in the file editor.

**Comment by Blindeddie** [comment]
This is fixed in the August Preview Insiders Build 0.32.3. (results grid and Editor) I have confirmed this on Windows only.  Should be included in the official August Preview release.

**Comment by MattIrv** [comment]
See #1744 for the main issue that tracked this
