### ISSUE TITLE
The minimum height of "Results" pane is almost half of screen

### ISSUE THREAD

**Issue by JohnyL** [Microsoft/sqlopsstudio#221]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---
The minimum height of "Results" pane is almost half of screen - and it can't be controlled. Please, make ability to give it zero height and/or close it.

**Comment by erickangMSFT** [comment]
@JohnyL Tracking this case with https://github.com/Microsoft/sqlopsstudio/issues/44 Suggestion to show /hide result pane.

**Comment by JohnyL** [comment]
Any progress about this?

**Comment by JohnyL** [comment]
@erickangMSFT Please, follow my [new issue](https://github.com/Microsoft/sqlopsstudio/issues/1747). I explained there the reasoning.
