### ISSUE TITLE
Sql Agent Job shows empty but it's not

### ISSUE THREAD

**Issue by perbauer** [Microsoft/sqlopsstudio#2225]
Issue Type: <b>Bug</b>

SSMS: https://i.imgur.com/xBD53aI.png
SOS: https://i.imgur.com/GqMficy.png
Under Edit Job in SOS jobs is empty in all tabs. In SSMS there are Steps and Alerts, job has no Schedule set though. 

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

**Comment by abist** [comment]
@perbauer Currently, the SQL Agent History page only shows the steps if they were run. In the coming release, you will be able to Add/Edit/Run from steps as well. The insider releases already let you Add and Edit steps, so please take a look. I'm going to close this issue for now, please let us know if you have any other questions!
