### ISSUE TITLE
Feature request: light weight SSMS like SQL query profiler.

### ISSUE THREAD

**Issue by subhankars** [Microsoft/sqlopsstudio#223]
Me and my team works a lot with ASP.NET MVC with Entity framework, and we have a lot of LINQ query written in the C# controller or in the DAL. We use sql server query profiler of SSMS to check the EF or LONQ generated query in the database and tune the LINQ query as needed. I would love to have the feature of query profiler, may be a light weight one with only Tracing t-sql will help a lot.

**Comment by kevcunnane** [comment]
This is on our roadmap. It's not targeted for the December release but should make one of the early-2018 releases based on current progress.

**Comment by ststeiger** [comment]
In the meantime, you can use the command-line profiler.
https://github.com/ststeiger/sql_profiler

**Comment by subhankars** [comment]
Finally this feature is in with June release. Thanks team for hearing and bringing this feature in my favorite SQL Operations Studio.
![profiler](https://user-images.githubusercontent.com/17920161/41806600-99199cbc-76de-11e8-8514-0f5b1696740a.gif)

**Comment by subhankars** [comment]
Feature added in June release.
