### ISSUE TITLE
Document VSCode Merge Process

### ISSUE THREAD

**Issue by firelizzard18** [Microsoft/sqlopsstudio#2235]
I am _very_ interested in the process that SQL Ops Studio uses for merging in (new versions of) the VSCode codebase. Please document this process.

Also Microsoft/vscode#56505.

**Comment by kburtram** [comment]
@firelizzard18 if you search the code base for `{{SQL CARBON EDIT}}` you can see the patches we've made to VS Code source code (for example, [this](https://github.com/Microsoft/sqlopsstudio/search?q=SQL+CARBON+EDIT&unscoped_q=SQL+CARBON+EDIT)).

Please work with VS Code team to document how best to extend their codebase.  We are using a manual, unsupported process to keep our codebases in-sync.
