### ISSUE TITLE
Cannot load databases in servers tab

### ISSUE THREAD

**Issue by c3as3r** [Microsoft/sqlopsstudio#2238]
Issue Type: <b>Bug</b>

While connected to Azure SqlDB  the servers tab can't load the databases. However, the queries work just fine, and can even select a particular database to query.

Server: Azure SQL
Connection method: SQL Authentication

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (7.97GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-dw|Mic|0.0.1

</details>

**Comment by kburtram** [comment]
@c3as3r we are tracking this problem in issue https://github.com/Microsoft/sqlopsstudio/issues/1503.  Please add additional scenario comments there is desired.
