### ISSUE TITLE
Context Menus are not working on Query Results grid

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#2244]
- SQL Operations Studio Version: `0.32.4`

Steps to Reproduce:
1. Run a query 
2. Right-Click on grid

Expected: Context menu

Actual: Nothing 😢

**Comment by kburtram** [comment]
@anthonydresser @alanrenmsft any ideas what's happening?  We probably need to release this week's insider build once we get a fix.

**Comment by kburtram** [comment]
@anthonydresser it looks like reverting the most recent SlickGrid bump that came in with the Edit Data fixes resolves this problem (https://github.com/Microsoft/sqlopsstudio/pull/2157).  Could you please take a look?

**Comment by anthonydresser** [comment]
I'll have a fix in the next 15 min

**Comment by kburtram** [comment]
@anthonydresser thanks!
