### ISSUE TITLE
Results grid Copy loses line breaks after Select All (Ctrl-A)

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#2255]
- SQL Operations Studio Version: `master`

Steps to Reproduce:
1. Run a query with multiple rows
2. Select All with Context Menu or Ctrl-A
3. Copy the results to Clipboard

Expected: Line breaks after each row

Actual:  All row values are concatenated into single line.

**Comment by kburtram** [comment]
@MattIrv any luck tracking this one down?

**Comment by MattIrv** [comment]
There also seems to be a related issue where sometimes copy doesn't work after select all, possibly similar to what we saw with #2091. I'll take a quick look at that too
