### ISSUE TITLE
Renaming of checkbox labels in chart options

### ISSUE THREAD

**Issue by AlexFsmn** [Microsoft/sqlopsstudio#2262]
- SQL Operations Studio Version: 0.31.4 / Master branch

Steps to Reproduce:
1. Go to the chart viewer after running a query.
2. Look at the chart options on the right side.

Depending on if "Horizontal" / "Vertical" chart view has been selected. You will see the labels:
"Use Column names as labels?" or "Use First Column as row label?"

I think a better naming for these would be to first:
1. Only use a captital letter on the first letter.
2. Remove the question mark

Result:
"Use column names as labels"
"Use first column as row label"

**Comment by kburtram** [comment]
@AlexFsmn I merged your related PR so I'll close this as fixed.  Thanks!
