### ISSUE TITLE
Initial value of the chart optionset is wrong

### ISSUE THREAD

**Issue by AlexFsmn** [Microsoft/sqlopsstudio#2265]
- SQL Operations Studio Version: 0.31.4 / Master branch

The inital value for the optionsets "Use column names as labels?" & "Use first column as label?" doesn't match the inital value of the charts.
The displayed value is "true" meanwhile the charts are initalized with false.
This makes the initial value wrong but synchronizes with the optionset value after a few clicks.

Steps to Reproduce:
1. Run a query
2. Switch to horizontal view
3. Click "Use First Column as row label?" -> Nothing will happen
4. Click it again and nothing will happen.
5. After clicking it a third time the value will synchonize with the checkbox and will update the chart.

The same error lies in the vertical view as well. However, there is no visual representation that will show this.

**Comment by kburtram** [comment]
@AlexFsmn I merged your related PR, so I'll close this as fixed.  The change will be in the next build later this week.
