### ISSUE TITLE
Can't edit AdventureWorks.Humanresources.Employee JobTitle column in Data Editor

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#2270]
- SQL Operations Studio Version: `master`

Steps to Reproduce:
1. Open `AdventureWorks.Humanresources.Employee` table in Data Editor
2. Edit `JobTitle` column and commit change by navigating to other row
3. Refresh resultset using `Run` buttong

Expected: Updated `JobTitle` value in edited column
Actual: Edit is lost and no error message

**Comment by kburtram** [comment]
@MattIrv you can use `sqltools300, 1833` for a repro if you don't have AdventureWorks installed in your test environment.

**Comment by kburtram** [comment]
@alanrenmsft any luck tracking this one down?

**Comment by alanrenmsft** [comment]
@kburtram still looking into it. having trouble with debugging, trying to fix the debugging issue now.

**Comment by kburtram** [comment]
Closing as fixed based on the merged PR https://github.com/Microsoft/sqlopsstudio/pull/2285.
