### ISSUE TITLE
Connect / Add Connection Doesn't Work

### ISSUE THREAD

**Issue by nwmiller** [Microsoft/sqlopsstudio#2274]
- SQL Operations Studio Version: Version 0.31.4 (0.31.4)

I am using a MacBook Pro running macOS High Sierra version 10.13.6.

Steps to Reproduce:
1. Open SQL Operations Studio.
2. Click the Add Connection button.
3. Connection drawer does not allow selecting a connection type or filling in any other details to establish a connection.

<img width="1670" alt="sqlopsstudio_connectiondrawer" src="https://user-images.githubusercontent.com/1454652/44406409-8a758580-a529-11e8-99e2-4ff8823dbb98.png">

<img width="1679" alt="sqlopsstudio_devconsole" src="https://user-images.githubusercontent.com/1454652/44406415-8cd7df80-a529-11e8-89e3-6cd1d791ecc9.png">

[sqlopsstudio-1534860158942.log](https://github.com/Microsoft/sqlopsstudio/files/2306563/sqlopsstudio-1534860158942.log)

Please let me know if any additional information is needed.

Thanks!

**Comment by kburtram** [comment]
@nwmiller I haven't seen an error condition like this yet, so initial thoughts could be something went wrong during install, or perhaps there is some invalid cached state.

I'd start by trying to reinstall by deleted the application binary, re-downloading, decompressing, etc.  If that doesn't work you can clear your cached state under `~/Library/Application Support/sqlops` (I'm not on my mac so the path my be off, let me know if you can't find it).  All the contents in the `Application Support/sqlops` directory can safely be deleted and will be recreated when SQL Ops executes.

**Comment by nwmiller** [comment]
@kburtram 

Hi,

Clearing the cached state under `~/Library/Application Support/sqlops` and reinstalling solved the issue. I initially had tried just reinstalling multiple times without success. It must have been a bad cached state.

Thank you for the quick response and resolution.

**Comment by kburtram** [comment]
@nwmiller thanks for confirming!  I'll keep an eye out for similar issue reports to try to determine what happened here.  Glad to hear you're unblocked.
