### ISSUE TITLE
Keep current connection

### ISSUE THREAD

**Issue by heneds** [Microsoft/sqlopsstudio#2288]
When working with multiple SQL-scripts (files) each file editor needs to be explicitly connected to a database. This is cumbersum since often the same database is used over and over again.

Steps to Reproduce:
1. Open a folder in explorer
2. Select one SQL file, connect and run the script
3. Select another SQL file, to run it you will need to connect again
Repeat step 3 for 10+ times and you'll soon switch SQL tool

It actually seems that even with an open file editor the connection is lost if the explorer is used to activate the editor. 

Expected behavior:
* More like Management Studio which has one current connection (application level) which changes depending on context so that different scripts can run against different connections if needed.

- SQL Operations Studio Version: 0.31.4

**Comment by heneds** [comment]
Issue #6 is similar but the solution only works for new (empty) queries.

**Comment by kburtram** [comment]
@heneds we're tracking this suggestion in https://github.com/Microsoft/sqlopsstudio/issues/641.  Please add comments there or reactivate if this is a different problem.  We plan to change to the behavior you describe in an upcoming release.
