### ISSUE TITLE
Keep connection on Script as...

### ISSUE THREAD

**Issue by Bikonja** [Microsoft/sqlopsstudio#2289]
Issue Type: <b>Bug</b>

When opening a connection and selecting a stored procedure (or something), the right click context menu contains options to Script as execute/alter/create, but when clicking on one of the options the resulting script does not have a connection.
By default, the scripts resulting from these options should use the same connection as the connection that was used to "Script as...".

![sql operations studio](https://user-images.githubusercontent.com/7753243/44470061-bcb5de80-a620-11e8-9027-0360da0877e5.png)

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (1.53GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2

</details>

**Comment by kburtram** [comment]
@Bikonja this should be fixed in the latest `insiders` build at https://github.com/Microsoft/sqlopsstudio/releases and will be in the August `stable` release planned for next week.
