### ISSUE TITLE
Add AAD authentication for Managed Instance

### ISSUE THREAD

**Issue by jovanpop-msft** [Microsoft/sqlopsstudio#2299]
Issue Type: <b>Feature Request</b>

For Managed Instance important scenario is connect with AAD account so please consider adding this. Min bar is AAD user with password like in SSMS.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@jovanpop-msft thanks for suggestion.  We're tracking this request in https://github.com/Microsoft/sqlopsstudio/issues/13.  Currently we're waiting on AAD support in the .Net Core SqlClient driver to surface this connection option in the UI.
