### ISSUE TITLE
Problems with stored procedures definitions

### ISSUE THREAD

**Issue by luismiguelgilbert** [Microsoft/sqlopsstudio#230]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Open SQL OS
2. Connect to database (OS: Microsoft Windows NT 6.1 (7601) || SQL: Microsoft SQL Server Standard (64-bit) 11.0.2100.60 || 
3. Go to procedures on left side panel
4. Right click on procedure and then select "Script as Create"
Error says "Title: Scripting Failed || Message: No script was returned when scripting as Create on object StoredProcedure".

This error is specific to some procedures. Some procedures doesn't show this error, while others do.

This is the procedure with error:

USE [FRAMEWORK_ERP_Clinicas]
GO
/****** Object:  StoredProcedure [dbo].[sp_RPT_Prj_Master_Select]    Script Date: 28/11/2017 10:07:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER  PROCEDURE [dbo].[sp_RPT_Prj_Master_Select]
(
	@Usuario VARCHAR(25),
	@CompanyID INT,
	@LanguageID VARCHAR(100)
)
AS
SELECT  
A.Project_ID ,
A.Parent ,
A.Code,
A.Name,
A.Prj_Stage_ID,
ISNULL(
	(SELECT TOP 1 int1.Name FROM dbo.Prj_Stages int1 WHERE int1.Prj_Stage_ID = A.Prj_Stage_ID AND int1.Language_ID = @LanguageID)
	,(SELECT TOP 1 int1.Name FROM dbo.Prj_Stages int1 WHERE int1.Prj_Stage_ID = A.Prj_Stage_ID)
)Prj_Stages_Name,
ISNULL(
	(SELECT TOP 1 int1.[Status] FROM dbo.Prj_Stages int1 WHERE int1.Prj_Stage_ID = A.Prj_Stage_ID AND int1.Language_ID = @LanguageID)
	,(SELECT TOP 1 int1.[Status] FROM dbo.Prj_Stages int1 WHERE int1.Prj_Stage_ID = A.Prj_Stage_ID)
)Prj_Stages_Status,
A.Partner_ID ,
ISNULL(
	(SELECT TOP 1 Partner_Name FROM dbo.Partner_Master_Names int1 WHERE int1.Partner_ID = A.Partner_ID AND int1.Language_ID = @LanguageID)
	,(SELECT TOP 1 Partner_Name FROM dbo.Partner_Master_Names int1 WHERE int1.Partner_ID = A.Partner_ID)
)Partner_Name,
ISNULL(
	(SELECT TOP 1 Partner_Name2 FROM dbo.Partner_Master_Names int1 WHERE int1.Partner_ID = A.Partner_ID AND int1.Language_ID = @LanguageID)
	,(SELECT TOP 1 Partner_Name2 FROM dbo.Partner_Master_Names int1 WHERE int1.Partner_ID = A.Partner_ID)
)Partner_Name2,
A.Date_Start,
A.Date_Stop,
A.Date_Start_Real,
A.Date_Stop_Real,
A.Progress,
A.Comments ,
A.Creation_User ,
A.Creation_Date ,
A.Last_User ,
A.Last_Date ,
A.Company_ID ,
(
	SELECT COUNT(*)
	FROM dbo.Prj_WareHouse INT1
	WHERE INT1.Project_ID = A.Project_ID
)Warehouses,
(
	SELECT COUNT(*)
	FROM dbo.Prj_Users INT2
	WHERE INT2.Project_ID = A.Project_ID
)Users
,CONVERT(NUMERIC(18,2),0) AS Facturado
,CONVERT(NUMERIC(18,2),1584614.78) AS Materiales
,CONVERT(NUMERIC(18,2),0) AS Varios
,CONVERT(NUMERIC(18,2),0) AS Contratistas
,CONVERT(NUMERIC(18,2),0) AS Mano_Obra
,CONVERT(NUMERIC(18,2),0) AS Direccion_Tecnica
,CONVERT(NUMERIC(18,2),0) AS Egresos
,CONVERT(NUMERIC(18,2),0) AS Rentabilidad
,CONVERT(NUMERIC(18,2),0) AS Porcentaje
/*B.Budget_Code ,
B.Budget_Name ,
B.Budget_Comments ,
B.Prj_Stage_ID ,
B.Estado AS Estado_Budget*/
FROM dbo.Prj_Master A
--INNER JOIN dbo.Prj_Budget_Master B ON B.Project_ID = A.Project_ID
WHERE A.Company_ID = @CompanyID
AND (
	(A.Parent IS NULL)
	OR (A.Project_ID IN 
			(SELECT int0.Project_ID FROM dbo.Prj_Master int0 WHERE int0.Company_ID = @CompanyID AND int0.Parent IN (SELECT int1.Project_ID FROM dbo.Prj_Master int1 WHERE int1.Company_ID = @CompanyID AND int1.Parent IS NULL ))
	   )
	)
ORDER BY A.Name

**Comment by llali** [comment]
This bug is fixed and will be in the next release

**Comment by llali** [comment]
Fixed in sqltoolservice v1.2.0-alpha.39
