### ISSUE TITLE
Modelview toolbar: buttons added don't act like buttons on the regular SQL query toolbar

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/sqlopsstudio#2306]
- SQL Operations Studio Version:

Steps to Reproduce:
- Create an extension that uses the `sqlops.ToolbarContainer` component and add a bunch of buttons to it
- Try clicking on the buttons

Expected:
- Buttons would act like the buttons on the SQL Query Editor. On click they "grow" then shrink in an animated way
Actual:
- Buttons have multiple click targets on clicking, just show an outline. 

This seems wrong and I'm not sure if any buttons should work this way. Would be great to fix / have configurable in the buttonComponent properties? This could be some kind of layout option?

![image](https://user-images.githubusercontent.com/10819925/44499645-a5371f80-a639-11e8-885e-b210c63c99f2.png)

![image](https://user-images.githubusercontent.com/10819925/44499647-a9fbd380-a639-11e8-95c1-af90c545b071.png)

**Comment by AbbiePetcht** [comment]
Fixed in master
