### ISSUE TITLE
"Started executing query at" line numbers are wrong

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#2320]
- SQL Operations Studio Version: master 4cce29e

Steps to Reproduce:
1. Run a query
2. View the messages pane

Actual behavior: The messages pane will show a message like "Started executing query at Line 0" where the line number is off by 1

@anthonydresser I think this is related to your grid changes, I don't remember seeing it before

**Comment by kburtram** [comment]
![image](https://user-images.githubusercontent.com/599935/45129403-5b216400-b138-11e8-8c83-9f1a6fac8fb4.png)
