### ISSUE TITLE
Settings to change the Results Pane formatting

### ISSUE THREAD

**Issue by sirphilliptubell** [Microsoft/sqlopsstudio#233]
- SQL Operations Studio Version: 0.23.6

Can settings be added so we can change the formatting of the Results pane? It would be nice to be able to edit the font, font-size, padding, etc.. for the cells. Currently the cells are much larger than in SSMS which limits how many rows are visible at a time.

**Comment by igor-khripun** [comment]
Also currently long cell content and long cell header are cut.

**Comment by real-napster** [comment]
Would be nice. Cannot wait for this!

**Comment by anthonydresser** [comment]
dupe #181
