### ISSUE TITLE
Cursor position on tab change

### ISSUE THREAD

**Issue by kalkotekedar** [Microsoft/sqlopsstudio#2343]
Issue Type: <b>Bug</b>

On every time switching tabs of open files, the cursor position moved to the top, If it is possible to persist the line number for that file then it would be great

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4610M CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (7.66GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by abist** [comment]
@kalkotekedar  This issue was fixed in the latest releases - https://github.com/Microsoft/sqlopsstudio/releases. Please try out the latest release and feel free to open the issue if you see it again.
