### ISSUE TITLE
Alter / Create statement needs reconnect to database

### ISSUE THREAD

**Issue by Hettic** [Microsoft/sqlopsstudio#2344]
- SQL Operations Studio Version: 0.31.4

Steps to Reproduce:
1. Connect to database
2. Search for View
3. Right mouse button on a view and choose Alter view...

Problem: Need to reconnect to the database again.
Solution: Why not stay connected as in SSMS?

**Comment by kburtram** [comment]
@Hettic this should be fixed in the 0.32.8 build.  Please reactive if the issue persists.
