### ISSUE TITLE
registerOperation for both dialog and wizard would throw exception. 

### ISSUE THREAD

**Issue by Xiaolei-Liu** [Microsoft/sqlopsstudio#2345]
Following exact the same sample code from https://github.com/Microsoft/sqlopsstudio/blob/e5096e61e5f8fd991f9dd440ffe6db2387f814b8/samples/sqlservices/src/controllers/mainController.ts

For both: 
sqlops.window.modelviewdialog.Wizard.registerOperation 
sqlops.window.modelviewdialog.Dialog.registerOperation 

It would directly throw exception:
TypeError: wizard.registerOperation is not a function
TypeError: dialog.registerOperation is not a function

It seems that even if it's defined as a function within sqlops.proposed.d.ts, but it's not actually a function. 
![image](https://user-images.githubusercontent.com/40051650/44775013-239a4100-aba7-11e8-834a-eeefca4ba1a1.png)

**Comment by MattIrv** [comment]
@Xiaolei-Liu what version of SQL Ops Studio are you using when you see this?

`registerOperation` was added recently so if you're using an old release (July Public Preview or older) then it won't have that API yet. If you need to upgrade I'd recommend building Ops Studio from master to get the latest changes or using the [most recent insiders release](https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.5)

**Comment by Xiaolei-Liu** [comment]
Hi Matt, yes, this is fixed once I use the most recent release. Thanks, I'll close this issue.
