### ISSUE TITLE
Text geht über Zelle hinaus

### ISSUE THREAD

**Issue by tenMari** [Microsoft/sqlopsstudio#2346]
Issue Type: <b>Bug</b>

Hi,
wenn ich eine Abfrage auf einer Logging-Tabelle ausführe in der in einer Spalte der Inhalt gesendeter E-Mails steht (Also ein langer HTML Code) geht der Inhalt der Zelle einfach über die anderen Zellen hinaus, sobald die Zelle in dem angezeigten Bereich ist.

<img src="https://user-images.githubusercontent.com/42807992/44791032-04001a00-aba1-11e8-986e-417431e957a3.png">

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor          (16 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.95GB (6.75GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4

</details>

**Comment by abist** [comment]
@tenMari This issue was fixed in the latest releases - https://github.com/Microsoft/sqlopsstudio/releases. Please try out the latest release and feel free to open the issue if you see it again.

**Comment by tenMari** [comment]
Still there for me in 0.32.7, which is the newest version i know so far.

<img src="https://user-images.githubusercontent.com/42807992/44850814-b3e78d00-ac5e-11e8-9b56-3d5cc197f80d.png">

**Comment by tenMari** [comment]
Error no longer occurs in version 0.32.8 for me, thanks.
