### ISSUE TITLE
Moverme entre archivos abiertos

### ISSUE THREAD

**Issue by JoseFloresDW** [Microsoft/sqlopsstudio#235]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.2.9200
---
Al abrir 2 archivos existentes y moverme dentro de ellos,  e iterncalar entro los 2 archivos, siempre me manda al principio del archivo, y no donde deje el cursor.

Steps to Reproduce:
1. 
2.

**Comment by kevcunnane** [comment]
This is a duplicate of #178. Closing this as #178 is the main tracking issue
