### ISSUE TITLE
Light SQL Color Theme error: white text on white background

### ISSUE THREAD

**Issue by dr-rodriguez** [Microsoft/sqlopsstudio#236]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:46:54.710Z)
- OS Version: Darwin x64 16.7.0
---

Steps to Reproduce:

1. Click the gear at bottom left and select Color Theme 
2. Change the color scheme to Dark SQL Operation Studio (or similar)
3. Change again to Light SQL Operation Studio

Color of basic text (and possibly other areas?) retains the previously selected color. So going from Dark to Light retains white text on white background. You can repeat this with other selections to have things like light orange text on the white background. Presumably the Light SQL color theme is lacking a default color definition for its text.

**Comment by kevcunnane** [comment]
I've seen this myself on a rare occasion, but had no luck debugging it. Restarting Ops Studio fixes the issue for me - can you try this too? There's some strange edge case where the default color is undefined even though it is set in the theme definition.

**Comment by dr-rodriguez** [comment]
Yes, restarting Ops Studio fixes this. I discovered this while cycling through the color-schemes using the up/down arrows.
