### ISSUE TITLE
Fix issues with VS Code 1.26.1 merge

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#2361]
List of issues:

_High priority bugs_
- [x] Execute query doesn't render results @mattirv
- [x] Query editor toolbar disappears when reloading tabs after hot exit @mattirv
- [ ] Fix test.bat @kburtram 
- [ ] Fix CI and VSO builds @kburtram 
- [x] Connection Dialog select boxes are broken on Windows @mattirv

_Lower priority bugs_
- [x] Profiler has similar issues to query execution with results not rendering (not a merge issue and addressed separately, see #2365)
- [x] Agent tables are throwing exception
- [x] Not all tests pass
- [x] Opening Agent dashboard fails (same issue as Profiler above, I verified that it's fixed by that PR)
- Show plan no longer works (not a merge issue, filed bug #2382)
- [x] Scroll position is no longer saved when switching tabs (see #2129 for previous fix) @mattirv
- [x] Some theme changes didn't get pulled over because our themes are different than VS Code's (Ken is looking at this)

_Other things to look at_
- [x] Editor positioning code changed, so make sure it's still working correctly
- [ ] Model view tree control may be broken due to VS Code tree interface changes
- [x] `OnAfterDocumentOpen` editor callback is gone so see if the removed code needs to be replaced somehow (this was the issue causing scroll position to not be saved)
- [ ] Make sure archived build works on all platforms
    - Windows build will need to be updated to run `vscode-win32-x64-user-setup` instead of `vscode-win32-x64-setup`

**Comment by MattIrv** [comment]
Just fixed the "Query editor toolbar disappears when reloading tabs after hot exit" and pushed it right to the merge branch. The file that we had edited to enable hot exit for query editors got moved as part of the editor group changes so the edits had to be reapplied

**Comment by karlb** [comment]
I think you've mentioned the wrong one. I'm not involved in this project.

**Comment by kburtram** [comment]
@karlb oops, it looks like you got my "preferred" username here on GitHub 😄 Sorry about the spam.
