### ISSUE TITLE
Insiders release of later date is triggering prompt for update to most recent stable release 

### ISSUE THREAD

**Issue by databull** [Microsoft/sqlopsstudio#2368]
Issue Type: <b>Bug</b>

Insiders release of later date is triggering prompt for most recent stable release

SQL Operations Studio version: sqlops 0.32.5-insider (d10e08e63ec26830efbcd070175ed935c36031f7, 2018-08-17T00:57:43.255Z)
![sketch](https://user-images.githubusercontent.com/22824483/44840851-ea5ee100-ac39-11e8-87b5-6376ec01f018.png)

OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (48 x 2197)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|383.91GB (238.34GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
server-report|Mic|0.1.3
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment]
@databull the current insiders release is `0.32.6` and current stable is `0.32.7`.  Are you being prompted to update again after installing `0.32.6`?

We'll have a new insiders build (`0.33.1`) out in the next few days that includes the VS Code 1.26.1 source refresh.

**Comment by kburtram** [comment]
@databull please reactive if the issue persists.
