### ISSUE TITLE
Release notes not available after install

### ISSUE THREAD

**Issue by brianjaikens** [Microsoft/sqlopsstudio#2369]
Issue Type: <b>Feature Request</b>

Just installed the latest version. 

The release notes are not available to view after choosing to install. 
Not even on the web site.

SQL Operations Studio version: sqlops 0.32.7 (b3766d7421bac5d8596eb2ce4980da5546325282, 2018-08-30T02:59:53.029Z)
OS version: Windows_NT x64 6.1.7601

**Comment by kburtram** [comment]
@brianjaikens you can view the engineering release notes at https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.7.  The official release notes will be published at 10am PST this morning and be available at https://docs.microsoft.com/en-us/sql/sql-operations-studio/release-notes?view=sql-server-2017 or using the `Show Release Notes` command.  

Typically I'll push the builds the night before the official documentation gets pushed to ensure the bits are correctly published.  I'll look into reducing this time gap for future releases to avoid confusing.  Thanks for pointing out this issue.

**Comment by brianjaikens** [comment]
Thank you for the reply.
You guys are awesome.

Brian

**Comment by AlexFsmn** [comment]
Seems like the official release notes are online now at:
https://docs.microsoft.com/en-us/sql/sql-operations-studio/release-notes?view=sql-server-2017
although most of the community contributions are missing. The only exception being the fix for issue 2099.

**Comment by kburtram** [comment]
Release notes are now public.  I'll try to reduce the window between publishing binaries and release notes in future builds.
