### ISSUE TITLE
Copy With Headers Will Now Copy The Header Before Each Row of Data

### ISSUE THREAD

**Issue by ryharris89** [Microsoft/sqlopsstudio#2372]
Before the July Update:
Copy With Headers copied the results data with the header row as the first row and the data following, like below:
column1header column2header column3header
row1column1data row1column2data row1column3data
row2column1data row2column2data row2column3data
row3column1data row3column2data row3column3data

After July Update:
Copy With Headers now copies the headers before each row of data. This is evident upon pasting the data into Excel, which looks similar to this:

column1header column2header column3header
row1column1data row1column2data row1column3data
column1header column2header column3header
row2column1data row2column2data row2column3data
column1header column2header column3header
row3column1data row3column2data row3column3data

**Comment by kburtram** [comment]
@ryharris89 this also looks like a bug with the way we're handing `Select All` similar to https://github.com/Microsoft/sqlopsstudio/issues/2371.

**Comment by kburtram** [comment]
@abist could you please look at this issue?  We should get a fix today so we can produce an August recovery build this evening if possible.

**Comment by kburtram** [comment]
This should be fixed in https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.8.  Please reactive if the problem persists in the latest build.

**Comment by kburtram** [comment]
This is back in `master`.  It may be related to the "Select All" PR that went in yesterday https://github.com/Microsoft/sqlopsstudio/pull/2496.  @anthonydresser or @abist could one of you please take a look?

**Comment by abist** [comment]
@kburtram I'll take a look
