### ISSUE TITLE
Can no longer export results to Excel, csv, or json 

### ISSUE THREAD

**Issue by dbarob** [Microsoft/sqlopsstudio#2384]
So prior to the new update SQL Ops Studio this was working, after the new update today, all this functionality is lost, 

I can attempt to export the file to say excel or csv, but when you go look for it nothing was written, no file anywhere ,

- SQL Operations Studio Version:

Steps to Reproduce:

**Comment by pmanna** [comment]
Same here, on build 0.32.8: it must be noted that, if a single row has been selected, the export succeeds.

Fortunately the previous build (0.32.7) was available to download and works properly, so I'm just avoiding updates at the moment.

**Comment by dbarob** [comment]
looks like if you select all the records right click and export it works, still looking at the new features list.

**Comment by kburtram** [comment]
@abist could you please take a look and see what happened her with the Export change in `0.32.8`?

**Comment by abist** [comment]
@dbarob  @pmanna Can you elaborate the steps to reproduce this issue? Are you directly clicking on the "Export to ..." buttons or Selecting a subset of the grid and right clicking to export into some file?

**Comment by dbarob** [comment]
@GDmac - what he said

**Comment by abist** [comment]
This is now fixed in the new release. I'm going to close this issue, please feel free to reopen it if you see it again!

**Comment by uniqalex** [comment]
Problem with export to Excel.
1. If you try to export the result to Excel after it is received, all the rows will be exported.
2. But if you have selected any rows or all of them - you cant roll back rows selecting and your export will be contains only first row.

Example for reproduce:
1. Execute some query where response have several rows
2. Select all rows in the result panel:
![image](https://user-images.githubusercontent.com/22915408/45829024-a627a380-bd02-11e8-8b8a-75d8819a5199.png)
3. Export data to Excel
The result has just first row
![image](https://user-images.githubusercontent.com/22915408/45829072-c0fa1800-bd02-11e8-99d1-00aae847c7a6.png)
