### ISSUE TITLE
Groups how to better orginize them

### ISSUE THREAD

**Issue by DavidhlnMT** [Microsoft/sqlopsstudio#2388]
- SQL Operations Studio Version:

Steps to Reproduce: Build groups.
If you would plz, after adding all instance I would like to change the order of groups. I attempted drag and drop which didn't work well and caused groups to disappear as well appears to put one in a sub group. I also thought I would change the order in the User Settings JSON but, they don't appear to be in any order there. So, my questions is how do you move groups around and how can you create sub groups? Thks

**Comment by anthonydresser** [comment]
This is a currently feature gap we have tracked #1275 . I'm going to close as dupe, feel free to reopen if you don't believe it is.
