### ISSUE TITLE
Error trying to edit any stored procedure.

### ISSUE THREAD

**Issue by AdrianCuartas** [Microsoft/sqlopsstudio#239]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.10586
---

Steps to Reproduce:

1. Right click on Stored Procedure 
2. Script as create

![image](https://user-images.githubusercontent.com/3962288/33363247-de52ebcc-d4df-11e7-8e4d-4005bc45a694.png)

It only happens over SQL SERVER 2016 Databases.

**Comment by Galaeci** [comment]
This seems to be related with procedures created using CREATE OR ALTER construct. If you use the standard
```
IF OBJECT_ID(N'schema.Procedure', N'P') IS NOT NULL
DROP PROCEDURE schema.Procedure;
GO
CREATE PROCEDURE schema.Procedure
```
the scripting option seems to work.

**Comment by AdrianCuartas** [comment]
Thanks for your reply.
I didn't do anything, today it just works.
