### ISSUE TITLE
Do not put an application shortcut when upgrading

### ISSUE THREAD

**Issue by Chiramisu** [Microsoft/sqlopsstudio#2391]
Issue Type: <b>Feature Request</b>

Please stop adding the shortcut back to the Desktop on every Upgrade. This should ONLY be done at the user's request, and I would argue only during the initial install. Deleting the shortcut is an act of intent, which usually means that the user does NOT want it there!

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:40:40.895Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@Chiramisu there is an update in the August installer to add a `Create Desktop Icon` checkbox, which is deselected by default.  If the option isn't set on initial setup then it isn't recreated on update.

@abist where did we land with fixing this in update scenarios from pre-August builds?  Did you find a way to avoid creating the icon in update scenarios?

**Comment by abist** [comment]
@kburtram The installations after the update changes the user setting but if a user has the old installation, the registry keys look for the old setting which has the Desktop Icon checked off by default. I'm not sure if we can override that without a fresh install.

**Comment by Chiramisu** [comment]
@kburtram Thank you sir. I have downloaded the latest installer (version 0.32.8) released on August 30 and installed it over the top of my existing install with the default options (unchecked as you stated). We will see on the next update if it honors that. :)
