### ISSUE TITLE
Cannot Export Data

### ISSUE THREAD

**Issue by hwrigh1** [Microsoft/sqlopsstudio#2403]
We have
Issue Type: <b>Performance Issue</b>

After I updated SQL Operations Studio, I can no longer export data in CSV, JSON, or Excel. Even something as small as 19 rows of data will not save. I get the 'Save As' dialog box, but nothing writes to the destination folder. I restarted and checked for updates again, but the issue still persists. 

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:40:40.895Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.83GB (3.90GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    99	  6492	sqlops main
    0	    47	  4564	   gpu-process
    0	   240	  6440	   window (_UPDATED_June_CallTags_Tina.sql - SQL Operations Studio)
    0	    91	  5976	     extensionHost
    0	    47	  4264	       electron_node jsonServerMain.js 
    0	    75	  6572	       "c:\Program Files\SQL Operations Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.28\MicrosoftSqlToolsServiceLayer.exe" --log-dir C:\Users\hwrigh1\AppData\Roaming\sqlops\mssql
    0	    26	  8680	       "c:\Program Files\SQL Operations Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.28\SqlToolsResourceProviderService.exe" --log-dir C:\Users\hwrigh1\AppData\Roaming\sqlops\mssql
    0	    38	  8888	       "c:\Program Files\SQL Operations Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.28\MicrosoftSqlToolsCredentials.exe" --log-dir C:\Users\hwrigh1\AppData\Roaming\sqlops\mssql
    0	    70	  6636	   shared-process
    1	    75	  7200	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none
 written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by 0angelic0** [comment]
Many Thanks @MattIrv! Right Click for the quick win.
@hwrigh1 Same as me lol

**Comment by abist** [comment]
@kburtram This should be fixed with the new insider build.

**Comment by the-reverend** [comment]
the workaround works for me also. thanks!

related to this, i'm getting a new error:
> You cannot save this document with extension “.txt” at the end of the name. The required extension is “.csv”
i don't know why it would decide to limit the file naming in this way. i'm saving a single column of data to a .txt file using a csv export feature. the new limitation seems overly opinionated. now i have to go rename the files after exporting them to meet my client's needs.

**Comment by abist** [comment]
This is now fixed in the new release. I'm going to close this issue, please feel free to reopen it if you see it again!
