### ISSUE TITLE
Column sizes are not retained when switching tabs

### ISSUE THREAD

**Issue by CobusKruger** [Microsoft/sqlopsstudio#241]
When switching editor tabs, the column widths of any open result sets are reset.

- SQL Operations Studio Version:
0.23.6

Steps to Reproduce:
1. Open two query tabs.
2. Execute a select statement in tab 1.
3. Resize a column in the result grid.
4. Switch to tab 2.
5. Switch back to tab 1.

Expected:
Column widths for the result set grid in tab 1 are as I left them.

Actual:
All column widths for the result set grid in tab 1 are back to their default widths.

**Comment by kburtram** [comment]
We are tracking all "lost state when tab switching" bugs in issue https://github.com/Microsoft/sqlopsstudio/issues/114.  Please add related comments there.

**Comment by CobusKruger** [comment]
> We are tracking all "lost state when tab switching" bugs in issue #114. Please add related comments there.

@kburtram Issue #114 has been closed, but this is still not fixed.
