### ISSUE TITLE
Save as CSV, Save as JSON, Save as Excel Buttons in Result set not working

### ISSUE THREAD

**Issue by ajinkyadeshpande** [Microsoft/sqlopsstudio#2415]
Issue Type: <b>Bug</b>

1. Connect to Server
2. Write Query
3. Run
4. Select Records
5. At Result Set : Try Clicking on: "Save as CSV, Save as JSON, Save as Excel Button" (Opens very slowly.)
6. If save acknowledged, there does not exist any file.
7. (Surprisingly on Right click on Result Set Saves perfectly.)

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:40:40.895Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.14GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by nilamo** [comment]
I can confirm this issue exists with version 0.32.8, and is a new issue as of this version.

**Comment by MattIrv** [comment]
See #2403 for more info
