### ISSUE TITLE
Not restoring unsaved files correctly

### ISSUE THREAD

**Issue by david-waterworth** [Microsoft/sqlopsstudio#2423]
The last or previous release seems to have broken the feature that if SSOS is closed, unsaved changes are still restored on open, i.e. originally if I created a new query, ran it then restarted SSOS without saving, the editor window containing my query would be restored. Now, when I open SSOS I get a series of empty editor windows, one for each unsaved query.

Also, If I create a new query via Ctrl+N, run it, then save, it creates a new editor window containing the saved file, and leaves the existing window blank. i.e. the image below shows the result of running a new query in SQLQuery1 editor window, then saving as data.sql. The sql has moved to a new editor window called data.sql, the SQLQuery1 editor is still open and contains the query result from the previous execution before saving.

![image](https://user-images.githubusercontent.com/38846586/45121333-e7716c80-b1b4-11e8-9f69-813229d5ed4a.png)

**Comment by david-waterworth** [comment]
To repo:

Open sqlopsstudio (if it restores any editors close them all)
CTRL+N to create a new query (Tab shows SQLQuery1)
Write a query (or just type some random text)
On the Explorer Panel to the left, click save all, name query SQLQuery1.sql

Now there's 2 tabs open, one empty titled SQLQuery1, and one with the new query titled SQLQuery1.sql

**Comment by kburtram** [comment]
@david-waterworth I was able to repro now.

**Comment by david-waterworth** [comment]
I suspect this is also the cause of it failing to properly restore on start.

**Comment by alanrenmsft** [comment]
the issue has been fixed by PR#2526.

**Comment by alanrenmsft** [comment]
@david-waterworth Could you please try the latest release: https://github.com/Microsoft/sqlopsstudio/releases/tag/0.33.3?

**Comment by david-waterworth** [comment]
Thanks @alanrenmsft  - that fixes the issue for me
