### ISSUE TITLE
Azure SQL DW Insights fails to install

### ISSUE THREAD

**Issue by abist** [Microsoft/sqlopsstudio#2425]
Installing Azure SQL DW Insights fails

**Reason** - https://sqlopsextensions.blob.core.windows.net/marketplace/v1/extensionsGallery.json/publishers/Microsoft/vsextensions/sqldw-insights/0.0.1/vspackage (says no blob found)

**Fix** - The actual link should be https://sqlopsextensions.blob.core.windows.net/extensions/sqldwInsights/sql-dw-0.0.1.vsix

**Comment by MattIrv** [comment]
Looks like a VS Code merge issue
