### ISSUE TITLE
Can't edit connection properties if part of server group

### ISSUE THREAD

**Issue by wmeitzen** [Microsoft/sqlopsstudio#243]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:46:54.710Z)
- OS Version: Darwin x64 17.2.0
---

I can't change a connection's properties if it's part of a server group.

Steps to Reproduce:

1. Launch SQL Operations Studio
2. Create a "New Server Group" (say, "Production")
3. Create a "New Connection" (say, "clienthost.company.com")
4. Right-click the new connection / Manage shows a list of tables in the database instead of bringing up a Properties window for the connection.

The only workaround I found to change one of the connection properties (say, to change the connection's default database), is to delete and re-create the connection.

**Comment by kevcunnane** [comment]
@wmeitzen can you elaborate on what you would like to edit? Are you looking to edit the name, the database being connected to, or some of the advanced properties...? This will help us understand the ask.

Note that the other workaround for this is to edit the `"datasource.connections"` JSON entry in your user settings.

**Comment by kburtram** [comment]
You should be able to open connection dialog and select the connection from the `Saved Connection` pane.  Once the connection properties have been loaded you can edit them and connect.  The connection will overwrite the previous connection properties.  Please reactive if this doesn't address your issue.

**Comment by andrew-bickerton** [comment]
Hi, can this issue be re-opened?
The only way to edit a connection is to click the 'New Connection' button, then in that dialog choose an already existing connection, alter the properties before finally clicking 'Connect'

This is not an intuitive process to manage a connection:
- To edit an existing connection, you need to click 'New Connection'?
- The process implies that you will either
  - Create a new connection (you're using the previous connection as the basis for the new one)
  - or create a temporary connection (not modify the previous saved connection)

Suggestions:
- Separate button to manage connections and/or right click menu option on Servers list to edit connection properties
- Save & Test connection option in the connection management pane

Note: A scenario that I use is to setup/configure all the servers that I'm going to need to connect to (I'll want to test my connections to make sure they work, but not want to open an active connection)
