### ISSUE TITLE
Saving untitled document w/results discards results

### ISSUE THREAD

**Issue by benrr101** [Microsoft/sqlopsstudio#2436]
Version 0.32.8
Commit efd470b3c771ef7473ba3cf108a33b6579c96a53
Date 2018-08-30T19:40:40.895Z
VS Code 1.23.1
Shell 1.7.16
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
1. Connect to a database, create new query and leave untitled, put in some kind of query
2. Execute query, observe there are results
3. Save untitled query

Expected: Results would be persisted
Actual: Results are discarded

I'm sure this is due to the underlying mechanism closing the untitled file and opening the saved file. Although this makes sense why it's happening, it's kinda annoying to lose results if you had a long running query and decided to save it after you wrote and tested it.

**Comment by anthonydresser** [comment]
dupe #1876
