### ISSUE TITLE
Backup Insights dialog doesn't show details and no action button

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#2444]
- SQL Operations Studio Version: `master`

Steps to Reproduce:

1. Open Backup Insights Details dialog on a server with databases needing backup

Expected: Details about select DB and a Backup action button

Actual: Expected UI elements are missing

![image](https://user-images.githubusercontent.com/599935/45185900-9a0af480-b1e0-11e8-8881-3627cbc5c2a4.png)

**Comment by abist** [comment]
This is fixed now.
