### ISSUE TITLE
Error Messages not showing up.

### ISSUE THREAD

**Issue by ranasaria** [Microsoft/sqlopsstudio#2464]
- SQL Operations Studio Version:
Version 0.33.2
Commit 9ca6200018fc206d67a47229f991901a8a453781
Date 2017-12-15T12:00:00.000Z
VS Code 1.26.1
Shell 2.0.7
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. In opsstudio run the following tsql:
```
USE [master]
GO
/****** Object:  Database [AdventureWorks]    Script Date: 9/6/2018 12:11:50 PM ******/
CREATE DATABASE [AdventureWorks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdventureWorks_Data', FILENAME = N'D:\sql\14.0.1000.169\sqlservr\data\AdventureWorks_Data.mdf' , SIZE = 174080KB , MAXSIZE = UNLIMITED, FILEGROWTH = 16384KB )
 LOG ON 
( NAME = N'AdventureWorks_Log', FILENAME = N'D:\sql\14.0.1000.169\sqlservr\data\AdventureWorks_Log.ldf' , SIZE = 18432KB , MAXSIZE = 2048GB , FILEGROWTH = 16384KB )
GO

USE [master]
GO
/****** Object:  Database [AdventureWorks1]    Script Date: 9/6/2018 12:11:50 PM ******/
CREATE DATABASE [AdventureWorks1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdventureWorks_Data', FILENAME = N'D:\sql\14.0.1000.169\sqlservr\data\AdventureWorks_Data.mdf' , SIZE = 174080KB , MAXSIZE = UNLIMITED, FILEGROWTH = 16384KB )
 LOG ON 
( NAME = N'AdventureWorks_Log', FILENAME = N'D:\sql\14.0.1000.169\sqlservr\data\AdventureWorks_Log.ldf' , SIZE = 18432KB , MAXSIZE = 2048GB , FILEGROWTH = 16384KB )
GO
```

This leads to the following messages:
**_6:11:33 PMStarted executing query at Line 1
Commands completed successfully.
6:11:33 PMStarted executing query at Line 2
Commands completed successfully.
6:11:33 PMStarted executing query at Line 10
Commands completed successfully.
6:11:33 PMStarted executing query at Line 13
Msg 5170, Level 16, State 4, Line 14
Msg 1802, Level 16, State 4, Line 14
Total execution time: 00:00:00.187_**

The actual error message is not visible. In fact if you copy and paste the output of the messages windows to a text editor then the correct messages can be seen. Here is the copy/paste output:
_6:11:33 PMStarted executing query at Line 1
Commands completed successfully.
6:11:33 PMStarted executing query at Line 2
Commands completed successfully.
6:11:33 PMStarted executing query at Line 10
Commands completed successfully.
6:11:33 PMStarted executing query at Line 13
Msg 5170, Level 16, State 4, Line 14_
### Cannot create file 'D:\sql\14.0.1000.169\sqlservr\data\AdventureWorks_Data.mdf' because it already exists. Change the file path or the file name, and retry the operation.
_Msg 1802, Level 16, State 4, Line 14_
### CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
_Total execution time: 00:00:00.187_

**Comment by DanwithArduino** [comment]
Same issue for me, running the latest stable release: 
![image](https://user-images.githubusercontent.com/10458867/45306597-13f5f300-b4eb-11e8-8f97-35a86f4e871b.png)
