### ISSUE TITLE
Database becomes "auto-closed"

### ISSUE THREAD

**Issue by JohnyL** [Microsoft/sqlopsstudio#247]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---
One of the databases constantly becomes "auto-closed". Reloading the editor about 10 times sometimes helps, but not always. In SSMS everything is OK. I'm using Local DB.

![SQLOPS_DB_AUTCLOSED_BUG](https://i.imgur.com/88muRYM.png)

**Comment by kburtram** [comment]
@JohnyL do you know if there are any particular repo steps that trigger this?  Are you doing anything with this DB that may help us determine what's going on?

**Comment by kburtram** [comment]
This issue may be related to https://github.com/Microsoft/sqlopsstudio/issues/189.  Or at least the same fix may help both issues.

**Comment by JohnyL** [comment]
@kburtram Thanks for tip! I have found the cause - the Auto Close option was somehow set in this databsase. I turned it off - now all is OK! 👍

**Comment by kburtram** [comment]
@JohnyL thanks for the confirmation!  I'll close this issue and track making a product fix in #189.
