### ISSUE TITLE
Export CSV\JSON is no longer working

### ISSUE THREAD

**Issue by lawrencebr** [Microsoft/sqlopsstudio#2482]
Issue Type: <b>Bug</b>

Write a query from a database.
Try to save the query as json or csv from the icon on the right with the query results.
A save as dialog will appear, but nothing happens.

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:40:40.895Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (17.40GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.1.5

</details>

**Comment by kburtram** [comment]
@abist this looks similar to some other issues you were looking at.  Can you confirm if this is fixed in `master`?

**Comment by kburtram** [comment]
FWIW this appears to be fixed in the latest `insiders` build per the discussion on https://github.com/Microsoft/sqlopsstudio/issues/1728.
