### ISSUE TITLE
Gap between results grid and messages

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#2485]
- SQL Operations Studio Version: `master`

Steps to Reproduce:

1. Run a query with several rows in the resultset

Expected: Result grid is full with messages

Actual: There's a gap between results and messages

![image](https://user-images.githubusercontent.com/599935/45328230-e1122600-b50f-11e8-9cd9-2bd291bc748c.png)

**Comment by kburtram** [comment]
@anthonydresser could you verify your recent style updates fixed this?

**Comment by anthonydresser** [comment]
@kburtram that was there intentionally to separate between grids
![image](https://user-images.githubusercontent.com/4324725/45329238-318b8280-b514-11e8-94b4-86c4cff5d426.png)
do you want me to remove it from every grid?

**Comment by kburtram** [comment]
@anthonydresser personally I prefer it without the space, and probably would optimize around the single resultset case, since that is the most common.

Though for minor issues like this I'm fine either way.  If possible it would be great to ask Smitha's opinion since I'm only going based on what "looks good" to me.
