### ISSUE TITLE
Running a query should expand the Results and\or Messages panes

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#2489]
- SQL Operations Studio Version: `master`

Steps to Reproduce:

1. Run a query
2. Collapse the Messages and Results Pane
3. Run a query

Expected: If the query successfully produces results the Results pane should expand, but the Messages pane should stay in previous state.  If the query has an error the Results pane is removed (assuming no results are produced) and the Messages pane is expanded.  This describes the August behavior.

Actual: Both Results and Messages panes stay in the previous state regardless of query execution outcome or error messages produced.

**Comment by anthonydresser** [comment]
I wonder if there is a better UX is accomplish the same problem. I could see it get annoying if a user has to keep closing a panel.

**Comment by kburtram** [comment]
@anthonydresser there may be a better UX, but the August behavior went through PM and UX design review, so we should either restore the previously reviewed behavior or do a design review for a new UX.  Since we want to ship the current gird changes in September I think it's probably quicker to just restore the previously reviewed behavior.  The current behavior is pretty broken, particularly if the rerun query has an error.
