### ISSUE TITLE
Failed SQL User Login on Saved Conection Right Click New Query

### ISSUE THREAD

**Issue by kd7vrc** [Microsoft/sqlopsstudio#2506]
Issue Type: <b>Bug</b>

I have a saved connection to a specific database on a server.  The correct credentials are also saved.  It is a SQL login, not a Windows login.  From the saved servers pane on the left, if it is currently disconnected, and I right click and select "New Query", I get an error that the login failed.  If I connect to the saved connection any other way (left click to connect, or connect new query to saved connection), it connects sucessfully.

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:40:40.895Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.49GB (8.36GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe .\stg\knx_icc_supmast_stg.sql|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
server-report|Mic|0.1.3
sql-dw|Mic|0.0.1

</details>

**Comment by alanrenmsft** [comment]
@kd7vrc Hi Steven, The issue has been fixed in this release: https://github.com/Microsoft/sqlopsstudio/releases/tag/0.33.5

Thanks
Alan
