### ISSUE TITLE
Query results grid loses scroll position and selection when tab switching 

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#2514]
- SQL Operations Studio Version: `master`

Steps to Reproduce:

1. Open two query editors
2. Run a query and scroll down and select some cells in one editor
3. Switch to the second editor
4. Switch back to the first editor

Expected: Results grid maintains scroll and selection position

Actual: Scroll position and selection is reset

**Comment by kburtram** [comment]
@MattIrv any ideas what might have regressed here?  It looks like it's working in August.

**Comment by MattIrv** [comment]
This functionality depended on the angular query results component and apparently didn't get carried over for the new one. I'll figure out how to put it back

**Comment by kburtram** [comment]
Assigning back to @anthonydresser per discussion in scrum this morning.  Please ping @MattIrv for context on how this was done previously if needed.

**Comment by kburtram** [comment]
This is fixed in `0.33.7`.  I opened a related "lost state" when tab switching bug at https://github.com/Microsoft/sqlopsstudio/issues/2641.
