### ISSUE TITLE
SQL Login to Server loses connection on new query

### ISSUE THREAD

**Issue by yualan** [Microsoft/sqlopsstudio#2516]
- SQL Operations Studio Version: 0.33.3

Steps to Reproduce:

1. Connect to SQL Server instance **with SQL Login** (not Windows Auth)
2. In object explorer, right-click server and open 'New Query'
3. Loses connection to server

**Comment by kburtram** [comment]
Looks like a dup of https://github.com/Microsoft/sqlopsstudio/issues/2506
