### ISSUE TITLE
Unable to see UDFs

### ISSUE THREAD

**Issue by ArmandoLacerda** [Microsoft/sqlopsstudio#252]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

When searching for functions  using the search box of browsing using the Servers pallet  I can't find any!
My database is a P2 Azure SQL DB compatibility level 110 and I am an server admin. No security issues.

The functions do show up when browsing using SSMS.

Steps to Reproduce:

1. Open SQL Operations Studio
2. Search or browse for UDFs

**Comment by llali** [comment]
@ArmandoLacerda the search box only searches for connections not database object.
So if you expand the tree nodes, you still cannot see the functions? can you please verify if you still see the same issue in the latest release?

**Comment by MattIrv** [comment]
This may be related to #595 where inline functions do not show up in Object Explorer but other kinds of user defined functions do.

**Comment by kburtram** [comment]
Closing since we don't have an active repro for this.  Please reactive if this is still an issue.  Thanks!
