### ISSUE TITLE
Add support for connection strings

### ISSUE THREAD

**Issue by aimankhan** [Microsoft/sqlopsstudio#253]
- SQL Operations Studio Version: 0.23.6

Add support for pasting a connection string directly into "New Connection"

**Comment by kburtram** [comment]
I verified this works with PR https://github.com/Microsoft/sqlopsstudio/pull/2284.  This feature will be available in the next insiders build later this week.

One note when pasting connection strings from Azure is they are provided in the format `tcp:####,1433` and thus we create the connection node matching this name.  It works, but ideally we'd strip out the `tcp:` and `,1433` if they're not needed to establish the connection.
