### ISSUE TITLE
Format Query

### ISSUE THREAD

**Issue by LGFN** [Microsoft/sqlopsstudio#254]
- SQL Operations Studio Version: 0.23.6

In Visual Studio we have a very useful function "Format", which essentially formats the codes with proper spacing and indents rendering it readable. How about having it here, as well?

**Comment by kburtram** [comment]
@LGFN there are commands `Format Document` and `Format Selection` available through the Command Palette and query editor context menu.

Are these commands not working as expected?

**Comment by LGFN** [comment]
Gosh, I missed it! Is it possible to customize?

**Comment by kburtram** [comment]
There are some options to customize formatting available in the user settings.  Please let us know if there are other options you are expecting.

![formatting_options](https://user-images.githubusercontent.com/599935/33494945-8d4fd05a-d679-11e7-9838-afd57f56212c.png)

**Comment by bigleka** [comment]
When I format a code with partition function we breaks part of the code:

`declare @mesSelecionado date = '2017-09-01'
SELECT count(1) as 'Total XPTO'
FROM [dbo].[TableX] n WITH (NOLOCK)
   where col1 <> 301
**AND $Partition
.PF_Part_01_Data
(n.timestampReg) = $Partition.PF_Part_01_Data
(@mesSelecionado)**`

**Comment by kburtram** [comment]
Closing this suggestion.  @bigleka I've moved your issue to https://github.com/Microsoft/sqlopsstudio/issues/432 to track that bug separately.
