### ISSUE TITLE
Find Table in field Search Servers

### ISSUE THREAD

**Issue by crmmvio** [Microsoft/sqlopsstudio#2546]
My Suggestion is allow field "Search Servers" find table too.

Is it possible?

Tks
Cleber

**Comment by kburtram** [comment]
@crmmvio we recommend people use the Redgate Search extension for searching their databases.  I'll keep this suggestion open to add an extensibility hook to the Object Explorer Search control so that extensions can hook-in to that experience to enable the functionality you've outlined.

**Comment by crmmvio** [comment]
Thanks for you return, I go to install Redgate Search.
