### ISSUE TITLE
Query Chart Tab disappears when tab switching

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#2548]
- SQL Operations Studio Version: `master`

Steps to Reproduce:

1. Run a query 
2. Click the Chart button to show a Chart Viewer tab
3. Switch to different tab
4. Switch back to original tab

Expected: Chart tab is still present

Actual: Chart tab disappears

**Comment by anthonydresser** [comment]
This should be fixed by the stating
