### ISSUE TITLE
sql.messagesDefaultOpen setting is not being honored

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/sqlopsstudio#2551]
- SQL Operations Studio Version:
master

Steps to Reproduce
1. Change the user setting sql.messagesDefaultOpen to false
2. Open a new query window and execute a query

Expected:
the messages tab is collapsed

Actual:
the messages tab is expanded

**Comment by anthonydresser** [comment]
I have a fix for this. Waiting on #2571 to be merged in since my fix utilizes the stating

**Comment by kburtram** [comment]
This is fixed in `0.33.7`
