### ISSUE TITLE
Connection Name field isn't disable while a connection is in progress

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#2557]
- SQL Operations Studio Version: `master`

Steps to Reproduce:

1. Connect to a server using Connection Dialog

Expected: Dialog fields are disabled while connecting

Actual: Connection name is still enabled.

![image](https://user-images.githubusercontent.com/599935/45458250-a93de680-b6a7-11e8-9fa5-fd0add96a5e1.png)

**Comment by abist** [comment]
This is now fixed in master, so closing.
