### ISSUE TITLE
sqlcmd cannot connect to local sql server using 'sqlcmd -S . -U sa' after sqlops installed

### ISSUE THREAD

**Issue by ChaosMerlin** [Microsoft/sqlopsstudio#256]
- SQL Operations Studio Version: sqlops-linux-0.23.6

- OS Version: CentOS7 x64 
-------------------------------------------------------------------------------------
Steps to Reproduce:
1. Installed sql server and sqlcmd on centos7 server,and use "sqlcmd -S . -U sa" to connect to local sql server succesefully.
2. Install sqlops,and now I can only use "sqlcmd -S 192.168.... -U sa" to connect to my sql server,while i can do that with "." or "localhost" specified within sqlops.

**Comment by kevcunnane** [comment]
@saurabh500 any ideas? This seems strange since SQLCMD is based on the ODBC driver stack and this should be unaffected by an independent .Net Core install? Could one of the recommended dependencies affect this?

**Comment by saurabh500** [comment]
@kevcunnane I agree that .Net core shouldn't impact the functionality of SQLCMD. I am not sure what is going on here. As you mentioned that the two stacks are independent, they shouldn't impact each other.

**Comment by erickangMSFT** [comment]
@ChaosMerlin This is a sqlcmd issue. Restarting the machine will resolve the sqlcmd issue. I also hit this issue regardless of sql ops studio on macOS.
