### ISSUE TITLE
Results view annoyingly steals focus from editor view

### ISSUE THREAD

**Issue by nalexander50** [Microsoft/sqlopsstudio#260]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Write a query
2. Execute a query
3. Try to modify that query immediately after execution
4. Results view has stolen focus away from the editor view

---

This is really annoying when you are trying to refine your query to get the data you want. Often times, your first query isn't the exact one that you wanted. We frequently have to qualify our queries with `where` clauses or `order by` clauses. Or sometimes we just make a mistake. In these instances, it's really frustrating that you have to manually click back on the editor view to begin typing again.

Furthermore, there is very little value in automatically selecting the first cell in the first row of the results. If you are copying results to share, it's very unlikely that the very first record was your target record.

**Comment by kburtram** [comment]
@corivera could you please verify this is already fixed?

**Comment by corivera** [comment]
Already fixed
