### ISSUE TITLE
Default keyboard bindings are messed up

### ISSUE THREAD

**Issue by AlexFsmn** [Microsoft/sqlopsstudio#2607]
- SQL Operations Studio Version: `master`

Steps to Reproduce:
1. Copy a text
2. Open a new script
3. Try to paste it using CTRL+V

Expected: clipboard text gets pasted in the new script file
Actual: nothing happens

Looking at the default keyboard bindings i find this:
![image](https://user-images.githubusercontent.com/11557675/45640426-eabd0000-bab2-11e8-81fb-5884182b10e6.png)

I have tried using the latest **stable** sqlopsstudio which works as expected.
Copy, pasting and selecting all text (CTRL+A) are the only commands I have tested so far. Might be more commands that doesn't work as expected.

**Comment by AlexFsmn** [comment]
I have no custom bindings that I know of. My user specific `keybindings.json` is the default one.

**Comment by MattIrv** [comment]
When I run Ops Studio I see the following errors in the console, maybe they're related?

```
[5520:0917/134105.963:INFO:CONSOLE(2280)] "Error: The module '\\?\C:\repos\sqlopsstudio\node_modules\native-keymap\build\Release\keymapping.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).", source: C:\repos\sqlopsstudio\node_modules\zone.js\dist\zone-node.js (2280)
[5520:0917/134105.964:INFO:CONSOLE(2280)] "TypeError: Cannot read property 'getKeyMap' of null", source: C:\repos\sqlopsstudio\node_modules\zone.js\dist\zone-node.js (2280)
Debugger listening on ws://127.0.0.1:5876/32a2c08c-6f6f-4a98-883f-6d3d569d64da
For help see https://nodejs.org/en/docs/inspector
```

**Comment by MattIrv** [comment]
Running a clean build (`git clean -ffxd` followed by `yarn; yarn run watch`) seems to have fixed things for me. Looks like this is a dev issue that needs to be fixed with a clean build by anyone running into it

**Comment by MattIrv** [comment]
I'll also double check if things are working correctly in the latest daily build

**Comment by MattIrv** [comment]
Verified things work correctly in the daily builds so this is definitely just a dev issue

**Comment by AlexFsmn** [comment]
Yes, that solved it. Thanks!
