### ISSUE TITLE
Results Panel - show / hide

### ISSUE THREAD

**Issue by ckcarroll** [Microsoft/sqlopsstudio#261]
- SQL Operations Studio Version: 0.23.6
Is there a way to nicely hide and show the results pane in a query window similar to SSMS Ctrl+R?
Steps to Reproduce: Run a query, try to hide the results pane.

**Comment by Hertweck** [comment]
when looking at the keyboard shortcuts I see, 
{
  "command": "grid.toggleResultPane",
  "key": "ctrl+alt+r",
  "when": "queryEditorVisible"
}
but it doesn't seem to do what I would expect, that being hiding and showing the results pane.

**Comment by erickangMSFT** [comment]
@saurabh500 + Saurabh to refer for the on-going work.

**Comment by saurabh500** [comment]
@ckcarroll I am not sure about the shortcut that you have found. We added the capability of hiding the results panel + message panel with a single action on our internal dev branch.

**Comment by saurabh500** [comment]
Note: I will look into the shortcut that you have found. May need a cleanup

**Comment by JayShockwave** [comment]
I accomplished this by creating my own hotkey as follows: File > Preferences > Keyboard Shortcuts, in the search area at the top, enter "toggle". Find "Toggle Query Results". Click the edit icon (pencil) to the right of this item and enter your keybinding. I entered CTRL+R. Works great.

**Comment by kburtram** [comment]
@ckcarroll the "Toggle Query Results" command should hide the results pane.  Please try setting the Ctrl-R shortcut to this command as @JayShockwave suggests.  Please reactive if this doesn't address your issue.

**Comment by MattIrv** [comment]
@hedmon I tried following the same instructions and see both the messages and results pane when it executes. Can you tell me what version of SQL Operations Studio you're using? Also, what is the output in the messages pane when you run the query? Thanks

**Comment by sthossan** [comment]
shift+windows icon+r

**Comment by gregoryderner** [comment]
Control+Shit+r on Mac Osx
