### ISSUE TITLE
Chart Viewer doesn't update when query is reexecuted

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#2619]
- SQL Operations Studio Version: `master`

Steps to Reproduce:

1. Run a query such as `SELECT 1`
2. Show the Chart Viewer
3. Re-execute the query with a change such as `SELECT 2`

Expected: Either the Chart tab does away or the chart is updated for resultset from step 3

Actual: Chart shows content from step 1.

**Comment by kburtram** [comment]
It looks like Query Plan tab has a similar issue where it doesn't update when the query is reexecuted.

**Comment by anthonydresser** [comment]
This has never been the behavior, it's just hid them before. I suppose I can restore that behavior

**Comment by kburtram** [comment]
@anthonydresser yes, we should either restore the previous behavior or correct the new behavior.  Having stale query plan and chart content that is out of sync with the resultset is confusing I think.

**Comment by anthonydresser** [comment]
I'll send a fix that restores the behavior of hiding those tabs. However we should probably keep a bug open to revisit this behavior to see if it makes more sense to just update the data.

**Comment by kburtram** [comment]
This is fixed in `0.33.7`
