### ISSUE TITLE
Ctrl-C with selected cell in Results won't copy item

### ISSUE THREAD

**Issue by ottadvantage** [Microsoft/sqlopsstudio#262]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1. Run a query
2. Click on a cell in the Results view
3. Press Ctl-C
4. Click in the query window
5. Press Ctl-V (or right click and select Paste)
You'll see the value pasted is not what you selected.
Workaround - 
1. Run a query
2. Right click on a cell in the Results view and select Copy
3. Click in query window
4. Press Ctl-V (or right click and select Paste)
Works!

**Comment by crushjz** [comment]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

I can confirm this. Moreover, i see an warning at the top saying: "rangy.getSelection is not a function".

**Comment by anthonydresser** [comment]
@ottadvantage @crushjz can you confirm if this is still happening in the most recent version of sqlops?

**Comment by nevridge** [comment]
I'm no longer having this issue with version 0.26.7
