### ISSUE TITLE
Results columns fit width to content

### ISSUE THREAD

**Issue by nalexander50** [Microsoft/sqlopsstudio#263]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Execute select query
2. Small columns take up extra space. Long columns are truncated

This is somewhat frustrating and something I really miss from SSMS. An ID column doesn't need to take up a fixed amount of space; it should just take whatever space it needs. Similarly, a datetime column shouldn't be truncated; it's actually important to see the full value.

The best way to handle this is just have the columns fit to their content width and truncate extra long columns like varchar(500) after a certain point. Right now, columns are truncated after about 15 characters and that's just way too few.

**Comment by corivera** [comment]
Same column size issue as https://github.com/Microsoft/sqlopsstudio/issues/172

Closing as duplicate
