### ISSUE TITLE
Cannot change back to default chart type when switching chart types

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#2635]
- SQL Operations Studio Version: master 03ea265

Steps to Reproduce:
1. Run a query
2. Click the "Chart" button to the right of the results
3. Switch the chart type to "image" and then back to "count"

Actual behavior: The chart shown is not the same one that was originally displayed
Expected behavior: There is some way to get back to the chart type that was originally displayed

Also if you switch off the tab where you ran your query and then switch back at this point it pops up an error "Unable to open 'SQLQuery1': Cannot read property 'set' of undefined." and you lose your query

**Comment by alanrenmsft** [comment]
the first issue has been fixed by: https://github.com/Microsoft/sqlopsstudio/pull/2651
the query window close issue has been fixed by Matt's PR.
