### ISSUE TITLE
Build 0.32.9 breaks Charts

### ISSUE THREAD

**Issue by Frank-Geisler** [Microsoft/sqlopsstudio#2646]
Hi!

I just discovered that build 0.32.9 breaks the diagram functionality. 

- SQL Operations Studio Version: 0.32.9

If you have this query (demo for a pie chart):

```sql
Select 'Text 1' as test, 0.3  as Num
UNION
Select 'Text 2' as test, 0.7  as Num
```
1. Execute it and display it as Chart

In 0.32.8 it is possible to select numberous chart types 

![image](https://user-images.githubusercontent.com/10083553/45812773-0867b080-bcd1-11e8-9373-95110e157bbb.png)

if you are using the exact same query in 0.32.9 the default chart looks strange and you can not select many charts:

![image](https://user-images.githubusercontent.com/10083553/45812852-48c72e80-bcd1-11e8-92d7-b10d8455ba5d.png)

**Comment by kburtram** [comment]
@Frank-Geisler sorry for the inconvenience.  We're working on a fix today.  The `0.32.8` build is available at https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.8 if you need to downgrade while we prepare a fix.

**Comment by Frank-Geisler** [comment]
Hi Karl!

Thank you for the Link to the old versiön. I will present on SQL Operations Studio at SQL Saturday Lisbon and so I can demo the Charts as well 😊

Thank you and have a nice day

Frank

**Comment by alanrenmsft** [comment]
Issue has been fixed by PR: https://github.com/Microsoft/sqlopsstudio/pull/2651
