### ISSUE TITLE
SELECT that returns a JSON hyperlinks the whole column

### ISSUE THREAD

**Issue by DanielSSilva** [Microsoft/sqlopsstudio#2648]
- SQL Operations Studio Version:

Steps to Reproduce:

1. Query a table that returns at least 1 JSON as result. Every record on that column is with an hyperlink and if you press it opens a new window.
![image](https://user-images.githubusercontent.com/6862119/45823190-10315000-bce5-11e8-9e79-c8783a4d76b5.png)

Changing the record that has the JSON to a "normal" nvarchar, the problem is gone
![image](https://user-images.githubusercontent.com/6862119/45823237-2d661e80-bce5-11e8-85fc-72816fda4c27.png)

Also, now the hyperlink is blue, making it unreadable. Previously it was orange it could be perfectly read.

**Comment by DanielSSilva** [comment]
What surprises me is not that it's being converted to JSON (I would assume it's being converted when it matches the JSON standard pattern). What surprised me is that if the column has at least one JSON, every record becomes blue and hyperlinked. This didn't happen previously

**Comment by kburtram** [comment]
We updated the results grid to better respect theme colors, which should improve the UX for most themes.  It looks like we missed setting the correct style for hyperlinks.  I'll work on a fix today.

**Comment by kburtram** [comment]
@AbbiePetcht please take a look at this bug it's appears related to https://github.com/Microsoft/sqlopsstudio/pull/2622.

**Comment by kburtram** [comment]
Here's what JSON columns look like with #2650.  It's now pulling the text color from the theme, but it looks like we lost the underline decoration.  At least the text is now readable and the mouse cursor changes to indicate a link on hover, so this should be acceptable for September, and we can fully address in October or a September recovery build.

![image](https://user-images.githubusercontent.com/599935/45851089-e3ce0180-bced-11e8-967a-ca0fe4d7a952.png)
