### ISSUE TITLE
Missing SPID number information in query window

### ISSUE THREAD

**Issue by gajuneja** [Microsoft/sqlopsstudio#266]
- SQL Operations Studio Version:

Steps to Reproduce:
1. Right Click on Server and select New Query.
2. At the bottom , i do see my SQL Server Instance name : database to which i am connected Line number,Column  Spaces UTF-X CRLF SQL  bu ti can not see the SPID number that has been established for this.

Thanks 
Gauravdeep Singh 
Gauravdeepjuneja@gmail.com

**Comment by kburtram** [comment]
@gajuneja closing this issue as a dup of https://github.com/Microsoft/sqlopsstudio/issues/229.  This is something that we plan to improve in an upcoming release.
