### ISSUE TITLE
Poor performance when a stored procedure prints a lot of messages

### ISSUE THREAD

**Issue by matuklong** [Microsoft/sqlopsstudio#268]
- SQL Operations Studio Version: SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)

My Machine: 
- SO: Win10 x64 - Build 15063.726
- Processor: Intel Core I5-6200
- Memory: 8GB

**Introduction:**

After executing a stored procedure that outputs many messages, the CPU and memory increases and the screen keep hanging. It takes a long time to end and stop hanging. While executing it, you can`t cancel.

The first execution takes a long time. The second execution performance is worse then the time before.

**Steps to Reproduce:**

1. Create a Stored Procedure to print messages:
```
    IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'TestPrint')
    DROP PROCEDURE TestPrint

    go
    create procedure TestPrint (
        @message    varchar(200),
        @quantity   INT
    ) 
    AS

    declare @i int = 1

    while (@i <= @quantity)
    begin
        declare @out varchar(250) = convert(varchar(10), @i) + ': ' + @message
        print @out
        set @i = @i + 1
    end

    go
```

2. Execute the procedure:
```
    -- Executes very fast
    -- exec TestPrint @message varchar(200), @quantity int
    exec TestPrint 'A simple test message', 10
    exec TestPrint 'A simple test message', 1000

    -- Takes a lot of time to execute, greater than 10 minutes
    -- if you can`t reproduce, just increase message quantity
    exec TestPrint 'A simple test message', 30000
```

Memory and CPU during the last command:
![sqlmessagehang-print1-while_executing](https://user-images.githubusercontent.com/4491249/33482679-64fddcfc-d681-11e7-8bf2-3c9cf50261fb.PNG)

**Comment by kevcunnane** [comment]
@anthonydresser I had thought we fixed a very similar issue to this, but I can repro this in the release build. Any thoughts on how to fix?

**Comment by anthonydresser** [comment]
This just looks like a problem with rendering so much on the dom. the proper fix would be to not use a table for the messages and convert it to an optimized table like slickgrid.

**Comment by kburtram** [comment]
Please check the repro in https://github.com/Microsoft/sqlopsstudio/issues/364 when closing this issue to confirm it is also fixed.

**Comment by anthonydresser** [comment]
This should be fixed in the next release
