### ISSUE TITLE
Result Grid doesn`t display all the rows when executing multiple selects

### ISSUE THREAD

**Issue by matuklong** [Microsoft/sqlopsstudio#269]
- SQL Operations Studio Version: SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)

My Machine:
- SO: Win10 x64 - Build 15063.726
- Processor: Intel Core I5-6200
- Memory: 8GB

Steps to Reproduce:

1. Execute the selects toghether in a single:
```
    -- sysobjects returns 92 rows
    select 1 queryNumber, name, id from sysobjects -- Display 92 rows
    select 2 queryNumber, name, id from sysobjects -- Display 92 rows
    select 3 queryNumber, name, id from sysobjects -- Display 13 rows (But the scroll bar has the necessary space)
```

The third grid doesn`t show all the rows. Show only 13 rows:
![query_not_displaying_all_rows](https://user-images.githubusercontent.com/4491249/33486470-55740b98-d691-11e7-8bea-899af14dbf69.png)

**Comment by JstnJ** [comment]
I'm also getting this on OSX 10.12.6 (16G1036) using SQLOps Version 0.23.6

**Comment by MattIrv** [comment]
I can verify this happens for me too with the given query.

As a workaround, click in any cell in the grid that is displaying incorrectly, then click in the empty white space to the right of that result grid. It should refresh and display the results correctly

**Comment by kburtram** [comment]
@MattIrv  do you know if this is fixed now?  If so, could you please verify and close this issue?  Thanks!

**Comment by MattIrv** [comment]
Yes, this is fixed for the February release and is part of the latest preview build: https://github.com/Microsoft/sqlopsstudio/releases
