### ISSUE TITLE
Ctrl+N after selecting a Server, doesn't create new window under the Server connection

### ISSUE THREAD

**Issue by afroz429** [Microsoft/sqlopsstudio#270]
- SQL Operations Studio Version:
0.23.6
Steps to Reproduce:
* Connect to Localhost using Windows Authentication
* Select Localhost in SERVERS pane
* Ctrl + N
expected: New window opens connected to Localhost
actual: New window opens in disconnected state

**Comment by kburtram** [comment]
@afroz429 we're currently tracking this suggestion in https://github.com/Microsoft/sqlopsstudio/issues/6.  This is an issue we plan to fix in an upcoming release.
