### ISSUE TITLE
Shortcut for executing a statement

### ISSUE THREAD

**Issue by afroz429** [Microsoft/sqlopsstudio#271]
- SQL Operations Studio Version:
0.23.6
Steps to Reproduce:
This is a feature request. Please let me know if this is not the right place for it.

To execute a statement, the current way is to select the text and press F5.
It would be great if no text selection was necessary and the current statement could be executed with a shortcut preferably  Ctrl + Enter

**Comment by kburtram** [comment]
@afroz429 does the `Run Current Query` `Ctrl-F5` command do what you're expecting?  It should execute the current statement where the cursor is located.

**Comment by afroz429** [comment]
@kburtram yes it does. Good to know. This lead me to explore UI more and I found keyboard shortcuts page :-)

Since this is a cross-platform tool and users who are used to Toad/MySQL workbench might prefer this tool vs SSMS, my guess is that they will feel at home with Ctrl + Enter shortcut. I just checked Datagrip which also has same shortcut for executing current query.
