### ISSUE TITLE
UI no response  when I create script from storedProcedures menu

### ISSUE THREAD

**Issue by Jackcu** [Microsoft/sqlopsstudio#276]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:46:54.710Z)
- OS Version: Darwin x64 17.2.0
---

UI no response  when I create script from storedProcedures menu

**Comment by llali** [comment]
this bug is fixed and will be in the next release
