### ISSUE TITLE
Azure SQL Data Warehouse: Scripting Tables and Views Fail

### ISSUE THREAD

**Issue by kevinvngo** [Microsoft/sqlopsstudio#277]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1. Right Click on Table or View
2. Select Script as create or Script as delete
3. View the follow error message: "No script was returned when scripting as Create on object Table"

![image](https://user-images.githubusercontent.com/15145589/33447724-fb9c7fca-d5b8-11e7-97fd-7f3042779ca8.png)

**Comment by llali** [comment]
this bug is fixed and will be in the next release
