### ISSUE TITLE
Database keeps loading after initial add

### ISSUE THREAD

**Issue by misha130** [Microsoft/sqlopsstudio#279]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
  1. Add Multiple Databases

I have been adding multiple databases from my azure SQL. One after another until I added a specific one that just kept loading and wouldn't let me open it.

I saw an error in the console that said:

```
[93m[main 2:06:55 PM][0m Cannot find node status for session: objectexplorer://mydb.database.windows.net;databaseName=mydbname…upId=ed11069f-09e5-4a4b-92d4-fe60016f2c27;displayName=mydbnameand node path: mydb.database.windows.net/mydbname
warn @ workbench.main.js:146
```

After removing and adding again this issue resolved itself.

**Comment by kburtram** [comment]
Closing older issues that we haven't been able to repro and haven't been upvoted.  Please reactive if this is still occurring on current builds.  Thanks!
