### ISSUE TITLE
Chart Viewer with Image doesn't work after the first run

### ISSUE THREAD

**Issue by MsSQLGirl** [Microsoft/sqlopsstudio#281]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Run the following code once.
DECLARE @RPlot NVARCHAR(MAX);
-- R code that produces image.
SET @RPlot = N'	image_file = tempfile(); 
	jpeg(filename = image_file, width=1000, height=800); 
    plot(iris);
	dev.off(); 
	OutputDataSet <-  data.frame(
        data=readBin(file(image_file,"rb"),
        what=raw(),n=1e6));	
'
	EXEC sp_execute_external_script @language = N'R'
		,@script = @RPlot 
		,@output_data_1_name = N'OutputDataSet' 
		WITH RESULT SETS (( [plot] VARBINARY(MAX)));	

2. Click on "View as Chart". Then click on "CHART VIEWER". Choose "image" from the "Chart Type" drop down list on the right. This should successfully show an image. 
![image](https://user-images.githubusercontent.com/6405919/33529778-1e4fdbb6-d82a-11e7-8124-89e984f64f3f.png)

3. Re-run the script. The "View as Chart" button doesn't work anymore. 
![image](https://user-images.githubusercontent.com/6405919/33529644-95890786-d828-11e7-95ec-80aec5d90e47.png)

**Comment by kburtram** [comment]
I can't currently repro this on current builds.  Please reactive if this is still a problem.
