### ISSUE TITLE
Multi-connection queries

### ISSUE THREAD

**Issue by CobusKruger** [Microsoft/sqlopsstudio#283]
It's great to have the connection groups. Now can we please open a query page linked to a connection group instead of an individual connection.

What I'd like to accomplish, is being able to execute a query once and have it run once per included connection. A use case could be creating a new stored procedure on all development databases.

- SQL Operations Studio Version:
0.23.6

**Comment by erickangMSFT** [comment]
duplicate of https://github.com/Microsoft/sqlopsstudio/issues/28
