### ISSUE TITLE
Don't initialize GIT on everything

### ISSUE THREAD

**Issue by Hertweck** [Microsoft/sqlopsstudio#285]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.14393
---

Steps to Reproduce:

1. I had a workspace, saved a query result as JSON to a different folder than in the workspace
2. The new location of the saved JSON results is in it's entirety added as GIT repository, I don't want that
3. Now I don't know how to unlink this new folder from SOS

**Comment by erickangMSFT** [comment]
@Hertweck This is interesting case. As long as the result.json file is stored outside of the git folder, it must not be included. @kburtram Karl any idea?

**Comment by kburtram** [comment]
I couldn't repro this issue.  Please reactive if the problem persists.
