### ISSUE TITLE
[TO CLOSE]Restoring a Backup file to AWS RDS SQL Server Express 2012 does not work (From a Windows Server 2012 R2)

### ISSUE THREAD

**Issue by Alexandre-Nourissier** [Microsoft/sqlopsstudio#288]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.3.9600
---
On AWS, inside a Windows VM, I am trying to restore a backupfile to a RDS instance. But the side panel for the restore doesn't work as intended and the software workflow are broken.

Steps to Reproduce:

1. Connect to a AWS RDS SQL Server Express 12.0.4422.0 SP1 ( Windows_NT x64 6.1.7601 (Windows Server 2012R2) on a hypervisor) database using SQL Authentication.
2. Click on the breadcrumb's server name.
3. Click on Restore. 

-- From this point, the connection to the database doesn't work anymore, any interaction requesting a fetch of data (open Tables directory by example or explicitly asking for refresh) fails until the software is closed and reopened.

4. On the "Restore Database" side panel opened, notice the never-ending loading indicator in the bottom left corner.
5. Change the "Restore from" drop-down to "Backup file".
6. Click on the "..." button in the "Backup file path" field.
7. Notice the empty explorer and the never-ending loading indicator in the bottom left corner.
8. Notice the "Selected path" field set at "D:\RDSDBDATA\BACKUP" (NO D Disk in mounted).
9. Set the path to a valid .bak file, submit the form.
10. The software doesn't provide a database to select.
10. The software doesn't warn of errors.

**Comment by Alexandre-Nourissier** [comment]
Additional Info:
When trying to Backup on the database on the previously environment, I do have a error popup stating that the file explorer wasn't able to load.

**Comment by erickangMSFT** [comment]
Any RDS users can try and help confirm if it's consistently happening? I don't have AWS account to try it out 😄

**Comment by BrentOzar** [comment]
I tried to reproduce it just now on RDS SQL Server Express 12.0.4422.0 and 14.00.1000.169.v1, and I was able to restore databases. I didn't have the symptoms @Alexandre-Nourissier described.

Keep in mind that you can't use file explorer in AWS, though - you don't have the permission to see local drives. If you want to do file system backups to Amazon S3, you have to use their proprietary backup & restore stored procedures:

https://aws.amazon.com/premiumsupport/knowledge-center/native-backup-rds-sql-server/

**Comment by Alexandre-Nourissier** [comment]
@BrentOzar Thank you ! I was only able to try with SSMS 2017 this afternoon and it just crashed on this two scenarii too. I don't usually work with AWS so I guess I'm good to read the manual on this one.  I consider this issue non-pertinent, except maybe the lack of errors on the restore scenario, which is non consistent with the backup scenario. 
@erickangMSFT Thank for the hard work too!
