### ISSUE TITLE
Try to get SSOS to import group of servers

### ISSUE THREAD

**Issue by jrodDBA** [Microsoft/sqlopsstudio#289]
- SQL Operations Studio Version:
0.23.6

Steps to Reproduce:
I would like the ability for the tool to import or connect to a SQL central management server just like SQL Management Studio would.

**Comment by kburtram** [comment]
@jrodDBA we're currently tracking CMS integration in this issue https://github.com/Microsoft/sqlopsstudio/issues/17.
