### ISSUE TITLE
Ability to specify results grid font and messages window font

### ISSUE THREAD

**Issue by lbendlin** [Microsoft/sqlopsstudio#292]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce: File...Preferences
Can only specify font for editor but not for results window. Existing font uses way too much space.

**Comment by mrlife** [comment]
I would like to be able to change to a monospaced font so that scanning down a list of sorted numbers is easier.

**Comment by mrlife** [comment]
I would like to be able to change to a monospaced font so that scanning down a column of sorted numbers is easier.

**Comment by anthonydresser** [comment]
dupe #181
