### ISSUE TITLE
SqlSelect no autocomplete  ###bug

### ISSUE THREAD

**Issue by levo2165** [Microsoft/sqlopsstudio#294]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Open New query window.
2. Type sqlSelect press enter.
3. Type Schame name.
4.Type Table name.
5 Table name does not complete automatically.

**Comment by SebastianPfliegel** [comment]
Works for me though. Are you using Tab to cycle through the fields?

**Comment by erickangMSFT** [comment]
If it's an ask for IntelliSense support within T-SQL comment block, it's not supported feature. IntelliSense should work in the actual select statement itself otherwise it's an issue.

**Comment by levo2165** [comment]
I use tab.
Begin to navigate to TableOrViewName automatically, then press shift + tab to navigate to SchemaName.
Change the schema name then change the table name.

**Comment by levo2165** [comment]
I use tab.
Begin to navigate to TableOrViewName automatically, then press shift + tab to navigate to SchemaName.
Change the schema name then change the table name.0404ed5275

**Comment by kburtram** [comment]
I can't repro this on the current build.  Please reactive if this is still an issue.  Thanks!

**Comment by levo2165** [comment]
It is still there. Version 0.27.3

**Comment by kburtram** [comment]
I rechecked the scenario and it appears to be working as designed.  In order to get schema-based completions please verify that the editor is in a connected state.  Please reactive with additional scenarios details if the problem persists.
