### ISSUE TITLE
Expand the Window to Show the Full Table Name when Table name is Lengthy

### ISSUE THREAD

**Issue by skkulla** [Microsoft/sqlopsstudio#297]
- SQL Operations Studio Version:

Steps to Reproduce: When you click Manage Database and It will Show the Objects and Ability to Search but some tables have long names and does have a way to identify which one is selected.

**Comment by AbbiePetcht** [comment]
Look like the it's a duplicated issue as  #231: Suggestion: Add horizontal scrollbar for Explorer widget - Can't see right most characters of names of "searched for" database objects

**Comment by kburtram** [comment]
We plan to address this scenario with a scrollbar rather than auto-resize.  You can manually edit widget in dashboard edit mode or user settings.
