### ISSUE TITLE
Dashboard refresh doesn't work when underlying query has changed.

### ISSUE THREAD

**Issue by martinisaksenprogleasing** [Microsoft/sqlopsstudio#30]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Add an insight based on a custom query.
2. Open the dashboard.
3. Change the query and save.
4. Refresh the dashboard/insight.

The refresh button doesn't seem to be doing anything at the moment. I have to close and reopen the dashboard before it picks up any changes.

**Comment by anthonydresser** [comment]
@erickangMSFT How do we want to handle this? Currently refreshing doesn't re-retrieve config settings, it only reexecute's any queries the widget may have done and rerenders. Do we want it to always re-retrieve settings?

**Comment by kburtram** [comment]
Let's track this issue as part of https://github.com/Microsoft/sqlopsstudio/issues/31 since the query is part of the collection of settings.
