### ISSUE TITLE
[#tempData] latest "]" will display green color

### ISSUE THREAD

**Issue by kkbruce** [Microsoft/sqlopsstudio#300]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Change user setting: "workbench.colorTheme": "Default Dark SQL Operations Studio" setting.
2. User like [#TempData] Syntax

```sql
SELECT *
Into [#tempData]
```

latest "]" display green color.

**Comment by corivera** [comment]
Issue doesn't repro in latest version
