### ISSUE TITLE
table-space-db-insight

### ISSUE THREAD

**Issue by TheEres** [Microsoft/sqlopsstudio#301]
Hello,

The "table-space-db-insight" widget do not display graph when used on a case sensitive database.

Reproducible : yes, steps:
1. Add widget "table-space-db-insight" to "dashboard.database.widgets" in settings;
2. Right-click/Manage any DB with a CS collation;

Expected result: a graph
Actual result : Error: Query has no results to return

Cause: the script used by the widget use Pascal casing for tables in FROM clauses.

Correction: change script "/extensions/insights-default/sql/tablespace.sql", update FROM clauses to use full lowercase table names (sys.tables, sys.indexes, sys.partitions and sys.allocation_units).

- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299

**Comment by erickangMSFT** [comment]
@TheEres @kevcunnane I confirmed it as an issue for both released public preview and internal build.

**Comment by erickangMSFT** [comment]
@TheEres Can you please check the following query works in your environment? 

```sql

SELECT Top 5 TABL.name AS table_name,
SUM(PART.rows) AS rows_count,
SUM(ALOC.total_pages) AS total_pages,
SUM(ALOC.used_pages) AS used_pages,
SUM(ALOC.data_pages) AS data_pages,
(SUM(ALOC.total_pages)*8/1024) AS total_space_MB,
(SUM(ALOC.used_pages)*8/1024) AS used_space_MB,
(SUM(ALOC.data_pages)*8/1024) AS data_space_MB
FROM sys.tables AS TABL
INNER JOIN sys.indexes AS INDX
ON TABL.object_id = INDX.object_id
INNER JOIN sys.partitions AS PART
ON INDX.object_id = PART.object_id
AND INDX.index_id = PART.index_id
INNER JOIN sys.allocation_units AS ALOC
ON PART.partition_id = ALOC.container_id
WHERE
INDX.object_id > 255
AND INDX.index_id <= 1
GROUP BY TABL.name,
INDX.object_id,
INDX.index_id,
INDX.name
ORDER BY
(SUM(ALOC.total_pages)*8/1024) DESC
```

**Comment by kevcunnane** [comment]
@erickangMSFT I double-checked and the casing was fixed internally 2 weeks ago. We need to test this against a case-sensitive server/DB such as @TheEres has to see what's going wrong.

**Comment by TheEres** [comment]
Yes, this query works, and when changing tablespace.sql, the insight is ok (chart displayed correctly).

**Comment by kevcunnane** [comment]
@erickangMSFT - are you definitely seeing this fail on our internal builds? This should be fixed based on @TheEres answer. Separately I've fixed the matching code snippet which still had this issue in it.

**Comment by kburtram** [comment]
From the comments it sounds like this is fixed.  Please reactive if this is still a problem.
