### ISSUE TITLE
Edit Data does not support filtering or sorting

### ISSUE THREAD

**Issue by juanfhoyo** [Microsoft/sqlopsstudio#302]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:
Data editor does not allow to change the select or order.

**Comment by erickangMSFT** [comment]
@juanfhoyo Edit data feature is in early preview form. Please keep filing issues / suggestions in that feature area. [help wanted]

**Comment by thesmallbang** [comment]
This is huge. It is the biggest reason why I can't switch to this as my day to day over SSMS

**Comment by kburtram** [comment]
Closing as duplicate of #78.  @corivera is currently implementing this feature by adding a SQL editor to the edit data document.
