### ISSUE TITLE
databases Azure SQL

### ISSUE THREAD

**Issue by juanfhoyo** [Microsoft/sqlopsstudio#303]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:
Connected to azure has difficulty listing the databases and columns can not be edited

**Comment by erickangMSFT** [comment]
@juanfhoyo are you experiencing a performance issue on Object Explorer? For column renaming, it is not supported feature yet.

**Comment by kburtram** [comment]
Closing out older issues that don't have a pending request.  Please reactive if there's still anything we should look at for this issue.
