### ISSUE TITLE
Intellisense for Linked Servers

### ISSUE THREAD

**Issue by hedgehogface** [Microsoft/sqlopsstudio#305]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce: type name of a linked server, type dot "."
(a Linked server from Server objects, linked to the current connection)

Please provide intellisense for linked servers.

**Comment by kburtram** [comment]
This is a upstream limitation.  Please log a User Voice issue against SMO\SSMS to prioritize this scenario.
