### ISSUE TITLE
Can't close the tabs

### ISSUE THREAD

**Issue by ArmandoLacerda** [Microsoft/sqlopsstudio#308]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

I rebooted my PC with some files opened. When it came back SqlOpsStudio reopened the files. I was able to close them but 2. Both tabs point to the same file, although they have distinct titles for whatever reason.

Here are some images for the "unclosable" tabs point to the same file:
![image](https://user-images.githubusercontent.com/15189226/33735680-dd6e8d9a-db44-11e7-8888-303129faa8ac.png)
![image](https://user-images.githubusercontent.com/15189226/33735699-ee75885a-db44-11e7-8669-635798e0c63e.png)
![2017-12-07_11-55-59](https://user-images.githubusercontent.com/15189226/33735990-e77fe1b6-db45-11e7-9577-23ba709a00a9.gif)

Steps to Reproduce:
Can't really tell how to reproduce it much further than described above.

1.
2.

**Comment by kburtram** [comment]
I haven't seen this type of issue recently.  Please reactive if this is still a problem.  Thanks!
