### ISSUE TITLE
"Script As Create" feature is too slow.

### ISSUE THREAD

**Issue by surajds** [Microsoft/sqlopsstudio#311]
Script As Create doesn't works most of the time. Many times it just suddenly pops after 3-5 mins.

- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

**Comment by kburtram** [comment]
The Dec\Jan release has perf improvements in this area.  Please reactive with specific examples if this is still impacting you.
