### ISSUE TITLE
Database Providers Capability

### ISSUE THREAD

**Issue by JoshClose** [Microsoft/sqlopsstudio#318]
Ability to add other database providers like postgres, sqlite, mysql, oracle, etc.

I started down the path of a SQLite Management Studio that looks almost identical to SQL Operations Studio. I don't see a point in continuing that work when this exists. I should be able to just write a provider to connect to sqlite that works within this tool.

**Comment by anthonydresser** [comment]
@JoshClose I'm going to close this as a dupe of #56 which is on our radar and should capture this feature request.  Feel free to reopen if you don't agree.

**Comment by JoshClose** [comment]
No problem! I did a search for a few key words that apparently weren't in that issue. ;) Thanks!
