### ISSUE TITLE
Something went wrong getting more rows

### ISSUE THREAD

**Issue by ThiruppathiR** [Microsoft/sqlopsstudio#319]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.14393
---

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/14212074/33924313-7f9e90d2-dffb-11e7-828a-3a1253f4f960.png)
1.Something went wrong getting more rows: Error: Result set index cannot be less than 0 or greater than the number of result sets

**Comment by kburtram** [comment]
@saurabh500 do you have any idea what went wrong here?

**Comment by saurabh500** [comment]
Not sure what's going on here. I haven't faced this issue. 
This seems to be reported on preview 1.

**Comment by ThiruppathiR** [comment]
I tried to reproduce this issue. But i can't. I will open this issue when it will reproduce, Thank you
