### ISSUE TITLE
Cannot switch back to Results view after choosing Chart Type of "time series" in Chart Viewer

### ISSUE THREAD

**Issue by Ansssss** [Microsoft/sqlopsstudio#32]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. Run this query:
`select '2017-06-22T00:00:00' [dt], 791 [count] 
union all select '2017-06-22T01:00:00' [dt], 451
union all select '2017-06-22T02:00:00' [dt], 528
`

2. Click the "View as Chart" button in the bottom Results pane, on the right side.
3. In the Chart Type drop down menu, choose "timeSeries"
4. No chart is displayed (I expected a chart to be displayed)
5. Click the Results name to the right of the Chart Viewer name to switch back to Results view (this fails, nothing is displayed).

**Comment by kburtram** [comment]
I can't repro this on the `0.28.6` build.  Please reactive if the problem persists on the latest build.
