### ISSUE TITLE
grid.toggleMessagePane and grid.toggleResultsPane are not working in version 0.23.6

### ISSUE THREAD

**Issue by neumannc** [Microsoft/sqlopsstudio#325]
While working with SQL Operations Studio, I missed the SSMS "Ctrl + R" functionality to show/hide results tab after executing a query. So I went to Keyboard Shortcuts (File > Preferences > Keyboard Shortcuts) and found these 2 shortcuts:
- grid.toggleMessagePane: Ctrl + Alt + Y
- grid.toggleResultsPane: Ctrl + Alt + R

When I try to enter these shortcuts nothing happens.

After googling this I came across another comment by Silverninja on a MSFT Docs page regarding the same subject - please refer to [this page](https://docs.microsoft.com/en-us/sql/sql-operations-studio/quickstart-sql-server).

- SQL Operations Studio Version: 
Versão 0.23.6
Confirmação 8a3011756318a2ded1e6e84332230a2b2bf9c544
Data 2017-11-06T21:51:43.232Z
Shell 1.7.9
Renderizador 58.0.3029.110
Nó 7.9.0
Arquitetura x64

**Comment by MikeRouten** [comment]
I can echo that this does not work in release 0.23.6.  Even if I set the grid.toggleMessagePane and grid.toggleResultsPane to a different shortcut it does not hide either message or results panes.

**Comment by MattIrv** [comment]
This bug is still in the current release. It looks like the results and messages panes only update correctly once you use the keyboard shortcut and then switch off the current tab and then back. I have a fix in #944
