### ISSUE TITLE
Error messages logged to console on Ubuntu 17.10

### ISSUE THREAD

**Issue by squillace** [Microsoft/sqlopsstudio#33]
- SQL Operations Studio Version:

Steps to Reproduce:
Ubuntu 17.10
bash/oh-my-zsh/terminology

follow install steps as described
type "sqlops" at prompt
receive the following, _but the app comes up and seems to work fine_

```
 ~ sqlops
Gtk-Message: Failed to load module "overlay-scrollbar"
/usr/share/themes/Ambiance/gtk-2.0/apps/mate-panel.rc:30: error: invalid string constant "murrine-scrollbar", expected valid string constant
```

relevant possibility: https://forum.qt.io/topic/68608/gtk-message-failed-to-load-module-overlay-scrollbar/6

https://twitter.com/kevcunnane/status/930924938298400768

**Comment by kburtram** [comment]
@squillace I installed a clean, default 17.10 Ubuntu desktop OS this morning to validate this scenario.  From a default install I had to manually install the following dependencies.

```
sudo apt install libgconf-2-4
sudo apt install libunwind8
```

I can see the "invalid string constant" error message, but not the module load error.  In any case, if the app is working then I would ignore the messages (assuming scrollbars are rendering correctly, etc.).  We'll look into getting this cleaned up once we have a .DEB package available in an upcoming release (likely Dec or Jan).

**Comment by squillace** [comment]
@kburtram thanks for having a look. I've not used the app extensively yet, but it does appear to be working fine, so I'm happy for now. Thanks for this tool!

**Comment by kburtram** [comment]
The current release at  https://github.com/Microsoft/sqlopsstudio/releases/tag/v0.24.1 introduces a DEB package that will auto-install dependencies.  I think if sqlops is installed via DEB it gets installed in a way that the stdout logging doesn't show in the console.  Please let me know if there is still an issue with the most recent build.
