### ISSUE TITLE
Learn More About Firewall Settings link doesn't do anything

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#339]
- SQL Operations Studio Version: 0.24.1

Steps to Reproduce:
1. Cause Create Firewall Rule dialog to display
2. Click the "Learn More..." link

Expected: Content to help me learn more is displayed

Actual: Nothing happens

**Comment by kburtram** [comment]
@benrr101 could you please take a look at this.

**Comment by benrr101** [comment]
@kburtram I've created a cheap fix for the issue by disabling the link. I've opened #450 to track a long term solution. But this should resolve for Jan release.
