### ISSUE TITLE
Chart Viewer doesn't work if query is re-run

### ISSUE THREAD

**Issue by martinisaksen** [Microsoft/sqlopsstudio#35]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Run "SELECT 1"
2. Select "View as Chart"
3. Run query again in same window.
4. Select "View as Chart"

What I'd expect to see:
I'd expect to be able to see the Chart Viewer tab again.

What I see:
The button doesn't do anything and the Chart Viewer tab doesn't appear.

**Comment by anthonydresser** [comment]
I can't repro this, @martinisaksen can you confirm if this is still happening in the most recent release?

**Comment by martinisaksen** [comment]
Yes. This still seems to be an issue in 0.26.7. 

The Chart Viewer tab is still missing on a subsequent execution run.

**Comment by anthonydresser** [comment]
I see, so you are expecting that the tab stays visible rather than having to re click to view chart button?

**Comment by martinisaksen** [comment]
No. I click the View as Chart button but nothing happens

**Comment by anthonydresser** [comment]
I think there are a few issues here.
1. Select 1 results throws an error if you view as chart
2. Once the result view throws an error, the view chart button no longer works

However, if you have a result that doesn't throw (ex. `select * from sys.objects`), it works as expected. If you rerun the tab goes away, but the button still works.

Does this sound accurate?

**Comment by martinisaksen** [comment]
Yes. That seems to be what is happening. I changed the SELECT to be "SELECT 1, 1" and that works fine. It seems like it throws an error when there is only one value in the SELECT. "SELECT 'test'" also errors.

**Comment by anthonydresser** [comment]
I'm going to lump the error being thrown issue in with #37 and re-title it as appropriate then open another tracking suggestion to not hide chart tab on re-run, #952.
