### ISSUE TITLE
After hot exit, editors display connection/query results incorrectly when switching tabs

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#356]
- SQL Operations Studio Version: December 18 RC 1

Steps to Reproduce:
1. Open a new query tab, optionally saving it (this repros for both saved and unsaved editors)
2. Close SQL Ops Studio with hot exit enabled and then reopen it. Your editor should still be open
3. Connect in the editor. You can do things like run queries. Do not save
4. Switch to another tab or open a new tab, then switch back to the original tab

Expected behavior: The original tab still displays its connection and query results correctly
Actual behavior: The original tab appears as if it no longer has a connection, though you can still run the query by clicking the "Run" button or using the command palette, and Intellisense still works. If you had executed a query in that tab, the results disappear
Workaround: Save the query after starting from hot exit

It looks like editors are opened as instances of `UntitledEditorInput` when reopening from hot exit, when they should be instances of `QueryInput`, which seems to be related to this issue.

Repros on Mac, Linux, and Windows.

![out](https://user-images.githubusercontent.com/3758704/34135923-4827b554-e418-11e7-88d1-232b52f1c43f.gif)

**Comment by kburtram** [comment]
@MattIrv I think I saw something like this before.  We should turn off hotexit and revert HotExit and get a new build produced.  I send a PR to revert the HotExit change.

**Comment by kburtram** [comment]
@AbbiePetcht I disabled HotExit for Dec due to this issue.  Could you please investigate a fix for January? Thanks!
