### ISSUE TITLE
Bar chart options start at lowest value

### ISSUE THREAD

**Issue by martinisaksen** [Microsoft/sqlopsstudio#36]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Run "
SELECT 'A' AS Label
    , 10 AS Cnt
UNION ALL
SELECT 'B'
    , 20
UNION ALL
SELECT 'C'
    , 21
"
2. Select "View as Chart"
3. Select horizontalBar or Bar from the Chart Type list.

What I'd expect to see:
The bar charts to start at 0.

What I see:
The bar charts start at the lowest value, 10 in this case. This makes it hard to read bar charts correctly since some of the meaning of the value is lost.

Perhaps an option to specify a starting value?

**Comment by anthonydresser** [comment]
It turns out we provide this capability through configuration already, but we don't expose this in the chart viewer. So I'm going to work on exposing this in the chart viewer rather than changing the default behavior.
