### ISSUE TITLE
Region collapse/expand hidden

### ISSUE THREAD

**Issue by chassq** [Microsoft/sqlopsstudio#363]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Region expand/collapse buttons fade in when hovered over. Makes them hard to find. At first I thought no region support was available. Can they be visible by default and have an option to make them fade in if others want it that way? Or vice-versa?

**Comment by egamma** [comment]
@chassq please use the following setting

`"editor.showFoldingControls": "always"`

**Comment by chassq** [comment]
@egamma Thank you!!
