### ISSUE TITLE
Copy paste with control->C doesn't work in results window

### ISSUE THREAD

**Issue by etriebe** [Microsoft/sqlopsstudio#367]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Run query
2. Highlight a row or column
3. Pretty ctrl->C

Result:
Nothing is copied and you get a warning that shows up something to do with range get selection something or other. This issue is intermittent.

**Comment by kevcunnane** [comment]
This should be fixed in the upcoming release. You can test the candidate for this at https://github.com/Microsoft/sqlopsstudio/releases/tag/v0.24.1. We are taking a handful of fixes for our final release but it will be pretty close to this version. Thanks for reporting!
