### ISSUE TITLE
Cannot connect to server that does not advertise

### ISSUE THREAD

**Issue by JalapenoBob** [Microsoft/sqlopsstudio#368]
- SQL Operations Studio Version:  0.24.1 for Windows

Steps to Reproduce:
During connection, using Windows authorization, name an SQL server that does not advertise..  I gave the server name in the forms: **machine.domain.tld** and **machine.domain.tld\sqlinstance**.  Neither worked. 
 Both returned the following:
    Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.

This server does not advertise as a security precaution, by order of management.  MS's Server Management Studio can connect, however. This appears to be a common issue with "third-party" tools:  many only allow selection from a list of servers who do advertise and, thus, are visible.

**Comment by kburtram** [comment]
We've fixed numerous connection related issues in the past few releases.  Please reactive if this still repros on the July build.
