### ISSUE TITLE
Add ability to easily change GUI Language

### ISSUE THREAD

**Issue by jrbilodeau** [Microsoft/sqlopsstudio#377]
- SQL Operations Studio Version: 0.24.1

Steps to Reproduce:
I installed SQL Operations Studio on Windows 10 localized to Français (Canada), so be default when i opened up the app, everything is in french. Normally i just go into the apps settings or prefferences and change the default language to English for ease of use of the application, but I can't find that option.

I when to File > Settings and searched for "lang" but didn't see any obvious setting to change the default language of the app.

**Comment by egamma** [comment]
@jrbilodeau pls use the 'Configure Language' command that is available in the command palette (`View>Command Palette...`), then you can change the language setting as shown below.

![image](https://user-images.githubusercontent.com/172399/34337082-e24b3324-e95c-11e7-8422-f9cbc20d021d.png)

**Comment by kburtram** [comment]
I'll close this issue now since the UI locale can be set following instructions above.  Please reactive if that isn't working.  Thanks!
