### ISSUE TITLE
Databases created using restore dialog should show in OE without needing to refresh

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#381]
- SQL Operations Studio Version: 0.24.1

Steps to Reproduce:
1. Use restore dialog to create a new database

Expected: Database is shown in OE tree once restore task completes

Actual: OE tree needs to be manually refreshed to show new DB.

**Comment by kburtram** [comment]
@abist I'll move this to March milestone, but if we can get it in for Feb that would also be great.  Thanks!

**Comment by abist** [comment]
@kburtram I have a PR out for this. If we get time to go over it, we can get it in for Feb or March is fine.
