### ISSUE TITLE
If a query fails due to timeout or network connection the next query execution doesn't works.

### ISSUE THREAD

**Issue by surajds** [Microsoft/sqlopsstudio#386]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. execute a huge query
2. Timeout occures
3. All next executions will now give below error.

Error: Query failed: BeginExecuteReader requires an open and available Connection. The connection's current state is closed. 
	

![untitled](https://user-images.githubusercontent.com/21216035/34246604-4d2b789e-e655-11e7-8974-fa15cd209daf.png)

**Comment by kevcunnane** [comment]
Can you try this on the December update (0.24.1)? We made a fix that should reopen closed connections on the next query run. This should resolve this issue. I’m going to proactively close but please reopen if this does not resolve it for you.
