### ISSUE TITLE
SQL Tab DB Icon is red

### ISSUE THREAD

**Issue by chassq** [Microsoft/sqlopsstudio#387]
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. When opening a new blank tab the db icon on the tab is red. I know this is a very minor point but red usually indicates a problem. Can you change colors?

**Comment by kburtram** [comment]
@smithaBharadwaj do you have any thoughts on the color of the DB icon in SQL Query editor documents?  We're currently reusing the icon that VS Code selected for us.

![screen](https://user-images.githubusercontent.com/599935/35074171-8218878e-fba1-11e7-8aba-1978a5662ef4.png)

**Comment by Chrille79** [comment]
Please let the icon color refects the Server Group Color. That why you know you are querying the right db

**Comment by anthonydresser** [comment]
@Chrille79 You can do something similar by changing the tab color to be the server group color
`  "sql.tabColorMode": "off"`

**Comment by kburtram** [comment]
The query editor icon will be updated in the next `insiders` build tomorrow.  The details are in PR #2135.
