### ISSUE TITLE
RID Lookup operator shown as Key Lookup (Clustered) in Explain Plan or Actual Plan

### ISSUE THREAD

**Issue by HugoKornelis** [Microsoft/sqlopsstudio#391]
- SQL Operations Studio Version: 0.24.1

Steps to Reproduce:
Connect to AdventureWorks2012 and paste in this query:
SELECT *
FROM   dbo.DatabaseLog
WHERE  DatabaseLogID BETWEEN 195 AND 198;
Click Explain, or select Run Current Query with Actual Plan from the Command Palette.

The resulting plan includes an operator "Key Lookup (Clustered)".
![afbeelding](https://user-images.githubusercontent.com/13858053/34264244-8a68acdc-e672-11e7-8e27-c7dd548c161a.png)
The corresponding node in the showplan's XML reads:
<RelOp NodeId="3" PhysicalOp="RID Lookup" LogicalOp="RID Lookup" (...) >

The node showing a Key Lookup should show an RID Lookup instead,

**Comment by kburtram** [comment]
The related upstream bug is closed and we've picked a vbump.  So I'll close this now.  Please reactive if the issue persists.
