### ISSUE TITLE
Windows Portable Exe

### ISSUE THREAD

**Issue by bladefist** [Microsoft/sqlopsstudio#393]
Instead of having to use a MSI installer would be nice to just download it and drop it on the system and run it.  Possible?

Thanks.

**Comment by kburtram** [comment]
@bladefist have you tried using the Windows ZIP download at https://go.microsoft.com/fwlink/?linkid=865304.  This ZIP contains and xcopy'able EXE that runs without Windows Installer installation.

**Comment by bladefist** [comment]
@kburtram Ah. I did not know that, many times the zip file is just a zipped installer.   Consider renaming it to Windows Portable to really get peoples attention.   Thanks! This'll work nicely.
