### ISSUE TITLE
gulp compile error

### ISSUE THREAD

**Issue by amwwgjj** [Microsoft/sqlopsstudio#400]
- SQL Operations Studio Version:0.24.1

Steps to Reproduce:

gulp compile

Error: D:/sqlopsstudio/extensions/mssql/client/src/resourceProvider/resourceProvider.ts(36,14): Argument of type '{}' is not assignable to parameter of type 'CreateFirewallRuleResponse | PromiseLike<CreateFirewallRuleResponse>'.
  Type '{}' is not assignable to type 'PromiseLike<CreateFirewallRuleResponse>'.
    Property 'then' is missing in type '{}'.
Error: D:/sqlopsstudio/extensions/mssql/client/src/resourceProvider/resourceProvider.ts(49,14): Argument of type '{}' is not assignable to parameter of type 'HandleFirewallRuleResponse | PromiseLike<HandleFirewallRuleResponse>'.
  Type '{}' is not assignable to type 'PromiseLike<HandleFirewallRuleResponse>'.
    Property 'then' is missing in type '{}'.
Error: D:/sqlopsstudio/extensions/mssql/client/src/resourceProvider/resourceProvider.ts(36,14): Argument of type '{}' is not assignable to parameter of type 'CreateFirewallRuleResponse | PromiseLike<CreateFirewallRuleResponse>'.
  Type '{}' is not assignable to type 'PromiseLike<CreateFirewallRuleResponse>'.
    Property 'then' is missing in type '{}'.
Error: D:/sqlopsstudio/extensions/mssql/client/src/resourceProvider/resourceProvider.ts(49,14): Argument of type '{}' is not assignable to parameter of type 'HandleFirewallRuleResponse | PromiseLike<HandleFirewallRuleResponse>'.
  Type '{}' is not assignable to type 'PromiseLike<HandleFirewallRuleResponse>'.
    Property 'then' is missing in type '{}'.
Error: D:/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/protocolConverter.d.ts(3,21): Cannot find module 'dataprotocol-languageserver-types'.
Error: D:/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/codeConverter.d.ts(3,21): Cannot find module 'dataprotocol-languageserver-types'.
Error: D:/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/protocol.d.ts(1,47): Cannot find module 'dataprotocol-jsonrpc'.
Error: D:/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/protocol.d.ts(2,1645): Cannot find module 'dataprotocol-languageserver-types'.
Error: D:/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/main.d.ts(5,134): Cannot find module 'dataprotocol-jsonrpc'.
Error: D:/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/main.d.ts(6,110): Cannot find module 'dataprotocol-languageserver-types'.
Error: D:/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/protocolConverter.d.ts(3,21): Cannot find module 'dataprotocol-languageserver-types'.
Error: D:/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/codeConverter.d.ts(3,21): Cannot find module 'dataprotocol-languageserver-types'.
Error: D:/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/protocol.d.ts(1,47): Cannot find module 'dataprotocol-jsonrpc'.
Error: D:/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/protocol.d.ts(2,1645): Cannot find module 'dataprotocol-languageserver-types'.
Error: D:/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/main.d.ts(5,134): Cannot find module 'dataprotocol-jsonrpc'.
Error: D:/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/main.d.ts(6,110): Cannot find module 'dataprotocol-languageserver-types'.
Finished compilation with 16 errors after 9013 ms

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
undefined

**Comment by abist** [comment]
Hi @amwwgjj, please run `scripts\npm.bat(.sh) install` and try running `gulp compile` again.

**Comment by SebastianPfliegel** [comment]
Got the same error. `./scripts/npm.sh install --arch=x64` runs fine, `gulp compile` fails though. I'm using the `master` branch and OpenSuse Tumbleweed as operating system.

> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/mssql/client/src/resourceProvider/resourceProvider.ts(36,14): Argument of type '{}' is not assignable to parameter of type 'CreateFirewallRuleResponse | PromiseLike<CreateFirewallRuleResponse>'.
>   Type '{}' is not assignable to type 'PromiseLike<CreateFirewallRuleResponse>'.
>     Property 'then' is missing in type '{}'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/mssql/client/src/resourceProvider/resourceProvider.ts(49,14): Argument of type '{}' is not assignable to parameter of type 'HandleFirewallRuleResponse | PromiseLike<HandleFirewallRuleResponse>'.
>   Type '{}' is not assignable to type 'PromiseLike<HandleFirewallRuleResponse>'.
>     Property 'then' is missing in type '{}'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/protocolConverter.d.ts(3,21): Cannot find module 'dataprotocol-languageserver-types'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/codeConverter.d.ts(3,21): Cannot find module 'dataprotocol-languageserver-types'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/protocol.d.ts(1,47): Cannot find module 'dataprotocol-jsonrpc'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/protocol.d.ts(2,1645): Cannot find module 'dataprotocol-languageserver-types'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/main.d.ts(5,134): Cannot find module 'dataprotocol-jsonrpc'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/main.d.ts(6,110): Cannot find module 'dataprotocol-languageserver-types'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/protocolConverter.d.ts(3,21): Cannot find module 'dataprotocol-languageserver-types'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/codeConverter.d.ts(3,21): Cannot find module 'dataprotocol-languageserver-types'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/protocol.d.ts(1,47): Cannot find module 'dataprotocol-jsonrpc'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/protocol.d.ts(2,1645): Cannot find module 'dataprotocol-languageserver-types'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/main.d.ts(5,134): Cannot find module 'dataprotocol-jsonrpc'.
> [19:27:07] Error: /home/sebastian/Software/sqlopsstudio/extensions/node_modules/extensions-modules/node_modules/dataprotocol-client/lib/main.d.ts(6,110): Cannot find module 'dataprotocol-languageserver-types'.
> [19:27:07] Finished compilation with 14 errors after 28523 ms
> 
> internal/streams/legacy.js:59
>       throw er; // Unhandled stream error in pipe.
>       ^
> undefined
>

**Comment by kburtram** [comment]
@SebastianPfliegel could you please try cleaning the repo using `git clean -fxd` prior to running `./scripts/npm install` and `gulp compile`?  I haven't seen this particular issue before, but if cleaning doesn't resolve the issue I'd guess there is some incompatibility with with the TypeScript or Node version being used to compile.

**Comment by SebastianPfliegel** [comment]
I used both `git clean -xfd` and `git checkout -- *` to have a clean repo.

Used versions:
NodeJS: 8.9.3
NPM: 5.6.0
Gulp: 3.9.1

I uploaded the logs from both commands:
[npm.txt](https://github.com/Microsoft/sqlopsstudio/files/1598675/npm.txt)
[gulp.txt](https://github.com/Microsoft/sqlopsstudio/files/1598676/gulp.txt)

**Comment by kburtram** [comment]
@SebastianPfliegel  thanks for the update.  I think there is an issue building with the latest version of node (or perhaps more specifically npm).  I believe our wiki recommends using the latest 7.## node (that's bundled with npm 3.## IIRC).  I know that I've used the 6.### LTS successfully recently on RHEL.

Let me try building with the latest 8.### node and see if the error can be easily worked around.

**Comment by SebastianPfliegel** [comment]
Using nvm to use node 7.9.0 (and npm 4.2.0) did the trick for me.
