### ISSUE TITLE
Prevent application launch using /VERYSILENT installation of Windows package

### ISSUE THREAD

**Issue by kendaleiv** [Microsoft/sqlopsstudio#401]
Hi! I'm the author of the `sql-operations-studio` Chocolatey package (https://chocolatey.org/packages/sql-operations-studio).

I'm looking to change the Chocolatey installer to use the Windows installer. However, I'm encountering some difficulty preventing the launch of the application after running the installer.

Should the installer launched with `/VERYSILENT` launch the application after installation? As in, should there be a code change, perhaps at https://github.com/Microsoft/sqlopsstudio/blob/8afebd2e10f7a671e268768d270f3b860f6aa85d/build/win32/code.iss#L71 or somewhere?

Or, is there some way to accomplish this from command line arguments?

**Comment by pascalberger** [comment]
It seems like it has taken the installer from Visual Studio Code and also supports the `! runCode` merge task.

So you can try to do it similar to what the Visual Studio Code package does [here](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/visualstudiocode/Tools/ChocolateyInstall.ps1)

**Comment by kburtram** [comment]
@kendaleiv could you please review @pascalberger's comment and confirm if that resolves the issue?  We use the same installer support as VS Code so presumably the same packaging techniques should work for both.  If this isn't the case please let me know.  Thanks!
