### ISSUE TITLE
Modify edit query

### ISSUE THREAD

**Issue by josh890** [Microsoft/sqlopsstudio#402]
- SQL Operations Studio Version: 0.24.1

**As a user I want to** modify Edit Data query to add filtering and joins for large tables **to be able to** manage datasets with large amount of data (or ones with complicated FK entries)

**Comment by erickangMSFT** [comment]
related: https://github.com/Microsoft/sqlopsstudio/issues/302

**Comment by thesmallbang** [comment]
This is huge. It is the biggest reason why I can't switch to this as my day to day over SSMS

**Comment by ScottRFrost** [comment]
Duplicate of #78 , #302 .  This can probably be closed.

**Comment by kburtram** [comment]
I'll close as dup.  @corivera is currently working on this feature and it should be in either April or May release.
