### ISSUE TITLE
All functions showing as scalar-valued despite showing as Table-valued in SSMS

### ISSUE THREAD

**Issue by useless5** [Microsoft/sqlopsstudio#407]
SQL Operations Studio Version: 0.24.1

Steps to Reproduce:
Connect to an existing database with Table-valued functions.
Expand the Functions folder and see if they are still listed as Table-valued or whether they now show under Scalar-valued Functions

**Comment by incredibleweirdo** [comment]
To be clear, all Table-Valued functions do show under Table-valued functions, but they _also_ show under Scalar-valued functions, cluttering the list of Scalar-valued functions. 
![image](https://user-images.githubusercontent.com/1223976/34422288-6a66ad42-ebc9-11e7-930c-d573cc3d1fcd.png)
![image](https://user-images.githubusercontent.com/1223976/34422293-73833b84-ebc9-11e7-9d62-4591dbff3071.png)

**Comment by useless5** [comment]
Hi - thanks for looking into this. When I connect to a server running Microsoft SQL Server 2008 R2 (SP3) - 10.50.6220.0 (X64)  - I don't get any table valued functions at all. They are all in the Scalar section.
![image](https://user-images.githubusercontent.com/17408087/34433232-d0cb95be-ec75-11e7-903f-d608e6f75cec.png)

![image](https://user-images.githubusercontent.com/17408087/34433236-d802af70-ec75-11e7-9517-d446749e6fea.png)

**Comment by useless5** [comment]
Sorry - same picture twice
![image](https://user-images.githubusercontent.com/17408087/34433256-00ec6aac-ec76-11e7-9fd8-2dd58d2ac9a1.png)
