### ISSUE TITLE
Pasting query from dark version is unreadable

### ISSUE THREAD

**Issue by quadzz** [Microsoft/sqlopsstudio#408]
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 10.0.14393
---

Hello,
When pasting from query editor window to anything that keeps formatting in default dark mode (Default Dark SQL Operations Studio) - the query is unreadable - the letters are white etc.
Except for Word - it keeps dark background:
![obraz](https://user-images.githubusercontent.com/28461795/34414865-00b7426c-ebec-11e7-9472-59b3eb9fbd62.png)

Oiriginal query:
![obraz](https://user-images.githubusercontent.com/28461795/34414798-a0b71dd8-ebeb-11e7-8965-7e99e9abb1d3.png)

Pasted:
![obraz](https://user-images.githubusercontent.com/28461795/34414810-ae1ae93c-ebeb-11e7-83d2-85208603eb10.png)

When pasting from dark SSMS (created by myself) - it uses default formatting.

**Comment by kburtram** [comment]
This is upstream behavior of VS Code (which we use for editing functionality).  They're tracking in this issue https://github.com/Microsoft/vscode/issues/21071 [No longer able to copy/paste without coloring](https://github.com/Microsoft/vscode/issues/21071).

You're probably aware already, but when pasting into Word there are Paste Options to use default formatting when pasting that may provide a workaround.

![paste](https://user-images.githubusercontent.com/599935/34588674-1e978838-f163-11e7-89d8-0681e230d3bb.png)

**Comment by kburtram** [comment]
Please reactive if this problem persists.
