### ISSUE TITLE
Right clicking on a database has very limited options

### ISSUE THREAD

**Issue by useless5** [Microsoft/sqlopsstudio#409]
SQL Operations Studio Version: 0.24.1

Steps to Reproduce:
Add a new connection to a server without specifying a default database.
Expand the Databases folder.
Right-click on a database - no option to view properties or delete database. Could these be added as tasks or as a right-click option?

**Comment by kburtram** [comment]
@useless5 thanks for the suggestion.  We plan to add additional options for managing databases, both through the context menu and through other UX, in future releases as we implement these features.
