### ISSUE TITLE
Results not aligned correctly

### ISSUE THREAD

**Issue by sateeshmachineni** [Microsoft/sqlopsstudio#41]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.17025
---

Steps to Reproduce:

1.run a query 
2.In the grid, you can see rows and columns are not aligned correclty

![capture](https://user-images.githubusercontent.com/13929851/32874230-f864e26e-cab6-11e7-992e-583aeea4f5e5.GIF)

**Comment by kburtram** [comment]
I haven't seen this issue recently (in the past few months).  Please reactive if this issue persists.
