### ISSUE TITLE
An awkward tile icon 

### ISSUE THREAD

**Issue by SAM224** [Microsoft/sqlopsstudio#410]
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 10.0.15063
---
when i add the program to my start menu, an awkward tile displayed 
Steps to Reproduce:

Change it pls.

**Comment by kburtram** [comment]
This looks like a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/375.  The issue has been fixed master and will be included in the next release.  Please reactive if the fix doesn't address your concerns.  Thanks!
