### ISSUE TITLE
Feature request: provide refresh interval,alert and sections for dashboard

### ISSUE THREAD

**Issue by ricoisme** [Microsoft/sqlopsstudio#413]
- SQL Operations Studio Version:0.24.1

Steps to Reproduce:

Hi 

I have some ideas about dashboard as below

1.Refresh interval:
I would like to get last status of sql server via charts but I need to click refresh first.
If we have this option of refresh interval (just like active monitor of ssms) , I think this option is really helpful in the real world.

2.Dashboard sections
I have a lot of dashboards on the sqlops already but I can't easy to manager or category them.
I think this option can make me to read charts clearer if I can create some section like OS section,wait type section,AlwaysOn AG section or else.

3.Alert
I can quick to find problem on my sql server if I can set up threshold of alert by each dashboard.

anyway sqlops is a so cool tool for sql server.

Thanks

**Comment by kburtram** [comment]
@ricoisme several of the items you suggested align well with our upcoming dashboard plans.  Once we have more concrete design notes available I'll post them on the wiki so we can collect early feedback.  Thanks!

**Comment by ricoisme** [comment]
@kburtram sounds good.
Thanks

**Comment by kburtram** [comment]
This is similar to issue https://github.com/Microsoft/sqlopsstudio/issues/31

**Comment by kburtram** [comment]
This should be supported now with the `autoRefreshInterval` setting.  Please checkout here for additional info https://github.com/Microsoft/sqlopsstudio/issues/1481.
