### ISSUE TITLE
Difficult to Tell State of Arrow in Tree for Highlighted Items

### ISSUE THREAD

**Issue by jopuckman** [Microsoft/sqlopsstudio#417]
- SQL Operations Studio Version: 0.24.1

Steps to Reproduce:

1. Add/attach database.
2. Expand a table.
3. Expand an empty folder underneath the table. For example, "Constraints".
4. Notice that the arrow to the left of the folder in the tree is difficult to see as it is gray and the highlighted item is blue.

![image](https://user-images.githubusercontent.com/5373721/34498584-50a7e9d8-efd0-11e7-961e-f69c865173e4.png)

Suggest making the color of the arrow match the color of the font when selected, so when the text is white, so is the arrow.

**Comment by kburtram** [comment]
@abist did you look at this issue previously?  if so, do you know what's going on here?

**Comment by abist** [comment]
@kburtram I did not work on this issue before, but I'll work with Smitha to get the correct colors.
