### ISSUE TITLE
Go statement doesn't recognize numerical execution count parameter

### ISSUE THREAD

**Issue by Matticusau** [Microsoft/sqlopsstudio#42]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Create a new query in SQLOPS

```
SELECT @@SERVERNAME
GO 5
```

2. Execute and it will only run once

3. Run the same query within SSMS or SQLCMD and it will execute multiple times.

This probably isn't a production type feature but handy with demonstrations, automation, and development work to provide a multi execution of a single batch
I know that this is not strictly a TSQL language but has been in our other client tools and very useful in the field.

**Comment by sateeshmachineni** [comment]
I think this is a bug,since it works on ssms and doesn't work only on ops studio

**Comment by erickangMSFT** [comment]
@sateeshmachineni this is a SSMS's feature but not T-SQL feature, hence a suggestion :)

**Comment by kevcunnane** [comment]
I may have an implementation for this, will update if correct.

**Comment by kevcunnane** [comment]
The fix works - will have this out for review shortly. Thanks for the feedback! The feature will be available in the next public release (and will also be supported in the VSCode-MSSQL extension).
