### ISSUE TITLE
UI glitches (empty squares) with version 0.24.1 on Mac OS Sierra 

### ISSUE THREAD

**Issue by gomezo76** [Microsoft/sqlopsstudio#424]
- SQL Operations Studio Version: 0.24.1

Steps to Reproduce:
Click right on a table then _Select Top 1000_ 

Result :
![sqloperationsstudio](https://user-images.githubusercontent.com/10235227/34522305-48d8e8de-f092-11e7-9feb-626e8ff7b138.jpg)

**Comment by kburtram** [comment]
I haven't seen this issue for a few months.  Please reactive if the problem persists.
