### ISSUE TITLE
Pull requests from forked repos fail to build on Travis because vscode-ripgrep can't be installed

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#428]
See https://travis-ci.org/Microsoft/sqlopsstudio/jobs/324680571 for example

We use a GitHub API token to download vscode-ripgrep as part of the build process on Travis, otherwise builds usually fail to install it with an error like "Downloading ripgrep failed: Error: API rate limit exceeded for 34.233.56.198. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", but Travis strips this token for builds from forked repos.

**Comment by MattIrv** [comment]
Investigated this a bit. It turns out we also install Electron directly from GitHub, so we would encounter rate limit errors there too. Fixing this while still using Travis may be difficult

**Comment by MattIrv** [comment]
Fixed this last week but forgot to close it

**Comment by nhooyr** [comment]
@MattIrv how did you fix this? We're running into this at codercom/code-server too.
