### ISSUE TITLE
Last DB Doesn't show on Server Dashboard

### ISSUE THREAD

**Issue by pabmcdonald** [Microsoft/sqlopsstudio#429]
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Clip on a server with a lot of databases (there is a DB named ZZZ)
2. Scroll to the bottom on the last DB (ZZZ) doesn't show up...

It is visible on the left on the Servers under Databases on the left tab.  But missing from the Server Dashboard.

**Comment by kburtram** [comment]
@anthonydresser could you please take a look at this?
