### ISSUE TITLE
How and where can we pose questions on SQL Operations Studio?

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/sqlopsstudio#433]
I have a few questions on SQL Operations Studio. Where to I put them, and which tags are required?

(E.g.: Does it interfere/coexist with existing VS Code installation? Will I have two VS Code installations or can I reuse my original VS Code installation?)

Please add the answer to my question [to the docs](https://docs.microsoft.com/de-de/sql/sql-operations-studio/faq#is-includename-sosincludesname-sos-shortmd-open-source).

**Comment by kburtram** [comment]
We don't currently have anywhere specifically to ask questions for SQL Ops Studio.  We do try monitor this gitter page https://gitter.im/Microsoft/mssql.

SQL Ops Studio should be fully isolated from VS Code.  We aren't aware of any bugs in side-by-side installations (we use VS Code as the primary dev environment for SQL Ops and haven't experienced any issues).  After installing SQL Ops Studio SxS with VS Code you will have two separate applications installed.

**Comment by SetTrend** [comment]
Marvellous!

Thanks for enlightening me 👍
