### ISSUE TITLE
Feature request: Shortcut for hiding query results

### ISSUE THREAD

**Issue by scalancea** [Microsoft/sqlopsstudio#44]
Would be handy to have a shortcut for toggling the results of the query. In SSMS it was Ctrl-R

**Comment by soham85** [comment]
I was searching for this all day long only to understand that this doesn't yet exists.

**Comment by jb300** [comment]
Yeah, used to (in mgm studio 2017.3) be a setting under "Tools", "Options", "Environment", "Keyboard", "Keyboard": "Window.ShowResultsPane (default CTRL+R), but in SQL Operations Studio preview (023.6) , under settings: "Settings", or "Keybord Shortcuts" I find no such option.

**Comment by felipebossolani** [comment]
Any update?

**Comment by erickangMSFT** [comment]
@felipebossolani this is addressed since December release. closing it as completed.

**Comment by felipebossolani** [comment]
@erickangMSFT thanks for your message. I'm using 0.24.1 on Windows and I can't find how to use it.

**Comment by saurabh500** [comment]
@felipebossolani Refer https://github.com/Microsoft/sqlopsstudio/issues/261#issuecomment-358779537
Assign your own hotkey to `Toggle Query Results` command.

**Comment by felipebossolani** [comment]
thanks @saurabh500 . It's working!
