### ISSUE TITLE
Object explorer doesn't work with APS

### ISSUE THREAD

**Issue by filipefumaux** [Microsoft/sqlopsstudio#455]
- SQL Operations Studio Version:

Steps to Reproduce:
Connect to APS using 17001
Expand  any object on explorer
An error will show: 'CONNECTIONPROPERTY' is not a recognized built-in function name.

**Comment by kburtram** [comment]
I'll duplicate this issue against https://github.com/Microsoft/sqlopsstudio/issues/840.  Thanks!
