### ISSUE TITLE
Feature Request: Keep saved query tabs after restarting

### ISSUE THREAD

**Issue by mrlife** [Microsoft/sqlopsstudio#463]
SQL Operations Studio Version: 0.25.0

After restarting sqlops, I would expect the query tabs to be in the same state as before sqlops was closed.

Steps to Reproduce:

- Create a new query
- Save the query to the file system (but don't close it)
- Restart sqlops
- Notice that there is an unsaved, empty query tab with the same title as the previously open and saved query tab

**Comment by kburtram** [comment]
I think this is related to HotExit feature we've enabled recently.  We'll try to fix for Jan release, otherwise we'll disable HotExit until we have a fix.
