### ISSUE TITLE
SQL Operations Studio cant expand list of databases.

### ISSUE THREAD

**Issue by ArsenAblaev** [Microsoft/sqlopsstudio#47]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/11280147/32882753-0e146470-cabe-11e7-8258-423205a49c17.png)

![image](https://user-images.githubusercontent.com/11280147/32883041-e53d17bc-cabe-11e7-9aab-cbc682e61bd6.png)

I cant see all list of databases, however there are a lot of ones.

**Comment by llali** [comment]
close as duplicate https://github.com/Microsoft/sqlopsstudio/issues/12
