### ISSUE TITLE
Edit Data: Deleting Last Row Adds New Row

### ISSUE THREAD

**Issue by benrr101** [Microsoft/sqlopsstudio#477]
- SQL Operations Studio Version: 0.25.2 (not a regression)

Steps to Reproduce:
* Open a table for editing that has some data in it (I'm using the table defined in https://gist.github.com/benrr101/31628b57f1ab410090237c9018860e05#file-ddl-sql)
* Right click on the any cell in the last row and select "Delete Row"

Expected Behavior: Row is deleted.
Actual Behavior: Row is deleted, a new empty row is added. (Note, no changes are made to the database).

**Comment by kburtram** [comment]
This doesn't repro on the current build.
