### ISSUE TITLE
Add "Check for updates" option.

### ISSUE THREAD

**Issue by mhosman** [Microsoft/sqlopsstudio#481]
Add "Check for updates" option in order to update the version of SQL Operations Studio.

**Comment by kburtram** [comment]
@mhosman the January release will contain the required product changes to support auto-updating to the February release.  We're in the process of setting up the necessary web service APIs to support this.

**Comment by kburtram** [comment]
February release will be released as an auto-update.

**Comment by mrlife** [comment]
@kburtram I just downloaded 0.26.4 (macOS) and the "Check for Updates..." menu item is gone. The menu item was there in 0.25.3 (though it didn't find the update for 0.26.4).

![screen shot 2018-02-14 at 2 18 14 pm](https://user-images.githubusercontent.com/213164/36223467-7f39bb76-1192-11e8-8437-aab7ff6d5715.png)
