### ISSUE TITLE
Doesn't connect with aliases

### ISSUE THREAD

**Issue by LarryC42** [Microsoft/sqlopsstudio#482]
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 10.0.15063
---
It would be nice if it could pick up on aliases at least on Windows.

Steps to Reproduce:

1. Create an alias
2. Attempt to connect to the alias

**Comment by kburtram** [comment]
@LarryC42 we're currently tracking this request in the following issue.  I'll close this as a duplicate.  Please upvote this issue so we can gauge user interest https://github.com/Microsoft/sqlopsstudio/issues/71.

The underlying problem were considering with this feature is that it depends on the Windows Registry which doesn't work in cross-platform scenarios, so we're deciding if this should be a Windows-only feature or if there is something we should also do to support non-Windows platforms.
