### ISSUE TITLE
Adding a record = Commit row failed: The target table 'dbo.PoopType' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

### ISSUE THREAD

**Issue by wallym** [Microsoft/sqlopsstudio#486]
- SQL Operations Studio Version:  0.24.1 (0.24.1)

Steps to Reproduce:
I am trying to add a record to one of my tables (don't ask why it is named what it is).  This is in sql azure.  I get the following error message:
Commit row failed: The target table 'dbo.PoopType' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.
In my 22 years of using and working with sql server, I have never seen this error before.  :-)
I can add this same record in Visual Studio on my windows system, and do not get an error.

table layout and triggers:
/****** Object:  Table [dbo].[PoopType]    Script Date: 1/15/2018 1:31:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PoopType](
	[PoopTypeId] [bigint] IDENTITY(1,1) NOT NULL,
	[DateEntered] [datetime2](7) NULL,
	[DateUpdated] [datetime2](7) NULL,
	[Name] [nvarchar](100) NULL,
	[TissueMultiplier] [float] NOT NULL,
	[Length] [int] NULL,
	[TissueRandomMultiplier] [bit] NULL,
	[AudioFile] [nvarchar](100) NULL,
 CONSTRAINT [PK_PoopType] PRIMARY KEY CLUSTERED 
(
	[PoopTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

/****** Object:  Trigger [dbo].[tr_PoopType_Insert]    Script Date: 1/15/2018 1:32:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[tr_PoopType_Insert]
	ON [dbo].[PoopType]
	FOR INSERT
	AS
	BEGIN
		SET NOCOUNT ON
		Update PoopType Set DateEntered=getdate(), DateUpdated=getdate() where PoopTypeId in (select PoopTypeId from inserted)
	END
GO

ALTER TABLE [dbo].[PoopType] ENABLE TRIGGER [tr_PoopType_Insert]
GO

/****** Object:  Trigger [dbo].[tr_PoopType_Update]    Script Date: 1/15/2018 1:32:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[tr_PoopType_Update]
	ON [dbo].[PoopType]
	FOR UPDATE
	AS
	BEGIN
		SET NOCOUNT ON
		Update PoopType Set DateUpdated=getdate() where PoopTypeId in (select PoopTypeId from inserted)
	END
GO

ALTER TABLE [dbo].[PoopType] ENABLE TRIGGER [tr_PoopType_Update]
GO

**Comment by kburtram** [comment]
@wallym I think this issue should be fixed in the latest builds from `master`.  The January Preview release candidate public is available at https://github.com/Microsoft/sqlopsstudio/releases/tag/0.25.4 which has this fix.

**Comment by benrr101** [comment]
That's correct, this issue will be fixed in the next release

**Comment by kburtram** [comment]
I'll close this as fixed in the Jan release (links available in readme.md).  Please reactive if the issue persists.
