### ISSUE TITLE
Feature Request: Extensions Support

### ISSUE THREAD

**Issue by junderhill** [Microsoft/sqlopsstudio#49]
Couldn't see that this has already been raised - it'd be great to be able to install Extensions as in VSCode. For instance being able to install VIM emulation.

**Comment by Ettery** [comment]
Agreed, makes sense to leverage the VS Extensions community, there are already a number of VS extensions which would be useful in the SQL context and more will come.

**Comment by kburtram** [comment]
The **March Public Preview** release announced our extensibility support.  We are now open to accept community contributed extensions and are working on multiple 1st party extensions that will be delivered over the next several releases.
