### ISSUE TITLE
Connection error when connecting to an Azure SQL Server with no firewall rule

### ISSUE THREAD

**Issue by stevestein** [Microsoft/sqlopsstudio#494]
- SQL Operations Studio Version:
Version 0.25.4
Date 2018-01-13T00:10:17.197Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

[OK]
Steps to Reproduce:
When connecting to an Azure Server, if I don't have a firewall rule I get this error. If I manually add the firewall rule (in the Azure Portal, etc..), I connect fine. If I then delete the firewall rule and try to connect, I get this error again.

![connection error](https://user-images.githubusercontent.com/9388190/35005445-4230531c-faa8-11e7-9af1-f7a5e4e440a1.png)

**Comment by kevcunnane** [comment]
@benrr101 @AbbiePetcht  this looks like an error in the firewall rule dialog - if I had to guess there are numerous calls to `this._createButton.enabled = true/false` so if one happens before `render` creates the button this could fail.

**Comment by kevcunnane** [comment]
@kburtram this breaks Azure scenarios badly. I think we need a reset for this. I'll have a fix out shortly.

**Comment by kburtram** [comment]
@kevcunnane @stevestein I've started the process of recreating a new release build.  Assuming no infra issues we should be fine for release tomorrow, if there are issues with signing\download publishing\etc. we may need to slip the release until Thursday.  I should have a good idea if we're still on-track for tomorrow within a few hours.
