### ISSUE TITLE
Feature Request - Show configured connections in "Connect" dialog

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [Microsoft/sqlopsstudio#50]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.17025
---
The Connect dialog shows "Recent History" connections for a simple "click to connect" experience.
It would be nice just have the configured connections available whether I have recently used them or not, so please replace "Recent History" with "Configured Connections".

Steps to Reproduce:

1. Write a query e.g. SELECT 'Hello World';
2. Disconnect by clicking Disconnect
3. Click connect - it only shows recent history

![image](https://user-images.githubusercontent.com/11338430/32885242-daabefe4-cab4-11e7-87b9-f7497fcfb255.png)

**Comment by kburtram** [comment]
We now show `Saved Connections` in the `Connection Dialog`.  Thanks for the suggestion!
