### ISSUE TITLE
Query execution shortcuts

### ISSUE THREAD

**Issue by CobusKruger** [Microsoft/sqlopsstudio#51]
Okay, firstly: For a first preview, this is already tremendously good.

One of the best features in SQL Management Studio is the ability to assign shortcut keys to query templates. So for example, if the cursor is on the table name 'Clients', pressing Ctrl+4 does a select from Clients, because that's how I have it configured.

I realize some of those shortcuts already do something different, but any ability to assign shortcuts to often-used queries will be terrific to have.

- SQL Operations Studio Version:
Preview 1

Steps to Reproduce:
1. Select some text
2. Ponder about the shortcut key that should execute a favourite query.
3. Realize that won't work.

**Comment by erickangMSFT** [comment]
Design note: 'Bring your own T-SQL script as a task (w/ a custom shortcut)'

**Comment by gbritton1** [comment]
for that matter, what _are_ the keyboard shortcuts in SOS?   I can't seem to find them

**Comment by anton-johansson** [comment]
`Tools -> Options -> Environment -> Keyboard -> Query shortcuts`

There they are.

Also, I suggest that you should be able to do this for arbitrary key binding, and not just `CTRL+X`, `CTRL+F1` and `ALT+F1`. Not that I need more (as of now), but you might as well open up for it, right?

**Comment by gbritton1** [comment]
@anton-johansson That's the path in SSMS.  We're talking about SOS here.  There is no Tools menu in SOS

**Comment by gbritton1** [comment]
never mind, found them under File/Preferences/Keyboard Shortcuts (or Ctrl+K, S)

**Comment by kevcunnane** [comment]
This should have been merged in for the December release. @CobusKruger you can have 10 shortcuts under your user / query settings - type in “shortcut” to the search box there to see these. You’ll also need to add key bindings. Let us know if this works and if you have feedback on the design.

**Comment by CobusKruger** [comment]
@kevcunnane This will do nicely, thanks.

The only issue is with the default shortcut assignments. [Windows Key]+number switches between active applications and it doesn't seem to make a difference whether I have Shift pressed as well. So the existing shortcuts for sp_who and sp_lock don't work for me (Windows 10 Anniversary update).
