### ISSUE TITLE
Connection List Gone

### ISSUE THREAD

**Issue by tmoorejoey** [Microsoft/sqlopsstudio#514]
- SQL Operations Studio Version: 0.25.4 - Mac

Steps to Reproduce:
After installation, if I delete a connection in the server area, I can no longer have ANY connections show up in the server window. I am able to reconnect to servers, but none of my connections show up under the servers section, and therefore I cannot browse through my objects.

I was able to uninstall and reinstall a newer version to fix it once, but now the problem is back.

**Comment by kburtram** [comment]
@tmoorejoey could you please check the "Help->Toogle Developer Tools" Console and let me know if there are any error message there?

Also, could you please try `datasource.connections` and `datasource.connectionGroups` entries from the user settings file to see if that helps?

**Comment by tmoorejoey** [comment]
At launch I got the following in the Console.

/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2296 [createInstance] First service dependency of RecentConnectionActionsProvider at position 1 conflicts with 3 static arguments
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2296

When adding the first connection the following was added.

/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:388 Angular is running in the development mode. Call enableProdMode() to enable the production mode.

After adding the connection and looking at user settings, the following is in the datasource areas.  It looks like the connections might not be being added perhaps?  After I add the connection, I get the Database Dashboard showing the connection, but nothing shows up in the Servers section.

{
    "datasource.connectionGroups": [
        {
            "name": "ROOT",
            "id": "C777F06B-202E-4480-B475-FA416154D458"
        },
        {
            "name": "Billing System",
            "id": "c01a6b63-e4bc-49e8-a6b8-30b806e46642",
            "parentId": "C777F06B-202E-4480-B475-FA416154D458",
            "color": "#515151",
            "description": ""
        }
    ],
    "datasource.connections": [],
    "workbench.sideBar.location": "left",
    "window.zoomLevel": 0
}

**Comment by kburtram** [comment]
The below error message shouldn't be in the log and is likely related to this issue (and possibly related to this change https://github.com/Microsoft/sqlopsstudio/pull/411, @AbbiePetcht any ideas what's happening?).  I'll try to repro and investigate a fix.

```
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2296 [createInstance] First service dependency of RecentConnectionActionsProvider at position 1 conflicts with 3 static arguments
```

As a temporary workaround you may be able to manually add your connection details in the settings file.  Here are a couple examples that use SQL Login and Integrated Auth.

```
    "datasource.connections": [
        {
            "options": {
                "server": "servername",
                "database": "",
                "authenticationType": "Integrated",
                "user": "",
                "password": "",
                "applicationName": "sqlops",
                "databaseDisplayName": ""
            },
            "groupId": "c01a6b63-e4bc-49e8-a6b8-30b806e46642",
            "providerName": "MSSQL",
            "savePassword": true,
            "id": "0bf60c21-d5ba-4a20-a224-730430f6c078"
        },
        {
            "options": {
                "server": "azuredbservername.database.windows.net",
                "database": "databasename",
                "authenticationType": "SqlLogin",
                "user": "username",
                "password": "PASSWORD",
                "connectTimeout": 30,
                "applicationName": "sqlops",
                "databaseDisplayName": "databasename"
            },
            "groupId": "c01a6b63-e4bc-49e8-a6b8-30b806e46642",
            "providerName": "MSSQL",
            "savePassword": true,
            "id": "0a72474e-1426-47cb-9da4-6652ebc35677"
        }
    ],
```

In the SqlLogin example the PASSWORD will be removed from the settings file and saved into the credential store when you first  use the connection if `"savePassword": true` is set.

**Comment by kburtram** [comment]
@tmoorejoey looked into this a bit and the `RecentConnectionActionsProvider` is being created incorrectly, but this doesn't appear related to your issue (if that was failing the Connection Dialog wouldn't be shown).  I'll fix that call though it won't resolve this issue.

I assume from your response there are no additional error messages in the Console after creating the connection?  Also, could you please confirm that the `Server group` value in the Connection Dialog is set to either `<Default>` or `Billing System` from your example snippet?

**Comment by kburtram** [comment]
Closing out older issues that don't have a pending request.  Please reactive if there's still anything we should look at for this issue.
