### ISSUE TITLE
Doe not run as a different user

### ISSUE THREAD

**Issue by UXR7002** [Microsoft/sqlopsstudio#53]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.14393
---

Steps to Reproduce:

1. Shift Right click... run as diff. user
2.

**Comment by kburtram** [comment]
Please reactive if this issue persists.
