### ISSUE TITLE
Encountered exception when adding a server to a group

### ISSUE THREAD

**Issue by AnEpicBeard** [Microsoft/sqlopsstudio#538]
- SQL Operations Studio Version: 0.25.4

Steps to Reproduce:
Made several server groups for prod I right clicked the server group and clicked add new connection, the other ones I used the new connection button at the top.  When connecting to a database where I don't have full access (while connected to a database in another server group) I received the following exception stacktrace:
System.IndexOutOfRangeException: Index was outside the bounds of the array. at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.d__37.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 309 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.ObjectExplorerService.d__37.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\ObjectExplorerService.cs:line 510

**Comment by kburtram** [comment]
Closing since we don't have an internal repro.  Please reactive if you're still hitting this on current builds.  Thanks!
