### ISSUE TITLE
Edit Data: Insert in table with identity fails

### ISSUE THREAD

**Issue by mrg3d** [Microsoft/sqlopsstudio#54]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1.Select any table with an identity column
2.Right click and select  "Edit Data"
3. Try to enter values manually
4. The result is the error  message "Commit row failed: A required cell value is missing"

**Comment by benrr101** [comment]
Hi @mrg3d, thanks for your report! Can you provide the schema of the table you're trying to edit and which columns you're trying to edit? The editor is *supposed* to disallow editing identity columns, but it's possible there are scenarios we're not addressing correctly.

This issue may be addressed with https://github.com/Microsoft/sqltoolsservice/pull/533, but I'll need to verify this more carefully with your scenario.

**Comment by mrg3d** [comment]
Hi @benrr101, 
At the moment I haven't the exact schema... but I got the error on more than one table. 
Each one with an identity column specified. On monday, once at work, I can give you one. 
But I'm pretty sure you can try creating one and replicate the case.
For example try with

CREATE TABLE dbo.TestIdentity (
  IdentityColumn INT IDENTITY(1,1) PRIMARY KEY,
  ValueColumn1 VARCHAR(100) NULL,
  ValueColumn2 VARCHAR(100) NULL, 
)

This is a schema very very similar to the one I was working on.
Well.. trying enter data manually, for exemple in col "ValueColumn1" (not in the identity col... obviously :) ) I always received the error.

**Comment by mrg3d** [comment]
Hi @benrr101,
This is the exact schema of my original table:
CREATE TABLE dbo.MarkupRules (
    RowId INT IDENTITY(1,1) PRIMARY KEY,
    CompanyId INT NULL,
    SupplierId INT NULL,
    CustomerId INT NULL,
    FromDate DATE NULL,
    ToDate DATE NULL,
    Percentage DECIMAL (5,2) NOT NULL
)

.. and this is a partial screenshot of the error
![image](https://user-images.githubusercontent.com/412938/33008830-06c7deee-cdd5-11e7-9d61-d85dcd888932.png)
 as you can see I tried entering values in columns CustomerId and Percentage (mandatory)..

Hope this help!!

**Comment by wallym** [comment]
I just tried this from my sqlops on mac.  The december update resolved my issue.
