### ISSUE TITLE
Missing feature: Displaying query plan in a separate window tab/panel

### ISSUE THREAD

**Issue by kohcj** [Microsoft/sqlopsstudio#543]
- SQL Operations Studio Version: 0.25.4

Steps to Reproduce:
Clicking on "Explain" toolbar menu on a query window, overwrites any previously query result panel with no way of going back to the result without having to re-run the query.

![sqlopstudio result query panel 1](https://user-images.githubusercontent.com/35787403/35366044-3d0160de-016f-11e8-81aa-d7aa9110ede2.JPG)

![sqlopstudio result query panel 2](https://user-images.githubusercontent.com/35787403/35366043-3cb6aaf8-016f-11e8-9f02-7c774031482f.JPG)

**Comment by kburtram** [comment]
@kohcj if you click the XML link it will open in a new editor.  If you then save that XML file with the `.sqlplan` extension it will render with the Show Plan UI control.  Please reactive if this doesn't meet your requirements in this scenario.  Thanks!
