### ISSUE TITLE
Database Folder and System Database folder missing

### ISSUE THREAD

**Issue by HakuAnnaruto** [Microsoft/sqlopsstudio#550]
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:51:42.102Z)
- OS Version: Windows_NT x64 10.0.14393
---
Database Folder and System Database folder missing - I cannot find any way to "add" them, e.g. like Tables, Views, etc. Every screen shot I've seen the Docs shows the Database folder and system Database folders - but mine is missing.

Steps to Reproduce:

1. open SQL Ops
2. expand Db connection

**Comment by MattIrv** [comment]
Hi @HakuAnnaruto, we only show the databases folders when you've established a "server" connection by leaving the database name blank (or setting it to master) when connecting. It sounds like your connection was set up with a specific database name filled in, is that correct? In that case you should be able to get to those folders by making a new connection that leaves the database name blank.

**Comment by HakuAnnaruto** [comment]
I deleted all my connections and tried again. If I enter the server name (instance server), using Windows Authentication AND enter Master for the database (not default) I get the object explorer tree WITH the database Folder and System database sub-folder. Seems odd; like it should be easier? Thank you though, as your reply, got me to re-think!
