### ISSUE TITLE
Script indexes

### ISSUE THREAD

**Issue by under3415** [Microsoft/sqlopsstudio#555]
- SQL Operations Studio Version: 0.25.4

New feature request:
- Add scripting option for indexes

**Comment by ghedwards** [comment]
Scripting the table for creation does not include the indexes, I think it should by default.

**Comment by kburtram** [comment]
This appears to be working as expected in the July release.  Please reactive if additional repro steps if the problem persists.

![screen](https://user-images.githubusercontent.com/599935/42957266-f33a9e1e-8b36-11e8-8c2f-68dd572131ad.PNG)
