### ISSUE TITLE
single quote in column name breaks syntax highlight

### ISSUE THREAD

**Issue by alexandregregoire** [Microsoft/sqlopsstudio#557]
- SQL Operations Studio Version:
0.25.4
Steps to Reproduce:
Use an alias with a single quote between brackets causes the syntax highlight to break.

![image](https://user-images.githubusercontent.com/26188087/35436331-4bc26210-028e-11e8-9a00-e0e27b175d14.png)

Thanks for this otherwise great tool :)

**Comment by corivera** [comment]
Fixed in https://github.com/Microsoft/sqlopsstudio/pull/580
