### ISSUE TITLE
Update README to be more relevant

### ISSUE THREAD

**Issue by mikaoelitiana** [Microsoft/sqlopsstudio#573]
It would be great if the README can be more relevant about SQL Operations Studio. It would contain description and screenshot from SQL Operations Studio instead of Visual Studio Code.

**Comment by jiskim** [comment]
the last commit( #571 )  seems to have forgot to  remove the Contribution.md and README.md from  the merge of  VS code and overwrote the old one. somone need to revert those file i think

**Comment by mikaoelitiana** [comment]
I will check and fix that.
