### ISSUE TITLE
 Error with charts

### ISSUE THREAD

**Issue by Finnhax** [Microsoft/sqlopsstudio#575]
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:51:42.102Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. Open new query
2. Run query
3. Click on 'View as chart'
4. Run query again
5. 'View as chart'-Button is no longer functional

**Comment by anthonydresser** [comment]
dupe #35
