### ISSUE TITLE
SQL Operations Studio reports itself as "sqlops" on MacOS

### ISSUE THREAD

**Issue by benrr101** [Microsoft/sqlopsstudio#576]
- SQL Operations Studio Version: 0.26.0 (dev build)

Steps to Reproduce:
* Run SQL Operations Studio on MacOS (I'm using Sierra)

Expected Results: Application Toolbar and about dialog says "SQL Operations Studio"
Actual Results: Toolbar/about dialog only says "sqlops"

<img width="324" alt="screen shot 2018-01-29 at 10 42 00 am" src="https://user-images.githubusercontent.com/585878/35527913-18381e94-04e1-11e8-9e4c-ba85015da6b5.png">

Not sure if this is only an issue in dev builds or if it is an issue all around.

**Comment by kevcunnane** [comment]
Same for VSCode. I'd suggest "by design"

![image](https://user-images.githubusercontent.com/10819925/35528031-666219e4-04e1-11e8-9c7a-b71628ef24a8.png)

**Comment by kburtram** [comment]
The vscode build scripts we forked use the product shortname for branding in macOS Application Bar and About box.  I'll close as "By Design" for now, but we can revisit if there is significant customer confusion from this.
