### ISSUE TITLE
Keyword "FULL" not highlighted by IntelliSense

### ISSUE THREAD

**Issue by yooakim** [Microsoft/sqlopsstudio#584]
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:56:42.471Z)
- OS Version: Linux x64 4.13.0-32-generic
---

Steps to Reproduce:

1. Enter a SELECT query
2. Write `FULL OUTER JOIN xxx`

The keyword FULL is never hightlighted

**Comment by kburtram** [comment]
@corivera please take a look at this when looking at other colorization issues.  Thanks!

**Comment by abist** [comment]
Fixed by https://github.com/Microsoft/sqlopsstudio/pull/580
