### ISSUE TITLE
Insigths (relative) path does not resolve correctly

### ISSUE THREAD

**Issue by mrg3d** [Microsoft/sqlopsstudio#585]
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:51:42.102Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Created my demo workspace (you can clone it from https://github.com/mrg3d/demo-opsstudio-repo)
2. Started ops from command line in this way, in order to start ops in my workspace
![image](https://user-images.githubusercontent.com/412938/35557361-32ee924e-05a5-11e8-8c7d-b05a0865cbf6.png)
3. Created a demo Insight and added to workspace settings (using a relative path)
![image](https://user-images.githubusercontent.com/412938/35557499-987a2eb6-05a5-11e8-8278-91d2be90bad8.png)
4. Opened the dashboard and... got an error: the path is resolved on sqlops.exe dir instead of workspace folder
![image](https://user-images.githubusercontent.com/412938/35557723-38a3a4bc-05a6-11e8-9e1d-d05425cbd04e.png)

**Comment by anthonydresser** [comment]
If you would like to use a workspace relative path you can use the keyword `${workspaceRoot}` to the beginning of the path and it will resolve it to the current workspace.
ex.
`${workspaceRoot}/Insight/Waitstats_simple.sql`
