### ISSUE TITLE
"ALT+ mouse selection" in text editor 

### ISSUE THREAD

**Issue by mrg3d** [Microsoft/sqlopsstudio#586]
- SQL Operations Studio Version: any

Steps to Reproduce:

On VS, SSMS, and many other editors we can make complex selection combining ALT key and mouse.
This feature is very useful but missing in ops text editor! 
 
![image](https://user-images.githubusercontent.com/412938/35558252-d96f229e-05a7-11e8-86a1-4c58be308763.png)

**Comment by kevcunnane** [comment]
These are supported but with slightly different keybindings. Please take a look at the `Multi-cursor and selection` section in https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf and if there's still a missing feature please do let us know. Also you can change / override any keybinding in `Keyboard Shortcuts` if you want to go back to using Alt + Mouse Click

![image](https://user-images.githubusercontent.com/10819925/35585457-c94467ee-05ac-11e8-9355-e248fb838a35.png)
