### ISSUE TITLE
Table-valued Functions not shown in Explorer bar

### ISSUE THREAD

**Issue by louis77** [Microsoft/sqlopsstudio#595]
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:51:42.102Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Connection to database
2. Open "Programmabillity" > "Functions" > "Table-valued Function"

None of the existing functions are shown. However, Scalar-valued Functions are listed correctly.

**Comment by belliste** [comment]
It doesn't show inline table valued functions. Multi-statement functions are correctly listed. (Ver 0.25.4)

**Comment by kburtram** [comment]
@erickangMSFT please verify if this still repros on the latest builds in master.

**Comment by belliste** [comment]
January Preview Insiders Build 0.25.4 is the latest build, isn't it?

**Comment by emredjan** [comment]
I confirm this bug is still there on 0.26.1 February insiders build.

**Comment by belliste** [comment]
Still on 0.26.4. This is a major bug for me.

**Comment by RiccardoScarpa** [comment]
Still on 0.26.7

**Comment by MattIrv** [comment]
This will be fixed in the upcoming March release and is included in the public preview builds that are available now. If you keep having problems with this after upgrading to the March release or the preview builds, please reopen this issue. Thanks!
