### ISSUE TITLE
invalid sql syntax color highlighting when using temporary table in from clause

### ISSUE THREAD

**Issue by jsmircic** [Microsoft/sqlopsstudio#60]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1. write SQL with a temporary table in from clause
ex
SELECT * 
FROM #temptable INNER JOIN dbo.SomeOtherTable ON ...

the entire text after #temtable is in green color, expected to have blue INNER JOIN

![image](https://user-images.githubusercontent.com/10010504/32890248-410da994-cace-11e7-863e-b548fba7f32c.png)

**Comment by corivera** [comment]
Closing this issue since it doesn't repro in the latest version of SqlOps
