### ISSUE TITLE
"Show details" does nothing for dashboard widgets

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#602]
SQL Operations Studio Version: 2/2/2018 daily build (fe04fd7)

Steps to Reproduce:
1. Connect to a server and open the dashboard
2. Click on the options menu for the Backup Status widget and observe that nothing happens

I don't see an error anywhere though

**Comment by kburtram** [comment]
This should be fixed now (at least with latest pending PR for fixing regressions)
