### ISSUE TITLE
intellisense - Bad suggestion for 'update' command

### ISSUE THREAD

**Issue by realfreebird** [Microsoft/sqlopsstudio#606]
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:51:42.102Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. Type 'upd'
Expecting to see "UPDATE" on the intellisense list. 

![sos_update1](https://user-images.githubusercontent.com/17299389/35809427-40bedc76-0a91-11e8-9427-aa6988b2df17.jpg)

**Comment by kburtram** [comment]
This is fixed in latest `insiders` build.  Thanks for reporting~

![screen](https://user-images.githubusercontent.com/599935/39147443-71f35300-46ee-11e8-8d6f-f3b12af050ce.png)
