### ISSUE TITLE
Feature Request: Add shortcut to sp_help

### ISSUE THREAD

**Issue by eduronqui** [Microsoft/sqlopsstudio#61]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:

On a SQLQuery pane, type an object name (table, view, sp, ...), place the cursor over typed object name and press (default, could be configurable) ALT+F1. It shoud call `exec sp_help <object_name>` and return the result to user.

**Comment by GrzegorzLyp** [comment]
![image](https://user-images.githubusercontent.com/29247982/33530253-4eaa7656-d87d-11e7-91b1-4f757c87c4f0.png)

Please include complete support for this SSMS feature.

**Comment by rafaatsouza** [comment]
Why was this issue closed?

**Comment by kevcunnane** [comment]
This feature is supported in the December release. Look for “query shortcut” in the user settings to see the defaults and how to add your own shortcuts.

**Comment by GrzegorzLyp** [comment]
So how to add my own. Nothing in description about how to add Ctrl+0 ?

**Comment by GrzegorzLyp** [comment]
No question. It works fine.

**Comment by kevcunnane** [comment]
@GrzegorzLyp in user settings there are 10 shortcut values listed. Above each is a text comment showing how to set up the keybinding as needed.

**Comment by GrzegorzLyp** [comment]
Yes it works. I have already blogged it for community.
http://www.lyp.pl/blog/sql-operations-studio-december-2017-shortcuts-like-in-ssms/

**Comment by EugeniaMoya** [comment]
Hi!!! I am looking for an SP of the SQL system that executes what the shortcut CTRL + F5 executes.
Just as ALT + F1 executes sp_help
I would like to know what is running CTRL + F5.
You know? or where could I ask?

Graciassss!! :)

**Comment by Jeankininho** [comment]
I'm still waiting for this function, someone know how to setup ALT+f1 for sp_help ?

**Comment by kevcunnane** [comment]
@Jeankininho you can change the keybinding for `shortcut1` in the Keyboard Shortcuts page.

![image](https://user-images.githubusercontent.com/10819925/47235511-1d963480-d38e-11e8-89dd-0410ea9258c2.png)

![image](https://user-images.githubusercontent.com/10819925/47235525-27b83300-d38e-11e8-889b-98bd7641b8a6.png)

**Comment by Jeankininho** [comment]
> @Jeankininho you can change the keybinding for `shortcut1` in the Keyboard Shortcuts page.
> 
> ![image](https://user-images.githubusercontent.com/10819925/47235511-1d963480-d38e-11e8-89dd-0410ea9258c2.png)
> 
> ![image](https://user-images.githubusercontent.com/10819925/47235525-27b83300-d38e-11e8-889b-98bd7641b8a6.png)

Awesome ! Sorry ask in a closed issue.
