### ISSUE TITLE
Save query results - no extension added

### ISSUE THREAD

**Issue by LSTANCZYK** [Microsoft/sqlopsstudio#615]
- SQL Operations Studio Version:
0.25.4

Steps to Reproduce:

1 execute any select query to get data
2. Use export results to Excel button
3. Select a folder where to save results and override entire name of the file (Results.xlsx) with "test"
4. Save the file. 
5. View file on disk 
6 confirm the file was saved without xlsx extension.

Desired result - since we already know we are exporting to excel, unless explicitly specified, file should be saved with default xlsx extension if no extension is given

**Comment by kburtram** [comment]
I couldn't repro on the July release.  Please reactive with additional repro info if the problem persists.

![screen](https://user-images.githubusercontent.com/599935/42957860-b38a5294-8b38-11e8-96a5-11ade8bff673.PNG)

**Comment by kburtram** [comment]
It looks like if you rename the file from `Results.xlsx` and don't provide an `xlsx` extension then we don't auto-appended.  I think this is the issue being reported here.

We'll track that issue over in https://github.com/Microsoft/sqlopsstudio/issues/892.
