### ISSUE TITLE
sp_help not working in "Table is referenced by foreign key", constraints and indexes

### ISSUE THREAD

**Issue by gilberto-ferreira** [Microsoft/sqlopsstudio#626]
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:51:42.102Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. sp_help my_table

**Comment by kevcunnane** [comment]
Could you clarify the issue here? Is something in the tool failing to work as expected? sp_help is a server stored procedure so the tool should just reflect the results of you calling this.

**Comment by kburtram** [comment]
sp_help seemed to work the same as in SSMS as far as I can tell.  Please reactive if there is still an issue.

![screen](https://user-images.githubusercontent.com/599935/37185894-705c0f16-22f7-11e8-9154-c9fa1544bbc7.png)
