### ISSUE TITLE
Feature Request: Tabs should be color of server group

### ISSUE THREAD

**Issue by sroyvs** [Microsoft/sqlopsstudio#63]
Suggestions; when opening a query tab (or any tab for that matter) for a connection that's part of a server group that has a color, the tab and border of the selected tab would had the same color as the server group. 

![ssms](https://user-images.githubusercontent.com/20728797/32892405-81a5f7da-caac-11e7-98b5-387b564c2361.png)

**Comment by MattIrv** [comment]
This is in progress now. The work is being tracked in https://github.com/Microsoft/sqlopsstudio/issues/327

**Comment by kburtram** [comment]
This insiders test build contains an implementation of this suggestion https://github.com/Microsoft/sqlopsstudio/releases/tag/0.25.0.  If anyone has time, it would be great to get some testing and feedback on this feature.

Also, one design question...should the tab coloring be enabled or disabled by default (it can always be toggled with the setting).  I'm thinking disabled by default, but wanted to some opinions before making any changes.

**Comment by kburtram** [comment]
I'm going to close this now since this feature is available in today's January Public Preview build.  Please reactive if the feature doesn't meet the intended use case of this issue.
