### ISSUE TITLE
Dashboard tab should be configurable for server version, and server vs database view

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/sqlopsstudio#635]
I can't currently provide a tab that only works on SQL Server 2017. Similarly, I cannot currently provide a tab that appears only on the Server.

**Comment by AbbiePetcht** [comment]
@anthonydresser does you context key service support solve these issues? Have you verified that it support showing only server or database?

**Comment by anthonydresser** [comment]
I would need to test it, either way we can explicitly add this to the context. The problem will be I don't think you are filtering when you add a tab, are you?
