### ISSUE TITLE
Dashboard: Backup task shows on Server connection

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/sqlopsstudio#636]
- SQL Operations Studio Version: Dashboard tabs dev branch build
@anthonydresser this is a regression in the dashboard tabs dev branch. In the official Feb release you still see the Backup task filtered out of the server page, but in the tab branch it always shows. This leads to users clicking it and seeing `undefined` as part of the backup name & other badness. What's regressed here?

![image](https://user-images.githubusercontent.com/10819925/35949753-fc4ed6de-0c27-11e8-89f7-8369130a1151.png)

**Comment by anthonydresser** [comment]
@AbbiePetcht this is being caused by the removal of https://github.com/Microsoft/sqlopsstudio/blob/master/src/sql/parts/dashboard/pages/serverDashboardPage.component.ts#L52 during your tab refactoring stuff.
