### ISSUE TITLE
IntelliSence against APS (on Premise) doesnt work for columns

### ISSUE THREAD

**Issue by MartinWagnerDPD** [Microsoft/sqlopsstudio#64]
- SQL Operations Studio Version:
0.23.6 

Steps to Reproduce:
  Open Connection against APS via Port 17001, connect to database.
  Write select statement and intellisence is starting for schema and tables. Everything is working fine.
  But the columns are not available after them. Only a lot of standard entries. 
  Example
   Select l.<...> From schemaname.tabelename l where l.<...>

**Comment by kburtram** [comment]
At the moment SQL DW team does not support APS in SMO\Intellisense.  If this changes we'll pick this in a SMO refresh.
