### ISSUE TITLE
GO statement performance issues

### ISSUE THREAD

**Issue by bciesielski** [Microsoft/sqlopsstudio#645]
- SQL Operations Studio Version: 0.25.4
- SQL Server 2016 SP1 Developer

There seems to be a performance problem when using GO statement especially for larger iteration counts. I suspect this to be related to the amount of information output into the Messages window. 
With every iteration the spacing between messages increases which might lead to much much longer message text and therefore eat up memory and make GUI irrensponsive.

Steps to Reproduce:
1. create table e.g.
`drop sequence s
create sequence s as int start with 1 increment by 1
DROP TABLE IF EXISTS b
CREATE TABLE b
(
    id INT IDENTITY(1,1) PRIMARY KEY
    ,value INT
    ,fk INT  default next value for dbo.s 
)`

2. execute INSERT statement together with GO 50000
e.g.
`INSERT INTO b with (tablock) DEFAULT VALUES 
go 50000`
3. Let it finish or break execution after a while of running
4. At this point UI is very laggy or even unresponsive and takes approx 600-800MB of RAM

![image](https://user-images.githubusercontent.com/36210825/36006991-84549a00-0d40-11e8-9d81-1a5f5959a4c1.png)

Setting NOCOUNT ON doesn't really help, so probably it is inserting the new line characters anyways.

![image](https://user-images.githubusercontent.com/36210825/36007116-36093f9e-0d41-11e8-856a-3954beaeed05.png)

**Comment by kburtram** [comment]
@corivera I think this issue is somewhat related to https://github.com/Microsoft/sqlopsstudio/issues/480 when a lot of resultsets cause various performance\responsiveness issues.  Could you please see if your planned fixes for 480 also help with this issue.  Thanks!

**Comment by kburtram** [comment]
The message related problems should be fixed in next `insiders` build
