### ISSUE TITLE
Edit results in grid

### ISSUE THREAD

**Issue by pfaisant** [Microsoft/sqlopsstudio#65]
- SQL Operations Studio Version:

Steps to Reproduce:

**Comment by kevcunnane** [comment]
We currently support edit data as an option from Object Explorer and the Search widget in the dashboard. We don't have plans to add inline editability to results panes at this time.

**Comment by kburtram** [comment]
Closing as duplicate of https://github.com/Microsoft/sqlopsstudio/issues/78 which is targeting April Public Preview release.

**Comment by Zyxious** [comment]
This is one of the main reasons I don't switch to SQL Operations Studio.
