### ISSUE TITLE
Feature Suggestion: Have the ability to give a name to connections

### ISSUE THREAD

**Issue by sroyvs** [Microsoft/sqlopsstudio#66]
Instead of just showing server names in the left panel; when creating a new connection give the ability to give a name to the connection that would then be used in that list (same as registered servers in SSMS)

**Comment by erickangMSFT** [comment]
Refer to https://github.com/Microsoft/sqlopsstudio/issues/240 for design suggestions

**Comment by EvilVir** [comment]
IMO it's crucial feature that should be there from the beginning. I have like 5 connections only and yet I have problems with knowing which one's which as they are all on the internal VPN network and only difference is one digit in the IP address (username is same on each of them).
