### ISSUE TITLE
Windows 10 tile-friendly icon

### ISSUE THREAD

**Issue by CobusKruger** [Microsoft/sqlopsstudio#67]
The present icon looks pretty sad on a Windows 10 start menu tile. Please provide an icon that also fills the background, like the VS Code icon does.

![image](https://user-images.githubusercontent.com/10893522/32893505-6a4f39da-cae2-11e7-9b95-e1f2cd7a80c8.png)

While you're at it, could you also make the icon a nice orange hue? 😉

**Comment by kevcunnane** [comment]
I don't think the orange hue worked out that well the last time a Microsoft tool tried it 😉 but the request to improve the tile experience is a good ask.

**Comment by Depechie** [comment]
Looking at the other app icons that are available in my Mac toolbar, the one from sqlopsstudio looks a bit dated. Certainly in ref to the modern ones from VS for Mac, VSCode and recently announced Azure logo.

**Comment by Matticusau** [comment]
With the latest Dec preview release the icon got worse. I didn't mind the old one, it was small but it was nice. Now it makes the text unreadable.

![image](https://user-images.githubusercontent.com/11083642/34145303-1d98ac48-e4e1-11e7-864c-668c9f5b2464.png)

**Comment by CobusKruger** [comment]
@Matticusau Actually, I really like the new icon. It has that DIY vibe that makes me think I may be a talented designer...

**Comment by Matticusau** [comment]
Sorry I should clarify, I don't mind the logo, when you set it to the small size it looks good. But in medium size it clashes with the icon text and this makes it look worse in my opinion. Of cause just my opinion, but as most of the other application icons are sized so they do not overlap with the text I guess that is what I am looking at.

**Comment by hikidd** [comment]
The new icon is really NOT beautiful....

**Comment by kburtram** [comment]
This pull request fixes the icon regression in the Dec release. https://github.com/Microsoft/sqlopsstudio/pull/382.  The fixed icon will look as below.

![screen4](https://user-images.githubusercontent.com/599935/34230077-a825263e-e58b-11e7-9433-8c872e62edeb.png)

**Comment by CobusKruger** [comment]
@kburtram Well, that's perfect. Exactly what I was hoping for, thanks!

**Comment by kburtram** [comment]
I close this issue as the fix is in the Jan release.
