### ISSUE TITLE
Settings.json Insight widget suggestion is not functioning after installing insight widget extension

### ISSUE THREAD

**Issue by erickangMSFT** [Microsoft/sqlopsstudio#670]
- SQL Operations Studio Version:

Steps to Reproduce:

1. git clone https://github.com/erickangMSFT/opsstudio-ext.git 
2. Side load insight vsix extension under https://github.com/erickangMSFT/opsstudio-ext/tree/master/serverInsights 
3. Open User or Workspace setting
4. Add a new insight widget configuration using keyword suggestion for "widget" property.

Expected: "widget" property lists available insight widget names.
Actual: the suggestion list does not work

**Comment by anthonydresser** [comment]
@erickangMSFT is this still reproing?

**Comment by anthonydresser** [comment]
This isn't reproing. It works for me.
