### ISSUE TITLE
Show loading indicator while opening a new script from the list

### ISSUE THREAD

**Issue by mikaoelitiana** [Microsoft/sqlopsstudio#678]
- SQL Operations Studio Version: 0.25.4

Steps to Reproduce:

- Open an existing connection
- Right click an element from the list widget to open a script (Select top 1000 or anything else)
- The new tab take a few seconds to open but there is no indication that it is loading

Attached gif in real speed:

![sqlops](https://user-images.githubusercontent.com/674667/36141738-2d5a8c6e-10a6-11e8-94ab-4cec2494fc0f.gif)

**Comment by anthonydresser** [comment]
I would like to use the editor progress bar for this, however there is problems with our dashboard angular injection and the services that it has access to. We'll have to fix that before we can fix this.
