### ISSUE TITLE
Feature Request: Sql Search

### ISSUE THREAD

**Issue by mijaved** [Microsoft/sqlopsstudio#679]
Looking forward to have the features or integration with "Sql Search" tool from Red Gate

- Find fragments of SQL in tables, views, stored procedures, functions, jobs, and more
- Quickly navigate to objects wherever they happen to be on a server
- Search across multiple object types and multiple databases
- Find all references to an object
- Search with booleans and wildcards

Ref:
[SSMS Add-in](https://www.red-gate.com/products/sql-development/sql-search/index)
[VS 2017 Ext.](https://marketplace.visualstudio.com/items?itemName=vs-publisher-306627.RedgateSQLSearch)

**Comment by kburtram** [comment]
Please checkout the `Redgate SQL Search` extension in the Extension Manager.
