### ISSUE TITLE
copying from Messages pane not working

### ISSUE THREAD

**Issue by af4jm** [Microsoft/sqlopsstudio#696]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1. highlight stuff (usually error messages) in Messages pane
2. Ctrl+C
3. Go to TFS/GitHub/Slack/Gitter/etc.
4. Ctrl+V

Expected result: message is pasted

Actual result: nothing happens, clipboard is empty.

**Comment by kburtram** [comment]
@af4jm I can't repro this issue.  I see you're using an older build.  Could you please try the latest build (download links are on repo home page README.md)?

If the issue persists please reactive this issue.
