### ISSUE TITLE
Entering HTML-like text in edit data causes value to display incorrectly until refresh

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#703]
SQL Operations Studio Version: February preview 0.26.5

Steps to Reproduce:
1. Open edit data for a table where a column allows text input
2. Enter html-like text, such as `<b>Hello world</b>` and observe that it renders the HTML instead of displaying as text

The text is saved correctly and renders correctly after hitting refresh. Certain combinations of characters result in other invalid results, such as `"</>` which causes the cell to display some other HTML as text instead of the entered text.

![screen shot 2018-02-14 at 3 02 50 pm](https://user-images.githubusercontent.com/3758704/36232867-37af1fde-1198-11e8-80fb-20f55134695c.png)

**Comment by kburtram** [comment]
@MattIrv do you know if this is a regression from Jan?

**Comment by MattIrv** [comment]
@kburtram it's not a regression

**Comment by kburtram** [comment]
Thanks for confirming.  Let's chat about this issue during next scrum.
