### ISSUE TITLE
sql agent jobs

### ISSUE THREAD

**Issue by dontommy** [Microsoft/sqlopsstudio#707]
I would love if SQL Operations Studio had functions to adminster sql agent jobs, creating and viewing them like in SSMS - that would be great! Specially for us Linux desktop users, where we really cant admin the agent jobs fra a GUI when using SQL Server on Linux.

Thanks

**Comment by kburtram** [comment]
@dontommy we're tracking this request in this issue https://github.com/Microsoft/sqlopsstudio/issues/27.  Please upvote that issue to help us track customer demand for this feature area.

We're actively designing this feature area and expect to deliver this functionality over the next couple releases.  I'm planning to post some of our SQL Agent workflow design content on GitHub tomorrow so we can get community feedback as we develop the feature.  Please checkout the design content when available.
