### ISSUE TITLE
Default chart type for timeseries doesn't render correctly

### ISSUE THREAD

**Issue by rgward** [Microsoft/sqlopsstudio#709]
- SQL Operations Studio Version: 0.26.6

I had submitted a request to allow you to change in settings the default Chart Type for results which made it into this version. But the chart doesn't render correctly with this setting. It only renders correctly if I first choose HorizontalBar and then switch to TimeSeries

Steps to Reproduce:

I've seen this when I've been doing demos for auto tuning. So in one window run this script to generate data to collect

IF EXISTS (SELECT [object_id] FROM tempdb.sys.objects (NOLOCK) WHERE [object_id] = OBJECT_ID('tempdb.dbo.##tblPerfCount'))
DROP TABLE ##tblPerfCount;
-- When counter type = 272696576 (find delta from two collection points)

IF NOT EXISTS (SELECT [object_id] FROM tempdb.sys.objects (NOLOCK) WHERE [object_id] = OBJECT_ID('tempdb.dbo.##tblPerfCount'))
CREATE TABLE ##tblPerfCount (
       [counter_name] [NVARCHAR](128),
       [retrieval_time] [datetime],
       [cntr_value] float NULL,
       );

WHILE 1=1
BEGIN
       INSERT INTO ##tblPerfCount
       SELECT counter_name, GETDATE(), cntr_value
       FROM sys.dm_os_performance_counters pc0 (NOLOCK)
       WHERE counter_name LIKE 'Batch Requests/sec%';

       WAITFOR DELAY '00:00:01'
END;

In another window run this query

SELECT top 70 counter_name, [retrieval_time],
              CASE WHEN LAG(cntr_value,1) OVER (ORDER BY [retrieval_time]) IS NULL THEN  
                     cntr_value-cntr_value
                     ELSE cntr_value - LAG(cntr_value,1) OVER (ORDER BY [retrieval_time]) END AS cntr_value
FROM ##tblPerfCount
ORDER BY [retrieval_time] DESC
GO

If you change the default chart type in your settings to TimeSeries and run this 2nd query, the chart is small and doesn't use the entire footprint of the screen which skews what the results should look like. If you though choose HorizontalBar and then go back and choose TimeSeries it renders correctly (as it did in the previous release when I had to do this manually>

Bob Ward

**Comment by kfarlee** [comment]
I still see this in the current build 0.27.3
If the default is set to timeseries, the chart renders in a different style than if you switched to it.  Not only is the style different, but as mentioned above it doesn't fill the screen space, and the time axis is reversed.  changing the chart to a different type and back to timeSeries again gives the correct (expected) rendering (without re-running the query).
Is there some workaround?  Do I need to explicitly configure the appearance in the customization?  This isn't making sense.

**Comment by kevcunnane** [comment]
@anthonydresser and @AbbiePetcht, can we prioritize this as we look at top dashboard issues to fix? We need to get some focused fixes here and it's a good candidate.
