### ISSUE TITLE
Edit in dashboard doesn't work correctly

### ISSUE THREAD

**Issue by AbbiePetcht** [Microsoft/sqlopsstudio#713]
Delete/move around widgets are not persisted
- cannot delete task and explorer widgets
- Delete one insight widget, delete another insight widget
- moving around widget doesn't persisted

**Comment by anthonydresser** [comment]
This seems to work for me. The only problem is moving the first widget, without moving something else, some odd stuff happens, but this isn't new and seems to be a library problem
