### ISSUE TITLE
Getting Started banner is covered by the Connections flyout

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/sqlopsstudio#714]
- SQL Operations Studio Version: sqlops 0.26.6 (49bf9163461901730033f85f69220ab4db44045f, 2018-02-14T22:22:52.051Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

Upon first install of the February Public Preview, the Getting Started banner is immediately covered by the Connections flyout. Hitting Cancel on the flyout makes the banner appear. While I did not capture a screencap, the text on the banner was also cut off. This all seems related to the small starting window size.

![image](https://user-images.githubusercontent.com/8250560/36276105-b0c7eb4a-1241-11e8-8702-d06e1c47d2f4.png)

**Comment by kburtram** [comment]
@vickyharp we plan to brainstorm a bit more regarding the first launch and build-to-build upgrade experiences.  Currently we want to both prompt the user to create a connection which is basically required to do anything, but we'd also like to provide an opportunity to view additional documentation to get awareness on what the tool can do.  These two "prompts" are unfortunately conflicting as you've noted.

In the meantime you can view the documentation that is linked from the Getting Started prompt by running the `Show Getting Started` command in the Command Palette.  Thanks for opening the issue.

**Comment by kburtram** [comment]
We've removed the `Getting Started` banner and replaced with Telemetry notification.  The Telemetry notification doesn't appear until the dialog is dismissed.
