### ISSUE TITLE
Dashboard errors when connected to a contained database

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#715]
SQL Operations Studio Version: February public preview 0.26.6

Steps to Reproduce:
1. Set up a contained database with its own user
2. Connect to the database (you'll have to fill in the database name in order to connect)
3. Open the dashboard

Actual behavior: The dashboard opens, but some parts of it don't render correctly. Errors get logged in the output
Expected behavior: Dashboard should handle these failures gracefully and render what it can without printing errors

I'm not aware of a workaround yet.

This was reported by @SebastianPfliegel in https://github.com/Microsoft/sqlopsstudio/issues/687#issuecomment-366020538.

**Comment by kburtram** [comment]
@MattIrv could you please investigate?

**Comment by SebastianPfliegel** [comment]
@MattIrv, just checked out 0.26.7 and it looks like it is fixed. Opening the dashboard won't welcome me with an exception and the widgets are displayed. The only thing that's not working is the dashboard header shows `Unable to load dashboard properties`, but that might be because I'm lacking permissions to retrieve that information.

**Comment by MattIrv** [comment]
I'm going to close this now since the main part of the issue was exceptions being thrown when loading the dashboard, which is no longer the case. As of the March release the database dashboard should also show the correct info for a contained database instead of "Unable to load dashboard properties". Going forward we might also want to look at disabling the server dashboard when connected to a contained database since it's not really relevant
