### ISSUE TITLE
Selecting partial query and hitting Cmd or Ctrl+C opens terminal with Error message

### ISSUE THREAD

**Issue by Code-DJ** [Microsoft/sqlopsstudio#717]
- SQL Operations Studio Version: 0.26.6

Steps to Reproduce:
Open New Query
Type a query
Highlight a portion (not all) of the query
Hit Ctrl+C on Windows or Cmd on Mac
Terminal opens with the following text:
```
[Error - 11:27:43 AM] Request textDocument/definition failed.
  Message: Operation timed out.
  Code: 0
```

In some situations, you get the following:
```
[Error - 11:35:26 AM] Request textDocument/definition failed.
  Message: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at Babel.ParserGenerator.MinimalList`1.get_Item(Int32 index)
   at Babel.ParserGenerator.ModifiedMinimalList`1.get_Item(Int32 index)
   at Microsoft.SqlServer.Management.SqlParser.Parser.TokenManager.GetToken(Int32 tokenNumber)
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.Completion.ScriptDocumentInfo.GetPeekDefinitionTokens(ScriptParseInfo scriptParseInfo, Int32 startLine, Int32 startColumn) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\ScriptDocumentInfo.cs:line 158
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.LanguageService.GetDefinition(TextDocumentPosition textDocumentPosition, ScriptFile scriptFile, ConnectionInfo connInfo) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\LanguageService.cs:line 1194
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.LanguageService.<HandleDefinitionRequest>d__50.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\LanguageService.cs:line 377
  Code: 0 
```

**Comment by Code-DJ** [comment]
To be more specific use the following sample query:
SELECT * FROM Person WHERE PersonID = 1

Highlight partial query above "SELECT * FROM Person WH". This will open terminal with the error.
If you select "SELECT * FROM Person" or "SELECT * FROM Person WHERE" i.e. complete words, you don't get the error.

**Comment by kburtram** [comment]
@anthonydresser this looks similar to the other "Output Window" popping up on language client errors issue you were looking at.  Do know if the fix you submitted was supposed to fix this?

**Comment by kburtram** [comment]
@Code-DJ I'm having trouble repro'ing this issue, but we investigated a similar issue where non-user impacting internal errors were being (annoyingly) logged in the Output window.  This commit fixed the scenarios we had repro's for https://github.com/Microsoft/sqlopsstudio/commit/6f21d6e27ed27cad9375dddf9839dcce971e8730.

Let me keep investigating.  Please let me know if there are any additional steps to narrow down the repro.

**Comment by kburtram** [comment]
@Code-DJ nevermind, it seems like if I hit Ctrl-C several times in a row quickly using your repro I can get the error.  Let me see why the previous commit isn't preventing this pop-up.

**Comment by Code-DJ** [comment]
@kburtram on macOS I am able to consistently recreate by pressing Cmd first, then dragging the mouse to select a portion of the query. As soon as you let go of the mouse, the terminal comes up with the error. Additionally, if you select the entire query and Cmd click it, the error pops up.

This is not how I intend to use the app, was just trying to recreate the issue several different ways.

**Comment by jiskim** [comment]
i get this error too on windows.

Just  to add a bit i get those error  too from the same  window, wich one show up depend on  if im connected to  a server or not...


if my  connection is closed

```
[Error - 3:03:27 PM] Request textDocument/definition failed.
  	Message: Please connect to a server.
  	Code: 0 
```

if im  connected i  get one of those ( including the one in  op message ). 

``` 
[Error - 3:03:07 PM] Request textDocument/definition failed.
  	Message: No results were found.
  	Code: 0 
 ```
 
  ```
 [Error - 10:55:11 AM] Request textDocument/definition failed.
  	Message: This object type is currently not supported by this feature.
  	Code: 0 
   ```
   
thanks, i was going crazy thinking i was the only  one getting those!

**Comment by anthonydresser** [comment]
What is the output channel it is pushing these messages to?

**Comment by jiskim** [comment]
its getting pushed to  SqlToolServices ( not the init one )

**Comment by kburtram** [comment]
@Code-DJ @jiskim I'm going to publish a Feb Hotfix Build with the fix for this later today.

**Comment by kburtram** [comment]
The 0.26.7 builds for Windows and Linux are available at https://github.com/Microsoft/sqlopsstudio/releases/tag/0.26.6 which contains the proposed for fix this issue.  

macOS build is still signing and may take another 1hr or so.  I'll update the auto-update feeds once all the builds are posted and we've completed build verification testing.

**Comment by kburtram** [comment]
The hotfix for this issue has been published to the auto-update feeds and the download page fwlinks have been updated.  Sorry for the inconvenience of needing to update again so frequently.  Please reopen the issue if the issue persists on the 0.26.7 build.  Thanks!

**Comment by Code-DJ** [comment]
Thanks. Updated it. So far so good.
