### ISSUE TITLE
Allow changing the connection display name in the servers list

### ISSUE THREAD

**Issue by xt0rted** [Microsoft/sqlopsstudio#72]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
Connections in the server list show as `server, dB name (user name)`. For situations like azure dBs you don't actually see the dB name because the server name is a url like `someserver.database.windows.net`. It'd be nice if you could change the order so the dB name came first, or allow customizing the display on a per connection basis. Having multiple azure dBs on this list means I need to make the column much wider so I know which dB I'm looking at. The server name could also be redundant if you end up grouping the connections by server (which is what I'm doing).

**Comment by erickangMSFT** [comment]
Let track this ask with https://github.com/Microsoft/sqlopsstudio/issues/66
