### ISSUE TITLE
Show tempdb spool warnings in Explain view

### ISSUE THREAD

**Issue by justingrant** [Microsoft/sqlopsstudio#725]
One feature I miss from SQL Management Studio is the yellow triangle warning icons in the query plan. 

In particular, I'd like to see the spool warning for an actual plan so I can identify problems with cardinality estimation in earlier operators.

**Comment by JustinPealing** [comment]
Do you mean these warnings?

![image](https://user-images.githubusercontent.com/4189474/35033118-57749d1e-fb61-11e7-8635-719646a0abcd.png)

If so this is https://github.com/JustinPealing/html-query-plan/issues/63, which is in v2.4 of html-query-plan.

**Comment by justingrant** [comment]
@JustinPealing that is exactly what I was talking about. Does JustinPealing/html-query-plan#63 show a warning icon or just the warning text in the tooltip?

**Comment by JustinPealing** [comment]
There are warning icons, although they don't stand out against the node icons particularly well in some cases

![image](https://user-images.githubusercontent.com/4189474/36445025-e1ebc4bc-1674-11e8-8981-4bc72cfcc51c.png)

**Comment by kburtram** [comment]
@anthonydresser do you know how I can upgrade html_query_plan to 2.4?  Do I need to merge `JustinPealing/html-query-plan` into `anthonydresser/html-query-plan` then bump our package.json to #2.4?

**Comment by anthonydresser** [comment]
It's a little more involved than that, I can just do it real quick

**Comment by kburtram** [comment]
Thanks @anthonydresser!  Please document the process somewhere (or walk me through the process) if you don't want to be the only on-going owner of this step.

**Comment by kburtram** [comment]
We updated to html-query-plan 2.4 so I think this will be fixed in the next March Insiders build that I'll publish next week.  Please reactive if this is still in issue in that build (or in a private build from master if you can't wait for that build 😄).

**Comment by LitKnd** [comment]
I found this while looking to file a bug on this very issue -- I am not seeing the warning icons on plans in SQL Ops Studio today. Attached is a gif showing code with the warning on the sort operator in SSMS, then the same code with no warning on the sort in Ops Studio.

You can see that there was a spill from the tooltip in Ops Studio, but there is no warning indication on the operator, but practically speaking most plans are complex enough that the operator level visual indication is needed to draw attention.

Repro code to cause the spill...

`declare @foo table (i int);

WITH Ten(N) AS 
(
    SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
    SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
    SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1
)   
insert @foo
SELECT T1000000.N
FROM Ten T10
CROSS JOIN Ten T100
CROSS JOIN Ten T1000
CROSS JOIN Ten T10000
CROSS JOIN Ten T100000
CROSS JOIN Ten T1000000;

select 0
FROM @foo
ORDER BY i DESC`

![no warnings on sort operator with spill](https://user-images.githubusercontent.com/1623675/43656458-55fcb1aa-9707-11e8-8ceb-684dfe7ae05c.gif)
