### ISSUE TITLE
Error Notification messages are getting cropped

### ISSUE THREAD

**Issue by samirbehara** [Microsoft/sqlopsstudio#729]
- SQL Operations Studio Version:
Version 0.26.7 (0.26.7)

Steps to Reproduce:
Error Notifications getting displayed at the top of the browser are getting cropped. I have attached a screenshot showing the exact problem. For better user experience, it will be nice if the modal popup displaying the error auto-sizes based on the error message length - allowing the complete error message to be displayed to user.

![error notifications](https://user-images.githubusercontent.com/10365808/36357523-dfcef476-14c4-11e8-8110-7e40ce1351ad.png)

**Comment by kburtram** [comment]
The next VS Code source code update will completely change the notification UI.  Please see VS Code 1.21 release notes for details.  Let's wait to see if that change handles this situation better and revisit if necessary.

**Comment by kburtram** [comment]
The new notification UI no longer crops error messages.  Thanks for reporting this issue.

![screen](https://user-images.githubusercontent.com/599935/42958387-409697fa-8b3a-11e8-8bdf-fc26bc524e46.PNG)
