### ISSUE TITLE
Delete Connection does not confirm selection.

### ISSUE THREAD

**Issue by zeroactive** [Microsoft/sqlopsstudio#733]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1.Right click on Connection in Server pane.
2.Select "Delete Connection"

Should present dialog to confirm delete.

**Comment by abist** [comment]
Duplicate of https://github.com/Microsoft/sqlopsstudio/issues/711
