### ISSUE TITLE
Maximum Characters Retrieved

### ISSUE THREAD

**Issue by mrangelba** [Microsoft/sqlopsstudio#735]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Query data or xml truncate in results

**Comment by kburtram** [comment]
@mrangelba could you please provide a bit more repro details?  Is this issue that if a column value is too large it is truncated?  Is there an example of what value is truncated when selected?  Thanks!

**Comment by kburtram** [comment]
Please reactivate with additional repro steps if this is still an issue.
