### ISSUE TITLE
February preview update not saving user settings

### ISSUE THREAD

**Issue by ssubramanian84** [Microsoft/sqlopsstudio#736]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: none
---

Steps to Reproduce:

1. Click on add new server connection.
2. Input the required information.
3. Click on connect.
4. Error banner pops up saying the following
"Error: Unable to write to user settings. Please open User settings file to correct errors/warnings in it and try again"

This is happening after I updated to the Feb update that was pushed. Even editing the user settings manually and saving it does not actually persist the update.

How to proceed?

![sqlops_errorsavingsettings](https://user-images.githubusercontent.com/30613382/36398893-018e8972-1615-11e8-9d36-e05991a18e41.PNG)

**Comment by bwunder** [comment]
I had this error. In my case I am on openSUSE 42.3 and sqlops had just been updated with the January release (25.4). I found the syntax as existed in the settings.json  was marked invalid on a widget I had added previously - and had been working just fine. Hovering on the marked syntax produced a message about sqlops expecting null for each key in my widget. I removed the widget from settings, and was able to save the settings file. From there sqlops was happy. (The widget simply ran a catalog query. Nothing special...)

**Comment by inteladu84** [comment]
Hi bwunder,
Appreciate the response and share. I will try this and see how it goes.
Thank you.

**Comment by inteladu84** [comment]
For some reason, it is unable to save user settings even when I try to change the theme!

**Comment by kburtram** [comment]
@inteladu84 any luck tracking down what's going on?  Or additional details that may help us get an internal repro?

**Comment by kburtram** [comment]
Closing since we don't have a repro.  Please reactivate if the issue persists.
