### ISSUE TITLE
Request textDocument/definition failed

### ISSUE THREAD

**Issue by trschmidt** [Microsoft/sqlopsstudio#739]
- SQL Operations Studio Version: sqlops 0.26.6 (49bf9163461901730033f85f69220ab4db44045f, 2018-02-14T22:08:11.844Z)
- OS Version: Darwin x64 17.4.0
- Extensions: none
---

since the last update I keep getting errors when copying and pasting.  Not exactly consistent, but very frequent.  All I am doing is copying and then pasting into a SQL script.  Happens when copy from another app, from the same app different window and same app same window.  here is the error I keep getting

[Error - 07:21:05] Request textDocument/definition failed.
  Message: No results were found.
  Code: 0

**Comment by jiskim** [comment]
update to the lastest version (0.26.7) it fixed  that issue specificly :) 

see old bug report #717

**Comment by kburtram** [comment]
Please update to 0.26.7 (there should be an auto-update available on macOS).
