### ISSUE TITLE
Auto-Refresh Option

### ISSUE THREAD

**Issue by robertpreseau** [Microsoft/sqlopsstudio#74]
This thing is fantastic, but I could really use an option to auto-refresh dashboards.  I personally don't need anything more than 10 or 15 mins although I'm sure others would want/need a much quicker turnaround.

**Comment by luiznovaesneto** [comment]
I totaly agree! The dashboard is a fantastic feature but must have the auto-refresh function to be really usefull!

**Comment by mikedavem** [comment]
+1.

**Comment by IsItGreyOrGray** [comment]
+1 on this as well. This was probably the second thing I looked for and was surprised it wasn't available.
