### ISSUE TITLE
Open after exporting to CSV/XLS/JSON

### ISSUE THREAD

**Issue by bciesielski** [Microsoft/sqlopsstudio#746]
- SQL Operations Studio Version: 0.26.7

**Feature request**
After exporting the grid results to XLS,CSV,JSON it would be really helpful to be able to directly open:
* a folder containing the exported file
* direclty the file with the associated program

in a single mouse click - like in popular web browsers after downloading a file.

Since there is already a notification bar in the top of the application window once the file gets exported - two additional buttons there "Open location" and "Open file" would save the day.

E.g.
![image](https://user-images.githubusercontent.com/36210825/36479403-e8fe7fb2-1708-11e8-8672-342370a27962.png)

**Comment by joeangry** [comment]
I'm playing around with 0.26.6 and that behavior is more or less there. JSON and CSV files open in the editor and Excel files are supposed to open Excel but currently that doesn't seem to work.

**Comment by kburtram** [comment]
JSON and CSV files should automatically open after writing.  We can try to open Excel in the default app handler.

**Comment by bciesielski** [comment]
Unfortunately, neither exporting to XLS nor to CSV triggers opening associated application here, so yes, trying a different approach to opening files might be needed.

but even having that working, it would be helpful to be able to open exported file location so one could easily attach to an email (I frequently get requests of some custom semi-reports, since they are mostly one-time, non-repeatable - xls over email is the easiest way to go ).

**Comment by Ettery** [comment]
It would be very useful to open the excel file after saving; or perhaps (alternatives) 
* to open it when the use clicks on the "Successfully saved" notification - this puts the user in control.
* next best to open the folder containing the file, either automatically or if the user clicks on the notification.
Thanks!  I'm using SQL Ops Studio as my primary tool now.
