### ISSUE TITLE
"Check for Updates" option missing in latest build

### ISSUE THREAD

**Issue by mrlife** [Microsoft/sqlopsstudio#747]
On 0.26.4 (macOS), the "Check for Updates..." menu item is gone. The menu item was there in 0.25.3 (though it didn't find the update for 0.26.4).

![screen shot 2018-02-14 at 2 18 14 pm](https://user-images.githubusercontent.com/213164/36223467-7f39bb76-1192-11e8-8437-aab7ff6d5715.png)

**Comment by mrlife** [comment]
Fixed on 0.26.7.

**Comment by kburtram** [comment]
Thanks for confirming!  I think this was related to some issues getting updates working with the insiders builds.  I'll try to be more careful with the March insiders builds.  

One note is that in the future the insiders builds and stable builds will be different update channels.  So 0.26.7 will upgrade to the final March Public Preview build, not the insiders builds that I'll start publishing next week (in case you wanted to be on the latest dev builds 😄).
