### ISSUE TITLE
Window crashes after Mac sleep

### ISSUE THREAD

**Issue by benrr101** [Microsoft/sqlopsstudio#748]
- SQL Operations Studio Version: Latest Master
- OS: macOS 10.12.6 (Sierra)

Steps to Reproduce:
* Open SQL Ops Studio
* Put Mac to sleep
* Go home for the night
* Come back next day, open Mac

Expected result: Everything fine and working
Actual Result: 
<img width="494" alt="screen shot 2018-02-21 at 10 31 19 am" src="https://user-images.githubusercontent.com/585878/36498553-72e20250-16f3-11e8-86de-7904ce3dc4af.png">

<img width="740" alt="screen shot 2018-02-21 at 10 34 15 am" src="https://user-images.githubusercontent.com/585878/36498444-2832bc90-16f3-11e8-933e-9d6a186f1f0d.png">

**Comment by kburtram** [comment]
Closing older issues that we haven't been able to repro and haven't been upvoted.  Please reactive if this is still occurring on current builds.  Thanks!
