### ISSUE TITLE
Populating table list is incredibly slow against Azure SQl DW

### ISSUE THREAD

**Issue by NeilP-global** [Microsoft/sqlopsstudio#75]
- SQL Operations Studio Version:
0.23.6
Steps to Reproduce:

Connect to SQL DW. Open the tables folder.

**Comment by erik-mileiq** [comment]
Mine is so slow that the tables view never populates. I can see the existing views (there are only two), and stored procedures.

Azure SQL Data Warehouse
Version 0.23.6 (0.23.6)
Mac OSX 10.13.1

**Comment by llali** [comment]
this bug is fixed and will be in the next release
