### ISSUE TITLE
Seeking community feedback on SQL Agent UX prototype

### ISSUE THREAD

**Issue by yualan** [Microsoft/sqlopsstudio#750]
The SQL Operations Studio engineering team is working on an initial design for the SQL Agent extension. We would appreciate your feedback or any questions you may have with the direction we are going.

Please view the video and comment on this issue. Thank you.

[![youtube_player_ux_agent](https://user-images.githubusercontent.com/30873802/36498121-39706a12-16f2-11e8-8fff-be7f0b5f7509.png)](https://www.youtube.com/watch?v=xnnVG66rvCk)

**Comment by vickyharp** [comment]
I think it has a nice clean look. A couple comments, all of which of course would need to be borne out with more feedback:

Column Defaults:
- The "created by" column on the main screen does not seem very important. I expect you can hide it but I would want to verify that this is something that users want to see more than more dynamic information 
- I would like to see duration information in the default layout. Most recent duration and average duration probably. Jobs that run significantly longer or shorter than average can be as bad as a job failure.
- Some users rely on categories, not shown here. This may be handled fine by the column picker though

Usability:
- Job names often run WELL longer than this prototype and they can be a nightmare to visually parse. When you have really long gnarly names, possibly with GUIDs, you may need lookups to their human-readable names, or the ability to alias
- This does not seem to be color-blind sensitive. Using colors is probably ok but there should be a secondary indicator like shape, or if not, it should be easy and intuitive to add status as an additional column.
- I'm finding myself wanting to see a group by functionality - group by last run status, group by category, etc - in addition to the filter

**Comment by Code-DJ** [comment]
I got a little lost at the point where you said, install the extension then also add it to the dashboard. I understand the idea of having to install the extension but once installed it should be available to all servers.

I see in your mockup you have profiler tab. May be make SQL Agent also a tab. Below the list of databases, add SQL Agent (like SSMS), on double click, open everything you have in a new tab.

In the jobs list, need an indicator for disabled jobs.
How do you enable/disable/delete a job?
I agree with @vickyharp duration is more important than who created it. Also need a Next Run column.

**Comment by jasonhorner** [comment]
Need support for job categories, the ability to create and recall filters and columns in the job list and the ability to script out the job definition to tsql. It would also be nice if you could add support for starting a job at a given step. It also looks like there is no support for setting up on fail and on success steps

**Comment by dalehhirt** [comment]
A good beginning, but I agree with @Code-DJ I shouldn't have to both install and add the extension for use.

It's not clear when you initially edit the job step to make sure the job runs, that it is only for that run.  My assumption would have been that I am editing the actual job step.

Requirements for the advanced tab would be to see where the log file is being output to.

The job view shows the target server, but it actually is displaying the schedule.

**Comment by SebastianPfliegel** [comment]
Nice job! I like using tabs and dashboards instead of popup windows like in SSMS.

It would be nice if the Agent extension would come with additional home dashboard widgets. This way you can see the job 'health' status at one glance.

**Comment by reharmsen** [comment]
How does this work when you have a master (MSX) server and one or multiple target servers?
Do I see differences within the extension?

**Comment by IsItGreyOrGray** [comment]
Is the _Error message_ the same as what we would currently see in the _Message_ field when looking at the job history in the log viewer or msdb..sysjobhistory? Assuming it is, is the field displayed being limited to a certain number of characters or is it collapsible? Having 4000 characters of output message shoved right under a "failed" status, but above the other info pertaining to the job run will be unwieldy (and annoying) without a way to control it. 

Additionally, for those of us with large output going to a table or file, the standard _Message_ won't necessarily contain the actual point of failure. It probably shouldn't specifically be called "Error message" on the dashboard unless you've got some way of presenting just the actual error message. 

Also, having an option to pull the full log from the table or get the filepath to the output file would be nice.

**Comment by ndwivedi** [comment]
Love the new UI. Agree with the feedback given above. I would also love to be able to group jobs based on categories or even databases. Would love to keep the managing job history option as we have in SSMS.

**Comment by cirinovargas** [comment]
Nice. Please add search box, to filter the Jobs by name.

**Comment by mrlife** [comment]
On macOS (0.27.0-insider), I'm only seeing the Jobs tab on the left, no Alerts, Schedules, or Operator tabs. On the Jobs tab, there's no Refresh, Columns, or New job options. The columns displayed are also very different from the ones in the video.

**Comment by Houndin** [comment]
It would be great to see a visual glyph or indicator to show if a job is disabled on the home tab.

Does the job edit function show when you have different 'next step' for success and failure?

**Comment by dabasys** [comment]
How can I get this version? I got no "add job" or "edit job" in my sql agent extension?

Thanks

**Comment by dabasys** [comment]
Anybody in here knows how to get the version in the video on a linux machine?

Much appreciated..

**Comment by SebastianPfliegel** [comment]
Which version of sqlops are you running (0.30.6 being the current one)? The latest agent extionsion build is 0.29.0 and can be obtained via the extension market place within sqlops.

**Comment by dabasys** [comment]
Thats the one I am using? So the build in the video havent been released yet?

**Comment by SebastianPfliegel** [comment]
Let's just say it's a different build.

**Comment by dabasys** [comment]
Well why not say where I can get that build in the video instead?;)

**Comment by kburtram** [comment]
Thanks for all the feedback in this feature area.  Please checkout the latest Agent extension and open issues for any remaining gaps.  We'll continue to integrate your feedback into the product in subsequent releases.
