### ISSUE TITLE
Manual Entries for Windows Auth - Feature

### ISSUE THREAD

**Issue by robdob6** [Microsoft/sqlopsstudio#752]
- SQL Operations Studio Version: 0.26.7 MacOS

It would be great to have an option where someone can manually enter a domain account and password for the Windows Authentication option.  Use case: I am required to use an AD account that is not my normal working account to do DBA related tasks.  

As a workaround, I tried using "open Electron" after running an "su" to my other account, which is as close to a Windows style "Run As" that I can find.  The following message is returned:

$ cd /Applications/SQL\ Operations\ Studio.app/Contents/MacOS/
$ open Electron 
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/SQL Operations Studio.app/Contents/MacOS/Electron.

**Comment by kburtram** [comment]
We are tracking this request in issue https://github.com/Microsoft/sqlopsstudio/issues/112.  Please add comments to that issue if desired.  Thanks!
