### ISSUE TITLE
Disconnecting server does not works sometime

### ISSUE THREAD

**Issue by surajds** [Microsoft/sqlopsstudio#759]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.17074
---

![image](https://user-images.githubusercontent.com/21216035/36580257-84bea136-188d-11e8-9968-b395ca16345e.png)

1. As you can see above the server is showing as disconnected but still the child folders are loading
2. Even after manually disconnecting the server again, server doesn't collapses and the child folders stays same.

**Comment by kburtram** [comment]
I'll close since we still don't have an internal repro.  Please reactivate with additional repro context if the issue persists.
