### ISSUE TITLE
Save Query dialog shows *.sql twice

### ISSUE THREAD

**Issue by CoolDadTx** [Microsoft/sqlopsstudio#760]
- SQL Operations Studio Version: sqlops 0.26.6 (49bf9163461901730033f85f69220ab4db44045f, 2018-02-14T22:22:52.051Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Open a new query window.
2. Select Save
3. Notice the SQL file type is listed as (*.sql;*.sql;*.dsql)

**Comment by ntovas** [comment]
This took me a while to figure it out, but it happens because there is 2 folders for sql in the \extensions\ folder, the mssql and the sql. 
I will add a fix for duplicate extensions tomorrow.
