### ISSUE TITLE
Suggestion: Allow setting RowHeight in Results Grid View.

### ISSUE THREAD

**Issue by Elestriel** [Microsoft/sqlopsstudio#761]
- SQL Operations Studio Version: 0.26.7

Steps to Reproduce: Run any query that returns results.

The Results Grid has very tall rows, showing about half the data density that SQL Server Management Studio would show in its Results view.

Suggestion: Add a Setting to set the RowHeight of the Results Grid.

**Comment by bciesielski** [comment]
Found that a bit annoying too, some way of workaround is to CTRL +/- the size of text and actually the query window and rest of the UI are scaled separately. If you get focus in the result pane and resize and then go to query window and resize text you might get decent results.
Hope this helps.

![scale](https://user-images.githubusercontent.com/36210825/36872797-ca8d9b7c-1da6-11e8-8032-11d9765a80c7.gif)
