### ISSUE TITLE
Toogle Message Panel

### ISSUE THREAD

**Issue by wsalmi** [Microsoft/sqlopsstudio#762]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Execute SQL Query
2. No close options to message panel

**Comment by kburtram** [comment]
The `Toggle Query Results` command should hide the results and messages pane.  Setting `"sql.messagesDefaultOpen": false` in the User Settings will make the Messages collapsed by default.  Please reactive if these options don't meet your ask.  Thanks!
