### ISSUE TITLE
Explain Issue with SP (temp table available)

### ISSUE THREAD

**Issue by rajumarella** [Microsoft/sqlopsstudio#768]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Create Procedure with a temp table insertion (User INTO option to create above)
    ex: Select Id INTO #temp from TableName 
2. Now save the procedure and try execute the plan. It will throw an error says #temp object not found. But you execute the same in SSMS it will work.

This is a silly issue. please fix it.

**Comment by kburtram** [comment]
@rajumarella I wasn't able to repro this using the below snippet.  Running `Explain` on `EXEC Test1`.  Do you know if there are additional repro steps required?

```SQL
CREATE PROC Test1    
AS    
Select a.collation_name INTO #temp from sys.all_columns a

EXEC Test1
```

![screen1](https://user-images.githubusercontent.com/599935/38710391-246b51d6-3e75-11e8-81ab-aaba0956054e.png)

**Comment by kburtram** [comment]
Closing since we don't have a repro.  Please reactivate if the problem persists.
