### ISSUE TITLE
Content inside dashboard tab isn't scrollable

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#769]
Steps to Reproduce:
1. Open dashboard with window size to small for content

Actual: No scrollbar for tab content

![screen](https://user-images.githubusercontent.com/599935/36617538-a0242c8e-189c-11e8-9a13-b867d8c2df8b.png)

**Comment by AbbiePetcht** [comment]
@kburtram  The fixed has checked in. Can I close this?

**Comment by AbbiePetcht** [comment]
verified the fix
