### ISSUE TITLE
Filters not exists on edit data

### ISSUE THREAD

**Issue by buster95** [Microsoft/sqlopsstudio#770]
- SQL Operations Studio Version:
0.26.7

Steps to Reproduce:
option edit data on rigth click in table

**Comment by kburtram** [comment]
@corivera I think this is related to the feature you're starting on.  Please duplicate this issue if you're tracking a different customer opened issue for this.  Thanks!

**Comment by ScottRFrost** [comment]
Duplicate of #78 , #302 , and #402 .  Please search before you raise issues.

**Comment by kburtram** [comment]
I'll close this as a duplicate of #302.  Thanks for the suggestion!
