### ISSUE TITLE
Feature request: SQL Pane in Edit mode

### ISSUE THREAD

**Issue by salem84** [Microsoft/sqlopsstudio#78]
- SQL Operations Studio Version: 0.23.6

View and edit SQL query when editing data like in SMSS

Steps to Reproduce:

1. Select any table with an identity column
2. Right click and select "Edit Data"
3. Click button to view SQL Query

**Comment by MaxxDelusional** [comment]
Yes please.  The lack of this feature pretty much makes Operation Studio a non-starter for me.

**Comment by blaskoa** [comment]
It would also be nice to have Criteria pane and Diagram pane, same as in SSMS.

**Comment by AdrianCuartas** [comment]
SQL Operations Studio is awesome but I really miss this feature.

**Comment by JulianJdangelo** [comment]
Any update on this feature?
It really is an important and helpful feature.

**Comment by Globalrun** [comment]
Agree. The only feature, that's really missing.

**Comment by ScottRFrost** [comment]
Please at least give us the option to have a WHERE & ORDER BY clause when editing a table.  I don't want to go back to hand writing UPDATE statements.

**Comment by haroonyoeu** [comment]
This is a very helpful feature for on-the-fly edits in SQL Operations Studio. I find myself having both this and Management Studio open for quick updates.

**Comment by ionred** [comment]
This feature is available with the May release.

**Comment by ScottRFrost** [comment]
I'm going to have to respectfully disagree with you @ionred , unless there's some option I don't see here:

![image](https://user-images.githubusercontent.com/3866418/39870871-d8fb303c-5430-11e8-8f7c-b9babc0afabd.png)

Perhaps you're running a beta / source built version newer than the May release (0.29.3)?

**Comment by kburtram** [comment]
The implementation of this feature request is in the initial June `insiders` build at https://github.com/Microsoft/sqlopsstudio/releases/tag/0.30.1.  It should also to be in the June `stable` build planned for mid-June.  Please try out the feature and let us know if you hit any issues.

I close this issue based on the current availability in the `insiders` build.

**Comment by sabas** [comment]
On latest version, I see "Show SQL Pane", is there any plan about the Criteria Pane from SSMS?
(I see that previous tickets where merged on this one)
