### ISSUE TITLE
Need no of lines selected along with no of characters

### ISSUE THREAD

**Issue by surajds** [Microsoft/sqlopsstudio#780]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.17074
---
1. The status bar shows no of selected characters. Showing no. of selected lines too will be much more helpful.

![image](https://user-images.githubusercontent.com/21216035/36655715-63dfc6de-1aea-11e8-80a2-4c2a7aee0242.png)

**Comment by kburtram** [comment]
For core editor functionality we generally defer to VS Code (since they are area experts and we fork their code).  Generally we'd recommend opening editor specific  (non-SQL related) suggestions in the VS Code repo as they are more likely to fix this type of issue.  Thanks!

**Comment by surajds** [comment]
thanks. i've posted that in vscode
