### ISSUE TITLE
SQL Agent is not showing up

### ISSUE THREAD

**Issue by ECITMS** [Microsoft/sqlopsstudio#808]
- SQL Operations Studio Version:

Steps to Reproduce:

**Comment by kburtram** [comment]
We don't currently have SQL Agent support, but we are actively working on it.  We're tracking the feature ask in https://github.com/Microsoft/sqlopsstudio/issues/27.  I'll close this as a dup.

We are currently collecting community feedback on our planned SQL Agent UX in this issue https://github.com/Microsoft/sqlopsstudio/issues/750.  Please take a look at the mockup walkthough video posted there and provide us any feedback you have.  Thanks!
