### ISSUE TITLE
Message panel can not be minimized or closed.

### ISSUE THREAD

**Issue by BoredGamer-Me** [Microsoft/sqlopsstudio#809]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.14393
- Extensions: none
---
Steps to Reproduce:

1.  Created SQL statement which lead to a "String or binary data would be truncated" error in the message panel.
2.

**Comment by dewdeded** [comment]
Yeah, this sucks. Please fix.

[Window Title]
SQL Operations Studio

[Main Instruction]
SQL Operations Studio

[Content]


Version 0.26.7
Commit 723c7cb3bfd80d87fc8a1141632089cd4808495c
Datum 2018-02-16T21:34:47.034Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64



**I have this bug on Windows and Mac OS.**

**Comment by kburtram** [comment]
@BoredGamer-Me Have you tried the `Toggle Query Results` command?  It should hide the messages pane in the scenario mentioned above.

**Comment by kburtram** [comment]
Please reactive if `Toggle Query Results` doesn't fix the issue. There's a nice screen capture GIF in https://github.com/Microsoft/sqlopsstudio/issues/1259 which shows how that feature works.
