### ISSUE TITLE
Add VSCode like extensibility with ORM capabilities

### ISSUE THREAD

**Issue by carloshm** [Microsoft/sqlopsstudio#812]
Talk to and align with VSCode extensibility https://code.visualstudio.com/docs/extensionAPI/overview
Think of ORM interfaces so developers implement its own db support https://en.wikipedia.org/wiki/Object-relational_mapping

**Comment by kburtram** [comment]
@carloshm we are working on extensibility over the next few releases.  For the most part you can use the VS Code extensibility APIs (except for debugging) and many VS Code extensions work fine in SQL Ops Studio.

We also implement a JSON-RPC protocol that would allow 3rd parties to pull in their own DB support.  But it isn't based on ORM technology.  Please provide a bit more details on what type of scenarios you'd like us to enable using ORM so we can better capture this suggestion.  Thanks!

**Comment by kburtram** [comment]
We introduced an extensibility model in the **March Public Preview** release that is pretty similar to VS Code, with a bunch of data management-specific enhancements.  Please let us know if there is anything additional here beyond what I addressed in the previous comment.
