### ISSUE TITLE
Need doc for package.json contribution points

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/sqlopsstudio#814]
We need to have documentation on all the contribution points - see https://code.visualstudio.com/docs/extensionAPI/extension-points for how VSCode does this. At the moment I cannot tell what's supported due to #813 and this one.

I'd propose we create a markdown file for now or put this on the wiki. We can have this as a living doc version, and then convert that to online documentation in the future.

**Comment by AbbiePetcht** [comment]
Already created https://github.com/Microsoft/sqlopsstudio/wiki/Contribution-points
