### ISSUE TITLE
Chart won't display properly if float numbers used

### ISSUE THREAD

**Issue by jeffest** [Microsoft/sqlopsstudio#82]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. Run "
SELECT 'A' AS Label, 10.0 AS Cnt UNION ALL
SELECT 'B', 20.5 UNION ALL
SELECT 'C', 21.5
"
2. Click "View as chart"

What I see: Empty chart with scale going from -1.0 to 1.0 step 0.2 (see attached picture)
![sqloperation_float_chart](https://user-images.githubusercontent.com/9037132/32901389-f85ac9a8-caef-11e7-928f-7cdddbe119bb.png)

What I expect: a chart with good scale

**Comment by kburtram** [comment]
The appears to be fixed in current builds.  Please reactive if this is still an issue.
