### ISSUE TITLE
Can save Excel

### ISSUE THREAD

**Issue by joni4444** [Microsoft/sqlopsstudio#839]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. Make a SQL with Select
2. Run
3. press Save as Excel 
4. No error, but I haven't excel file

**Comment by joni4444** [comment]
It only happens when I use Work Area. Without working area it is working.

Sorry

**Comment by kburtram** [comment]
@joni4444 are you unblocked with this scenario?  Or is there still something you'd like us to look at?

**Comment by joni4444** [comment]
No, I can work without solve it. Don't worry. Thanks to your reply

________________________________
De: Karl Burtram <notifications@github.com>
Enviado: jueves, 8 de marzo de 2018 23:58:46
Para: Microsoft/sqlopsstudio
Cc: joni4444; Mention
Asunto: Re: [Microsoft/sqlopsstudio] Can save Excel (#839)


@joni4444<https://github.com/joni4444> are you unblocked with this scenario? Or is there still something you'd like us to look at?
