### ISSUE TITLE
Sql Server Operations Studio on Mac cannot connect via kerberos when SPN is set on Service Account

### ISSUE THREAD

**Issue by HoveyJr** [Microsoft/sqlopsstudio#842]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:17:29.202Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
---
Error:
System.Data.SqlClient.SqlException (0x80131904): Cannot access Kerberos ticket. Ensure Kerberos has been initialized with 'kinit'.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error -  An unsupported mechanism was requested (unknown mech-code 0 for mech unknown).

Steps to Reproduce:
1. SPN is configured and is set on the account SQL Server Service runs as per instructions here: https://technet.microsoft.com/en-us/library/bb735885.aspx

2. Follow Instructions Here:
https://docs.microsoft.com/en-us/sql/sql-operations-studio/enable-kerberos#connect-using-includename-sosincludesname-sos-shortmd

3. Receive error on trying to configure SPN on the Server as there is a duplicate because it is set on the Service Account. 

4. OS X is joined to the domain

5. krb5.conf is properly configured

6. Kinit is successful and other programs can auth using the kerberos ticket. 

7. Trying to connect to sql server host using SqlServerOperationsStudio results in the following error:
has been initialized with 'kinit'.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error -  An unsupported mechanism was requested (unknown mech-code 0 for mech unknown).

**Comment by HoveyJr** [comment]
@kburtram - Curious if you have any insight into this issue or if there is additional data I can collect that will help get to a root cause. I've noticed there are a few other open tickets with very similar issues connecting using kerberos from a Mac that you have commented on. Please let me know how I can help to get to the bottom of what is going on here.

**Comment by kburtram** [comment]
@HoveyJr unfortunately I'm not really familiar with troubleshooting in this area.  I see you've already looked through the suggestions in some of the related issues such as https://github.com/Microsoft/sqlopsstudio/issues/141.  I'll ping someone on the SqlClient team to see if they have any suggestions.

**Comment by kburtram** [comment]
We're tracking mac Kerberos auth issues in https://github.com/Microsoft/sqlopsstudio/issues/447.  Please add any additional related comments there.  Thanks.
