### ISSUE TITLE
Wrong items alphabetical ordering in server/database view

### ISSUE THREAD

**Issue by jeffest** [Microsoft/sqlopsstudio#85]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. Create a table named "ATable"
2. Create a table named "_ATable" 

What I see: 
Table "ATable" appears first in the list
![sqloperation_name_ordering](https://user-images.githubusercontent.com/9037132/32902074-b5afb206-caf1-11e7-9bd1-8721e3e870ef.png)

What I expect:
Table "_ATable" should appear first.

**Comment by llali** [comment]
this bug is fixed and will be in the next release
