### ISSUE TITLE
Come up with the pattern when there is an error in dashboard

### ISSUE THREAD

**Issue by AbbiePetcht** [Microsoft/sqlopsstudio#855]
Work with Smitha on the pattern when the extension cannot be loaded in dashboard

**Comment by AbbiePetcht** [comment]
![image](https://user-images.githubusercontent.com/25463959/37112335-f0d92d1a-21f6-11e8-8e10-104bbf75fb9e.png)

**Comment by anthonydresser** [comment]
Most of these we should write validators for and catch these before we even register them. The only exception is where we try and get data from the extension at run time, but the only example of this is webviews.

**Comment by AbbiePetcht** [comment]
@anthonydresser The only case when the unknown registered container is used

**Comment by anthonydresser** [comment]
Well currently we are only supporting using a container you define yourself, so this should be verifiable.
