### ISSUE TITLE
Feature Request : Add sqlopsstudio into chocolatey

### ISSUE THREAD

**Issue by jbpaux** [Microsoft/sqlopsstudio#87]
- SQL Operations Studio Version: SQL Operations Studio Public Preview 1

Steps to Reproduce: none

Would be awesome to have a chocolatey package for sqlopsstudio and install it directly using : choco install sqlopsstudio

SQL Management studio is available so should be sql operations studio

Thank you !

**Comment by pascalberger** [comment]
If you provide a Chocolatey package it would be nice to have the binaries embedded instead that they are downloaded from a website, as this would result in a much more stable package.

**Comment by pascalberger** [comment]
There was now a package submitted and approved on the community feed: [sql-operations-studio](https://chocolatey.org/packages/sql-operations-studio)

**Comment by kendaleiv** [comment]
Thoughts about adding the Chocolatey package to the README.md or anywhere else? Or, is it preferred to not advertise the Chocolatey package (at least, for now)?

**Comment by kburtram** [comment]
I think this is resolved.  Please reactive if there are still remaining requests for this.

**Comment by jbpaux** [comment]
Issue is that it's not managed by Microsoft and thus the package is behind current release ...
