### ISSUE TITLE
[uncaught exception]: TypeError: Cannot read property 'providerName' of null

### ISSUE THREAD

**Issue by markdreyer** [Microsoft/sqlopsstudio#875]
- SQL Operations Studio Version:

Version 0.26.7
Commit 723c7cb3bfd80d87fc8a1141632089cd4808495c
Date 2018-02-16T21:34:47.034Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

Update to latest version and open editor.  The editor does not load. It is just a big black box. I see the following error in the console of DEV tools:

![capture](https://user-images.githubusercontent.com/4984469/37161652-e292c9ec-22b8-11e8-99dc-564f2d0bff68.PNG)

**Comment by kburtram** [comment]
I haven't seen this exception yet.  You could try clearing out the application cache and see if that helps.

To do that you would delete all the files under C:\Users\`USERNAME`\AppData\Roaming\sqlops.  You probably would want to backup the `User` directory to avoid losing any saved connections.

Do you happen to know which build you upgraded from?

**Comment by markdreyer** [comment]
Thanks for your time, I will give that a try. I'm not sure which version I
upgraded from. I think it was fairly old so maybe it's because of that... I
think it may be something with the connection dialog. I left it open
overnight and the DB closed my connection. When I attempted to connect
again, it would just spin. That's when I upgraded hoping it would resolve
the issue.

If you need anything else to diagnose, let me know. Glad to help, enjoying
the preview so far!

**Comment by kburtram** [comment]
We had a connection profile schema change in the cached metadata in this month's release.  We saw a different error related to that which we think we fixed for customers moving between January to February release.

If clearing the cache fixes the issue then we'll keep an eye out to see if this has broader impact as people upgrade.  If that doesn't resolve the problem please let me know and I'll try to determine what information will help root cause the issue.

**Comment by markdreyer** [comment]
Hi Karl - clearing the cache fixed the issue. My connections remained, too. This can probably be closed out. Thank you!

**Comment by kburtram** [comment]
@markdreyer thanks for confirming.  We'll investigate further if we see additional repros of this issue.
