### ISSUE TITLE
Dashboard should tell user to install extensions if available feature list is empty

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#878]
The dashboard needs to help the user discover that they way to get "Installed Features" for command center is install extensions.  Otherwise, the Add Feature dialog will be empty and it won't be obvious where to get available features.

In general we need a story have to improve extension discoverability.  There are several way to address this experience for March.  Such as,

1. A 1-time popup on dashboard that says something like "Install extensions to get additional features..."
2. Some text in the Add Features dialog when the feature list is empty that says "Install extensions..."

**Comment by AbbiePetcht** [comment]
![image](https://user-images.githubusercontent.com/25463959/37232725-12e8154c-23a5-11e8-95cb-cda156eb239c.png)
