### ISSUE TITLE
useTabStops is ignored

### ISSUE THREAD

**Issue by Spongman** [Microsoft/sqlopsstudio#884]
SQL Operations Studio Version:
````
Version 0.26.7
Commit 723c7cb3bfd80d87fc8a1141632089cd4808495c
Date 2018-02-16T21:34:47.034Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
````

Steps to Reproduce:
- verify useTabStops to true
- new query
- see that indentation is set to spaces: 4
![image](https://user-images.githubusercontent.com/1088194/37226142-d86e4bfa-238d-11e8-817c-dcfdebd7597b.png)

**Comment by llali** [comment]
@Spongman the default value of the tab size is set to 4. you can change it in your settings:

// The number of spaces a tab is equal to. This setting is overridden based on the file contents when `editor.detectIndentation` is on.
  "editor.tabSize": 4,
