### ISSUE TITLE
Cant sort columns by clicking headers

### ISSUE THREAD

**Issue by AndersBillLinden** [Microsoft/sqlopsstudio#897]
When I clicked a header in edit view, the rows were not sorted on that column. Should not that be possible?

**Comment by anthonydresser** [comment]
Currently column sorting isn't supported in the results grid.

**Comment by kburtram** [comment]
We're tracking this category of request to enhance the results grid in issue https://github.com/Microsoft/sqlopsstudio/issues/569.
