### ISSUE TITLE
Minor graphic glitch of results grid selection

### ISSUE THREAD

**Issue by akerd** [Microsoft/sqlopsstudio#9]
SQL Operations Studio Version:
Version 0.23.6
Windows 10 Fall Creator

Steps to Reproduce:

Drag a selection on results grid from left-top to right-bottom and there is a minor graphic glitch that remove the bottom border of first cell.

![image](https://user-images.githubusercontent.com/1030305/32849138-a2c2a4aa-ca2e-11e7-81e8-9feb7b80e853.png)

If you drag from bottom-right to top-left the selection is different but I feel that also in this case there is some problem with the bottom border of first cell.

![image](https://user-images.githubusercontent.com/1030305/32849245-e5129bf8-ca2e-11e7-80ec-c9024a1f7d99.png)

**Comment by kburtram** [comment]
@anthonydresser any ideas which CSS style we'd need to update to fix this?

**Comment by anthonydresser** [comment]
Yeah, it's interesting since we use slickgrid default css styling. It might be worth going through and create entirely our own styling so it's easier to identify and get the consistent experience we want.

**Comment by alanrenmsft** [comment]
closing as the issue has been fixed by PR #2301
