### ISSUE TITLE
Make database selection dropdown list wider

### ISSUE THREAD

**Issue by jeffest** [Microsoft/sqlopsstudio#90]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)

Make the database selection dropdown list wider in SQL scripts tabs.
Long database name are being truncated.
![sqloperation_db_dropdown](https://user-images.githubusercontent.com/9037132/32906522-6057fbe0-cafd-11e7-97f3-b6ad4346007a.png)

**Comment by AlexTroshkin** [comment]
It seems to me that it's not a good idea to make a drop-down list wider, it looks not so good ![capture](https://user-images.githubusercontent.com/11016542/32918827-b980ebaa-cb34-11e7-84c1-700ef000e2c5.PNG)

I propose to do with long names in the same way on the server panel 
![capture1](https://user-images.githubusercontent.com/11016542/32918858-da51bc24-cb34-11e7-88c8-5aed30bf225f.PNG)
Crop long names and add dots to the end, and when navigating with a mouse, show a pop-up message with a full name 
![capture3](https://user-images.githubusercontent.com/11016542/32918748-7ef6615e-cb34-11e7-9c1f-0b059bc634f6.PNG)
