### ISSUE TITLE
[loc]Request to add Japanese language to SQL Operations Studio

### ISSUE THREAD

**Issue by MasayukiOzawa** [Microsoft/sqlopsstudio#919]
I would like to localize to Japanese.

**Comment by Monasr** [comment]
Localization is opened for community contributions http://aka.ms/sqlopsStudioLoc
Please contribute and help make the Japanese version available!

**Comment by kburtram** [comment]
Community localization resources are now available in the July release.  Please help us fill any localization gaps in your desire language.  Thanks!
