### ISSUE TITLE
Can't open files in Sqlops

### ISSUE THREAD

**Issue by gmiseria** [Microsoft/sqlopsstudio#927]
- SQL Operations Studio Version:0.26.7 on windows 10

Started Sqlops I can see only a blank page with menu on top. Ctrl+N result in the following error:
[createInstance] GlobalNewUntitledFileAction depends on UNKNOWN service QueryEditorService.

Steps to Reproduce:
1) start sqlops 
2) Ctrl+N

**Comment by kburtram** [comment]
@gmiseria generally when we see common scenarios like this fail it's often due to an acquisition issue.  Did you install using the setup EXE or the ZIP?  In any case, could you please try uninstalling or deleting the app folder and reinstalling?

**Comment by gmiseria** [comment]
Installed the application via the setup exe and worked for two weeks
without problems.
Deleted the app folder and now the application start and I can open files
and folders normally.
Thanks
Gianluca


2018-03-19 18:19 GMT+01:00 Karl Burtram <notifications@github.com>:

**Comment by kburtram** [comment]
@gmiseria the app was working fine and then started failing one day?  This is pretty strange, since setup **should** install the app into a read-only directory.  I'll keep an eye out for similar issues as this is unexpected.  Thanks for confirming the app is now working.  I'll close the issue.
