### ISSUE TITLE
Unable to access folders under my user account folder (like Desktop for example)

### ISSUE THREAD

**Issue by urig** [Microsoft/sqlopsstudio#928]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. In SQL Operations Studio, click the Restore button to start a Restore task.
2. In the window that opens, under 'Restore' from choose 'Backup'.
3. In the `Backup file path` field, click the '...' button.
4. In the file dialog that opens try to navigate to `C:\Users\<username>`

Expected Results:
Folders under `C:\Users\<username>` should be visible and selectable.

Actual Results:
Folders under `C:\Users\<username>` (for example: `Desktop`) are not visible .
Please see screenshot for reference, here: http://www.imgpaste.net/image/WKhuw

**Comment by MattIrv** [comment]
@urig Because [`BACKUP`](https://docs.microsoft.com/en-us/sql/t-sql/statements/backup-transact-sql) works by specifying a path on the server to save to, that file browser is a remote file browser, showing files on the server and not on your local machine.

Does that explain the missing folders or would you still expect certain ones to be there that aren't?

**Comment by urig** [comment]
Thanks @MattIrv. Seeing as the remote server was my local computer, I still would expect to see these folders. Now that I understand it's a remote file browser, I still wonder why it wouldn't show those folders to me - after all I have privileges to see them. Under whose credentials is the remote server accessed?

**Comment by MattIrv** [comment]
@urig It should match whatever account SQL Server is running on. Does that account have access to your `C:\Users\<username>` directory?

**Comment by urig** [comment]
I suspect not. Then maybe something in the UI could indicate this?

**Comment by MattIrv** [comment]
That makes sense. Looking through our issues I think there are a few other open issues where users don't expect the backup/restore file paths to be remote paths.

I've opened #941 to track that request, so I'll close this issue now. Thanks

**Comment by urig** [comment]
Thank you.
