### ISSUE TITLE
Running a backup from the server dashboard backup widget no longer works

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/sqlopsstudio#935]
SQL Operations Studio Version: Master 1bfc8c1

Steps to Reproduce:
1. Open a server dashboard
2. Click "..." then "Show details" on the backup widget
3. Click "Backup" in the window that opens (you can change the database if you want)
4. Observe that the database name is not filled in correctly in the dialog that opens (see picture 1 below). Click "Backup" or "Script" and observe that the backup task fails (picture 2 below)

![screen shot 2018-03-19 at 2 38 00 pm](https://user-images.githubusercontent.com/3758704/37623796-254a72a8-2b83-11e8-91ce-e7dcd9c9d7cf.png)

![screen shot 2018-03-19 at 2 37 35 pm](https://user-images.githubusercontent.com/3758704/37623777-180384e0-2b83-11e8-9f4a-7f5eb688bf76.png)

**Comment by kburtram** [comment]
@AbbiePetcht @anthonydresser this looks like a regression in the insights code.  We should fix for March.  Could you please take a look?
