### ISSUE TITLE
Can´t expand databases

### ISSUE THREAD

**Issue by mortenasp** [Microsoft/sqlopsstudio#968]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:17:29.202Z)
- OS Version: Darwin x64 17.4.0
- Extensions: none
---

Steps to Reproduce:

1. Connect to database
2. Click on the small expand icon to the left of Databases
3. Nothing happens but the icon changing like it has expanded
![expand_databases](https://user-images.githubusercontent.com/37689192/37831192-ea39f56a-2ea4-11e8-8dd1-207eade417ee.jpg)

**Comment by mortenasp** [comment]
Hi.

I only receive the failed to connect message.
I’ve attached the output from the console.

Kind regards,
Morten Asp Andersen
[Email Signatur - Dansk (1000x600)]
Telefon: +45 69 15 50 70
E-mail: maa@klarpris.dk<mailto:maa@klarpris.dk>

Fra: Anthony Dresser <notifications@github.com>
Svar til: Microsoft/sqlopsstudio <reply@reply.github.com>
Dato: torsdag den 29. marts 2018 kl. 21.07
Til: Microsoft/sqlopsstudio <sqlopsstudio@noreply.github.com>
Cc: Morten Asp Andersen <maa@klarpris.dk>, Author <author@noreply.github.com>
Emne: Re: [Microsoft/sqlopsstudio] Can´t expand databases (#968)


This seems like a limited repro, since this is basic behavior that works in most other cases. Are there any errors shown anywhere? If you toggle the developer tools on, do you see any errors in the console?

**Comment by kburtram** [comment]
@mortenasp we haven't been able to repro internally.  There are some issues where the request can timeout when trying to get the list of DBs, particularly when querying a busy Azure DB server.  We have another active issue tracking that.  

If you're still hitting this issue with the July release please reactive this issue.  Thanks!
