### ISSUE TITLE
Dashboard shows duplicate task icons

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#970]
- SQL Operations Studio Version: 0.27.0

![screen](https://user-images.githubusercontent.com/599935/37851630-d63ac808-2e9c-11e8-949e-0bc9eb4ecc08.png)

**Comment by kburtram** [comment]
@anthonydresser could you please take a look?  This will block the March release.

**Comment by anthonydresser** [comment]
I think you have settings causing this.

**Comment by MattIrv** [comment]
@anthonydresser clearing my old dashboard settings makes the duplicates go away. Did the format of the dashboard settings change from last version to this version in a way that would cause this?

**Comment by kburtram** [comment]
a customer reported this on Gitter and I have the same issue.  We need to make sure this isn't going to be a broadly impactful issue for users upgrading to the March release.  Asking them to clear their settings isn't really a great option.

**Comment by cirinovargas** [comment]
Yes, clearing the old dashboard settings the duplicates go away. But I think is not the solution. In attachment my dashboard settings maybe can help.
[dashboard.txt](https://github.com/Microsoft/sqlopsstudio/files/1843392/dashboard.txt)
