### ISSUE TITLE
Query results pane throws missing rowHeight exception

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#978]
- SQL Operations Studio Version: 0.27.1

Steps to Reproduce:
1. Use the 0.27.1 to try and run a query

Expected: Results displayed

Actual: Exception about missing rowHeight property on slickgrid control.

Note: Looks possibly related to https://github.com/Microsoft/sqlopsstudio/pull/962.  I'll try reverting this commit to get an updated build.

<img width="1002" alt="screen shot 2018-03-23 at 10 02 45 pm" src="https://user-images.githubusercontent.com/599935/37860609-f887653a-2ee5-11e8-8492-ec65e6be73e6.png">

**Comment by anthonydresser** [comment]
Did you rerun yarn? this is because you didn't get the updated angular2-slickgrid.

**Comment by kburtram** [comment]
The error is from the official builds from the lab.  The checked in files need to pull in the correct dependencies.  Though, yes, locally I did still see this issue after running yarn.
