### ISSUE TITLE
Temp tables are highlighted as comments

### ISSUE THREAD

**Issue by martinisaksen** [Microsoft/sqlopsstudio#98]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Open a new SQL file in the editor.
2. Make sure SQL is the selected markdown language.
3. Type "CREATE TABLE #test (ID INT)"

What I'd expect to see:
![ssms temp highlighting](https://user-images.githubusercontent.com/17652470/32920892-5ef31650-cae8-11e7-8322-b689bc293ed3.PNG)

What I see:
![msos temp highlighting](https://user-images.githubusercontent.com/17652470/32920898-645744f4-cae8-11e7-9158-72ed1377b618.PNG)

**Comment by abist** [comment]
Confirmed repro on 0.23.6, but this was seemed to be fixed in the January release.
