### ISSUE TITLE
MacOS - Couldn't start client sqltools service

### ISSUE THREAD

**Issue by krwinter** [Microsoft/sqlopsstudio#983]
- SQL Operations Studio Version:
0.26.7
MacOS High Sierra 10.13.2

Steps to Reproduce:
Start app, UI appears, immediately get error: "Couldn't start client sqltools service"
0.25.4 works fine. Haven't tried 0.26.1

**Comment by MattIrv** [comment]
We've had reports of similar issues on other operating systems but it seems pretty inconsistent, see #286 for more details on those.

@krwinter would you be willing to enable logging and share the logs for the crash like in that thread?

See https://github.com/Microsoft/sqlopsstudio/wiki/Troubleshooting-Issues for info on how to enable it and where to find the logs.

If you enable logging following those instructions and then run SQL Ops Studio and get the error, the newest sqltools_<some numbers>.log file in the log directory should have a log of the error. If you're willing to share it here then we can take a look.

Thanks!

**Comment by kburtram** [comment]
Closing since we don't have a repro.  Please reactivate if the problem persists.

**Comment by adlersd** [comment]
I had a similar problem in Arch Linux. I had to symlink the Unknown folder to the Linux one in  folder **sqlops-linux-x64/resources/app/extensions/mssql/sqltoolsservice**

```console
$ pwd
/home/adlersd/sqlops-linux-x64/resources/app/extensions/mssql/sqltoolsservice
$ mv Unknown Unknown2
$ ln -s ./Linux /home/adlersd/sqlops-linux-x64/resources/app/extensions/mssql/sqltoolsservice/Unknown
```
