### ISSUE TITLE
Is This the Corollary to VS Code but for Data? 

### ISSUE THREAD

**Issue by obsidience** [Microsoft/sqlopsstudio#99]
Why not name it "VS Data"?  Just a thought...

**Comment by kburtram** [comment]
@obsidience we are using the core VS Code source code as our shell platform and we do like a lot of aspects of how they are running their project (and plan to continue "copying" where we think it benefits users).

Naming and branding at Microsoft is not an engineering function so I don't have much comments on any particular name.  We do hope users will come to appreciate the tool and name as we complete out the feature set focusing on common DBA, developer and devops scenarios.

**Comment by gattila** [comment]
It can be nice if it can be install as a simple visual studio code plugin instead of a separated application.

**Comment by obsidience** [comment]
Thanks for the response Karl.  You are right - this is a branding issue and I'm not sure how we outsiders make suggestions on that.  

Anyway keep up the good work, I look forward to the day I don't have to install SSMS to run a quick query or two.

**Comment by erickangMSFT** [comment]
@gattila Yes you have it. We released it one year ago :) https://github.com/microsoft/vscode-mssql 
Just type in mssql in the Visual Studio Code extension side bar.

**Comment by kburtram** [comment]
Closing based on above responses.

**Comment by gattila** [comment]
@erickangMSFT: Thank you,
