### ISSUE TITLE
Close button styling isn't correct

### ISSUE THREAD

**Issue by kburtram** [Microsoft/sqlopsstudio#994]
- SQL Operations Studio Version: 0.27.2

Steps to Reproduce:
1. Open a few document windows

Expected: Close button is reasonable size

Actual: Close button is too large.  And Close button shows on SQL Query editors that aren't focused.  Close button should only show on focused editor or when tab is hovered (similar to VS Code behavior).

![close-button](https://user-images.githubusercontent.com/599935/37935397-344864ee-3106-11e8-88c8-3c9c512b0b8f.png)

**Comment by kburtram** [comment]
@AbbiePetcht we worked around this issue for March by reverting the changes to the close icon with PR https://github.com/Microsoft/sqlopsstudio/pull/997.  Please follow-up to get this resolved for April in the correct way.  Thanks!

**Comment by MattIrv** [comment]
VS Code shows a circular icon for tabs that have unsaved changes. In master right now we show the same X that we show to close active tabs, which probably isn't what we want. That's why Karl is seeing the X on some inactive tabs in his screenshot
